Iteratorsize for partition iterator
JuliaLang/julia pull request #16552
Opened 2016-05-24 10:31 UTC by mschauer

Before, collect of a partition could fail because it assumed the existence of length method via the iteratorsize fall back..

2016-05-24 12:34 UTC, tkelman commented on test/functional.jl
> +    @test v1[1] == v1[1] == [1,2]
presumably this should be `v1[1] == v2[1]` ?

2016-05-24 14:04 UTC, mschauer commented
The test failure after adressing @tkelman's spot is unrelated, previously passing test here https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.2015

2016-06-06 08:33 UTC, mschauer commented
Personal assessment: this change is straight forward.

2016-06-06 08:37 UTC, tkelman commented
Thanks for the bump, I agree this looks fine.

I think all the iterator size business still needs more thorough interface documentation, right?

2016-06-06 08:41 UTC, mschauer commented
Yes, I wrote https://gist.github.com/mschauer/c8d8b7eb5b455cb12ddc9bda15695203 but I would like to wait for feedback before writing more docs. See issue #15977

2017-07-06 08:19 UTC, mschauer commented
Bump.

2017-07-06 09:11 UTC, rfourquet requested changes
LGTM! (modulo the few comments)

2017-07-06 09:11 UTC, rfourquet commented on base/iterator.jl
> +partition_iteratorsize{T}(isz::T) = isz
The type parameter can be omitted.

2017-07-06 09:11 UTC, rfourquet commented on base/iterator.jl
> +iteratorsize{T}(P::Type{PartitionIterator{T}}) = partition_iteratorsize(iteratorsize(T))
the argument `P` can be omitted, and when rebasing update to the `where` syntax

2017-07-06 09:11 UTC, rfourquet commented on test/functional.jl
> +let v1 = collect(Base.partition([1,2,3,4,5], 2)), v2 = collect(Base.partition(Base.flatten([1,2,3,4,5]), 2))
wrap at 92 (IIRC) chars

2017-07-06 20:36 UTC, Sacha0 approved these changes
lgtm! Thanks @mschauer! :)

(The CI failures appear unrelated.)

2017-07-11 15:05 UTC, StefanKarpinski commented
If this is good to go, please merge, @rfourquet since you have some outstanding review comments.

2017-07-11 15:26 UTC, mschauer commented
@rfourquet Let me make one amendment first, after #22691 ``partition(flatten([1,2,3,4,5]),2)`` will actually have a length and not trigger anymore the ``SizeUnknown``-code path of collect. One can replace with``partition(flatten([[1,2],[3,4],5]),2)``.

2017-07-12 08:18 UTC, rfourquet commented on base/iterators.jl
> +end
out of curiosity: you switched to the long-form function syntax because of the `where` syntax?

2017-07-12 08:37 UTC, merged

2017-07-12 08:37 UTC, rfourquet commented
Thanks @mschauer !

2017-07-12 09:05 UTC, mschauer commented on base/iterators.jl
> +end
yes