patch for issue #17139
JuliaLang/julia pull request #18540
Opened 2016-09-16 10:43 UTC by citisolo

To add support to 'code_native()' to specify asm assembly output syntax

2016-09-16 12:30 UTC, martinholters commented on base/reflection.jl
> +function _dump_function(f::ANY, t::ANY, native::Bool, wrapper::Bool, strip_ir_metadata::Bool, dump_module::Bool, asmvariant=0)
Why not `asmvariant::String="att"`? Being consistent about the default value and further restrict the type to avoid the ambiguity problem.

2016-09-16 12:30 UTC, martinholters commented on base/reflection.jl
> +function _dump_function(linfo::Core.MethodInstance, native::Bool, wrapper::Bool, strip_ir_metadata::Bool, dump_module::Bool, asmvariant="att")
Also here `asmvariant::String="att"` and the ambiguity should be gone.

2016-09-16 12:34 UTC, yuyichao commented on test/asmvariant.jl
> +using Base.Test
This test should be x86 only.

2016-09-16 12:34 UTC, yuyichao requested changes

2016-09-16 12:37 UTC, martinholters commented on base/reflection.jl
> +generic function and type signature to `io` which defaults to `STDOUT`.Switch assembly syntax using asm_variant:[att|intel].Output is AT&T syntax by default.
From this, it is not clear that asm_variant should be given as a string. Maybe: ``The assembly syntax to use can be controlled with `asm_variant`; use "att" for AT&T style (default) or "intel" for Intel style.``

2016-09-16 12:44 UTC, martinholters requested changes
The tests could be in reflection.jl, I guess.

For the `asmvariant` parameter, a `Symbol` (`:att` or `:intel`) might be preferable on the Julia side. Throwing an error for unsupported formats also sounds like good idea.

2016-09-16 18:22 UTC, yuyichao commented on test/asmvariant.jl
> +if Sys.ARCH === :x86_64 || Sys.Arch === :i386
I think we use `:i686`. It also spells as `Sys.ARCH` not `Sys.Arch`.

2016-09-16 18:22 UTC, yuyichao requested changes

2016-09-16 18:23 UTC, yuyichao commented on src/disasm.cpp
>  #ifdef LLVM37
This needs rebasing.

2016-09-16 18:23 UTC, yuyichao requested changes

2016-09-16 18:24 UTC, tkelman commented on test/asmvariant.jl
> +if Sys.ARCH === :x86_64 || Sys.Arch === :i386
it might end up as `:i586` on some linux distros, possibly even `:i386` on some so maybe check for all ?

2016-09-16 23:10 UTC, tkelman commented
avoid merging in unrelated changes from other pull requests if you can. rebase the branch so it's just your commits, then force push over this branch in your fork

2016-09-17 01:59 UTC, closed without merging

2016-09-17 09:00 UTC, citisolo commented
Thanks 'tkelman' I did try to do a rebase but something has gone wrong , closing this issue will update the patch and figure out why the build is breaking then resubmit

2016-09-17 09:54 UTC, tkelman commented
Okay. It's a good PR so far, just needs another iteration or two of revisions.