increase default maximum number of openblas threads on power
JuliaLang/julia pull request #18638
Opened 2016-09-22 20:57 UTC by vchuravy

Right now we are defaulting to a hard-limit to 8. Which makes a decent size power node sad.

The question is what a realistic limit is and @xianyi suggested at least 24, while I went to the maximum number of cores currently available.

2016-09-22 21:57 UTC, tkelman commented
what's the impact on stack use?

2016-09-22 22:10 UTC, vtjnash requested changes
need to make sure this doesn't cause runtime performance issues (see past discussions of this constant)

2016-09-22 22:37 UTC, yuyichao commented
Ref https://github.com/xianyi/OpenBLAS/issues/103

2016-09-22 23:23 UTC, tkelman commented
also https://github.com/JuliaLang/julia/issues/14857 and https://github.com/JuliaLang/julia/issues/15715

2016-09-23 13:44 UTC, vchuravy commented
Okay let's be conservative for now and go with @xianyi suggestion of 24 threads.

Re: https://github.com/JuliaLang/julia/issues/14857#issuecomment-178689968
On power we are setting `OPENBLAS_DYNAMIC_ARCH=0` so maybe we should also not set NUM_THREADS?

2017-07-15 02:08 UTC, closed without merging

2017-07-15 02:09 UTC, vtjnash commented
I think we can just suggest that users customize their BLAS build in Make.user if they have custom (e.g. very large) matrices and very large machines.