Avoid boxing variables that may be used undef
JuliaLang/julia pull request #18732
Opened 2016-09-29 20:41 UTC by carnaval

use a separate `i1` flag so that we avoid boxing and give visibility to llvm in the defined/undefined dataflow, to remove redundant branches etc

```julia
f(a,b) = (if a; c = b; end; c)
```
gives
```
define i64 @julia_f_65179(i8, i64) #0 {
top:
  %2 = and i8 %0, 1
  %3 = icmp eq i8 %2, 0
  br i1 %3, label %err, label %ok

err:                                              ; preds = %top
  call void @jl_undefined_var_error(%jl_value_t* inttoptr (i64 140728621134648 to %jl_value_t*))
  unreachable

ok:                                               ; preds = %top
  ret i64 %1
}
```

2016-09-29 21:13 UTC, JeffBezanson approved these changes

2016-09-29 21:13 UTC, JeffBezanson commented on src/codegen.cpp
> +    Value *undefFlag;
I suggest calling it `defFlag` to avoid double negatives :)

2016-09-29 21:13 UTC, JeffBezanson commented
Awesome; this has been a long time coming.

2016-09-29 21:39 UTC, yuyichao commented on src/codegen.cpp
> +        vi.undefFlag = emit_static_alloca(T_int1, ctx);
We only need this if the slot is a `isbits` type right?

2016-09-29 21:53 UTC, carnaval commented on src/codegen.cpp
> +        vi.undefFlag = emit_static_alloca(T_int1, ctx);
or a constant. It should only be called in those cases. I'll add an assertion.

2016-09-29 21:55 UTC, carnaval commented on src/codegen.cpp
> +    Value *undefFlag;
yep, that was gratuitously confusing

2016-09-30 00:50 UTC, tkelman commented
we need to remember to do this more often: @nanosoldier `runbenchmarks(ALL, vs = ":master")`

2016-09-30 03:28 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18732#issuecomment-250631988) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/90d960f1e46fedaa284d8bdbb381a710b4ee1b08/8ff9156_vs_b36141f/report.md). cc @jrevels

2016-09-30 15:16 UTC, StefanKarpinski requested changes

2016-10-06 22:21 UTC, JeffBezanson commented
Bump. Just needs a bit more renaming, then good to go.

2016-10-11 20:41 UTC, JeffBezanson commented
Ok, did it myself :P

2016-10-11 20:54 UTC, JeffBezanson commented
Fixes #6914

2016-10-12 03:34 UTC, merged

2016-10-17 00:57 UTC, vtjnash commented
I think there was a bug in this.
```
Assertion failed: (vi.defFlag), function emit_local, file /Volumes/Lion/Users/jameson/Documents/julia/src/codegen.cpp, line 3142.

signal (4): Illegal instruction: 4
while loading /Volumes/Lion/Users/jameson/Documents/julia/base/precompile.jl, in expression starting on line 480
abort at /Volumes/Lion/Users/jameson/Documents/julia/build-llvm37/usr/lib//libLLVM-3.7.dylib (unknown line)
__assert_rtn at /Volumes/Lion/Users/jameson/Documents/julia/build-llvm37/usr/lib//libLLVM-3.7.dylib (unknown line)
emit_local at /Volumes/Lion/Users/jameson/Documents/julia/src/codegen.cpp:3142 [inlined]
emit_expr at /Volumes/Lion/Users/jameson/Documents/julia/src/codegen.cpp:3338
emit_assignment at /Volumes/Lion/Users/jameson/Documents/julia/src/codegen.cpp:3217 [inlined]
emit_expr at /Volumes/Lion/Users/jameson/Documents/julia/src/codegen.cpp:3421
emit_stmtpos at /Volumes/Lion/Users/jameson/Documents/julia/src/codegen.cpp:3327 [inlined]
emit_function at /Volumes/Lion/Users/jameson/Documents/julia/src/codegen.cpp:5081
jl_compile_linfo at /Volumes/Lion/Users/jameson/Documents/julia/src/codegen.cpp:927
jl_generate_fptr at /Volumes/Lion/Users/jameson/Documents/julia/src/codegen.cpp:1170
```
```julia
CodeInfo(code=Array{Any, 1}[
  # line 312,
  Expr(:meta, :push_loc, :multidimensional.jl)::Any,
  # line 315,
  SlotNumber(id=10) = SlotNumber(id=3),
  SlotNumber(id=8) = SlotNumber(id=1),
  SlotNumber(id=9) = SlotNumber(id=2),
  SlotNumber(id=11) = SlotNumber(id=4),
  SlotNumber(id=5) = Expr(:call, Base.to_index, Expr(:call, Base.getindex, SlotNumber(id=11), 1)::Any)::Any,
  # line 316,
  SlotNumber(id=6) = Expr(:call, Base.index_shape, SlotNumber(id=10), SlotNumber(id=5))::Any,
  # line 317,
  SlotNumber(id=7) = Expr(:call, Base.similar, SlotNumber(id=10), SlotNumber(id=6))::Any,
  # line 318,
  SSAValue(0) = Expr(:call, Base.==, Expr(:call, Base.map, Base.unsafe_length, Expr(:call, Base.indices, SlotNumber(id=7))::Any)::Any, Expr(:call, Base.map, Base.unsafe_length, SlotNumber(id=6))::Any)::Any,
  Expr(:gotoifnot, SSAValue(0), 17)::Any,
  goto 19,
  17:,
  Expr(:call, Base.throw_checksize_error, SlotNumber(id=7), SlotNumber(id=6))::Any,
  19:,
  # line 319,
  SSAValue(1) = Expr(:call, Base._unsafe_getindex!, SlotNumber(id=7), SlotNumber(id=10), SlotNumber(id=5))::Any,
  Expr(:meta, :pop_loc)::Any,
  Expr(:return, SSAValue(1))::Any], slottypes=nothing, ssavaluetypes=2, slotnames=Array{Any, 1}[
  :#self#,
  :#unused#,
  :A,
  :I,
  :I_1,
  :shape,
  :dest,
  :#self#,
  :#unused#,
  :A,
  :I], slotflags=Array{UInt8, 1}[0x02, 0x02, 0x02, 0x02, 0x12, 0x12, 0x12, 0x02, 0x02, 0x02, 0x02], inferred=false, inlineable=false, propagate_inbounds=false, pure=false)
```

2016-10-20 02:02 UTC, JeffBezanson commented
I have a fix.

2016-10-20 02:12 UTC, JeffBezanson commented
#19036