fix type instability in exp exp1m for Complex{Int}
JuliaLang/julia pull request #18786
Opened 2016-10-04 15:15 UTC by KristofferC

Fixes #18785

2016-10-04 16:31 UTC, JeffBezanson approved these changes

2016-10-04 16:49 UTC, yuyichao commented on base/complex.jl
> +exp(z::Complex) = exp(float(z))
Why can't type inference figure this out given `isnan(::Int)` and `isfinite(::Int)` are both constants? I was thinking about doing this a while ago (before we had constant propagation in type inference) but this adds branches (`isfinite` one in particular) that seems hard for LLVM to eliminat

2016-10-04 17:34 UTC, yuyichao requested changes

2016-10-04 17:34 UTC, yuyichao commented on base/complex.jl
> +exp(z::Complex) = exp(float(z))
Ref https://github.com/JuliaLang/julia/pull/13539 for a better workaround to the same issue.

2016-10-04 17:36 UTC, yuyichao commented on base/complex.jl
> +exp(z::Complex) = exp(float(z))
And also the (probably) new preferred way of adding similar test one line above the one you added.

2016-10-04 18:13 UTC, KristofferC commented on base/complex.jl
> +exp(z::Complex) = exp(float(z))
I think I missunderstand you but the test above the one I added looks pretty similar to how I did it?

2016-10-04 18:16 UTC, yuyichao commented on base/complex.jl
> +exp(z::Complex) = exp(float(z))
I think you need to rebase https://github.com/JuliaLang/julia/blob/fe29cb590d85df1d2c10ccc3c929f38418121f37/test/complex.jl#L945

2016-10-04 18:16 UTC, KristofferC commented on base/complex.jl
> +exp(z::Complex) = exp(float(z))
Oh yeah, of course. Thanks.

2016-10-05 08:13 UTC, KristofferC commented
Subsumed by #18793

2016-10-05 08:13 UTC, closed without merging