Use === instead of == where appropriate
JuliaLang/julia pull request #18853
Opened 2016-10-09 13:21 UTC by nalimilan

Continuation of https://github.com/JuliaLang/julia/pull/16764.

2016-10-09 14:06 UTC, yuyichao requested changes

2016-10-09 14:06 UTC, yuyichao commented on base/libgit2/libgit2.jl
> +    cert_file === C_NULL && cert_dir === C_NULL && return
This looks wrong.

2016-10-09 14:07 UTC, yuyichao requested changes

2016-10-09 14:07 UTC, yuyichao commented on test/libgit2.jl
> +                        sshp !=== nothing && kill(sshp)
This is disabled but is also wrong.

2016-10-09 14:09 UTC, nalimilan commented on base/libgit2/libgit2.jl
> +    cert_file === C_NULL && cert_dir === C_NULL && return
Good catch. Is `=== Cstring(C_NULL)` OK?

2016-10-09 14:16 UTC, yuyichao commented on base/libgit2/libgit2.jl
> +    cert_file === C_NULL && cert_dir === C_NULL && return
Maybe just remove the `Cstring` above.

2016-10-09 14:23 UTC, nalimilan commented on base/libgit2/libgit2.jl
> +    cert_file === C_NULL && cert_dir === C_NULL && return
Sounds better indeed.

2016-10-09 20:16 UTC, nalimilan commented on base/cartesian.jl
> +    elseif ex.head === :call && (ex.args[1] === :+ || ex.args[1] === :-) && length(ex.args) == 3 && ex.args[3] === 0
Sorry, I'm not following (I don't know what that code does). Are you talking about the `=== 0` part?

2016-10-09 20:36 UTC, yuyichao commented on base/cartesian.jl
> +    elseif ex.head === :call && (ex.args[1] === :+ || ex.args[1] === :-) && length(ex.args) == 3 && ex.args[3] === 0
It used to accept anything that's `== 0` as `ex.args[3]`.

2016-10-11 09:08 UTC, nalimilan commented on base/cartesian.jl
> +    elseif ex.head === :call && (ex.args[1] === :+ || ex.args[1] === :-) && length(ex.args) == 3 && ex.args[3] === 0
@timholy Do you think this is OK? From the comment on line 384, it seems this should only handle literal `0`, so should be fine.

2016-10-11 17:19 UTC, JeffBezanson requested changes

2016-10-11 17:19 UTC, JeffBezanson commented on base/cartesian.jl
> +    elseif ex.head === :call && (ex.args[1] === :+ || ex.args[1] === :-) && length(ex.args) == 3 && ex.args[3] === 0
This is a behavior change, which is not the purpose of this commit, so I think it should be changed back.

2017-01-31 20:54 UTC, nalimilan commented
I had completely forgotten about this PR. I've rebased and reverted the change in behavior, so should be good to merge now.

2017-01-31 21:03 UTC, yuyichao requested changes

2017-01-31 21:03 UTC, yuyichao commented on base/libgit2/libgit2.jl
> +    cert_file === C_NULL && cert_dir === C_NULL && return
This is still wrong. The function also look very strange. Is it actually setting the envs to `"Cstring(0x0000000000000000)"`?

```julia
julia> ENV["AAA"] = Cstring(C_NULL)
Cstring(0x0000000000000000)

julia> ENV["AAA"]
"Cstring(0x0000000000000000)"
```

The setting of the `ENV` should probably just be folded with the `isdir`/`isfile` check (can they possibly both pass?) and clear the corresponding variable if necessary.

2017-01-31 21:36 UTC, nalimilan commented on base/libgit2/libgit2.jl
> +    cert_file === C_NULL && cert_dir === C_NULL && return
Funny. Cc: @simonbyrne who recently worked on libgit2.

2019-02-15 13:30 UTC, closed without merging