WIP: day of week cleanup
JuliaLang/julia pull request #19212
Opened 2016-11-03 22:36 UTC by simonbyrne

* Make `DayOfWeek` an `Enum`, deprecate `dayofweek`. (#19210)
* Provide optional argument to `firsdayofweek`/`lastdayofweek` (#19208)
* A few misc fixes.

2016-11-04 02:14 UTC, quinnj commented on test/dates/adjusters.jl
> +#@test_throws KeyError Dates.tonext(dt,8)
Are you planning on adding this back in?

2016-11-04 02:15 UTC, quinnj commented
Looking good.

2016-11-04 09:02 UTC, simonbyrne commented on test/dates/adjusters.jl
> +#@test_throws KeyError Dates.tonext(dt,8)
No, it's going to be removed (`tonext` no longer takes integer arguments).

2016-11-04 09:54 UTC, femtotrader commented on test/dates/adjusters.jl
A test with

```julia
@test Dates.firstdayofweek(Dates.DateTime(2013,12,24), firstday=Monday) == Dates.DateTime(2013,12,23)
@test Dates.firstdayofweek(Dates.DateTime(2013,12,24), firstday=Sunday) == Dates.DateTime(2013,12,22)
```

could be a good idea

and a similar test with `lastdayofweek`

Something like

````julia
@test Dates.lastdayofweek(Dates.DateTime(2013,12,24), firstday=Monday) == Dates.DateTime(2013,12,29)
@test Dates.lastdayofweek(Dates.DateTime(2013,12,24), firstday=Sunday) == Dates.DateTime(2013,12,28)
```

2016-11-04 10:43 UTC, simonbyrne commented on test/dates/adjusters.jl
Good call, done.

2016-11-04 10:44 UTC, simonbyrne commented
Okay, hopefully this should be ready. One question is whether the optional arguments to `firstdayofweek`/`lastdayofweek` should be keyword or positional? (I've gone with positional at the moment).

2016-11-04 11:04 UTC, nalimilan commented
`dayname` and `dayabbr` use a keyword argument `locale`, which is conceptually similar. So maybe use a keyword argument here too?

2016-11-04 11:45 UTC, simonbyrne commented
Also, should we deprecate `ismonday`, `istuesday`, etc? These seem like overkill.

2016-11-04 13:27 UTC, quinnj commented
I'd be fine with either positional or keyword + deprecating `ismonday` `istuesday`; those were only there for the `Dates.tonext(dt, ::dayofweek)` calls

2016-11-18 11:55 UTC, simonbyrne commented
Okay, this is rebased and ready to go. Any objections?

2016-11-18 16:16 UTC, simonbyrne commented
@nanosoldier `runbenchmarks("dates", vs = ":master")`

2016-11-18 18:05 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19212#issuecomment-261571746) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/617fc587144c20cc661eeffb6de8c04d093c4285/0ddaec6_vs_51da590/report.md). cc @jrevels

2016-11-18 19:46 UTC, KristofferC commented
That looks like an objection :p

2016-11-18 21:20 UTC, jrevels commented
I'd assume the regressions are from the deprecation right? If that's true, then the slowdown is expected and the benchmark should just be rewritten.

2016-11-18 22:03 UTC, simonbyrne commented
Well, the `firstdayofweek` is legitimately slower, as I changed the function definition slightly.

2017-01-28 18:51 UTC, tkelman commented
Do we still want to do this?

2017-01-28 19:18 UTC, quinnj requested changes
Yes, I'm still in favor of this. I don't think the previously noted performance regression should stop this; we're adding functionality that makes up for it.

2017-01-28 19:18 UTC, quinnj commented on base/dates/query.jl
> +    DayOfWeek(dt::TimeType)
I think I'd like to still keep this lowercase `dayofweek`, it follows the more general pattern in Dates with types being proper-cased and accessors being lowercased.

2017-01-28 19:18 UTC, quinnj commented on doc/stdlib/dates.rst
> +to use all other ``Dates`` functions, you'll need to prefix each function call with an explicit ``Dates.``, e.g. ``Dates.DayOfWeek(dt)``.
Looks like these docs need to be moved from dates.rst.

2022-03-28 20:49 UTC, vtjnash commented
Seems dead?

2022-04-09 17:41 UTC, closed without merging