Rename num/den to numerator/denominator
JuliaLang/julia pull request #19246
Opened 2016-11-07 08:43 UTC by fredrikekre

Fix #19233 

Think I found all the places. Also moved docstrings inline.

2016-11-07 15:21 UTC, StefanKarpinski requested changes
Needs an entry in NEWS.md. Looks good otherwise!

2016-11-07 15:25 UTC, fredrikekre commented
@StefanKarpinski  Link to issue or PR? Seems like all entries in `NEWS.md` are linked to the issue, but in `deprecated.jl` the references are for the PR.

2016-11-07 16:53 UTC, StefanKarpinski commented
I don't think it really matters which as long as there's an entry and a trail of breadcrumbs.

2016-11-07 16:53 UTC, StefanKarpinski approved these changes

2016-11-09 06:39 UTC, fredrikekre commented
I don't have the power of the button, but I think this is all done?

2016-11-09 06:55 UTC, KristofferC commented
LGTM

2016-11-09 09:00 UTC, nalimilan commented on NEWS.md
> +  * `num` and `den` has been deprecated in favor of `numerator` and `denominator` respectively ([#19233]).
has -> have

2016-11-09 09:02 UTC, fredrikekre commented on NEWS.md
> +  * `num` and `den` has been deprecated in favor of `numerator` and `denominator` respectively ([#19233]).
fixed

2016-11-09 16:54 UTC, StefanKarpinski commented
There seems to be a modicum of disagreement on the original issue, so let's that discussion play out before merging this.

2016-11-10 10:20 UTC, martinholters commented
I think that discussion is resolved in favor of the change. Merge?

2016-11-10 14:02 UTC, merged

2016-11-10 14:02 UTC, KristofferC commented
Argh, I think I left the CI skip message in the squash merge. Sorry :/

2016-11-11 17:35 UTC, StefanKarpinski commented
Not your fault: controlling the CI tools via commit messages is an incredibly dump, bad UX design.