Update metaprogramming.rst
JuliaLang/julia pull request #19462
Opened 2016-11-30 16:28 UTC by p-i-

I've added a missing logical step in the exposition of `Expr`. 
Further down I've added a few words of explanation to the `:(:)` vs `:(::)` example which currently risks stalling the reader.

PS I wonder if the code sections under each bullet point can be indented so as to fall within that bullet point. Unfortunately the GitHub "preview" option hangs (i.e. fails to render a preview) so I haven't tried using spaces to do the indentation.

2016-11-30 22:59 UTC, StefanKarpinski requested changes

2016-11-30 22:59 UTC, StefanKarpinski commented on doc/manual/metaprogramming.rst
> +  A symbol is an `interned string <https://en.wikipedia.org/wiki/String_interning>`_
I disagree with the characterization of a Symbol as an "interned string":

http://stackoverflow.com/questions/23480722/what-is-a-symbol-in-julia/23482257#23482257

Maybe use this line instead: "A symbol is used to represent a variable in metaprogramming". I realize you're just moving text around, but I guess we can improve it while we're at it.

2016-11-30 23:19 UTC, p-i- commented on doc/manual/metaprogramming.rst
> +  A symbol is an `interned string <https://en.wikipedia.org/wiki/String_interning>`_
Oh good, I hit a speed bump with that term as well (however as I'm learning a lot of new words with Julia I tend to assume every term is correct). I feel like the word 'Token' is begging to make some appearance.

I get it I think, it's actually really simple.  A Symbol is a meta-variable.  Just as a variable is used to reference and manipulate a value in programming, so a symbol is used to reference and manipulate a variable in metaprogramming.

Would it be acceptable to link to that (or any other) SO page from the doc? (I don't think SO posts are going anywhere).

2016-12-01 09:19 UTC, martinholters commented on doc/manual/metaprogramming.rst
> +  `kind of expression <http://docs.julialang.org/en/release-0.5/devdocs/ast/#expr-types>`_.
This link should probably not be a URL but rather use an RST reference to that section.

2016-12-01 13:59 UTC, tkelman commented on doc/manual/metaprogramming.rst
> +and the token `::` as in `x::Int`:
double backticks here as well

2016-12-01 14:55 UTC, StefanKarpinski commented on doc/manual/metaprogramming.rst
> +  A symbol is an `interned string <https://en.wikipedia.org/wiki/String_interning>`_
Sure, linking to it is ok.

2020-04-30 18:51 UTC, closed without merging