Add tests for ObjectIdDict
JuliaLang/julia pull request #19499
Opened 2016-12-03 20:05 UTC by kshyatt

2016-12-04 17:52 UTC, kshyatt commented
@JeffBezanson looks like you were the last person to touch `ObjectIdDict` - this look OK?

2016-12-05 19:29 UTC, mauro3 commented on test/dict.jl
> +    @test d == ObjectIdDict(1=>1, 2=>2, 3=>3)
Maybe add a `@test eltype(d)==Pair{Any,Any}`?

2016-12-07 02:29 UTC, StefanKarpinski requested changes

2016-12-07 02:29 UTC, StefanKarpinski commented on test/dict.jl
> +    a[a] = 2
Shouldn't we be testing something about what's in `a` after this?

2016-12-07 02:29 UTC, StefanKarpinski commented on test/dict.jl
> +    @test ca == a
Test that they're not the same object? I.e. `ca !=== a`.

2016-12-07 02:29 UTC, StefanKarpinski commented on test/dict.jl
> +    @test length(ca) == 0
Test that `length(a) == 2` still?

2016-12-07 02:44 UTC, yuyichao commented
Note that if you want to test the difference between `Dict` and `ObjectIdDict`, you can probably check that `ObjectIdDict(1=>2, 1.0=>3)` has two entries where as `Dict(1=>2, 1.0=>3)` has only one.

2016-12-09 01:03 UTC, kshyatt commented on test/dict.jl
> +    a[a] = 2
I've addressed all the comments but this one - what's a reasonable looking test for this?

2016-12-09 18:49 UTC, StefanKarpinski approved these changes

2016-12-09 18:49 UTC, merged

2016-12-09 18:53 UTC, StefanKarpinski commented on test/dict.jl
> +    a[a] = 2
Maybe something like this:
```jl
@test length(a) == 2
@test 1 in keys(a)
@test a in keys(a)
@test a[1] === a
@test a[a] === 2
```
In other words check that `a` is the object we thing we've constructed: an associative collection with exactly two keys, which are `1` and `a`, mapped to `a` and `2`, respectively.

2016-12-09 19:33 UTC, tkelman commented
@yuyichao's suggestion was not added here and would still be a good idea

2016-12-09 20:05 UTC, kshyatt commented
@tkelman Doesn't the test I put in at line 395 (struggling to link, I'm on phone, sorry) test that my `ObjectIdDict` has two elements, not one, as @yuyichao suggested? The other statement is one about `Dict`, isn't it?

2016-12-09 20:08 UTC, tkelman commented
Yes but the point there was about testing ObjectIdDict-specific behavior, for which you'd want to test with keys that are equal so would be a single key in a Dict, but have different object id so would be separate keys in an ObjectIdDict.

2016-12-09 20:09 UTC, kshyatt commented
Ah, right, well then I will open a second PR to incorporate that and @StefanKarpinski's suggestion as well.