fix mach spawn fail interrupt
JuliaLang/julia pull request #19590
Opened 2016-12-14 00:38 UTC by vtjnash

I believe this should fix the occasional failure we've seen this past year on the spawn test on macOS where it gets a spurious InterruptException generated by the mach kernel. I guess that's what the man page meant when it said this function could have "unspecified behavior".

2016-12-14 00:43 UTC, tkelman commented on deps/libuv.version
> +LIBUV_SHA1=52d72a52cc7ccd570929990f010ed16e2ec604c
why a partial sha? 52d72a52cc7ccd570929990f010ed16e2ec604c8

2016-12-14 01:12 UTC, yuyichao approved these changes

2016-12-14 01:12 UTC, yuyichao commented on src/signals-unix.c
> +        errno = 0;
This one shouldn't be necessary? Or is this just to help future debugging?

2016-12-21 14:14 UTC, vtjnash commented on src/signals-unix.c
> +        errno = 0;
future debugging

2017-01-03 18:57 UTC, tkelman commented on deps/checksums/libuv-52d72a52cc7ccd570929990f010ed16e2ec604c.tar.gz/md5
> +0e6ec181c8bfd322a17dbd843b2b8ebb
filenames are missing the last char

2017-01-10 16:50 UTC, tkelman requested changes

2017-01-10 16:50 UTC, tkelman commented on .travis.yml
> +    - moreutils/mispipe "make \$BUILDOPTS NO_GIT=1 -C deps 2> deps-err.log" "$BAR" > deps.log ||
Please do not merge this unless you've verified that this branch builds from a completely clean cache. The deps should not need the spawn modification.

2017-01-10 22:55 UTC, closed without merging