RFC: Rewrite homedir based on uv_os_homedir
JuliaLang/julia pull request #19636
Opened 2016-12-17 21:59 UTC by ararslan

Fixes #11331

Rather than relying on environment variables to determine the user's home directory, this calls `uv_os_homedir` from libuv, per @stevengj's suggestion.

The "magic number" of 1024 in there is what we're setting as the `PATH_MAX` if none is found in the system (see [src/support/dirpath.h](https://github.com/JuliaLang/julia/blob/master/src/support/dirpath.h)), so it seemed to me like a decent choice for the number of bytes to allocate for the output path. Let me know if that isn't reasonable or if there's a better choice.

For reference, here is the upstream libuv documentation on `uv_os_homedir`: http://docs.libuv.org/en/v1.x/misc.html#c.uv_os_homedir

2016-12-17 22:14 UTC, yuyichao requested changes
And a better implementation is

```jl
julia> function homedir2()
           sz = Ref{Csize_t}(1024 + 1)
           buf = Vector{UInt8}(sz[] - 1)
           while true
               rc = ccall(:uv_os_homedir, Cint, (Ptr{UInt8}, Ptr{Csize_t}), buf, sz)
               if rc == 0
                   resize!(buf, sz[])
                   return String(buf)
               elseif rc == Base.UV_ENOBUFS # No Base. in base
                   resize!(buf, sz[] - 1)
               else
                   error("Unable to retrieve home directory.")
               end
           end
       end
```

2016-12-17 22:14 UTC, yuyichao commented on base/path.jl
> +    rc == 0 || error("unable to retrieve home directory")
Hard to imagine it will happen but the correct way is to use `sz[] - 1` to resize the array.

2016-12-17 22:14 UTC, yuyichao commented on base/path.jl
> +    sz = Ref{Csize_t}(sizeof(buf))
Should be `sizeof(buf) + 1`

2016-12-17 22:14 UTC, yuyichao commented on base/path.jl
> +    return unsafe_string(pointer(buf[1:nbytes]))
This is wrong and inefficient.

2016-12-17 22:37 UTC, ararslan commented
Thanks for the feedback, @yuyichao!

`String(buf)` causes an error because `Cchar` is `Int8`, not `UInt8`, so `String` can't convert the array. That's why I had initially used `unsafe_string` with `pointer`. Would it be better to convert to `UInt8`, then call the `String` constructor?

2016-12-17 22:52 UTC, yuyichao commented
That s why I used UInt8

2016-12-17 22:53 UTC, ararslan commented
Oh sorry! Missed that part.

2016-12-18 19:20 UTC, ararslan commented
Looking better, @yuyichao?

2016-12-18 20:12 UTC, yuyichao approved these changes

2016-12-18 20:20 UTC, merged

2017-03-13 04:52 UTC, asampal commented
With this change, is there any way to override the value that homedir() will return from the OS for homedir? I'd like my Julia homedir to be the home directory under my MSYS2/MinGW installation instead of the standard user dir Windows defines.

2017-03-13 12:10 UTC, stevengj commented
@asampal, yes.  From the [libuv documentation](http://docs.libuv.org/en/v1.x/misc.html):

> Gets the current user’s home directory. On Windows, uv_os_homedir() first checks the USERPROFILE environment variable using GetEnvironmentVariableW(). If USERPROFILE is not set, GetUserProfileDirectoryW() is called. On all other operating systems, uv_os_homedir() first checks the HOME environment variable using getenv(3). If HOME is not set, getpwuid_r(3) is called. The user’s home directory is stored in buffer. When uv_os_homedir() is called, size indicates the maximum size of buffer. On success size is set to the string length of buffer. On UV_ENOBUFS failure size is set to the required length for buffer, including the null byte.

2017-03-13 22:11 UTC, asampal commented
@stevengj if I redefine `USERPROFILE` in `juliarc.jl` I can get `homedir()` as I need it, but this will be overwritten by a new install.  I can't use `.juliarc.jl`, to set the home dir, obviously, and this isn't an env variable that should be changed globally (actually marked as read-only).  So without running Julia using a batch file, there's no other option?