More backticks/refs for manual and add docs about references
JuliaLang/julia pull request #19702
Opened 2016-12-23 21:56 UTC by kshyatt

2016-12-23 22:05 UTC, MichaelHatherly commented on doc/src/manual/documentation.md
> +between two similar-seeming functions.
Should make it clear here that `@ref` is not markdown syntax, and requires use of Documenter. (Might better to mention this kind of thing in CONTRIBUTING.md instead?)

2016-12-23 22:44 UTC, kshyatt commented on doc/src/manual/documentation.md
> +between two similar-seeming functions.
Why not both? If I were looking for "how to document Julia code and add cross-refs" I'd look at the manual too.

2016-12-23 23:31 UTC, tkelman commented on doc/src/manual/documentation.md
> +It's also possible to add cross-references to other documented functions/methdods/variables within
methods misspelled

2016-12-23 23:35 UTC, kshyatt commented on doc/src/manual/documentation.md
> +It's also possible to add cross-references to other documented functions/methdods/variables within
Nice job, self

2016-12-24 00:55 UTC, kshyatt commented
Good to go if CI passes?

2016-12-24 01:01 UTC, tkelman commented on doc/src/manual/documentation.md
> +The above cross referencing is *not* a Markdown feature, and relies on
does the body of this need indenting?

2016-12-24 05:13 UTC, kshyatt commented on doc/src/manual/documentation.md
> +The above cross referencing is *not* a Markdown feature, and relies on
Yep.

2016-12-24 10:11 UTC, MichaelHatherly requested changes

2016-12-24 10:11 UTC, MichaelHatherly commented on doc/src/manual/modules.md
> +3. Expecting the filesystem to be unchanged between compile-time and runtime e.g. [`@__FILE__`](@ref)/[`source_path()`](@ref)
`source_path` isn't exported (see https://travis-ci.org/JuliaLang/julia/jobs/186485491#L771) so will need to be written as `` [`Base.source_path`](@ref) `` to be visible to Documenter.

2016-12-24 16:42 UTC, kshyatt commented on doc/src/manual/modules.md
> +3. Expecting the filesystem to be unchanged between compile-time and runtime e.g. [`@__FILE__`](@ref)/[`source_path()`](@ref)
I think I got it this time?

2016-12-26 20:51 UTC, MichaelHatherly commented on doc/src/manual/modules.md
> +3. Expecting the filesystem to be unchanged between compile-time and runtime e.g. [`@__FILE__`](@ref)/[`source_path()`](@ref)
Actually, `source_path` isn't documented at all as far as I can see, so we can't have a reference to it.

2016-12-27 19:36 UTC, kshyatt commented
@MichaelHatherly Is this ok to go?

2016-12-27 19:42 UTC, MichaelHatherly approved these changes

2016-12-27 19:42 UTC, merged