types.jl: sleep with Date.Period types
JuliaLang/julia pull request #19749
Opened 2016-12-29 04:48 UTC by Shade5

Supports sleep(Dates.Second(10))
		 sleep(Dates.Milliesecond(10))

Closes #19736

2016-12-29 05:04 UTC, TotalVerb requested changes
Thanks for the contribution! A few comments:

As is, this will only work for seconds and milliseconds. That's what I asked for, but it can be made more generic. There's a `Dates.toms` function that takes any fixed-length `Dates.Period` and gives the number of milliseconds it represents. I would therefore suggest writing

```julia
sleep(time::Dates.Period) = sleep(Dates.toms(time) / 1000)
```

Also, in addition to `sleep`, there are functions like `Timer`, `timedwait` that could receive the same treatment.

I also think that this is not the right file to define these methods in. Could these methods be moved near the other methods for these functions?

As for tests, `sleep` is not easy to test properly. But I think having a test that the call does not raise an error is useful. One could do

```julia
@test sleep(Dates.Millisecond(10)) === nothing
```

Finally, make sure the file ends in a new line character. If it doesn't, it's likely that Travis will reject the PR.

2016-12-29 05:26 UTC, Shade5 commented
@TotalVerb I'll make it more generic as you suggested and also include timer and timedwait.
I tried defining these new functions near the old ones but the problem is that while building julia the Date module is not defined yet while the time modules are being built. Thus I had to move it to the Date module

2016-12-29 05:29 UTC, TotalVerb commented
You could consider moving the loading of `Dates` in `sysimg.jl`, line 357, a little earlier. Is there a reason why `Dates` is loaded so late? cc @quinnj

2016-12-29 06:12 UTC, TotalVerb commented
Note that the `repeat` argument for `Timer` is also a time.

2016-12-29 07:11 UTC, Shade5 commented
So, I'll have to add three more functions
```
Timer(time::Dates.Period, repeat::Real=0.0)
Timer(time::Real, repeat::Dates.Period=0.0)
Timer(time::Dates.Period, repeat::Dates.Period=0.0)
```
?

2016-12-29 07:14 UTC, TotalVerb commented
I think it would be very confusing to mix real numbers and quantities with units. I would just define a single method for both arguments being `Dates.Period`.

2016-12-29 08:19 UTC, Shade5 commented
Done!

2016-12-29 08:29 UTC, tkelman commented on base/dates/types.jl
> +sleep(time::Dates.Period) = sleep(Dates.toms(time) / 1000)
don't need `Dates.` while inside the `Dates` module

2016-12-29 08:54 UTC, Shade5 commented on base/dates/types.jl
> +sleep(time::Dates.Period) = sleep(Dates.toms(time) / 1000)
My bad, Fixed it

2016-12-29 10:45 UTC, TotalVerb requested changes

2016-12-29 10:45 UTC, TotalVerb commented on base/dates/types.jl
> +Timer(time::Period, repeat::Period=0.0) = Timer(toms(time) / 1000,toms(repeat) / 1000)
I don't think `0.0` will convert properly to `Period`. Use `Second(0)` as the default instead.

2016-12-29 10:45 UTC, TotalVerb commented on base/dates/types.jl
> +timedwait(testcb::Function, time::Period, pollint::Float64) = timedwait(testcb, toms(time) / 1000, pollint)
`pollint` is supposed to be a keyword argument; it's also a time.

2016-12-29 12:00 UTC, Shade5 commented on base/dates/types.jl
> +timedwait(testcb::Function, time::Period, pollint::Float64) = timedwait(testcb, toms(time) / 1000, pollint)
Changed!

2016-12-29 22:22 UTC, TotalVerb requested changes

2016-12-29 22:22 UTC, TotalVerb commented on base/dates/types.jl
> +timedwait(testcb::Function, time::Period, pollint::Period) = timedwait(testcb, toms(time) / 1000, toms(pollint) / 1000)
The signature is still not correct. Keyword arguments should be delimited like

`timedwait(testcb, time::Period; pollint::Period=Millisecond(100)) = ...`

2016-12-29 22:27 UTC, TotalVerb commented
Please add some tests that these methods work properly. See `test/channels.jl` for a good way to test timedwait; alternatively, it should also work just to test that these methods work at all.

2016-12-30 08:21 UTC, Shade5 commented
@TotalVerb Where are the default tests for sleep and Timer? I've tried, but I can't find them.

2016-12-30 10:24 UTC, TotalVerb commented
There are no tests specifically for `sleep` and `Timer`, but it should be enough to test the `sleep(Dates.Millisecond(60))` version in `threads.jl`, replacing the existing `sleep(0.06)` calls.

2016-12-30 10:47 UTC, Shade5 commented
Alright, I'll add the tests, there seems to be a problem with timedwait. I've posted it on gitter.

2017-01-01 04:11 UTC, Shade5 commented
Added tests

2017-01-01 04:14 UTC, TotalVerb commented
It would be better to avoid duplicating test code. Consider instead a `for` loop;

```julia
for period in (0.06, Dates.Millisecond(60))
    ... # testing code goes here, using `Timer(period)` / `sleep(period)`
end
```

2017-01-01 06:50 UTC, Shade5 commented
I didn't add the test for timedwait in a forloop as the log output was different

2017-01-01 10:15 UTC, Shade5 commented
Anything else?

2017-01-01 22:26 UTC, TotalVerb requested changes

2017-01-01 22:26 UTC, TotalVerb commented on test/channels.jl
> +        warn("timedwait-Period tests delayed. et=$et, isready(rr3)=$(isready(rr3))")
No need for this `-Period` here.

2017-01-01 22:27 UTC, TotalVerb commented
@tkelman I suppose since it is now past feature freeze, this will have to wait until 1.0, right?

2017-01-02 03:18 UTC, Shade5 commented on test/channels.jl
> +        warn("timedwait-Period tests delayed. et=$et, isready(rr3)=$(isready(rr3))")
:+1:

2017-01-02 04:47 UTC, musm commented on test/channels.jl
> +    timedwait(callback, Dates.Second(1))
why is this necessary, shouldn't `timedwait(callback, 1.0)` still work?

2017-01-02 06:00 UTC, Shade5 commented on test/channels.jl
> +    timedwait(callback, Dates.Second(1))
As TotalVerb said, The Period version dispatches to the Real version anyway.

2017-01-02 08:14 UTC, TotalVerb commented
Travis failure is https://github.com/JuliaLang/julia/issues/19792.

2017-01-02 08:27 UTC, Shade5 commented
@TotalVerb Should I do anything?

2017-01-03 20:53 UTC, StefanKarpinski approved these changes

2017-01-03 20:54 UTC, merged