Limit broadcast mechanism over Nullables
JuliaLang/julia pull request #19787
Opened 2016-12-31 00:13 UTC by pabloferz

This should address @JeffBezanson's concerns over #16961. That is `broadcasting` over `Nullable`s treats them as containers only when mixed with scalars. I people need to work with arrays the can use comprehensions, e.g.

```julia
[x .+ 1 for x in [Nullable(1), Nullable(2)]]
```

If someone is relying heavily on arrays or `Nullable`s they probably should be using `NullableArrays` instead.

CC. @TotalVerb

2016-12-31 00:18 UTC, TotalVerb commented
I'm ok with this limitation to scalars, as was @johnmyleswhite in the other issue.

cc @nalimilan @Sacha0 @ararslan

2016-12-31 00:24 UTC, TotalVerb requested changes
Needs modification of NEWS.md and the manual, in the section on Nullables.

2016-12-31 00:44 UTC, JeffBezanson commented
My hero! Thank you.

2016-12-31 00:52 UTC, tkelman commented on base/broadcast.jl
> +The following additional rule apply to `Nullable` arguments:
rule applies

2016-12-31 01:00 UTC, andreasnoack commented
This seems to simplify things so 👍. One thing that would be great to include in future design considerations for the broadcasting code would be extensibility beyond base. I.e. how user defined arrays should overload broadcast methods. I've been working on such a case in https://github.com/JuliaParallel/DistributedArrays.jl/pull/120 and although it wasn't too hard with the current structure, it didn't feel like extensibility beyond base had been a priority.

2016-12-31 06:42 UTC, tkelman commented on test/broadcast.jl
> +    String(take!(io)) == "Nullable{Float64}(1.0)"
missing `@test`

2016-12-31 06:44 UTC, tkelman commented on base/broadcast.jl
> +_broadcast_type(f, A, Bs...) = Base._default_eltype(Base.Generator{ziptype(A, Bs...), ftype(f, A, Bs...)})
this is used a couple of times in the new sparse code that I suspect you'll have to change

2016-12-31 07:57 UTC, tkelman commented on base/sparse/higherorderfns.jl
> +    entrytypeC = Base.Broadcast._broadcast_type(f, A, Bs...)
(should be squashed on merge to avoid broken intermediate commits)

2016-12-31 14:41 UTC, nalimilan commented on base/broadcast.jl
>   - If there is at least a `Nullable`, and all the arguments are scalars or
Remove the list since there's only one bullet.

2016-12-31 14:54 UTC, nalimilan commented on test/broadcast.jl
> +    @test String(take!(io)) == "Nullable{Float64}(1.0)"
Sounds a bit weird to use string comparison to test the type of the result. Why not e.g. call `push!` to add values to a vector instead?

2016-12-31 19:57 UTC, pabloferz commented on base/sparse/higherorderfns.jl
> +    entrytypeC = Base.Broadcast._broadcast_type(f, A, Bs...)
Already squashed it to prevent that.

2016-12-31 20:46 UTC, pabloferz commented
I think this is ready, unless there are more comments/concerns.

2016-12-31 20:46 UTC, TotalVerb commented
Thanks for doing this work. This still needs an update to doc/src/manual/types.md.

2016-12-31 20:49 UTC, Sacha0 commented
> I think this is ready, unless there are more comments/concerns.

Hoping to review shortly (beginning within the next fifteen minutes). Best!

2016-12-31 21:13 UTC, TotalVerb requested changes

2016-12-31 21:13 UTC, TotalVerb commented on base/broadcast.jl
>  # if the first argument is Any, then Nullable should be treated like a
Delete this comment.

2016-12-31 21:13 UTC, TotalVerb commented on base/broadcast.jl
>  import Base: broadcast, broadcast!
I think the `is_nullable_array` import can be removed, and probably the function itself too (in `base/nullable.jl`).

2016-12-31 21:13 UTC, TotalVerb commented on base/broadcast.jl
> -that is not a subtype of `AbstractArray`, `Ref` (except for `Ptr`s) or `Tuple`,
I don't think `Nullable` should be removed from this paragraph.

2016-12-31 21:37 UTC, TotalVerb approved these changes
LGTM. Thanks again!

2016-12-31 21:48 UTC, Sacha0 commented on base/broadcast.jl
>  Broadcasts the arrays, tuples, `Ref`, nullables, and/or scalars `As` to a
Not from this pull request, but should ``` `Ref` ``` be plural ``` `Ref`s ``` for consistency?

2016-12-31 21:52 UTC, Sacha0 commented on base/broadcast.jl
> +that is not a subtype of `AbstractArray`, `Ref` (except for `Ptr`s), `Tuple`
(Serial/Oxford) comma after `Tuple`?

2016-12-31 21:56 UTC, Sacha0 commented on base/broadcast.jl
>     as a 1-dimensional array) expanding singleton dimensions.
Not from this pull request, but perhaps "If there is at least an array or a `Ref` in the arguments" -> "If there is at least one array or `Ref` in the arguments"? Similarly, perhaps "and treats any `Ref` as a 0-dimensional array of its contents and any tuple as a 1-dimensional array" -> "and treats `Ref`s as 0-dimensional arrays, and tuples as 1-dimensional arrays"?

2016-12-31 21:59 UTC, Sacha0 commented on base/broadcast.jl
> +least a `Nullable`, and all the arguments are scalars or `Nullable`, it returns
Perhaps "at least a" should be "at least one"?

2016-12-31 22:05 UTC, Sacha0 commented on test/broadcast.jl
> +# broadcast should only "peel off" one container layer
A simpler way to test this behavior might be nice if you can think of one?

2016-12-31 22:10 UTC, Sacha0 approved these changes
I am in no way qualified to provide feedback on the Nullable behavior change's desirability, but this pull request's mechanics LGTM! Thanks `@pabloferz`!

2016-12-31 22:13 UTC, TotalVerb commented on test/broadcast.jl
> +# broadcast should only "peel off" one container layer
`get.([Nullable(1), Nullable(2)]) == [1, 2]` will work as a simpler test.

2016-12-31 22:57 UTC, pabloferz commented on test/broadcast.jl
> +# broadcast should only "peel off" one container layer
Unfortunately I don't have much time for looking for better/simpler tests for today. Maybe we could revisit them another occasion?

2016-12-31 23:03 UTC, Sacha0 commented on test/broadcast.jl
> +# broadcast should only "peel off" one container layer
If `@TotalVerb`'s suggestion does not suffice, sounds good on this end. Best!

2016-12-31 23:42 UTC, pabloferz commented on test/broadcast.jl
> +# broadcast should only "peel off" one container layer
That should work fine. Test added.

2017-01-01 00:50 UTC, tkelman commented on base/broadcast.jl
> +   and tuples as a 1-dimensional arrays.
tuples as 1-element arrays

(can ci skip this if you do make check-whitespace locally)

2017-01-01 00:52 UTC, tkelman commented on base/broadcast.jl
> +   and tuples as a 1-dimensional arrays.
dimensional, not element, sorry - just drop the a now that arrays is plural

2017-01-01 01:59 UTC, tkelman commented
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

2017-01-01 05:40 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19787#issuecomment-269889366) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ed6d58958ba59605374eacfd6a3c628c2c66f913/290dd1e_vs_d9318d5/report.md). cc @jrevels

2017-01-01 05:56 UTC, merged

2017-01-01 13:45 UTC, tkelman commented
Looks like that i686 assertion failure "Cannot define a symbol twice!" in the reflection test is repeatable and has been happening since I merged this. Similar to #19792? I'll propose dropping back to LLVM 3.7 for now as a band-aid.

2017-01-02 11:04 UTC, tkelman commented
I don't get why nanosoldier here said "no regressions" but when run on the merged version against its immediate parent commit there were some big regressions - https://github.com/JuliaCI/BaseBenchmarkReports/blob/a1fd436b6823d8e27c7bc1cf3be1b8c1f212bde7/f147aaa_vs_b2ae5a5/report.md

I guess the intervening couple of commits that were merged to master between the time the PR run started and this was merged interacted badly here?

2017-01-02 14:44 UTC, pabloferz commented
That's strange, the code in this PR does not touch any code related to those regressions.

2017-01-02 20:47 UTC, TotalVerb commented
I too don't see how a change to broadcasting can possibly affect comprehensions.