Run non-Julia finalizers at exit
JuliaLang/julia pull request #19911
Opened 2017-01-06 23:37 UTC by barche

It seems function-pointer finalizers are not run at exit. The example at the bottom of this comment illustrates the problem, the proposed fix here makes that work but crashes on an MPFR test in make test-all:

```
signal (11): Segmentation fault
while loading no file, in expression starting on line 0
mpfr_clear at /usr/lib/libmpfr.so (unknown line)
jl_gc_run_finalizers_in_list at /home/bjanssens/src/julia/julia/src/gc.c:199 [inlined]
run_finalizers at /home/bjanssens/src/julia/julia/src/gc.c:229 [inlined]
jl_gc_run_all_finalizers at /home/bjanssens/src/julia/julia/src/gc.c:266
jl_atexit_hook at /home/bjanssens/src/julia/julia/src/init.c:223
jl_exit at /home/bjanssens/src/julia/julia/src/jl_uv.c:554
exit at ./initdefs.jl:22
unknown function (ip: 0x7f4d3eda2c08)
jl_call_method_internal at /home/bjanssens/src/julia/julia/src/julia_internal.h:246 [inlined]
jl_apply_generic at /home/bjanssens/src/julia/julia/src/gf.c:2198
jl_apply at /home/bjanssens/src/julia/julia/src/julia.h:1388 [inlined]
jl_f__apply at /home/bjanssens/src/julia/julia/src/builtins.c:548
#512 at ./multi.jl:1488
run_work_thunk at ./multi.jl:1024
#511 at ./event.jl:66
jl_call_method_internal at /home/bjanssens/src/julia/julia/src/julia_internal.h:246 [inlined]
jl_apply_generic at /home/bjanssens/src/julia/julia/src/gf.c:2198
jl_apply at /home/bjanssens/src/julia/julia/src/julia.h:1388 [inlined]
start_task at /home/bjanssens/src/julia/julia/src/task.c:261
```

Clearly I did something wrong, but I'm out of ideas, so there goes my great plan to fix this myself :)

Example C code:
```c++
#include <iostream>

extern "C"
{

int c_int = 0;

}

struct PrintDestruction
{
  ~PrintDestruction()
  {
    std::cout << "final c_int is " << c_int << std::endl;
  }

  static PrintDestruction& instance()
  {
    static PrintDestruction m_instance;
    return m_instance;
  }

private:
  PrintDestruction()
  {
    std::cout << "initial c_int is " << c_int << std::endl;
  }
};

extern "C"
{

int get_c_int(void)
{
    return c_int;
}

void set_c_int(int i)
{
    c_int = i;
    PrintDestruction::instance();
}

void finalizer_cptr(void* v)
{
  std::cout << "Running C finalizer" << std::endl;
  set_c_int(-1);
}

}

```

Example Julia code:
```julia
using Base.Test

const libccalltest = joinpath(dirname(@__FILE__),"finalizers")

let A = [1]
    ccall((:set_c_int, libccalltest), Void, (Cint,), 1)
    @test ccall((:get_c_int, libccalltest), Cint, ()) == 1
    finalizer(A, cglobal((:finalizer_cptr, libccalltest), Void))
end

```

2017-01-06 23:47 UTC, yuyichao requested changes

2017-01-06 23:47 UTC, yuyichao commented on src/gc.c
> +        schedule_finalization(v, f);
This is wrong. You have to run the finalizer instead of pushing it to the list.

2017-01-06 23:53 UTC, yuyichao commented
And the correct fix should be

```diff
diff --git a/src/gc.c b/src/gc.c
index 83a22e9..4bde4b4 100644
--- a/src/gc.c
+++ b/src/gc.c
@@ -246,6 +246,9 @@ static void schedule_all_finalizers(arraylist_t *flist)
         if (!gc_ptr_tag(v, 1)) {
             schedule_finalization(v, f);
         }
+        else {
+            ((void (*)(void*))f)(gc_ptr_clear_tag(v, 1));
+        }
     }
     flist->len = 0;
 }
```

2017-01-06 23:54 UTC, barche commented
@yuyichao That's actually the first thing I tried, but it gave the same segfault in the MPFR test, again at the line that calls the non-Julia finalizer. I'm wondering if that segfault was just hidden because the finalizer didn't get called...

2017-01-06 23:57 UTC, barche commented
I didn't do the `gc_ptr_clear_tag` though, so maybe that was it.

2017-01-07 00:00 UTC, yuyichao commented
At least your version segfault because it didn't clear the pointer tag and I imagine that's the issue in your other versions too. You didn't see that in you test case because you didn't actually read the pointer.

The use of tagged pointers and the restrictions of them in `to_finalize` is [documented](https://github.com/JuliaLang/julia/blob/77dfb35188cb329196e2e72c7a08ecf02e801355/src/gc.c#L56) in the code comment.

2017-01-07 00:22 UTC, barche commented
Confirmed, this works without segfault on my machine. To be sure, the fact that the `gc_ptr_clear_tag` is missing [here](https://github.com/JuliaLang/julia/blob/77dfb35188cb329196e2e72c7a08ecf02e801355/src/gc.c#L1632) is not a bug, right?

2017-01-07 00:40 UTC, yuyichao commented
https://github.com/JuliaLang/julia/blob/77dfb35188cb329196e2e72c7a08ecf02e801355/src/gc.c#L1603

2017-01-07 00:41 UTC, yuyichao approved these changes

2017-01-07 08:24 UTC, tkelman commented
Should we add the test case to libccalltest?

2017-01-07 08:39 UTC, yuyichao commented
We don't need to add those to `libccalltest`. Mainly need to launch a separate process to test this.

2017-01-08 20:51 UTC, barche commented
Thanks for the comments and the explanations. I didn't add the test because I have no idea how to automate it, maybe it's possible to set the exit state in the finalizer or something?

2017-01-08 22:40 UTC, yuyichao commented
You can print something `jl_safe_printf` in a C finalizer and check the output of a separate julia process that adds that C finalizer to a global variable.

2017-01-11 22:29 UTC, barche commented
I have added a test. I used `fprintf`, not sure if that's OK, but the output was not captured by `readstring` when using `jl_safe_printf`.

2017-01-11 22:50 UTC, yuyichao commented
`fprintf` or `printf` are fine (as long as it's not `jl_printf`). `jl_safe_printf` prints to `STDERR` so you need to capture that if you use it... The test should ideally also check the pointer. I would probably use it on a `Ref{Cint}(42)` and do `printf("c_exit_finalizer: %d, %u\n", *(int*)v, ((unsigned)(uintptr_t)v) & 0xf);` and check if the output is `c_exit_finalizer: 42, 0`.

2017-01-12 04:32 UTC, tkelman commented on test/ccall.jl
> +  @test result == "c_exit_finalizer"
4 space indent

2017-01-12 04:32 UTC, tkelman commented on test/ccall.jl
> +let result = readstring(`$(Base.julia_cmd()) -e "A = [1]; finalizer(A, cglobal((:c_exit_finalizer, \"$libccalltest\"), Void))"`)
add `--startup-file=no`

2017-01-12 14:12 UTC, barche commented
OK, done!

2017-01-13 17:33 UTC, barche commented
I did one more update because the pointer tag check failed on 32 bit.

2017-01-13 17:51 UTC, yuyichao approved these changes

2017-01-13 17:51 UTC, yuyichao commented on src/ccalltest.c
> +    printf("c_exit_finalizer: %d, %u", *(int*)v, (unsigned)((uintptr_t)v & (uintptr_t)1));
This can be `3` but this is also good enough...

2017-01-19 17:49 UTC, tkelman commented
Can we merge this then?

2017-01-19 17:53 UTC, merged