Add show methods for remotes and tags
JuliaLang/julia pull request #19955
Opened 2017-01-09 22:05 UTC by kshyatt

Re: #19839

2017-01-11 12:45 UTC, simonbyrne requested changes

2017-01-11 12:45 UTC, simonbyrne commented on base/libgit2/remote.jl
> +Base.show(io::IO, rmt::GitRemote) = print(io, "Remote name: ", name(rmt), " url: ", url(rmt))
I would suggest printing the name of the type.

2017-01-11 20:24 UTC, simonbyrne approved these changes

2017-01-15 17:22 UTC, merged

2017-01-16 02:24 UTC, tkelman commented on base/libgit2/tag.jl
> +Base.show(io::IO, tag::GitTag) = print(io, "GitTag:\nTag name: $(name(tag)) target: $(target(tag))")
kinda inconsistent to have one of these use interpolation and the other use multi-arg print

2017-01-16 02:25 UTC, tkelman commented on base/libgit2/remote.jl
> +    name_ptr == C_NULL && return ""
is it valid to have empty-name or empty-url remotes?

2017-01-16 15:04 UTC, kshyatt commented on base/libgit2/remote.jl
> +    name_ptr == C_NULL && return ""
You can have `Anonymous` remotes, can't you?

2017-01-16 15:05 UTC, kshyatt commented on base/libgit2/remote.jl
> +    name_ptr == C_NULL && return ""
Like [this](https://libgit2.github.com/libgit2/#HEAD/group/remote/git_remote_create_anonymous).

2017-01-16 15:14 UTC, tkelman commented on base/libgit2/remote.jl
> +    name_ptr == C_NULL && return ""
Is that the only thing that can result in getting a null pointer back from this function?