Trial run of adding newbase back
JuliaLang/julia pull request #19970
Opened 2017-01-10 20:00 UTC by kshyatt

Addresses part of #19839

2017-01-10 20:09 UTC, ararslan commented on base/libgit2/libgit2.jl
> +        end
This seems stylistically different than what's around elsewhere in Base (or maybe it's just that the `else` and `end` aren't in the same column that's bugging me). Perhaps something like
```julia
onto_ann = if isempty(newbase)
    Nullable{GitAnnotated}()
else
    Nullable{GitAnnotated}(GitAnnotated(repo, newbase))
end
```
would be acceptable? Not really a big deal.

2017-01-10 20:22 UTC, dmbates commented on base/libgit2/libgit2.jl
> +        end
or
```jl
onto_ann = isempty(newbase) ? Nullable{GitAnnotated}() :
    Nullable{GitAnnotated}(GitAnnotated(repo, newbase))
```

2017-01-11 10:36 UTC, simonbyrne requested changes
Maybe add a test as well?

2017-01-11 10:36 UTC, simonbyrne commented on base/libgit2/libgit2.jl
>  otherwise from the upstream tracking branch.
describe what `newbase` does here.

2017-01-11 10:36 UTC, simonbyrne commented on base/libgit2/libgit2.jl
> +        end
Or even change the `onto` argument in `GitRebase` to accept a `Union{Void, GitAnnotated}`? I don't think the cost of dynamic dispatch is going to be to burdensome.

2017-01-11 17:25 UTC, kshyatt commented
I'm a bit confused about how to test this, honestly.

2017-01-12 09:31 UTC, simonbyrne commented
Ideally, I guess, we could compare the results to command line git.
(to be honest though, I'm still not 100% sure what exactly this option is supposed to do)

2017-01-12 12:25 UTC, tkelman commented
what does this correspond to in the libgit2 api? if they don't have it documented we can bug them about it

2017-01-18 16:40 UTC, kshyatt commented
Test added!

2017-01-18 16:41 UTC, kshyatt commented on base/libgit2/libgit2.jl
> +        end
Better now?

2017-01-18 18:29 UTC, ararslan commented
> I don't know if we want ASCII art in the docstring?

Since these functions aren't exported from Base, I think they're more for people who know what they're doing. As such, I wouldn't think we need that level of detail in the docstrings. If anything, we could simply link to the relevant page in the Git documentation.

2017-01-18 20:32 UTC, simonbyrne commented on base/libgit2/libgit2.jl
> +`newbase` is the branch to rebase onto, or `NULL` to rebase onto the given `upstream`.
maybe:
```
`newbase` is the branch to rebase onto, by default this is `upstream`.
```

2017-01-18 20:33 UTC, simonbyrne commented
LGTM other than the doc wording.

2017-01-19 15:28 UTC, simonbyrne approved these changes

2017-01-19 21:45 UTC, merged