minimal hook into loading necessary for Pkg3
JuliaLang/julia pull request #20008
Opened 2017-01-13 01:42 UTC by StefanKarpinski

This is a less disruptive alternative to https://github.com/JuliaLang/julia/pull/19910 and https://github.com/JuliaLang/julia/pull/19866. Doesn't really change anything, just makes how code gets loaded extensible via putting things that aren't Strings in `LOAD_PATH` and defining appropriate methods for `Base.load_hook`.

2017-01-13 05:28 UTC, tkelman commented on base/initdefs.jl
>  An array of paths (as strings) where the `require` function looks for code.
needs some doc updating

2017-01-13 05:29 UTC, tkelman commented on test/loading.jl
> +empty!(LOAD_PATH)
should probably restore prior value when done?

2017-01-13 06:05 UTC, tkelman commented on base/reflection.jl
> +function find_source_file(file::String)
does this get called on package code?

2017-01-13 06:18 UTC, tkelman commented on base/loading.jl
> -function find_in_path(name::String, wd)
Blink, PkgDev, and node-julia are using the 2 arg version of this. And ClobberingReload is using find_in_node_path. deprecate?

2017-01-13 13:09 UTC, StefanKarpinski commented on base/loading.jl
> -function find_in_path(name::String, wd)
Ok, will do.

2017-01-13 16:08 UTC, tkelman commented on base/reflection.jl
> +function find_source_file(file::String)
calling edit on a method from a package?

2017-01-14 02:54 UTC, tkelman requested changes
The change to `find_source_file` breaks `edit("Example.jl")`. 2-arg `find_in_path`, and `find_in_node_path` should be deprecated.

2017-01-20 00:19 UTC, closed without merging

2017-01-20 00:20 UTC, StefanKarpinski commented
Closed in favor of https://github.com/JuliaLang/julia/pull/20120