isapprox with nans keyword (issue 19936)
JuliaLang/julia pull request #20022
Opened 2017-01-13 21:35 UTC by JeffreySarnoff

2017-01-13 21:49 UTC, StefanKarpinski requested changes
Maybe add a test for isapprox over arrays containing NaNs too?

2017-01-13 21:49 UTC, StefanKarpinski commented on test/floatfuncs.jl
> +    @test isapprox(nan, nan, nans=true) == true7
typo:`true7`?

2017-01-13 22:36 UTC, StefanKarpinski commented on test/floatfuncs.jl
> +    nan  = elty(NaN)
I don't think these tests mean what you want them to mean anymore.

2017-01-13 22:41 UTC, JeffreySarnoff commented on test/floatfuncs.jl
> +    nan  = elty(NaN)
oops

2017-01-13 22:59 UTC, tkelman commented on base/floatfuncs.jl
> +`nans` is false, meaning `isapprox(NaN,NaN) == false`; call with `nans=true` to have `isapprox(NaN,NaN) == true`.
describe what the keyword argument does before saying what its default is?

2017-01-13 23:00 UTC, tkelman commented on test/floatfuncs.jl
> +    @test isapprox(nan, nan) == false
I'd just `@test !isapprox(nan, nan)` instead of comparing to true/false

2017-01-13 23:10 UTC, StefanKarpinski commented
There's some trailing whitespace added here, otherwise it looks good!

2017-01-13 23:10 UTC, StefanKarpinski approved these changes

2017-01-13 23:37 UTC, StefanKarpinski commented
I would not add a new test file unless there are a lot of tests. You've also forgotten to git add the test file.

2017-01-13 23:41 UTC, JeffreySarnoff commented
That test file already existed -- I just found it
https://github.com/JeffreySarnoff/julia/edit/js/isapprox/test/floatapprox.jl

On Fri, Jan 13, 2017 at 6:37 PM, Stefan Karpinski <notifications@github.com>
wrote:

> I would not add a new test file unless there are a lot of tests. You've
> also forgotten to git add the test file.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JuliaLang/julia/pull/20022#issuecomment-272577102>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABmqxnCd01QGiFgD-Vum9Sathre2RD6Oks5rSAq_gaJpZM4LjVXb>
> .
>

2017-01-13 23:44 UTC, StefanKarpinski commented
Ah, ok. I see you added the tests back now. Carry on.

2017-01-14 02:39 UTC, tkelman commented on base/floatfuncs.jl
> +    x == y || (isfinite(x) && isfinite(y) && abs(x-y) <= atol + rtol*max(abs(x), abs(y))) || (nans && (isnan(x) & isnan(y)))
are there cases where it's faster to not short-circuit?

2017-01-14 03:00 UTC, StefanKarpinski commented
Introduces trailing white space, which is a failure.

2017-01-14 03:01 UTC, StefanKarpinski commented on base/floatfuncs.jl
> +    x == y || (isfinite(x) && isfinite(y) && abs(x-y) <= atol + rtol*max(abs(x), abs(y))) || (nans && (isnan(x) & isnan(y)))
I don't think this is a particularly performance-critical operation.

2017-01-14 03:03 UTC, tkelman commented on base/floatfuncs.jl
> +    x == y || (isfinite(x) && isfinite(y) && abs(x-y) <= atol + rtol*max(abs(x), abs(y))) || (nans && (isnan(x) & isnan(y)))
almost certainly isn't, may as well be consistent with the other comparisons in this condition

2017-01-14 03:05 UTC, tkelman commented on base/floatfuncs.jl
> +`nans` is false, meaning `isapprox(NaN,NaN) == false`; call with `nans=true` to have `isapprox(NaN,NaN) == true`.
How about "Keyword argument `nans` (defaults to false) determines whether or not `NaN` values are considered equal to one another."  ?

2017-01-14 03:05 UTC, JeffreySarnoff commented
do you mean (nans && isnan(x) && isnan(y))?

On Fri, Jan 13, 2017 at 10:03 PM, Tony Kelman <notifications@github.com>
wrote:

> *@tkelman* commented on this pull request.
> ------------------------------
>
> In base/floatfuncs.jl <https://github.com/JuliaLang/julia/pull/20022>:
>
> > @@ -188,8 +189,8 @@ approximately equal component-wise.
>  The binary operator `≈` is equivalent to `isapprox` with the default arguments, and `x ≉ y`
>  is equivalent to `!isapprox(x,y)`.
>  """
> -function isapprox(x::Number, y::Number; rtol::Real=rtoldefault(x,y), atol::Real=0)
> -    x == y || (isfinite(x) && isfinite(y) && abs(x-y) <= atol + rtol*max(abs(x), abs(y)))
> +function isapprox(x::Number, y::Number; rtol::Real=rtoldefault(x,y), atol::Real=0, nans::Bool=false)
> +    x == y || (isfinite(x) && isfinite(y) && abs(x-y) <= atol + rtol*max(abs(x), abs(y))) || (nans && (isnan(x) & isnan(y)))
>
> almost certainly isn't, may as well be consistent with the other
> comparisons in this condition
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JuliaLang/julia/pull/20022>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABmqxmfJ8oOg-ErmQkhBCn9PrBprsg1Hks5rSDrzgaJpZM4LjVXb>
> .
>

2017-01-14 03:06 UTC, JeffreySarnoff commented on base/floatfuncs.jl
> +    x == y || (isfinite(x) && isfinite(y) && abs(x-y) <= atol + rtol*max(abs(x), abs(y))) || (nans && (isnan(x) & isnan(y)))
what do you suggest doing?

2017-01-14 03:20 UTC, tkelman commented on base/linalg/uniformscaling.jl
> +end
there's trailing whitespace here (you can find these with `make check-whitespace` locally), otherwise lgtm

2017-01-14 03:20 UTC, tkelman commented on test/floatapprox.jl
> +# issue #19936
also trailing whitespace here

2017-01-14 03:22 UTC, tkelman commented on test/floatapprox.jl
> +# issue #19936
also trailing whitespace here

2017-01-14 03:45 UTC, JeffreySarnoff commented on base/linalg/uniformscaling.jl
> +end
That should do it .

2017-01-14 03:45 UTC, tkelman approved these changes
should be squashed on merge

2017-01-14 21:09 UTC, merged