Add reference count to LibGit2 objects
JuliaLang/julia pull request #20124
Opened 2017-01-19 09:57 UTC by simonbyrne

Fixes segfault from calling `git_libgit2_shutdown` before finalizers (#20109).

2017-01-19 10:06 UTC, simonbyrne commented
I just realised that one alternative to this would be to call `git_libgit2_init` on each object initialization, and `git_libgit2_shutdown` at each finalizer, as these act like a reference counter.

2017-01-20 00:03 UTC, kshyatt commented
Can this be reviewed/merged?

2017-01-20 00:05 UTC, tkelman commented
do we want the alternative, or this? pros/cons?

2017-01-20 00:08 UTC, Keno commented on base/libgit2/types.jl
> +                ccall((:git_libgit2_shutdown, :libgit2), Cint, ())
What if the number of libgit2 objects drops to 0 at runtime. Is that ok?

2017-01-20 00:09 UTC, yuyichao requested changes

2017-01-20 00:09 UTC, yuyichao commented on base/libgit2/libgit2.jl
> +const REFCOUNT = Ref(zero(UInt))
I would set this to `0` in `__init__` also.

2017-01-20 00:09 UTC, yuyichao commented on base/libgit2/libgit2.jl
> +    REFCOUNT[] += 1
Ideally we'll need to replace these with atomic counters but this should be good enough for now.

2017-01-20 00:09 UTC, yuyichao commented on base/libgit2/libgit2.jl
> +const REFCOUNT = Ref(zero(UInt))
`s/0/1/g`

2017-01-20 00:11 UTC, yuyichao commented on base/libgit2/types.jl
> +                ccall((:git_libgit2_shutdown, :libgit2), Cint, ())
The `__init__` holds a global reference so the reference should not drop to 0.

2017-01-20 09:21 UTC, simonbyrne commented
> do we want the alternative, or this? pros/cons?

The only differences I can tell:
- the alternative seems to [have some code for handling threading](https://github.com/libgit2/libgit2/blob/5fe5557e8a8d3fd6a4617c2d8c863c1f62848020/src/global.c#L153-L162) (I don't know how this would perform, though @yuyichao mentions atomic counter above
- the alternative uses a `Cint` for the counter, so there is theoretically a potential for overflow on 64-bit machines.

2017-01-20 09:30 UTC, simonbyrne commented on base/libgit2/libgit2.jl
> +const REFCOUNT = Ref(zero(UInt))
done.

2017-01-20 09:48 UTC, simonbyrne commented on base/libgit2/libgit2.jl
> +    REFCOUNT[] += 1
I've changed these to be atomic counters: can you have a quick look over it as I'm not really familiar with them.

2017-01-21 00:00 UTC, kshyatt commented
Did the changes @yuyichao want get made? Can we merge this?

2017-01-21 00:15 UTC, yuyichao approved these changes

2017-01-21 00:15 UTC, merged