Link was broken
JuliaLang/julia pull request #20126
Opened 2017-01-19 14:13 UTC by PallHaraldsson

[skip ci]

2017-01-19 14:16 UTC, PallHaraldsson commented
I'm not sure the is the correct/wanted fix.. Should "latest" work? Was it phased out?

[I can't see that I can make a thread to do arbitrary stuff, yes threads are bad.. correct that (experimental) threads are only for (when explictly asked for) `for` loops?]

2017-01-19 14:17 UTC, yuyichao requested changes
The master doc should not link to stable doc.

2017-01-19 20:49 UTC, ararslan commented
The correct link is http://docs.julialang.org/en/latest/manual/parallel-computing#Multi-Threading-(Experimental)-1

2017-06-26 18:38 UTC, ararslan commented
Needs a rebase

2017-06-26 18:50 UTC, fredrikekre commented on NEWS.md
> +    [multi-threading](https://docs.julialang.org/en/latest/manual/parallel-computing#Multi-Threading-(Experimental)-1).
Perhaps better to use `@ref` instead, to avoid using a link at all.

2017-06-26 18:55 UTC, KristofferC commented on NEWS.md
> +    [multi-threading](https://docs.julialang.org/en/latest/manual/parallel-computing#Multi-Threading-(Experimental)-1).
For sure.

2018-11-28 12:57 UTC, inkydragon commented
**This pr is out of Date. It could be closed.**

And Maybe we should change links in `HISTORY.md` to specfic version.

For example: In `Julia v0.6.0 Release Notes` Section, links should be chaned to `https://docs.julialang.org/en/v0.6/`. for content in NEW or HISTORY are version related.

2018-11-28 17:04 UTC, closed without merging