Use compiler intrinsics for byte swapping
JuliaLang/julia pull request #20139
Opened 2017-01-20 01:17 UTC by Keno

There is really no advantage to messing with inline assembly here,
but plenty of disadvantages. The compiler can't optimize this for
whatever domain the data happens to be in (integer vs SSE+ registers),
some of the code violates the C standard, and it generates warnings
on newer gcc platforms (on i686 at least). Just get rid of it, use
the compiler intrinsics, and fall back to generic C instructions for
unknown compilers.

2017-01-20 01:24 UTC, yuyichao commented on src/support/utils.h
> +#define bswap_16(x) __builtin_bswap16(x)
This seems to be available in https://gcc.gnu.org/onlinedocs/gcc-4.5.0/gcc/Other-Builtins.html which is older than our minimum gcc version requirement so remove the version check (or at least use it on 4.7)?

2017-01-20 01:25 UTC, yuyichao requested changes

2017-01-20 01:25 UTC, yuyichao commented on src/support/utils.h
> +#define bswap_16(X) _bswap16
`(X)`?

2017-01-20 01:26 UTC, Keno commented on src/support/utils.h
> +#define bswap_16(x) __builtin_bswap16(x)
Linux seemed to think 4.8 was the first one that had it. https://github.com/torvalds/linux/blob/master/include/linux/compiler-gcc.h#L261

2017-01-20 01:39 UTC, yuyichao commented on src/support/utils.h
> +#define bswap_16(x) __builtin_bswap16(x)
Ah, you are right. bswap16 is only in 4.8....

2017-01-20 01:40 UTC, yuyichao approved these changes

2017-01-20 22:20 UTC, merged

2017-01-21 00:56 UTC, tkelman commented on src/support/utils.h
> +#define bswap_16(x) __builtin_bswap16(x)
Apparently gcc 4.7 is mostly-in-theory the minimum for llvm since it wasn't the default system compiler on many particularly commonly tested distros.