Add callsuper macro.
JuliaLang/julia pull request #20131
Opened 2017-01-19 21:12 UTC by simonbyrne

Fixes #18252.

2017-01-19 21:13 UTC, simonbyrne commented
Feel free to bikeshed names.

2017-01-19 21:21 UTC, yuyichao requested changes

2017-01-19 21:21 UTC, yuyichao commented on base/util.jl
> +        if isa(arg,Expr) && arg.head == :kw
This is not entirely correct. A few cases that should be handled and possibly tested are. (These are the reason I started but didn't finish the pr yet...)

1. Evaluation order

    Currently `:parameters` are always evaluated the first. It's not necessarily the best choice but this should be consisent with normal calls.

2. `:parameters` can have `...`

3. `:parameters` can have non `:kw` in it

4. positional arguments can also have `...`

5. if `parameter` only have `...`s and all of them are empty, the non-kw version should be called.

2017-01-19 21:46 UTC, simonbyrne commented on base/util.jl
> +        if isa(arg,Expr) && arg.head == :kw
what non-`:kw` can a `:parameters` have other than `...`?

2017-01-19 22:23 UTC, yuyichao commented on base/util.jl
> +        if isa(arg,Expr) && arg.head == :kw
Any, iterable objects

```jl
julia> f(;kws...) = kws
f (generic function with 1 method)

julia> j = [:j, :k]
2-element Array{Symbol,1}:
 :j
 :k

julia> f(;:a=>:b, (:c, :d), [:e, :f], (:g, :h, :i), j)
5-element Array{Any,1}:
 (:a,:b)
 (:c,:d)
 (:e,:f)
 (:g,:h)
 (:j,:k)
```

2017-01-19 22:36 UTC, yuyichao commented on base/util.jl
> +                push!(blk.args, :($typ = $(esc(arg.args[2]))))
Also, `val` should be evaluated before the type.

2017-01-19 22:37 UTC, yuyichao commented on base/util.jl
> +        push!(blk.args, :(invoke($(esc(fname)), Tuple{$(types...)}, $(vals...))))
And `fname` should be evaluated before the arguments.

2017-01-21 21:25 UTC, simonbyrne commented on base/util.jl
> +        push!(blk.args, :(invoke($(esc(fname)), Tuple{$(types...)}, $(vals...))))
Actually, `fname` evaluation is a bit weird:
```
julia> f(args...; kwargs...) = (args,kwargs)
f (generic function with 1 method)

julia> (println("f"); f)((println("a"); "a"); [:y,(println("b"); "b")])
b
f
f
a
(("a",),Any[(:y,"b")])

julia> (println("f"); f)((println("a"); "a"); [:y => (println("b"); "b")]...)
b
f
a
f
f
(("a",),Any[(:y,"b")])
```

2017-01-21 22:18 UTC, StefanKarpinski commented on base/util.jl
> +        if isa(arg,Expr) && arg.head == :kw
@yuyichao, wouldn't be easier all around if you just did this PR? There was a similar back and forth when I proposed a possible implementation

2017-01-21 22:19 UTC, StefanKarpinski commented
I like the name, @simonbyrne. Thanks for pushing this forward – it's a much nicer interface than bare `invoke`.

2017-01-22 00:45 UTC, yuyichao commented on base/util.jl
> +        if isa(arg,Expr) && arg.head == :kw
Maybe. I started a implementation but haven't finished it yet (collecting data of what input should/can be supported and what generic fallback path I can use).....

2017-01-22 00:47 UTC, yuyichao commented on base/util.jl
> +        push!(blk.args, :(invoke($(esc(fname)), Tuple{$(types...)}, $(vals...))))
This is a lowering bug. The lowering code should emit a temporary variable to hold `f` if it cannot proof that evaluating `f` is "pure".

2017-01-30 20:48 UTC, JeffBezanson commented
IIUC, this doesn't fully fix #7045 since it doesn't fix the case of using `invoke` directly.

2019-12-29 00:50 UTC, jlumpe commented
This would be a really nice feature, is anyone still working on it?

2020-12-25 09:33 UTC, Keno commented
If I understand correctly this is superseded by #38438. Let me know if I misunderstood.

2020-12-25 09:33 UTC, closed without merging

2021-01-04 16:40 UTC, simonbyrne commented
Indeed it is.