RFC: Add support for dynamic doc strings
JuliaLang/julia pull request #20142
Opened 2017-01-20 02:47 UTC by malmaud

Useful for eg https://github.com/JuliaPy/PyCall.jl/issues/46.

Allows instances of the same type to have different docstrings which can only be determined at runtime. Useful for interlanguage support where the same Julia type (eg `PyObject`) corresponds to different types in the guest language that might have different docstrings.

2017-01-20 04:41 UTC, MichaelHatherly requested changes
Thanks @malmaud.

2017-01-20 04:41 UTC, MichaelHatherly commented on base/docs/Docs.jl
> +    end
Can be a bit shorter/clearer as

```diff
 function doc(binding::Binding, sig::Type = Union{})
+    if defined(binding)
+        result = getdoc(resolve(binding), sig)
+        result === nothing || return Markdown.parse(result)
+    end
     results, groups = DocStr[], MultiDoc[]
```

with a default `getdoc(obj, sig) = nothing` method. Passing `sig` through to `getdoc` as well may be useful?

2017-01-20 04:41 UTC, MichaelHatherly commented on base/docs/Docs.jl
> +end
Unintentional formatting change?

2017-01-22 17:45 UTC, malmaud commented on base/docs/Docs.jl
> +    end
Good call.

2017-01-22 19:31 UTC, tkelman commented on base/docs/Docs.jl
> +If `getdoc` returns a non-`nothing` result on the value of the binding, then a dynamic docstring is returned instead of one based on the binding itself.
wrap long lines

2017-01-22 23:30 UTC, malmaud commented on base/docs/Docs.jl
> +If `getdoc` returns a non-`nothing` result on the value of the binding, then a dynamic docstring is returned instead of one based on the binding itself.
Done

2017-01-23 16:29 UTC, malmaud commented
@MichaelHatherly look good now?

2017-01-24 12:20 UTC, MichaelHatherly approved these changes

2017-01-24 12:24 UTC, MichaelHatherly commented on base/docs/Docs.jl
> +        result === nothing || return Markdown.parse(result)
Would it make sense to *not* call `Markdown.parse` here and instead just return `result`? That way `getdocs` could return a more suitable object, such as an `RST` object for rst-formatted python docstrings.

2017-01-24 16:27 UTC, malmaud commented on base/docs/Docs.jl
> +        result === nothing || return Markdown.parse(result)
Ya, that's a good call.

2017-01-24 22:25 UTC, merged

2017-01-25 00:15 UTC, stevengj commented on base/docs/Docs.jl
> +the binding's documentation.
The docstring doesn't explain what the `sig` argument is for.