Add patch to set `-O2` for suitesparse build
JuliaLang/julia pull request #20165
Opened 2017-01-20 23:31 UTC by staticfloat

This fixes the compiler regression noticed in GCC 6.3.0 in https://github.com/JuliaLang/julia/issues/20123 by disabling `-ftree-slp-vectorize` as a side-effect of moving from `-O3` to `-O2`.  We prefer to compile with `-O2` by default anyway, so let's do so.

2017-01-21 00:23 UTC, tkelman commented
> We prefer to compile with `-O2` by default anyway, so let's do so.

Where are you getting that from? I see a heck of a lot more instances of `-O3` in our makefiles, only a handful of `-O2`.

@nanosoldier `runbenchmarks("sparse", vs = ":master")`

2017-01-21 00:24 UTC, tkelman commented on deps/suitesparse.mk
> +$(BUILDDIR)/SuiteSparse-$(SUITESPARSE_VER)/build-compiled: $(BUILDDIR)/SuiteSparse-$(SUITESPARSE_VER)/source-extracted $(BUILDDIR)/SuiteSparse-$(SUITESPARSE_VER)/SuiteSparse-O2.patch-applied
run `make check-whitespace` locally if you ever do ci skip

2017-01-21 02:26 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20165#issuecomment-274214587) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4be35989255c854bca716f8a48c8a9a83c2b3163/5333936_vs_d3bac6e/report.md). cc @jrevels

2017-01-21 02:31 UTC, tkelman commented
Ah some might be under linalg... @nanosoldier `runbenchmarks(ALL, vs = ":master")`

2017-01-21 06:39 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20165#issuecomment-274226830) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d94e208c3473ebe814c3f86719592a7d9468aa09/5333936_vs_d3bac6e/report.md). cc @jrevels

2017-01-21 12:05 UTC, ViralBShah commented
As @nalimilan pointed out elsewhere, we really ought to be using `-O2` as the default except in cases where we can prove that `-O3` does better. This is the policy in many linux distros apparently.

2017-02-11 20:34 UTC, staticfloat commented
@tkelman So it looks like we've got significant performance regressions with this changeset, huh.

2017-02-11 20:39 UTC, tkelman commented
I'm not so sure those were related, but I'd also prefer this be targeted to the specific architectures where it's known to cause a problem. And, you know, report the gcc bug and see how long it takes them to fix it (they can be very quick on some bugs).

In this case I'm not sure the benchmarks on nanosoldier include good test cases for suitesparse functionality. A cholfact or lufact of some large known sparse matrix (say from the formerly-UF collection) would be worth timing.

2017-02-11 21:00 UTC, pabloferz commented
Those regressions might be due to #19976

2017-02-12 19:52 UTC, tkelman requested changes
need to fix the whitespace, and benchmark on something that exercises suitesparse thoroughly

2017-02-12 19:56 UTC, tkelman commented
-O3 definitely enables a whole range of tree vectorization passes in gcc that should be improving performance on code like suitesparse. Since we've been using O3 for so long, the burden should be on proving that changing to O2 doesn't hurt.

2017-02-24 23:53 UTC, staticfloat commented
On this branch (newly rebased on top of `master`), built on `x86_64` using `gcc 5.4.0`:

```
Test (Worker)             | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
sparse/umfpack (5)        |    9.74  |  0.16  |  1.6 | 325.47     | 241.17
sparse/cholmod (5)        |   21.69  |  0.39  |  1.8 | 636.43     | 313.36
sparse/spqr (5)           |    2.47  |  0.04  |  1.5 | 86.65      | 313.36
sparse/sparse (2)         |   85.97  | 17.31  | 20.1 | 2012.92    | 387.27
sparse/higherorderfns (4) |   87.18  |  1.44  |  1.7 | 3554.29    | 413.45
sparse/sparsevector (3)   |   87.83  |  1.05  |  1.2 | 2588.59    | 381.42

Test Summary: |  Pass  Broken  Total
  Overall     | 16545     584  17129
    SUCCESS
```

On `master` (d321300):
```
Test (Worker)             | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
sparse/umfpack (5)        |    9.60  |  0.17  |  1.8 | 325.55     | 235.16
sparse/cholmod (5)        |   19.08  |  0.36  |  1.9 | 636.44     | 309.36
sparse/spqr (5)           |    2.49  |  0.03  |  1.4 | 86.65      | 309.36
sparse/sparse (2)         |   82.86  | 17.63  | 21.3 | 2012.94    | 387.06
sparse/sparsevector (3)   |   84.38  |  0.97  |  1.2 | 2581.58    | 384.82
sparse/higherorderfns (4) |   84.73  |  1.40  |  1.7 | 3554.21    | 411.90
```

@ViralBShah are there any other tests that it might be instructive to run to make sure that `suitesparse` isn't getting severely slowed down?  So far it looks like `cholmod` is ~10% slower.

2017-02-25 01:28 UTC, staticfloat commented
Here are the same results on the same machine but using `gcc 6.3.0`, like we use on the buildbots.  (All hail Docker 🐳 )

With `-O3` on `master`:
```
Test (Worker)             | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
sparse/umfpack (5)        |    9.39  |  0.18  |  1.9 | 326.13     | 238.03
sparse/cholmod (5)        |   18.44  |  0.34  |  1.9 | 636.91     | 312.15
sparse/spqr (5)           |    2.42  |  0.03  |  1.4 | 86.65      | 312.15
sparse/sparse (2)         |   80.55  | 17.08  | 21.2 | 2015.10    | 390.14
sparse/sparsevector (3)   |   82.44  |  0.98  |  1.2 | 2590.26    | 385.08
sparse/higherorderfns (4) |   83.13  |  1.38  |  1.7 | 3553.82    | 410.05
```

With `-O2` on this branch:
```
Test (Worker)             | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
sparse/umfpack (5)        |    8.75  |  0.20  |  2.2 | 302.62     | 228.37
sparse/cholmod (5)        |   17.34  |  0.30  |  1.7 | 603.76     | 302.43
sparse/spqr (5)           |    2.38  |  0.03  |  1.4 | 88.33      | 302.43
sparse/sparse (2)         |   77.48  | 16.12  | 20.8 | 1993.22    | 391.83
sparse/higherorderfns (4) |   79.89  |  1.28  |  1.6 | 3236.99    | 416.92
sparse/sparsevector (3)   |   81.31  |  1.13  |  1.4 | 2754.84    | 357.80
```

I.....huh.  Looks like GCC 6.3.0's `-O2` has improved.

2017-02-25 01:46 UTC, tkelman commented
test runtime isn't as useful as a perf benchmark run via BenchmarkTools, the tests are likely driven by julia JIT compile time rather than library function runtime

2017-02-28 04:48 UTC, staticfloat commented
I ran the `sparse` perf benchmark on `x86_64` with both `-O2` and `-O3` versions of suitesparse built.  I tested the performance using the following script:

```julia
# sparse_perf.jl
using BaseBenchmarks
using BenchmarkTools

benchmarks = BaseBenchmarks.load!("sparse")

warmup(benchmarks)
results = run(benchmarks; verbose = true)
BenchmarkTools.save("../master.jld", "results", results)
```

With an identical one that output to `../pr.jld` for the `-O2` version of Julia.  I analyzed with the following script:

```julia
# compare.jl
using BenchmarkTools, BaseBenchmarks, JLD

pr = load("pr.jld", "results")
master = load("master.jld", "results")
pairs = leaves(regressions(judge(minimum(pr), minimum(master))))
```

Which found no consistent regressions.  The full results are [available as `.jld` file](https://davinci.cs.washington.edu/compare.jld), if you're interested.

2017-02-28 08:51 UTC, tkelman commented
what does that benchmark run though? is it actually doing anything that exercises suitesparse, or only the lure-julia sparse code?

this needs to be reported as a gcc bug.

2017-02-28 21:15 UTC, staticfloat commented
> this needs to be reported as a gcc bug.

As I'm assuming I would have to boil this down into an MWE, I do not have the time or energy to report this as a GCC bug at the moment.

> is it actually doing anything that exercises suitesparse, or only the pure-julia sparse code?

I downloaded ~~three~~ two matrices (apparently we can't decompose integer-valued matrices) from the [University of Florida dataset](http://www.cise.ufl.edu/research/sparse/matrices/list_by_dimension.html) and ran `factorize()` on them.  Here's the script:

```julia
# sparse_perf.jl
using BenchmarkTools
using MatrixMarket

#M1 = MatrixMarket.mmread("rosen2/rosen2.mtx")
M2 = MatrixMarket.mmread("bayer09/bayer09.mtx")
M3 = MatrixMarket.mmread("bcsstk23/bcsstk23.mtx")

#t1 = @benchmark factorize(M1)
t2 = @benchmark factorize(M2)
t3 = @benchmark factorize(M3)


println("Real unsymmetric (bayer09)")
display(t2)
println("\nReal symmetric (bcsstk23)")
display(t3)
println()
```

Here's the `-O3` output:
```
Real unsymmetric (bayer09)
BenchmarkTools.Trial: 
  memory estimate:  3.17 MiB
  allocs estimate:  64
  --------------
  minimum time:     4.811 ms (0.00% GC)
  median time:      4.878 ms (0.00% GC)
  mean time:        4.946 ms (0.74% GC)
  maximum time:     16.998 ms (1.51% GC)
  --------------
  samples:          1004
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
Real symmetric (bcsstk23)
BenchmarkTools.Trial: 
  memory estimate:  9.49 MiB
  allocs estimate:  48
  --------------
  minimum time:     11.374 ms (0.00% GC)
  median time:      11.447 ms (0.00% GC)
  mean time:        11.701 ms (1.97% GC)
  maximum time:     62.680 ms (81.45% GC)
  --------------
  samples:          425
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

Here's the `-O2` output:
```
Real unsymmetric (bayer09)
BenchmarkTools.Trial: 
  memory estimate:  3.17 MiB
  allocs estimate:  64
  --------------
  minimum time:     4.752 ms (0.00% GC)
  median time:      4.833 ms (0.00% GC)
  mean time:        4.884 ms (0.78% GC)
  maximum time:     7.559 ms (3.49% GC)
  --------------
  samples:          1018
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
Real symmetric (bcsstk23)
BenchmarkTools.Trial: 
  memory estimate:  9.49 MiB
  allocs estimate:  48
  --------------
  minimum time:     11.782 ms (0.00% GC)
  median time:      11.830 ms (0.00% GC)
  mean time:        12.111 ms (1.98% GC)
  maximum time:     63.003 ms (81.00% GC)
  --------------
  samples:          411
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

It looks to me that we don't have too much difference here.

2017-02-28 21:55 UTC, tkelman commented
We already have the Julia-side example here, right? https://github.com/JuliaLang/julia/issues/20123#issuecomment-273981427 Translating that into `ccall`s shouldn't be that hard. If upstream defaults to `-O3` then we should consider this temporary until the GCC bug gets fixed, or convince SuiteSparse to change their defaults.

2017-03-04 07:48 UTC, staticfloat commented
I'd like to get this merged for 0.6 so that building with the latest GCC doesn't cause problems.

2017-03-04 08:50 UTC, tkelman commented
I still don't like doing this on platforms where it doesn't cause problems, or merging without an upstream bug report to gcc.

2017-03-04 10:09 UTC, ViralBShah commented
Sorry @tkelman I am going ahead with this.

2017-03-04 10:09 UTC, merged

2017-03-04 10:11 UTC, ViralBShah commented
Agree about the upstream bug report to gcc and we should perhaps also notify Tim Davis.

2017-03-04 15:08 UTC, tkelman commented
And if we don't do these things before merging, they never happen.

2017-03-04 19:08 UTC, tkelman commented
The passes enabled by `-O3` probably can't do much unless you also let gcc use newer instructions with `-march=native`.

2017-03-05 05:05 UTC, staticfloat commented
> And if we don't do these things before merging, they never happen.

Here's a [`ccall`-based MWE with a dockerfile](https://gist.github.com/staticfloat/bc973409f78776eff46820fd72ee692b) that sets up the environment for the segfault.

2017-03-05 08:03 UTC, tkelman commented on deps/suitesparse.mk
> +$(BUILDDIR)/SuiteSparse-$(SUITESPARSE_VER)/SuiteSparse-O2.patch-applied: $(BUILDDIR)/SuiteSparse-$(SUITESPARSE_VER)/SuiteSparse-winclang.patch-applied
this is also wrong, these belong in srccache

2017-03-05 21:24 UTC, staticfloat commented on deps/suitesparse.mk
> +$(BUILDDIR)/SuiteSparse-$(SUITESPARSE_VER)/SuiteSparse-O2.patch-applied: $(BUILDDIR)/SuiteSparse-$(SUITESPARSE_VER)/SuiteSparse-winclang.patch-applied
Should we move all the `.patch-applied` files into `srccache` then?  I was just following what was already in the file.

2017-03-05 22:48 UTC, tkelman commented on deps/suitesparse.mk
> +$(BUILDDIR)/SuiteSparse-$(SUITESPARSE_VER)/SuiteSparse-O2.patch-applied: $(BUILDDIR)/SuiteSparse-$(SUITESPARSE_VER)/SuiteSparse-winclang.patch-applied
ah on second thought it depends whether the dependency is capable of being built out of tree. we could use comments in these makefiles that explain inconsistencies like this