deprecate vectorized sign methods in favor of dot syntax
JuliaLang/julia pull request #20228
Opened 2017-01-25 05:17 UTC by Sacha0

This pull request deprecates all remaining vectorized `sign` methods in favor of dot syntax. Best!

2017-01-25 16:37 UTC, StefanKarpinski approved these changes

2017-01-25 16:42 UTC, p-zubieta requested changes

2017-01-25 16:42 UTC, pabloferz commented on base/bitarray.jl
> +broadcast(sign, B::BitArray) = copy(B)
`::typeof(sign)`?

2017-01-25 19:30 UTC, Sacha0 commented on base/bitarray.jl
> +broadcast(sign, B::BitArray) = copy(B)
Ouch. Good catch! Fixed on push. Thanks!

2017-01-27 01:31 UTC, p-zubieta approved these changes

2017-01-27 01:32 UTC, merged