[release-0.5] backport CI fixes
JuliaLang/julia pull request #20483
Opened 2017-02-07 02:27 UTC by vtjnash

to try making travis happier

2017-02-07 12:08 UTC, maleadt commented
Now that you're backporting CI fixes to 0.5, maybe include #20430? Example [CI failure](https://ci.maleadt.net/buildbot/julia/builders/Julia%200.5%20%28x86-64%29/builds/12).

Rebased patch:
```patch
From 7ff704c8feb084fad062f3e9a014dfc1c7d85c95 Mon Sep 17 00:00:00 2001
From: Tim Besard <tim.besard@gmail.com>
Date: Tue, 7 Feb 2017 13:01:27 +0100
Subject: [PATCH] Make sure flisp.boot is copied to an existing directory.

---
 src/Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/Makefile b/src/Makefile
index d7ec864f27..9aae087541 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -151,7 +151,7 @@ $(BUILDDIR)/julia_flisp.boot.inc: $(BUILDDIR)/julia_flisp.boot $(FLISP_EXECUTABL
 
 $(BUILDDIR)/julia_flisp.boot: $(addprefix $(SRCDIR)/,jlfrontend.scm \
                julia-parser.scm julia-syntax.scm match.scm utils.scm ast.scm macroexpand.scm mk_julia_flisp_boot.scm) \
-               $(FLISP_EXECUTABLE_release)
+               $(FLISP_EXECUTABLE_release) | $(BUILDDIR)
        @$(call PRINT_FLISP, $(call spawn,$(FLISP_EXECUTABLE_release)) \
                $(call cygpath_w,$(SRCDIR)/mk_julia_flisp_boot.scm) $(call cygpath_w,$(dir $<)) $(notdir $<) $(call cygpath_w,$@))
 
-- 
2.11.1
```

2017-02-07 17:37 UTC, tkelman requested changes
We should not be changing the libgit2 version on release-0.5

2017-02-08 01:05 UTC, tkelman commented on base/libgit2/types.jl
> +immutable ProxyOptions
should put the definition of this type under the `if LibGit2.version() >= v"0.25.0"` as well, it shouldn't be added to the module unless you're building in a non-default configuration and absolutely need it

2017-02-08 05:00 UTC, vtjnash commented on base/libgit2/types.jl
> +immutable ProxyOptions
It's not an API issue. I'm just attempting to roughly match whatever we have on master, not actually redesign that commit.

2017-02-08 05:17 UTC, tkelman commented on base/libgit2/types.jl
> +immutable ProxyOptions
release-0.5 shouldn't match what's on master, it should remain close to 0.5.0. just change msys_build.sh to download 0.5-latest and you won't need to touch libgit2 at all

2017-02-08 16:55 UTC, vtjnash commented on base/libgit2/types.jl
> +immutable ProxyOptions
I don't think semver cares about internal names. This is non-breaking at the API level to keep this slightly closer to master.

2017-02-08 17:36 UTC, tkelman commented on base/libgit2/types.jl
> +immutable ProxyOptions
I don't want to be defining an unused type in the default build configuration.

2017-02-09 16:34 UTC, StefanKarpinski commented
Can we make some progress on this, pretty please?

2017-02-09 20:12 UTC, tkelman approved these changes

2017-02-11 20:45 UTC, merged