improve two deprecations
JuliaLang/julia pull request #20529
Opened 2017-02-08 21:20 UTC by JeffBezanson

- for `_` by itself at the prompt
- add location info to inner constructor deprecation

2017-02-08 21:57 UTC, StefanKarpinski requested changes

2017-02-08 21:57 UTC, StefanKarpinski commented on base/client.jl
> +        # remove with 0.6 deprecation
Best practice at the moment is to drop a comment in `base/deprecated.jl` about this TODO.

2017-02-08 22:17 UTC, JeffBezanson commented on base/client.jl
> +        # remove with 0.6 deprecation
Done.

2017-02-08 22:27 UTC, StefanKarpinski approved these changes

2017-02-09 14:44 UTC, StefanKarpinski commented
This is safe to merge since the test failure on macOS was unrelated and random (my fault for adding lots of range tests that apparently sometimes actually fail.)

2017-02-09 14:44 UTC, merged