Fix embedding example and simplify Makefile
JuliaLang/julia pull request #20535
Opened 2017-02-09 05:46 UTC by ihnorton

- get rid of makefile cruft
- build in-place instead of putting in usr/bin
- use julia-config for flags, as documented in manual

(related: #18421)

2017-02-09 05:53 UTC, tkelman commented on examples/Makefile
> +JULIA = $(abspath ../usr/bin/julia)
this isn't right for an out-of-tree build

2017-02-09 05:53 UTC, tkelman commented on examples/Makefile
> +JL_SHARE = $(shell $(JULIA) -e 'print(joinpath(JULIA_HOME,Base.DATAROOTDIR,"julia"))')
may require spawn

2017-02-09 05:53 UTC, tkelman commented on examples/Makefile
> +ifeq ($(OS),Windows_NT)
not correct for cross-compiling

2017-02-09 05:54 UTC, tkelman commented on src/julia.h
> +JL_DLLEXPORT const char* jl_get_default_sysimg_path();
if exported, needs JL_DLLEXPORT on both prototype and implementation

2017-02-10 06:00 UTC, ihnorton commented
Updated, thanks. I'm going for non-reliance on `Make.inc`, so that this can serve as a usable template. However, added checks for spawn and BUILDROOT independently (to handle cross-compile and out-of-tree). Hopefully sufficient, though I'm not set up to test those right now.

I'll note that this example isn't built at all right now with out-of-tree.

2017-02-10 15:10 UTC, ihnorton commented
Win64 and OSX test failures seem unrelated.

2017-02-13 00:45 UTC, tkelman commented on examples/Makefile
> -JLDFLAGS += $(WHOLE_ARCHIVE) $(build_libdir)/libopenlibm.a $(NO_WHOLE_ARCHIVE)
does julia-config handle this and the llvm-config output?

2017-02-13 00:46 UTC, tkelman commented on test/examples.jl
> +    lines = readlines(pipeline(`$(joinpath(JULIA_HOME,Base.DATAROOTDIR,"doc","julia","examples","embedding","embedding"))`, stderr=DevNull))
wrap long line

2017-02-13 00:48 UTC, tkelman commented on examples/embedding/Makefile
> +	rm -f *.o *.do
doesn't look like this will create any object files any more

2017-02-13 00:54 UTC, tkelman commented
we shouldn't install binaries in the same place as documentation and source code. installing and redistributing the compiled embedding results isn't the most useful test of this, see my comments on https://github.com/JuliaLang/julia/pull/18688

2017-02-13 01:34 UTC, ihnorton commented on examples/Makefile
> -JLDFLAGS += $(WHOLE_ARCHIVE) $(build_libdir)/libopenlibm.a $(NO_WHOLE_ARCHIVE)
libm yes, llvm-config no. Doesn't libjulia link llvm already?

2017-02-13 04:05 UTC, tkelman commented on examples/Makefile
> -JLDFLAGS += $(WHOLE_ARCHIVE) $(build_libdir)/libopenlibm.a $(NO_WHOLE_ARCHIVE)
yes but presumably the llvm-config --ldflags call was needed for something

2017-02-13 04:50 UTC, ihnorton commented on examples/Makefile
> -JLDFLAGS += $(WHOLE_ARCHIVE) $(build_libdir)/libopenlibm.a $(NO_WHOLE_ARCHIVE)
That was added in 072a861828378 when the file was created. My guess is copy-paste or prior/local build issue. If it breaks the example we can put it back.

2017-02-13 04:56 UTC, ihnorton commented
> installing and redistributing the compiled embedding results isn't the most useful test of this, see my comments on #18688

Ok:
- I put the binary in libexec in the latest update, because I agree with Yichao (and your thumbs-up) in that thread that this could be a useful test of relocatability, which I will have a follow-up PR to make possible.
- I made the test optional, as you requested in that thread, and added to appveyor/travis scripts.

2017-02-13 19:22 UTC, tkelman commented on examples/embedding/Makefile
> +  BINDIR := $(abspath $(BUILDROOT)/usr/libexec)/
`build_libexecdir`

2017-02-16 18:45 UTC, tkelman commented on examples/embedding/Makefile
> +  $(error "Please set BIN to the path of the build directory!")
could maybe use a bit more clarification what is meant by this

2017-03-23 16:03 UTC, tkelman commented on examples/embedding/Makefile
> +$(BINDIR)/embedding-debug$(EXE): embedding.c
should this also be BIN ?

2017-03-23 16:06 UTC, tkelman commented on examples/embedding/Makefile
> +	$(CC) $^ -o $@ $(CFLAGS)
might want to also explicitly error if CC isn't set, or default to `cc`

2017-03-23 16:12 UTC, vtjnash commented on examples/embedding/Makefile
> +	$(CC) $^ -o $@ $(CFLAGS)
`make` already does that

2017-03-24 04:35 UTC, tkelman commented on contrib/julia-config.jl
> +        return """-std=gnu99 $(threading_def)-fPIC -DJULIA_INIT_DIR=\\"$arg1\\" -I$arg2"""
does the runtime need this, or the code in the embedding example?

2017-03-24 08:48 UTC, ihnorton commented on contrib/julia-config.jl
> +        return """-std=gnu99 $(threading_def)-fPIC -DJULIA_INIT_DIR=\\"$arg1\\" -I$arg2"""
the runtime.

2017-03-24 10:54 UTC, tkelman commented on contrib/julia-config.jl
> +        return """-std=gnu99 $(threading_def)-fPIC -DJULIA_INIT_DIR=\\"$arg1\\" -I$arg2"""
are we using gnu extensions in our headers, or which compiler versions don't default to c99 mode?

2017-03-24 19:04 UTC, JeffBezanson commented on examples/embedding/embedding.c
> +    jl_init(JULIA_INIT_DIR);
Does this still work with `NULL` as the argument?

2017-03-24 19:06 UTC, JeffBezanson commented on examples/embedding/embedding.c
> +    jl_init(JULIA_INIT_DIR);
Oh, even better, it looks like `jl_init` takes no arguments now?

2017-03-24 19:06 UTC, JeffBezanson commented on src/jlapi.c
> +JL_DLLEXPORT void jl_init()
Should be `jl_init(void)`.

2017-03-24 19:08 UTC, JeffBezanson requested changes

2017-03-24 19:08 UTC, JeffBezanson commented on src/julia.h
> +JL_DLLEXPORT const char* jl_get_default_sysimg_path();
This is duplicated and needs `(void)`.

2017-03-28 18:48 UTC, JeffBezanson commented
Bump.

2017-04-06 19:57 UTC, JeffBezanson commented
Moved to #21299.

2017-04-06 19:57 UTC, closed without merging