Fix missing root across safe-point
JuliaLang/julia pull request #20700
Opened 2017-02-20 22:33 UTC by Keno

As @yuyichao points out, JL_LOCK is a safe point.

2017-02-20 22:38 UTC, yuyichao requested changes

2017-02-20 22:38 UTC, yuyichao commented on src/codegen.cpp
> +        JL_GC_PUSH1(&src);
We are using a local array for the buffer so this has to be in the same or parent scope as the pop.

2017-02-20 23:10 UTC, Keno commented
Updated. Probably best viewed with whitespace ignored.

2017-02-21 05:59 UTC, yuyichao approved these changes
Got identical result following the same reorganization.

2017-02-21 05:59 UTC, yuyichao commented
Test failure unrelated....

2017-02-21 17:11 UTC, merged