improve precompiles
JuliaLang/julia pull request #20793
Opened 2017-02-24 22:14 UTC by JeffBezanson

- Be able to print any type in parse-able syntax. This lets us precompile many more things, such as closures, more operators, types containing `Symbol("text/plain")`, etc.
- Put the code for printing things to precompile in a better place. We want to print the observed concrete types that led to compilation, not something else (previously precompile.jl contained some abstract types, which the `precompile` function actually ignores to avoid poisoning the cache).
- The precompile statements needed to be updated for 0.6 anyway.

The system image is a bit bigger after this, but the repl is really snappy.

2017-02-24 22:26 UTC, KristofferC commented
How did you generate the `precompile` list? SnoopCompile style?

2017-02-24 22:28 UTC, vtjnash requested changes
what's the performance of the usual `using DataFrames` tests (from an empty lib code cache) after this change?

2017-02-24 22:28 UTC, vtjnash commented on src/rtutils.c
> +                if (globfunc && !jl_id_start_char(u8_nextchar(sn,&i))) {
missing spaces after a handful of the `,`'s in here

2017-02-24 22:28 UTC, vtjnash commented on src/rtutils.c
> +        int globfunc = globname && jl_get_global(dv->name->module, globname) &&
`jl_get_global` can mutate `m` & print deprecation warnings

2017-02-24 22:28 UTC, vtjnash commented on src/rtutils.c
> +        if (dv->name->module != jl_core_module || !jl_module_exports_p(jl_core_module, sym)) {
`jl_module_exports_p` can allocate and can't be used here (or should be fixed not to allocate?)

2017-02-24 22:36 UTC, JeffBezanson commented on src/rtutils.c
> +        if (dv->name->module != jl_core_module || !jl_module_exports_p(jl_core_module, sym)) {
Yes I can fix it not to allocate.

2017-02-24 22:41 UTC, yuyichao commented on src/rtutils.c
> +        int globfunc = globname && jl_get_global(dv->name->module, globname) &&
`jl_get_global` can also allocate?

2017-02-24 22:44 UTC, JeffBezanson commented
I enabled `TRACE_COMPILE` and used the repl with stderr redirected to a file. However it looks like this will not work, since various closures seem to end up with different compiler-generated names on different platforms. I don't know exactly why, but with any platform-conditional code it's bound to happen.

2017-02-24 23:08 UTC, KristofferC commented
FWIW, the REPL feels very snappy indeed!

2017-02-24 23:53 UTC, JeffBezanson commented
Comments addressed.

I manually removed the closures. Hopefully there will still be a bit of improvement.

2017-02-27 20:04 UTC, ararslan commented
Bump. @JeffBezanson, we you able to determine what the performance is of `using DataFrames` as @vtjnash asked in his review?

2017-02-27 20:13 UTC, vtjnash commented on src/rtutils.c
> +        int quoted = strchr(sn,'/') && strcmp(sn,"/") && strcmp(sn,"//") && strcmp(sn,"//=");
missing spaces after the `,`'s here too

2017-02-27 21:40 UTC, JeffBezanson commented
I tried but I haven't been able to get DataFrames to load on master yet.

2017-02-27 21:42 UTC, JeffBezanson commented on src/rtutils.c
> +        int quoted = strchr(sn,'/') && strcmp(sn,"/") && strcmp(sn,"//") && strcmp(sn,"//=");
Ok... this isn't in the formatting guidelines though.

2017-02-27 21:53 UTC, ararslan commented
> I haven't been able to get DataFrames to load on master yet.

Ah, yeah... Try checking out DataArrays to master then checking out DataFrames to anj/06.

2017-03-06 18:54 UTC, JeffBezanson commented
Ok, with this change precompiling DataFrames goes from 44 seconds to 50 seconds. Does that mean too many precompiles or not enough?

2017-03-06 20:12 UTC, vtjnash commented
> DataFrames goes from 44 seconds

Is this a recent regression? The only acceptable answer here is < 20s.

2017-03-17 18:33 UTC, JeffBezanson commented
Adding to milestone since updating precompiles should go with the release process, and also to remind us to look at the DataFrames compile time regression.

2017-03-17 18:42 UTC, ararslan commented
As a quick aside regarding DataFrames, it's now installable directly from `Pkg.add` on 0.6 without having to check out specific branches, as a working release has been tagged.

2017-03-23 18:29 UTC, JeffBezanson commented
DataFrames compile time regression persists.

2017-03-23 18:56 UTC, JeffBezanson commented
Looking at `ENABLE_TIMINGS`, most of the increases vs. 0.5 seem to be in inference.

2017-03-24 15:45 UTC, JeffBezanson commented
Ok, I updated this to just improve the mechanism.

Package load times can be improved a bit by adding precompile statements, and there might be a couple percent slowdown from #20343, but we still have a large performance gap vs. 0.5.

2017-03-28 08:32 UTC, vtjnash approved these changes

2017-03-28 10:49 UTC, vtjnash commented
OK, thanks. I reviewed the biggest contributors to inference time increase and think I can start working on a patch. That doesn't need to hold this up. It would be good to make sure the new precompile file includes whatever entries that `./julia -e 'using Glob'` also lists. I think that should at least prevent further regression in the timing for typical packages.

2017-03-28 12:04 UTC, vtjnash commented
CI failures are known issues

2017-03-28 15:39 UTC, merged