RFC: Added recursive transpose to `Diagonal`
JuliaLang/julia pull request #21019
Opened 2017-03-14 11:30 UTC by andyferris

I mentioned this one at #20978. (This has irked me for some time, but until that discussion I had been pretty sceptical of the foundations of block matrices as `Matrix{Matrix}`)

In theory, `Diagonal` might be used to represent a block-diagonal matrix structure. This takes one small step towards supporting this more fully, and arguably fixes a bug (since transpose is supposed to be recursive, but is not in this case).

@stevengj do you think it is reasonable that `Diagonal` is used for block-diagonal matrices?

2017-03-14 13:18 UTC, andreasnoack approved these changes

2017-03-14 13:18 UTC, andreasnoack commented on base/linalg/diagonal.jl
> +ishermitian(D::Diagonal) = all(ishermitian, D.diag)
I think definition also works for the previous signature so maybe delete the previous.

2017-03-14 13:19 UTC, andreasnoack requested changes

2017-03-14 13:19 UTC, andreasnoack commented on base/linalg/diagonal.jl
> +issymmetric(D::Diagonal) = all(issymmetric, D.Diag)
`Diag` -> `diag`

2017-03-14 17:02 UTC, Sacha0 commented on test/linalg/diagonal.jl
> +end
Perhaps also testing with symmetric and hermitian block diagonal matrices would be worthwhile?

2017-03-15 12:50 UTC, andyferris commented on base/linalg/diagonal.jl
> +ishermitian(D::Diagonal) = all(ishermitian, D.diag)
Yes, it works - but presumably line 104 is a no-op while 105 isn't?

2017-03-15 12:50 UTC, andyferris commented on base/linalg/diagonal.jl
> +issymmetric(D::Diagonal) = all(issymmetric, D.Diag)
Thanks

2017-03-15 12:50 UTC, andyferris commented on test/linalg/diagonal.jl
> +end
Yep - I'm adding some extra tests

2017-03-15 13:11 UTC, andyferris commented
I made fixes and added `expm`, `logm`, `sqrtm`.

2017-03-15 13:19 UTC, andyferris commented on base/linalg/diagonal.jl
>  trace(D::Diagonal) = sum(D.diag)
`trace`, `det`, etc confuse me. Are these meant to be recursive? Should these only work for elements which have a ring structure, such as square matrices of the same size (and return such a matrix), or should it reflect any general block-diagonal structure (and return an actual scalar - i.e. `T` in `Diagona{Matrix{T}}`)? 

(@stevengj @StefanKarpinski this reflects exactly what I was trying to get to the bottom of in the long "Taking matrix transposes seriously" discussion - any help would be appreciated greatly)

2017-03-15 15:16 UTC, StefanKarpinski commented on base/linalg/diagonal.jl
>  trace(D::Diagonal) = sum(D.diag)
I'm not sure, @stevengj may have an opinion. My guess would be that you add/multiply diagonal elements, whatever their type. I doubt these should be recursive, but I don't know.

2017-03-15 23:53 UTC, andyferris commented on base/linalg/diagonal.jl
>  trace(D::Diagonal) = sum(D.diag)
OK, so the recursive `ctranspose` or `adjoint` isn't aimed at trying to model an arbitrary block matrix *per se* (with blocks of possibly differing size), but is designed to (for instance) facilitate a matrix of (compatible) linear operators? 

This make a *lot* more sense to me!

2017-03-16 01:04 UTC, andreasnoack commented on base/linalg/diagonal.jl
>  trace(D::Diagonal) = sum(D.diag)
I guess these methods can just fail if the blocks are not compatible for a specific operation. For some operations, it makes perfect sense to allow different sizes of the blocks.

2017-03-16 01:08 UTC, andyferris commented on base/linalg/diagonal.jl
>  trace(D::Diagonal) = sum(D.diag)
Exactly :)

2017-03-16 10:38 UTC, andyferris commented
I *think* this should be good to go, now.

2017-03-16 16:57 UTC, andreasnoack approved these changes

2017-03-16 16:58 UTC, merged