use newest world callback on_done
JuliaLang/julia pull request #21027
Opened 2017-03-14 19:47 UTC by randy3k

RCall REPL mode requires a custom `on_done` to work. At the current master branch, it is [broken][1].

```
The applicable method may be too new: running in world age 20392, while current world is 20418.
```

It occurs after https://github.com/JuliaLang/julia/pull/17057 and has been reported by https://github.com/JuliaLang/julia/issues/19774. @KristofferC has reported a similar bug for custom keybind in REPL mode at https://github.com/JuliaLang/julia/issues/19718 and it was patched at https://github.com/JuliaLang/julia/pull/19924. This solution suggested is to use `eval` to execute the callbacks, it serves a temp solution before a better solution arrives.

[1]: https://github.com/JuliaInterop/RCall.jl/issues/171

2017-03-16 17:03 UTC, StefanKarpinski commented
Is there any way this could be tested?

2017-03-16 17:04 UTC, StefanKarpinski commented
@yuyichao – since @vtjnash is on vacation, would you mind taking a glance at this?

2017-03-16 20:01 UTC, yuyichao requested changes
This has the sames issue as https://github.com/JuliaLang/julia/pull/19924#issuecomment-271786833 and since it obviously lasted longer than a month it should be probably quoted similar to the ones in REPL.jl .

Also, when is the REPL mode loaded? It seems that it's better to run a heigher level function in the latest world instead.

2017-03-16 20:32 UTC, randy3k commented
So what changes which be made? The REPL modes are all initialized at [run_interface](https://github.com/JuliaLang/julia/blob/34be66a82b85c980ccec8cd84c4c608a93c48784/base/REPL.jl#L942).

2017-03-16 23:16 UTC, randy3k commented
@yuyichao, is this want you meant?

2017-03-16 23:18 UTC, yuyichao approved these changes

2017-03-16 23:19 UTC, yuyichao commented on base/LineEdit.jl
> +                          mode(state(s, s.current_mode)).on_done,
Actually the callee also needs to be quoted...

2017-03-16 23:30 UTC, randy3k commented on base/LineEdit.jl
> +                          mode(state(s, s.current_mode)).on_done,
check the latest commit.

2017-03-17 02:42 UTC, randy3k commented
It seems that appveyor failure is irrelevent.

2017-03-18 16:33 UTC, randy3k commented
@yuyichao does #20167 fix this? Or this patch is still required?

2017-03-18 16:45 UTC, yuyichao commented
This issue is unrelated to https://github.com/JuliaLang/julia/issues/19774 and is not fixed by  #20167

2017-03-18 16:49 UTC, randy3k commented
I see. Is it good to go?

2017-03-18 16:54 UTC, yuyichao commented
I approved this 2 days ago afaict....

2017-03-18 17:17 UTC, nsmith5 commented
Thanks for this work @randy3k. This fixes a similar issue on [Maxima.jl](https://github.com/nsmith5/Maxima.jl.git)

2017-03-18 17:19 UTC, merged

2017-03-18 21:52 UTC, tkelman commented
> Is there any way this could be tested?

was never answered