use crc32c checksum to validate .ji cache files
JuliaLang/julia pull request #21240
Opened 2017-03-30 22:50 UTC by stevengj

As discussed in #21154, the intention for a while has been to use a CRC checksum to validate `.ji` files.  This PR implements that by appending the 4-byte checksum to the `.ji` file after it is created.

It validates the checksum only after a cache file passes the other freshness tests, at which point it is about to be reconstituted/loaded, and the additional time for a checksum seems negligible compared to the cost of loading the cache file.

2017-03-31 00:43 UTC, stevengj commented
For example, `using Compat` takes about 0.02 seconds on my laptop (for a fresh cache), while checksumming the `Compat.ji` file takes about 0.0001 seconds.

2017-05-02 16:30 UTC, stevengj commented
Now that there is a release-0.6 branch, can this be merged into master?

2017-05-02 16:47 UTC, tkelman commented on base/util.jl
> +# compute sizeof correctly for, strings, arrays, and subarrays of bytes
no comma after `for`

2017-05-08 01:41 UTC, stevengj commented on base/util.jl
> +# compute sizeof correctly for, strings, arrays, and subarrays of bytes
fixed

2017-05-22 14:50 UTC, stevengj commented
Okay to merge.  @vtjnash or @yuyichao, do you have any thoughts on this?

2017-05-22 14:58 UTC, yuyichao requested changes

2017-05-22 14:58 UTC, yuyichao commented on base/loading.jl
> +        checksum = ntoh(reinterpret(UInt32, data[end-3:end])[1])
I believe this will throw an error now.....

2017-05-22 15:14 UTC, vtjnash commented on base/loading.jl
> +        checksum = ntoh(reinterpret(UInt32, data[end-3:end])[1])
(which it should, since this is definitely not aligned)

2017-05-24 17:13 UTC, stevengj commented on base/loading.jl
> +        checksum = ntoh(reinterpret(UInt32, data[end-3:end])[1])
Why is it definitely not aligned?  `data[end-3:end]` allocates a new array.

Anyway, I can fix it to not use `reinterpret`.

2017-05-24 17:21 UTC, stevengj commented on base/loading.jl
> +        checksum = ntoh(reinterpret(UInt32, data[end-3:end])[1])
```jl
checksum = UInt32(data[end]) + UInt32(data[end-1])<<8 + UInt32(data[end-2])<<16 + UInt32(data[end-3])<<24
```
should do it

2017-05-24 19:00 UTC, stevengj commented
Fixed and rebased.

2017-05-25 18:14 UTC, stevengj commented
@yuyichao, okay now?

2017-05-25 18:28 UTC, yuyichao approved these changes

2017-05-25 20:46 UTC, stevengj commented
Thanks, will merge in the next day or two if there are no further objections.

2017-06-06 19:17 UTC, merged