Update constructors.md
JuliaLang/julia pull request #21387
Opened 2017-04-14 18:07 UTC by musm

2017-04-14 18:12 UTC, tkelman commented on doc/src/manual/constructors.md
> +this call will return a `Point{T}`. For convenience, the parameters to new{} are
code highlight `new{}`

2017-04-15 17:16 UTC, Sacha0 commented on doc/src/manual/constructors.md
> +for convenience. The outer constructor declaration, on the other hand, defines a method for the
Perhaps nix the second (redundant) "for convenience"?

2017-04-15 17:20 UTC, Sacha0 commented on doc/src/manual/constructors.md
> +specifying parameters for the type to be constructed and this call will return a
The former "i.e." strikes me as more appropriate than the "and"; perhaps revert?

2017-04-15 17:37 UTC, Sacha0 commented on doc/src/manual/constructors.md
> +`SummedArray{T,S}`. `new{T,S}` can be used in any constructor definition (recall, the parameters to
Perhaps for consistency with the near-identical statements above, something along the lines of the following?

"`new{T,S}` can be used in any constructor definition. For convenience, the type parameters to `new{}` are automatically derived from the type being constructed when possible; in the example above, however, the type parameters must be specified explicitly."

2017-04-15 18:42 UTC, musm commented on doc/src/manual/constructors.md
> +`SummedArray{T,S}`. `new{T,S}` can be used in any constructor definition (recall, the parameters to
thanks! please see latest commit

2017-04-16 18:16 UTC, musm commented
Anything else to add here ?

2017-04-16 22:22 UTC, JeffBezanson requested changes

2017-04-16 22:22 UTC, JeffBezanson commented on doc/src/manual/constructors.md
> +           Point{T}(x,y) where {T<:Real} = new{T}(x,y)
This should be `new` instead of `new{T}`, because that is allowed, and we can automatically figure out the type to construct in this case.

2017-04-16 22:25 UTC, JeffBezanson commented on doc/src/manual/constructors.md
> +           Point{T}(x,y) where {T<:Real} = new{T}(x,y)
To further clarify, I feel `new(x, y)` is idiomatic here, so that's what we should show.

2017-04-16 22:25 UTC, JeffBezanson commented on doc/src/manual/constructors.md
> +               new{T}(num, den)
Same here.

2017-04-17 18:44 UTC, closed without merging