Do not use light version of colors by default
JuliaLang/julia pull request #21433
Opened 2017-04-18 17:49 UTC by musm

Ref https://github.com/JuliaLang/julia/pull/11250#issuecomment-294922716 

It looks like all the underscore light_ colors ended up breaking the julia repl color setup for me on 0.6 on, e.g.,  the bash subsystem for windows.

2017-04-18 19:28 UTC, KristofferC requested changes
What I was talking about in the issue was only related to the circles in the julia logo. For the normal text we have to think of something different than this because the standard red is too dark on most terminals. 

We should figure out why the light colors don't work and maybe we can detect those scenarios and only swap in those cases.

2017-04-18 19:37 UTC, JeffBezanson commented
Is using bold colors sufficient to make them readable? @musm can we see a screenshot after this change?

2017-04-18 19:45 UTC, musm commented
This PR simply restores the colors back to what it was in 0.5 .

Comparison of 0.6 and 0.5.1.   standard terminal colors
![image](https://cloud.githubusercontent.com/assets/4319522/25149868/ef8a2a6a-244d-11e7-8719-9460cd9728df.png)

2017-04-18 19:46 UTC, KristofferC commented
No, because they used to be bold and bold + standard color = light color in most terminals.

2017-04-18 19:46 UTC, TotalVerb commented
Changing away from bold seems to be a conscious decision taken in #11250. Can't we use 255-color when it's available?

2017-04-18 19:47 UTC, musm commented
not sure what "most" means, but it's clearly not the case here and I suspect once 0.6 is released I won't be the only one posting an issue regarding this.

2017-04-18 19:47 UTC, KristofferC commented
We could, but AFAIK (I am not an expert on this) it is quite hard to get the terminal to tell you exactly what it supports.

2017-04-18 19:50 UTC, musm commented
Sorry I was mistaken on what it was on 0.5, but clearly that was much better despite the contentious decision regarding the bold choice (which I didn't have a problem, since it rendered the colors properly) than having them show up as in the above screenshots.

2017-04-18 19:53 UTC, KristofferC commented
We've had this for months and this is the first one to report an issue about it. Is something special with your setup?

2017-04-18 20:23 UTC, JeffBezanson commented
I'm missing something here --- don't we still use bold for the prompt and error messages? In which case it seems asking for `light_` versions of colors is just redundant?

2017-04-18 20:33 UTC, JeffBezanson commented
Ah, it seems the `ERROR:` text would be ok, but the message too dark?

2017-04-18 20:44 UTC, KristofferC commented
I would argue standard red is a bit too dark for what is comfortable:

![image](https://cloud.githubusercontent.com/assets/1282691/25152208/9287c6f2-2488-11e7-8267-accb9c972449.png)

2017-04-18 20:49 UTC, JeffBezanson commented
I guess the only other option is to bold the entire message, instead of just the prefix.

2017-04-18 20:50 UTC, musm commented
I really don't think these should be `light_`. Either bold  or not bold, but I don't think it makes sense to have changed them to light variants as that screws up the colors, at least in my case.

light_red is pink on my terminal
and light_green shows up as a dark gray for some reason.....

The julia 0.5 colors worked perfectly. 

My argument is that `light_` are rather specialized colors and may not show up properly on all terminals, Where as you can pretty much be guaranteed `red`, `green`, etc. is not going to cause problems on any terminal that can show colors.

2017-04-18 20:59 UTC, KristofferC commented
You can get back the old color with i.e. `ENV["JULIA_ERROR_COLOR"] = :red`. Regarding the julia terminal, we could change that back to `:green`. I ask again:

> We've had this for months and this is the first one to report an issue about it. Is something special with your setup?

2017-04-18 21:03 UTC, KristofferC commented
Are you for example using the solarized theme?

2017-04-18 21:05 UTC, musm commented
> We've had this for months and this is the first one to report an issue about it. Is something special with your setup?

0.6 hasn't been released yet, so I suspect that is a contributing factor as to why. Nothing special I'm just running things on the linux subsystem for windows. 

> Are you for example using the solarized theme?
no
but if I do use the solarized theme here is how 0.6 looks:
![image](https://cloud.githubusercontent.com/assets/4319522/25153080/417fc9a0-2459-11e7-94ef-3bee6215e4a0.png)

2017-04-18 21:07 UTC, KristofferC commented
Can you do `Pkg.install("Crayons")` and run `Crayons.test_system_colors()`?

2017-04-18 21:11 UTC, JeffBezanson commented
Worth pointing out that everything in this PR except the error color change should be uncontroversial, since it only involves bold text.

2017-04-18 21:15 UTC, musm commented
Im posting the result under  a variety of color scheme to try and illustrate my point
![image](https://cloud.githubusercontent.com/assets/4319522/25153216/d7af2970-2459-11e7-8107-ba71fce7f70d.png)
![image](https://cloud.githubusercontent.com/assets/4319522/25153290/0ce8dc30-245a-11e7-83b4-ea288295b8ef.png)
![image](https://cloud.githubusercontent.com/assets/4319522/25153346/3d8f7a88-245a-11e7-901a-f1dc10ee226d.png)
![image](https://cloud.githubusercontent.com/assets/4319522/25153392/5f8891e2-245a-11e7-99f6-64af632fe791.png)

Most colors make arbitrary decision on what constitutes as a `light` variant, e.g. light_red, which is why I think it should also be changed

2017-04-18 21:16 UTC, TotalVerb commented
Yeah, I agree. It's unfortunate but `light_x` seems to be wildly inconsistent across terminals, so we should avoid using it.

2017-04-18 21:21 UTC, JeffBezanson commented
The second theme in that list should be the default --- is it not?

2017-04-18 21:27 UTC, musm commented
> The second theme in that list should be the default --- is it not?

it is the default theme of the terminal


@KristofferC  In your case I think it would be more desirable to tune the color of the red in your terminal, than to keep the current configuration, because it is very inconsistent as to what constitutes as 'light' in different terminal setups. I feel like the default, should be something that works decently for most people, even if it is not ideal for some.

2017-04-18 21:29 UTC, KristofferC commented
I tried myself, and there was no problems with the default colorscheme on Bash subsystem for windows:

![image](https://cloud.githubusercontent.com/assets/1282691/25153922/ac39b97e-248e-11e7-955c-ec2b4f14a604.png)


> I feel like the default, should be something that works decently for most people

Doing your change suggested here would make it worse for 99.9% of people.

> Yeah, I agree. It's unfortunate but light_x seems to be wildly inconsistent across terminals, so we should avoid using it.

Not really. It is inconsistent in that some (non default) colorschemes happen to set e.g. `light_red` to mean orange. If someone sets a colorscheme that sets their colors to be completely non standard, I don't think this is an issue here but with the color scheme.

2017-04-18 21:32 UTC, TotalVerb commented
The problem is that this is a regression from 0.5. People will not expect the prompt to become invisible upon upgrading to 0.6.

I agree that color schemes being nonstandard is the fault of the color scheme; but those color schemes are popular and we should pick colors that aren't horrible on any machine.

2017-04-18 21:35 UTC, KristofferC commented
They won't, unless they actively made the choice to define `light_red` color to mean invisible color.

2017-04-18 21:35 UTC, JeffBezanson commented
The prompt should be fine since it's still bold. I believe we can safely remove use of `light_` colors with bold.

2017-04-18 21:35 UTC, KristofferC commented
> I believe we can safely remove use of light_ colors with bold.

Yes

2017-04-18 21:49 UTC, musm commented
So is this then ok?

2017-04-18 21:50 UTC, KristofferC commented
No, the `default_error_color` is still being changed.

2017-04-18 21:51 UTC, musm commented
Don't' we want to print the whole error bracktrace in bold, since we have agreed that using `light` is troublesome

2017-04-18 21:52 UTC, KristofferC commented
Who have agreed with that?

As a reference, we also had problems when writing stuff in bold: https://github.com/JuliaLang/julia/issues/8096. It is impossible to support broken setups because they are broken in different ways.

2017-04-18 21:53 UTC, musm commented
I was referring to : 

> I believe we can safely remove use of light_ colors with bold.

and earlier 

> Yeah, I agree. It's unfortunate but light_x seems to be wildly inconsistent across terminals, so we should avoid using it.

2017-04-18 21:59 UTC, JeffBezanson commented
Where we currently use bold and light we might as well use just bold. That leaves light_red for errors, which we do not have an acceptable replacement for. The only thing I think we could do is put the whole error (prefix plus message) in bold, but for consistency that would also have to apply to warn and info, which would require a wider debate.

2017-04-18 22:25 UTC, musm commented
I have made the requested change. I still maintain that the usage of `light` should be avoided for the reasons stated earlier.

2017-04-19 00:30 UTC, JeffBezanson approved these changes

2017-04-19 07:01 UTC, merged