use MKL when available for sparse * dense
JuliaLang/julia pull request #21459
Opened 2017-04-20 21:03 UTC by KristofferC

This moves some code over from https://github.com/JuliaSparse/MKLSparse.jl to Base, so that everyone who compiles with MKL get's (potentially) faster sparse matrix * dense (vector / matrix), which is important in iterative solvers. On my laptop, it was about 25% faster for one "div grad"-matrix I tested.

cc @dmbates from whom the code originally comes from.

Would be nice if the people who regularly use MKL could test this. Tests passes locally using MKL as blas library.

2017-04-20 21:39 UTC, tkelman commented
Would prefer leaving it in the package personally. What problem is solved by putting this here?

2017-04-20 21:58 UTC, KristofferC commented
I explained in the post above what it "solves"?

2017-04-20 22:02 UTC, tkelman commented
Why isn't `Pkg.add("MKLSparse")` sufficient for this? We should be moving code out of base into packages, not the other way around.

2017-04-20 22:52 UTC, ararslan commented
Since this could provide performance improvements in Base code for users who've built Julia with MKL and Base includes an expansive and excellent linear algebra library, it makes some sense to me to have this in here rather than in a package.

2017-04-20 23:30 UTC, tkelman commented
> Since this could provide performance improvements in Base code for users who've built Julia with MKL

So can the package. The expansiveness of the linear algebra code is something that needs reorganization - if we're going to call the language 1.0 any time soon, the standard library is going to need to have less in it.

2017-04-21 06:27 UTC, KristofferC commented
> Why isn't Pkg.add("MKLSparse") sufficient for this?

Try it and report back.

I really don't want to have a long discussion about "standard libraries" that may or may not happen in this decade, there are plenty of dedicated issues for that. Also, indicating that this PR is a step away from calling the language 1.0 (a PR which only effect is improved performance in one of the current supported build configuration) is in my view, nonsense.

Can we focus on the actual code in this PR and then when we are happy of that, whoever wants can argue if it is worth adding 60 lines of code for improved performance of sparse matvec in one of our build configurations.

2017-04-21 07:41 UTC, tknopp commented
> Since this could provide performance improvements in Base code for users who've built Julia with MKL and Base includes an expansive and excellent linear algebra library, it makes some sense to me to have this in here rather than in a package.

Why? Is the code slower if it is contained in the package?

2017-04-21 07:43 UTC, tkelman commented
> Can we focus on the actual code in this PR

I did. I doesn't follow the style guidelines, and there's no technical reason for it to be in this repository.

2017-04-21 07:44 UTC, KristofferC commented
Sure there is. Type piracy is one of them.

2017-04-21 07:51 UTC, tkelman commented
This (like several of the vectorization libraries) is a pretty mild case of it, if it only changes performance and otherwise gives results that are comparable accurate.

Ideally it would be something where you could choose which implementation to dispatch to in a scoped and simple opt-in way, rather than relying on global method tables or version of Julia if this were to get merged here.

2017-04-21 08:08 UTC, tkelman commented
> there are plenty of dedicated issues for that. Also, indicating that this PR is a step away from calling the language 1.0 (a PR which only effect is improved performance in one of the current supported build configuration) is in my view, nonsense.

You're right, there are other issues for that. Issues that are on the 1.0 milestone, and merging this would be adding code that would need to be moved back out again in the process of closing those issues. So, literally, yes a step in the wrong direction. Not a big step, but why move code twice when updating the package for recent Julia versions and registering it will get everyone to the same place sooner?

2017-04-21 08:14 UTC, tkelman requested changes

2017-04-21 08:14 UTC, tkelman commented on base/sparse/mkl_sparse.jl
> +  @eval begin
wrong indent

2017-04-21 08:14 UTC, tkelman commented on base/sparse/mkl_sparse.jl
> +      function cscmv!(transa::Char, α::$T, matdescra::String, A::SparseMatrixCSC{$T, BlasInt}, x::StridedVector{$T}, β::$T, y::StridedVector{$T})
line length

2017-04-21 10:06 UTC, ViralBShah commented
This code doesn't change APIs and is not part of the standard distribution. I am ok with including it for people who use MKL. As for the larger 1.0 and linear algebra part, we have discussed a lot. Whoever really wants it can submit PRs. From my perspective, I am indifferent to it.

2017-04-21 10:09 UTC, tkelman commented
We have very, very little MKL-specific code here in Base. Just BLAS threading, and a single missing FFTW function, as far as I can tell. MKL is a huge library, packages are much better places for library bindings.

2017-04-21 11:07 UTC, KristofferC commented
Tried to do the "right thing". Got stuck on  https://github.com/JuliaLang/BinDeps.jl/issues/99

2017-04-21 11:09 UTC, tkelman commented
Are you attempting to automatically install MKL with BinDeps or something? Seems like the same ccall code as here would be sufficient without needing to do that?

2017-04-21 11:15 UTC, KristofferC commented
There is no point forcing user to build Julia with MKL just to call these MKL functions if it is in a separate package.

2017-04-21 11:19 UTC, tkelman commented
True, but ccall should find libmkl_rt if you've run the mklvars script without needing an absolute path, yeah?

2017-04-21 11:20 UTC, KristofferC commented
Anyway, I can probably just write my own `build.jl` file since the build logic is very simple. I'm ok with trying to revive MKLSparse.jl

2017-04-21 11:20 UTC, closed without merging

2017-04-21 11:41 UTC, ViralBShah commented
Seems reasonable.

2017-04-21 11:44 UTC, dmbates commented
Reviving MKLSparse.jl is fine with me.  It was something Andreas and I were playing with at a Juliacon Hackathon.  I haven't been working on it since because I didn't have a Julia version compiled with MKL.

2017-04-21 18:54 UTC, KristofferC commented
Ref https://github.com/JuliaSparse/MKLSparse.jl/pull/10