Ensure tryparse for dates returns null instead of throwing
JuliaLang/julia pull request #21509
Opened 2017-04-23 18:52 UTC by ararslan

Currently only issues with parsing will result in null values from `tryparse` for dates; invalid date values still result in errors. With this PR, invalid dates also result in null values, which is consistent with `tryparse` for other types.

Fixes #21504

2017-04-23 19:01 UTC, tkelman commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
what would make this throw? the point of tryparse is to avoid try-catch

2017-04-23 19:02 UTC, ararslan commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
The `T` constructor can throw. Not sure how else to avoid throwing an error from that.

2017-04-23 19:03 UTC, tkelman commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
is there an `isvalid` type check that could be done?

2017-04-23 19:05 UTC, ararslan commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
Not that I can think of, since `isvalid` currently only has methods for strings and characters.

2017-04-23 19:07 UTC, ararslan commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
The only other way I can think to do this is to specialize on each subtype of `TimeType` and duplicate the checks done by the type constructors. That's kind of intractable.

2017-04-23 19:10 UTC, tkelman commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
or refactor so the type constructors call isvalid ?

2017-04-23 19:17 UTC, ararslan commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
Thought about that but then you lose the ability to emit specific error messages for any potential issue.

2017-04-23 19:19 UTC, tkelman commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
should probably start using https://github.com/iamed2/ResultTypes.jl when all the dates code moves to a package (libgit2 could also use this kind of thing)

2017-04-23 19:30 UTC, ararslan commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
It would be nice to have a type like that in Base. In the meantime though, does this seem like a reasonable solution?

2017-04-24 11:36 UTC, tkelman commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
I wonder whether there's an API we could use for now where we have `isvalid` return both a flag and an error string if called with an optional `Val{true}` or something, as a way of avoiding the code duplication without needing try-catches.

2017-04-24 13:05 UTC, nalimilan commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
Makes sense. We could also pass `Exception` or a similar type as the first argument to `isvalid` to enable this behavior (with the idea that the non-throwing behavior would be equivalent to passing `Bool`).

2017-04-24 13:23 UTC, omus commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
We probably need to already have the first parameter of `isvalid` being the `TimeType` subtype. aka `isvalid{T<:TimeType}(T, values...)`.

2017-04-24 13:24 UTC, omus commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
I think what we probably need is a new function that returns a `Nullable{Exception}` which returns exception that the `TimeType` constructor would raise.

2017-04-24 13:33 UTC, nalimilan commented
> We probably need to already have the first parameter of isvalid being the TimeType subtype. aka isvalid{T<:TimeType}(T, values...).

That's not a problem, we can override `isvalid(::Type{Exception}, ::Type, ...)` without any ambiguity.

2017-04-24 13:33 UTC, tkelman commented on base/dates/parse.jl
> +            parsed = Nullable{T}(T(unsafe_get(values)...))
Oh I guess that's an interesting reversal, where null would mean no-exception, things are fine, it is valid.

2017-04-24 13:36 UTC, omus commented
> That's not a problem, we can override isvalid(::Type{Exception}, ::Type, ...) without any ambiguity.

I think there is a problem in that `isvalid` is suppose to just return `Bool`. We could make a similar function that just returns the exception which would be have been raised:

```
pretend(::Type{T}, parameters...) -> Nullable{Exception}
```

2017-04-24 13:43 UTC, omus commented on test/dates/io.jl
> +@test isnull(tryparse(Dates.Date, "0-1000"))
Would probably be good to add this kind of thing to the benchmarks.

2017-04-24 22:38 UTC, ararslan commented
Marking this WIP until I can find the time to properly refactor in accordance with the comments here. Thanks everyone for the feedback!

2017-04-26 02:28 UTC, ararslan commented
I have an implementation of @omus's suggested function that returns a `Nullable{Exception}`. Seems to work alright (the tests pass for me locally).

2017-04-26 14:43 UTC, omus requested changes

2017-04-26 14:43 UTC, omus commented on base/dates/types.jl
> +    return Nullable(ArgumentError(msg))
Avoid the negation and the nested ternary operator by writing as:
```julia
exception = str -> Nullable(ArgumentError(str))
0 < m < 13 || return exception("Month: $m out of range (1:12)")
0 < d < daysinmonth(y, m) + 1 || return exception("Day: $d out of range (1:$(daysinmonth(y, m)))")
...
return Nullable{ArgumentError}()
```

2017-04-26 14:43 UTC, omus commented on base/dates/parse.jl
>          Nullable{T}(T(unsafe_get(values)...))
Too bad that we are calling validargs twice

2017-04-26 16:45 UTC, ararslan commented on base/dates/types.jl
> +    return Nullable(ArgumentError(msg))
Good call, thanks.

2017-04-26 16:46 UTC, ararslan commented on base/dates/parse.jl
>          Nullable{T}(T(unsafe_get(values)...))
Well, I could add a flag to the `TimeType` constructors like `check=true` that should be user-invisible and dictates whether `validargs` should be called. `check=false` would really only be used in this function though, I'd imagine.

2017-04-26 18:02 UTC, omus commented on base/dates/parse.jl
>          Nullable{T}(T(unsafe_get(values)...))
I'm not too worried about this part. We can leave it as it is.

2017-04-26 19:28 UTC, ararslan commented on base/dates/parse.jl
>          Nullable{T}(T(unsafe_get(values)...))
Okay, will do.

2017-04-27 00:43 UTC, ararslan commented
@omus How does it look now?

An alternative to explicitly calling `validargs` in each function, we could do something like
```julia
macro checkargs(func)
    if func.head !== :function
        throw(ArgumentError("invalid use of @checkargs"))
    end
    sig = func.args[1].args
    body = func.args[2]
    f = sig[1]
    xs = sig[2:end]
    barexs = map(s -> isa(s, Symbol) ? s : s.head === :(::) ? s.args[1] : s, xs)
    quote
        function $(esc(f))($(xs...))
            err = validargs($(esc(f)), $(barexs...))
            isnull(err) || throw(get(err))
            $body
        end
    end
end
```
then define the constructors as `@checkargs function Date(...) ... end`. Just a thought.

2017-04-27 05:09 UTC, omus approved these changes
Looks good!

2017-04-27 17:18 UTC, ararslan commented
Does anyone else want to give this another look?

2017-04-28 08:39 UTC, merged