Only evalate `fexpr` in `fexpr(kw=...)` once
JuliaLang/julia pull request #21519
Opened 2017-04-24 08:19 UTC by martinholters

Lower e.g. `get_inner()(kw=1)` to
```
SSAValue(n) = get_inner()
((Core.kwfunc)(SSAValue(n)))((Base.vector_any)(:kw, 1), SSAValue(n))
```
instead of
```
((Core.kwfunc)(get_inner()))((Base.vector_any)(:kw, 1), get_inner())
```
as the latter would call `get_inner` twice.

Fixes #21518.

2017-04-24 19:23 UTC, JeffBezanson requested changes

2017-04-24 19:23 UTC, JeffBezanson commented on src/julia-syntax.scm
> +              (= ,f, fexpr)
Would be good to insert this only if `(not (sym-ref? fexpr))`, to keep the IR simpler.

2017-04-25 06:40 UTC, martinholters commented on src/julia-syntax.scm
> +              (= ,f, fexpr)
Makes sense. I hope my non-existent lisp skills can take me there...

2017-04-26 06:59 UTC, martinholters commented
@JeffBezanson does this look ok to you?

2017-04-26 11:37 UTC, tkelman commented on test/keywordargs.jl
> +a = 0
can this be made a `let` and still accomplish the test?

2017-04-26 17:02 UTC, JeffBezanson commented
@martinholters Yes this should work, thanks! I really appreciate your help here.

2017-04-26 17:03 UTC, JeffBezanson commented on src/julia-syntax.scm
> +            ,(if (eq? f fexpr) () `(= ,f, fexpr))
A slightly better way to write this is `,@(if (eq? f fexpr) '() `((= ,f, fexpr)))`, which will insert nothing at all when no assignment is needed.

2017-04-26 19:03 UTC, martinholters commented on test/keywordargs.jl
> +a = 0
Yes, `let` should work.

2017-04-26 19:46 UTC, martinholters commented on src/julia-syntax.scm
> +            ,(if (eq? f fexpr) () `(= ,f, fexpr))
Ah, ok, will update.

2017-04-26 19:49 UTC, martinholters commented
> I really appreciate your help here.

I was wondering whether reviewing my PR would be about as much work as doing it yourself. So I guess not quite :smile:

2017-04-26 19:56 UTC, martinholters commented
Updated. Should be squashed when merged.

2017-04-26 20:20 UTC, JeffBezanson commented
I consider this a very worthwhile investment in our "bus number" :)

2017-04-27 04:03 UTC, merged

2017-05-03 08:38 UTC, martinholters commented
Not the best time to ask with 0.5.2 almost ready, but... should we backport this? The bug does affect 0.5, but I don't think it will be hit very often and it has a simple work-around.

2017-05-03 16:58 UTC, StefanKarpinski commented
Does the patch apply fairly cleanly? If so, I don't see why not.