Fixing 2 broken links in Dates documentation
JuliaLang/julia pull request #21511
Opened 2017-04-24 00:06 UTC by charlesll

Searching for information about Dates and DateTime in

https://docs.julialang.org/en/release-0.5/manual/dates/

I found broken links at the end of the page, pointing to

https://docs.julialang.org/en/latest/stdlib/dates/

As it is in the doc of the stable 0.5 version, pointing to the stable version of stdlib/dates makes it work:

https://docs.julialang.org/en/stable/stdlib/dates/

2017-04-24 00:14 UTC, yuyichao requested changes
You are changing the master doc, which shouldn't point to the 0.5 version. It also seems that these should probably use reference syntax and not hardcode the full url? Do we support that here?.

2017-04-24 00:34 UTC, charlesll commented
OK, should I close this PR and do it on the 0.5 branch? 

The link https://docs.julialang.org/en/stable/stdlib/dates/ works, whereas https://docs.julialang.org/en/stable/stdlib/dates.html does not. 

I don't know really much more about the use of reference syntax vs url, so maybe I can open an issue instead of a PR if somebody more skilled wants to solve it?

2017-04-24 00:36 UTC, yuyichao commented
This should ideally be fixed using the correct syntax. Hard coding a release-0.5 URL on the 0.5 branch might be good enough for now. The master version should still be properly fixed.

2017-04-24 02:48 UTC, ararslan commented on doc/src/manual/dates.md
> +details on the available `RoundingMode` s can be found in the [API reference](https://docs.julialang.org/en/stable/stdlib/dates/).
If I'm not mistaken, I think this can be `[API reference](@ref Dates)`, which will tell Documenter to link to the Dates section.

2017-04-24 02:51 UTC, ararslan commented on doc/src/manual/dates.md
> +details on the available `RoundingMode` s can be found in the [API reference](https://docs.julialang.org/en/stable/stdlib/dates/).
That applies to master though; the 0.5 series doesn't use Documenter for docs.

2017-08-09 02:15 UTC, fredrikekre commented
#22201

2017-08-09 02:15 UTC, closed without merging