Fix #21604, check Any fields at runtime
JuliaLang/julia pull request #21607
Opened 2017-04-28 03:26 UTC by TotalVerb

This moves the check for whether field types are `Any` or not to runtime instead of at lowering time.

I made the assumption that `X == Any` iff `X === Any` here; please tell me if that is invalid. (Maybe we need `Core.issubtype(Any, X)`?)

2017-04-28 11:37 UTC, martinholters commented
Is it worth keeping the check in lowering to avoid the runtime check if it is known to be the case because there is a literal `Any` there?

2017-04-28 11:57 UTC, tkelman commented
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

2017-04-28 16:22 UTC, JeffBezanson approved these changes

2017-04-28 16:44 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21607#issuecomment-297979561) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/52eecdb4fc7e749fa7f3a7f8132ef9ff19ec3a6f/348bfe9_vs_e6ab126/report.md). cc @jrevels

2017-04-28 16:45 UTC, TotalVerb commented
Should we rerun the array and tuple benchmarks? I doubt the regressions are real.

2017-04-28 16:51 UTC, Sacha0 commented
> Should we rerun the array and tuple benchmarks? I doubt the regressions are real.

Some of the potential array regressions seem larger than typically occurs via noise, so to be safe @nanosoldier `runbenchmarks("array", vs = ":master")`

2017-04-28 18:42 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21607#issuecomment-298049889) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1d4cf2c645a00f91e90233dd1a6857340a1fc189/1ee55e9_vs_de15be0/report.md). cc @jrevels

2017-04-28 18:45 UTC, TotalVerb commented
The name looks similar but it's actually a different noisy `sumvector_view` benchmark, so I think this should be good to go.

2017-04-28 19:11 UTC, Sacha0 commented
Agreed, the combination of nanosoldier results look solid :).

2017-04-28 19:16 UTC, Sacha0 commented
@martinholters, your edit suggests you approve these changes? If so (with you and `JeffBezanson` both approving), perhaps merge at will? Best!

2017-04-28 19:47 UTC, martinholters commented
Fine with me, but not that I have thoroughly reviewed this.

2017-04-28 20:21 UTC, JeffBezanson commented
One thing we could do is use `(core Any)` as the default field type, and then we could skip the check for types `equal?` to that.

2017-04-28 20:49 UTC, TotalVerb commented
@JeffBezanson I've implemented that suggestion. Could you check again?

2017-04-28 21:08 UTC, TotalVerb commented
On a not-unrelated note, perhaps unnoticed until now because it is admittedly a very strange situation, there are some cases where we might prefer to use `(core Any)` instead of `'Any`:

```julia
julia> Any = Integer
WARNING: imported binding for Any overwritten in module Main
Integer

julia> type X end

julia> supertype(X)
Integer
```

2017-04-28 21:10 UTC, JeffBezanson commented
Yes, might as well fix those too.

2017-04-28 21:48 UTC, TotalVerb commented
I've replaced `'Any` with `'(core Any)` in many places and added some tests.

2017-04-28 22:24 UTC, JeffBezanson requested changes

2017-04-28 22:24 UTC, JeffBezanson commented on src/julia-syntax.scm
> +              ,(if (eq? rett '(core Any))
This will need to use `equal?`.

2017-04-28 22:28 UTC, TotalVerb commented on src/julia-syntax.scm
> +              ,(if (eq? rett '(core Any))
Good catch, thanks!

2017-04-28 22:36 UTC, JeffBezanson approved these changes

2017-04-29 15:50 UTC, Sacha0 commented
With the changes, what say you @nanosoldier `runbenchmarks(ALL, vs = ":master")` ?

2017-04-29 18:51 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21607#issuecomment-298176930) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/516cd0d72b84bbee80dcdc5474e28f1fc55028ab/7f340c3_vs_101dccc/report.md). cc @jrevels

2017-04-29 18:52 UTC, TotalVerb commented
I think it's safe to say that these are noise.

2017-04-30 00:47 UTC, merged