fix links to docs
JuliaLang/julia pull request #21766
Opened 2017-05-10 02:28 UTC by WestleyArgentum

These links weren't working for me. A couple returned 404 and the one about debugging segfaults said "permission denied" (how rude...)

It's possible these links are changing moving forward? Not sure, but this made them work for me for now.

2017-05-10 02:34 UTC, yuyichao requested changes
Please don't link to stable doc. The new doc is at  https://docs.julialang.org/en/latest

2017-05-11 12:43 UTC, StefanKarpinski commented
So the correct fix here is to link to latest docs hosted at docs.julialang.org and not include trailing slashes in URL names, e.g. `https://docs.julialang.org/en/latest/manual/packages`. Any doc links to http://julia.readthedocs.io/ should be changed and any trailing slashes should be stripped.

2017-05-11 21:35 UTC, WestleyArgentum commented
updated and ran threw all the links to make them consistent, let me know if that looks better

2017-05-11 21:38 UTC, Sacha0 commented on CONTRIBUTING.md
> +- Library feature requests are generally not accepted on this issue tracker. New libraries should be developed as [packages](https://docs.julialang.org/en/release-0.4/manual/packages/#package-develop
Should the link to the packages documentation point to latest rather than release-0.4?

2017-05-11 22:03 UTC, WestleyArgentum commented on CONTRIBUTING.md
> +- Library feature requests are generally not accepted on this issue tracker. New libraries should be developed as [packages](https://docs.julialang.org/en/release-0.4/manual/packages/#package-develop
oh, good catch

2017-05-12 15:50 UTC, Sacha0 approved these changes
Thanks @WestleyArgentum! :) (I have not tested the links.)

2017-05-13 01:05 UTC, merged