Fix stack overflow in SSHCredentials constructor
JuliaLang/julia pull request #21779
Opened 2017-05-10 19:33 UTC by ararslan

Fixes #21775

2017-05-10 21:29 UTC, kshyatt commented on test/libgit2.jl
> +        cred = LibGit2.SSHCredentials("rick", "astley")
nice

2017-05-10 21:30 UTC, kshyatt approved these changes
LGTM but you might want @Keno or @omus to take a look as well.

2017-05-10 21:47 UTC, omus requested changes
The fix looks good. I accidentally introduced this in #20738.

2017-05-10 21:47 UTC, omus commented on test/libgit2.jl
> +end
I'm not sure we need to explicitly be testing for a StackOverflow. Maybe just a basic test which uses this constructor should be added into the "Credentials" testset?

2017-05-11 02:43 UTC, ararslan commented on test/libgit2.jl
> +end
Good idea. I was just being lazy here. Implemented your suggestion. Thanks!

2017-05-11 04:22 UTC, ararslan commented
64-bit AV failure is unrelated

2017-05-11 12:10 UTC, omus approved these changes

2017-05-11 15:07 UTC, merged