[RFC] limit maximum vector alignment to heap alignment
JuliaLang/julia pull request #21980
Opened 2017-05-20 08:47 UTC by vchuravy

This imposes an upper limit on the vector alignment of 16. This is the current guaranteed alignment of the heap and after #21959 we can raise the limit to 64. In 0.5 we were a lot more conservative with the alignment given to memory loads.

I consider this a band-aid fix for #20961 and #21918. I don't know how the full fix for #20961 would look like, but I think it will involve fixing the `DataLayout` fallback in LLVM [1] and `jl_special_vector_alignment` will have to start taking the `DataLayout` into account.

[1] https://github.com/llvm-mirror/llvm/blob/836dd8e1f01318ac7f1149d399ce36b064404cb4/lib/IR/DataLayout.cpp#L507-L514

2017-05-20 09:05 UTC, vchuravy commented on src/cgutils.cpp
> +                       julia_alignment == llvm_alignment);
This assert is wrong needs to be:
```
assert(julia_alignment <= JL_SMALL_BYTE_ALIGNMENT);
assert(llvm_alignment <= JL_SMALL_BYTE_ALIGNMENT &
           julia_alignment == llvm_alignment);
```

2017-05-21 09:37 UTC, vchuravy commented
@yuyichao should I split the last three commits out into a separate PR? This became more invasive then I thought.

2017-05-21 11:16 UTC, vchuravy commented
@nanosoldier `runbenchmarks(ALL, vs = "master")`
@jlbuild

2017-05-21 11:16 UTC, jlbuild commented
Got it, building https://github.com/JuliaLang/julia/commit/f9931021fe1cd8982130a0c10e85c9d837bf5017

I will edit this comment as the build jobs complete.

2017-05-21 11:17 UTC, jlbuild commented
Got it, building https://github.com/JuliaLang/julia/commit/f9931021fe1cd8982130a0c10e85c9d837bf5017

I will edit this comment as the build jobs complete.

2017-05-21 11:17 UTC, vchuravy commented
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

2017-05-21 12:52 UTC, yuyichao requested changes

2017-05-21 12:52 UTC, yuyichao commented on src/cgutils.cpp
> +                if (llvm_alignment  <= JL_HEAP_ALIGNMENT)
This should only be a temporary workaround.

2017-05-21 12:52 UTC, yuyichao commented on src/gc.c
> +    sz = LLT_ALIGN(sz, JL_HEAP_ALIGNMENT);
This shouldn't be changed. (i.e. this should stay at 16 when you change the heap_alignment to 64)

2017-05-21 12:52 UTC, yuyichao commented on src/intrinsics.cpp
> +        alignment = JL_HEAP_ALIGNMENT;
This shouldn't be changed since this won't increase. It might even be too much and should be `sizeof(void*) * 2` now.

2017-05-21 12:52 UTC, yuyichao commented on src/cgutils.cpp
> +    if (alignment > JL_HEAP_ALIGNMENT)
This should be an assertion in the condition above. When used in `pointerref`/`pointerset` the user should be allowed to specify larger alignment.

2017-05-21 12:54 UTC, yuyichao commented
I was reviewing under the assumption that `JL_HEAP_ALIGNMENT` is meant to be the max alignment that the GC can provide.

2017-05-21 13:21 UTC, vchuravy commented on src/intrinsics.cpp
> +        alignment = JL_HEAP_ALIGNMENT;
so it should be `MAX_ALIGN`?

2017-05-21 13:43 UTC, vchuravy commented
@jlbuild !nuke

2017-05-21 13:43 UTC, jlbuild commented
Got it, building https://github.com/JuliaLang/julia/commit/151bd81ef8d1778ac771eb9e1ef680a09d8e2321

I will edit this comment as the build jobs complete.

2017-05-21 14:10 UTC, yuyichao requested changes

2017-05-21 14:10 UTC, yuyichao commented on src/cgutils.cpp
> +                // TODO: Fix alignment calculation in LLVM.
Also fix the calculation on our side both in GC and in the struct declaration....

2017-05-21 14:10 UTC, yuyichao commented on src/gc.c
> +                                  GC_PERM_POOL_SIZE + JL_HEAP_ALIGNMENT,
..... The comment above applys to these too....... The permgen allocation shouldn't be changed.

2017-05-21 14:10 UTC, yuyichao commented on src/intrinsics.cpp
> -         // julia's gc gives 16-byte aligned addresses
Keep this comment for now I guess...

2017-05-21 14:10 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21980#issuecomment-302930345) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ad9d8ed6ab5e700fab70fdfd9a60bc82cfd6cb5d/6e2e213_vs_f988566/report.md). cc @jrevels

2017-05-21 23:57 UTC, vchuravy commented
@jlbuild !nuke !filter=linux, osx
```
Pkg.add("SIMD"); Pkg.test("SIMD")
```

2017-05-22 00:47 UTC, jlbuild commented
Got it, building https://github.com/JuliaLang/julia/commit/3c39b0a78be002b61234234ff4507d6bd6914272

I will edit this comment as the build jobs complete.

2017-05-22 13:49 UTC, vchuravy commented
@eschnett have you seen the SIMD.jl failure on 32bit linux before? https://buildog.julialang.org/#/builders/45/builds/1

```
Test Failed
  Expression: s === sum(xs)
   Evaluated: -3.927754334663871e235 === 91.0
ERROR: LoadError: There was an error during testing
while loading /home/buildworker/.julia/v0.7/SIMD/test/runtests.jl, in expression starting on line 372
```

2017-05-22 14:26 UTC, yuyichao approved these changes

2017-05-22 16:41 UTC, tkelman commented on test/vecelement.jl
> +               NTuple{N, VecElement{T}},
unusual indent in this block?

2017-05-22 16:42 UTC, tkelman commented on test/vecelement.jl
> +            code_llvm(STDOUT, f20961, (Vector{Vec{N, T}}, Vector{Vec{N, T}}))
is this temporary? less noisy to output this to a buffer and test for something instead?

2017-05-23 21:26 UTC, vchuravy commented
If there are no further comments I plan to merge this in about 24h

2017-05-24 23:46 UTC, merged