[WIP/RFC] Exact array resize!()
JuliaLang/julia pull request #22038
Opened 2017-05-23 14:49 UTC by alyst

Sometimes it's useful to have precise control over memory size allocated for a given array (see e.g. #21938).
One would assume it could be done by `resize!()`, but under the hood it calls `jl_array_grow_at_end()`.
The latter method is actually tuned for the gradually growing arrays, it would set allocate the exactly requested size only if an array is empty,
otherwise it would allocate the next power of 2 that is greater or equal to the requested size.

There are several options:
* do nothing
* change the heuristic to allocate exactly requested amounts in more cases -- this is what is currently implemented by this PR
* add keyword/positional `exact` argument to resize!(); probably would also require new low-level `jl_array_set_size()` method
* change the behaviour of `resize!()` to always grow to the exactly specified size
* add new `resize_exact!()` method (either exported or not)
* ...

2017-05-23 14:59 UTC, KristofferC commented
Any thoughts about `sizehint!`? Does / should it follow the same rule?

2017-05-23 16:12 UTC, alyst commented
IMO the same changes should be done to `sizehint!()`. It would be nice if they remain easily interchangeable.

2017-05-23 16:20 UTC, KristofferC commented
This makes sense to me. For example, when you create a sparse matrix it is common that you know exactly how many stored elements you will have so you might do a `sizehint!(I, large_number)`. Wasting a factor of 2 memory seems unnecessary.

2017-05-23 16:22 UTC, StefanKarpinski commented
Since the cost of the size not being exact is ~one extra resize versus up to 2x memory waste, taking size hints and resizes literally seems like a good idea.

2017-05-23 16:55 UTC, andreasnoack commented
Also, in the motivating use case, #21938, we know that the arrays will never grow again.

2017-05-24 08:34 UTC, alyst commented
It seems #22044 has fixed the issue with the string interpolation that got exposed by 6d92926360032ce13897612674cd474bc9bcc885 (see #21938 comments): after rebasing to the current master the QR tests are fine again.

2017-05-25 07:59 UTC, KristofferC commented
Since `sizehint!` ends up calling the function modified here, this would automatically work for `sizehint!` as well, right? https://github.com/JuliaLang/julia/blob/298fffb6a9c4ecdf97c10e61f02414b16fa23da2/src/array.c#L925

2017-05-25 22:04 UTC, alyst commented
First take on making `resize!()` and `sizehint!()` always growing to an exactly specified size.

2017-05-26 05:05 UTC, alyst commented
@nanosoldier `runbenchmarks(ALL, vs=":master")`

2017-05-26 05:07 UTC, alyst commented
Looks like @nanosoldier doesn't listen to me.

2017-05-26 07:23 UTC, KristofferC commented
@nanosoldier `runbenchmarks(ALL, vs=":master")`

2017-05-26 10:23 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22038#issuecomment-304211950) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/23d322ac68c91b9bde763d9c08559c4e72a973a6/ea9cc72_vs_9e3318c/report.md). cc @jrevels

2017-05-26 10:30 UTC, KristofferC commented
On the positive side, `string, join` does take less memory now :D

2017-05-26 15:42 UTC, yuyichao commented
The necessity last commit basically means that user code that reserves multiple elements with `resize!` and then assign to them in batches will be much slower than just pushing individual elements so the behavior of `resize!` should not be changed when the increment is small (the original change in the heuristics is good though).

2017-05-26 15:54 UTC, alyst commented
Definitely there should be a way for the user to grow an array the old way.
It could be either the new exported `grow!(a, n)` method.
Or, an additional `exact` param for `resize!()`. In the latter case -- should it default to `exact=true` or `exact=false` (old behaviour)?
IMHO, calling `resize!()` within appending loop sounds a little bit confusing, I would rather use another verb.

2017-05-26 16:18 UTC, yuyichao commented
`resize!` should definitely stay with it's current default. I see no point of making everyone's code suddently slower unless we're moving to a new name altogether.

2017-05-26 16:32 UTC, alyst commented
I'm not sure `resize!()` is used that much in the packages in the append context. For arrays there's `push!()` and `append!()`, and low-level streams are already implemented in `Base`.
OTOH in the Base we don't see a lot of improvements when `exact=true` is the default.

2017-05-26 16:40 UTC, alyst commented
Could somebody ask nanosoldier? Thanks!

2017-05-26 16:44 UTC, KristofferC commented
@nanosoldier `runbenchmarks(ALL, vs=":master")`

2017-05-26 16:57 UTC, yuyichao requested changes
> I'm not sure resize!() is used that much in the packages in the append context.

The point is that this change gives a `O(1)` memory saving and a `O(n)` performance regression. It's basically always wrong when a small increment is used.

2017-05-26 19:39 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22038#issuecomment-304331300) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ecf5dc5b1a58bc4ac491b64d37a03954392d5dca/7d1c280_vs_7ffa3bf/report.md). cc @jrevels

2017-05-26 20:24 UTC, alyst commented
Now the benchmarks looks ok, let's try to decide on the API changes :)
 
I don't like `resize!(A, n, exact::Bool)` much: "non-exact resize" sounds confusing.
What about `resize!(A, n, preemptive::Bool=false)`, where `preemptive=true` means the current behaviour? At the moment `resize!()` documentation doesn't mention the fact that it allocates more than requested and that this feature could be exploited for growing an array. So making "exact resize" a default behaviour seems a fair change. The same for `sizehint!()`

2017-05-26 21:14 UTC, yuyichao commented
> At the moment resize!() documentation doesn't mention the fact that it allocates more than requested and that this feature could be exploited for growing an array. So making "exact resize" a default behaviour seems a fair change. The same for sizehint!()

No, it's not documented in the same way as `push!` isn't documented to be fast. People expect them to do the right thing and it's a bad argument to make them `O(n)` slower. They should still be documented but the lack of that is irrelevant for this change.

2017-05-26 21:53 UTC, alyst commented
> People expect them to do the right thing and it's a bad argument to make them O(n) slower.

What is "the right thing" for `resize!()`? At least it's context-dependent. For LAPACK preemptive behaviour could mean gigabytes of unnecessary allocated memory with all the consequences of hitting physical memory limits. IMHO if `resize!()` is called in a loop from the user/package code, it looks like a wrong code pattern, and the author should assert that he really means it by explicitly specifying `preemptive=true`.

Well, I'm out of anti-preemptive arguments for the moment :) With the updated `jl_array_grow_at_end()` heuristic I wouldn't be so much obsessed with specifying `preemptive=false` for each `resize!()` call in my code.
Just want to be sure that everyone interested agrees with `preemptive=true` (including the parameter name) before I'll update the PR.

2017-05-26 21:53 UTC, nalimilan commented
Personally I would expect "the right thing" for `resize!` to be "resize this array to the exact size I specified", not "leave a bit more room in case I want to resize it again soon". The right abstraction level seems to be `push!` and `append!`, which can easily pass `exact=false`. Do we have evidence that people use `resize!` when growing an array progressively, rather than calling `push!` or `append!`?

2017-05-27 01:07 UTC, yuyichao commented
> Do we have evidence that people use resize! when growing an array progressively, rather than calling push! or append!?

Short of any other function to do it currently I believe `resize!` is the correct function to do it right now. There are certainly a lot of cases in base that does something similar (not just `Array`, but also `arraylist_t` in C) so I believe it's a valid use case that shouldn't be broken and doesn't worth requireing users to change their code especially because there's no way we can issue a warning for this and it'll be really hard to catch (and this is also why I think it'll be fine to change the default [if we rename it altogether](https://github.com/JuliaLang/julia/pull/22038#issuecomment-304325045))

I'll still repeat that exact resize will only save `O(1)` memory (less than a factor of 2, maybe ~1.5x on average assuming some random distribution). The default heuristic can certainly be changed to do exact resizing after a threshold. In fact, doing at least 2x or exact resizing as default should still provide the same scaling while providing a net saving of memory.

2017-05-27 06:50 UTC, KristofferC commented
Isn't the thing that `O(1)` can still be very large?

2017-05-27 14:22 UTC, yuyichao commented
Well it cannot be larger than 2.

2017-05-30 19:21 UTC, andreasnoack commented
> I'll still repeat that exact resize will only save `O(1)` memory

The point is that in some applications, the asymptotic behavior is not relevant. In the LAPACK wrappers, we have `n = 2`, not `n -> Inf`, so big O is not the right metric for that usecase.

2017-05-30 19:33 UTC, yuyichao commented
Sure, I totally understand that. That's why I'm certainly fine with offering a function to do exact resize and even change the default heuristic to do exact resize in some cases.

What I don't think we should not be doing is to change the code in a way that can make previously valid use of the function much slower without a clear warning. The PR is it's current state causes just that.

2017-05-30 20:31 UTC, alyst commented
What if we still change the default behaviour, but for the transition period introduce a warning into `resize!()` that is triggered when the absolute and relative size increase are below certain threshold (say, 4 and 1/16)?

Can also do it in several phases:
1. introduce the exact resize, but keep the preemptive one the default, merge into master.
2. run pkgeval on the new branch that makes the exact resize the default and notify authors of packages that rely on preemptive resize
3. once the packages are updated, change the resize behaviour for master (but keep the warning until 1.0 cycle)

2017-05-30 20:34 UTC, yuyichao commented
> introduce a warning into resize!() that is triggered when the absolute and relative size increase are below certain threshold (say, 4 and 1/16)?

That will certainly be too annoy since it'll give way too many false positives. And unless you keep this warning for one full release it'll be impossible to catch all the cases in private code.

2017-05-30 20:42 UTC, StefanKarpinski commented
I suspect that we can come up with a better heuristic here. There are two use cases we expect:

1. Call `resize!` / `sizehint!` once with an exact correct size. In this case, we want to allocate exactly that much space and no more.
2. Call `resize!` / `sizehint!` repeatedly with approximate expected size. In this case, we want to make sure that we have O(n) extra room so that the amortized cost is O(1).

So how about this: if (new size)/(current size) < 1.25 then allocate exactly the requested size; otherwise, do exponential growth. I'm pretty sure that guarantees O(1) amortized cost while making the single hint case efficient.

2017-05-30 20:45 UTC, StefanKarpinski commented
Very hand-wavy analysis: in the exact growth case, exponential growth is guaranteed by the ≥ 25% threshold; in the other case, it's guaranteed by the growth algorithm itself.

2017-05-30 20:54 UTC, yuyichao commented
Yeah, that's exactly what I proposed in https://github.com/JuliaLang/julia/pull/22038#issuecomment-304416201 (with a different factor). And also what the PR originally implements (with yet another factor).

2017-05-30 20:56 UTC, alyst commented
In the previous of heuristic the threshold was 700%, so I'm fine with 25%. Can even use 100% so that both cases have the same exponent.

2017-05-30 21:21 UTC, StefanKarpinski commented
My reasoning for 25% is that there are papers which report that 50% growth actually gives optimal performance for exponential growth, and 0% is O(n^2) case that's problematic, so split the difference and make the cutoff halfway between 0% and 50%. The precise cutoff probably doesn't matter.

2017-05-30 21:22 UTC, StefanKarpinski commented
Should there be a shrinkwrap exception? I.e. when the requested size is ≤ the current size, we make it exactly that size? I guess that could lead to bad behavior if a vector is being used as a stack or a dequeue.

2017-05-30 22:08 UTC, yuyichao commented
The growing factor is https://github.com/JuliaLang/julia/issues/8269 and https://github.com/JuliaLang/julia/pull/16305 and I would rather not tie it up with this one. What I was suggesting as a default heuristic is basically

```
size_t new_size = old_size * grow_factor;
new_size = new_size > request_size ? new_size : request_size;
```

And we can change the grow factor if there's clear evident that it's better.

2017-05-30 22:20 UTC, rfourquet commented
It's an expected pattern to call `resize!` repeatedly by (small) increments (e.g. in a loop), so doing always "exact resize!" would be terrible. `resize!` is about the actual size of the array, I agree with @yuyichao that the allocation mechanism should do "the right thing" (I would believe most of the time RAM memory is big enough to accomodate the exponential growth factor). If one wants to opimize for space, `sizehint!` seems the more appropriate level to control those implementation details. At the same level, there could be a `shrink_to_fit!` (name borrowed from c++) to free the non-used space when the vector is not expected to grow anymore (which seems preferable to me than the "shrinkwrap" proposed above). If exact resize is needed, I vote for a new name instead of a keyword, e.g. `setsize!` which sounds more final than `resize!`. 
Exact `resize!` beyond a threshold sounds good though, but I would feel more comfortable with at least 50% to get the "optimal exponential growth" (i.e. the same growth factor as `push!` etc.). If I remember correctly, c++ libs do this with a growth factor equal to 2: `newsize = max(requestedsize, oldsize*2)`.

2017-05-30 22:27 UTC, rfourquet commented
Also https://github.com/JuliaLang/julia/pull/16305#issuecomment-237025415 may be relevant?

2017-05-30 22:43 UTC, alyst commented
I've reverted the API changes and implemented 125%/200% growth thresholds heuristic discussed above. I think it should be sensitive enough to do exact resize in most of relevant cases. Let's see what nanosoldier thinks of that.

Shrinkwrap might be useful for some applications, although it's much more easy to hit memory limits with imprecise growth than with imprecise shrinkage. And definitely it would break much more code patterns than exact growth.

2017-05-30 23:19 UTC, alyst commented
CI tests look ok, could somebody please ping nanosoldier as it doesn't listen to me?

2017-05-30 23:20 UTC, andreasnoack commented
@nanosoldier `runbenchmarks(ALL, vs=":master")`

2017-05-31 01:59 UTC, tkelman commented on src/array.c
> -        while ((n + inc) > newlen - a->offset)
isn't this while loop still needed?

2017-05-31 02:02 UTC, tkelman commented
it would make the most sense to me if the cutoff here was such that this PR didn't change the minimum amount of growth, but only the amount of space used when that minimum is exceeded

2017-05-31 02:17 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22038#issuecomment-305036389) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/5d785659358b42262e61c6cfd5750f427ab30a37/b84bf49_vs_0e8408f/report.md). cc @jrevels

2017-05-31 03:13 UTC, StefanKarpinski commented
Why? Why does that make more sense? The point of my proposal was that if you're in the bad O(n^2) then each growth is small – of fixed size, typically. Having *any* 1+ε threshold should suffice to avoid that. It doesn't make sense to me why 2x growth makes sense as the cutoff and no one has made a compelling argument for it. Feeble as my 25% is halfway between 0% and 50% argument is, at least it was an argument.

2017-05-31 03:21 UTC, tkelman commented
2x is our array growth cutoff elsewhere, and it doesn't make sense for resize to arbitrarily use a different growth ratio.

This also resizes to a discontinuous size - ask for 24% larger and the space doubles, but ask for 25% larger and it grows by less? That doesn't seem like a useful or predictable behavior.

2017-05-31 03:23 UTC, yuyichao commented
> 25% is halfway between 0% and 50%

So it's in between a "optimum" and the worst? That actually feels kind of random, mostly the 0% part. And

> This also resizes to a discontinuous size - ask for 24% larger and the space doubles, but ask for 25% larger and it grows by less? That doesn't seem like a useful or predictable behavior.

is actually also why I think the cutoff should not be lower than the grow factor.

2017-05-31 03:33 UTC, StefanKarpinski commented
Ok. The continuity argument is a good one – I buy that. Thank you for actually making a case. Let's go with that then, and the appropriate growth factor can be tweaked later.

2017-05-31 08:07 UTC, alyst commented
Now it should be "continuous". I wonder if it helps sparse matrix tests. Nanosoldier, please?

2017-05-31 08:18 UTC, nalimilan commented
@nanosoldier `runbenchmarks(ALL, vs=":master")`

2017-05-31 11:14 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22038#issuecomment-305119598) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b709f68ef1c267e46dd6265845d99729be3a80fc/e64b684_vs_bc606f6/report.md). cc @jrevels

2017-05-31 11:30 UTC, alyst commented
I see no relevant regressions in the last nanosoldier run (no real improvements either).
Do you think we have reached the convergence? :)
Should I mention the change of `resize!()` behaviour in `NEWS.md`?

2017-05-31 12:56 UTC, StefanKarpinski commented
A NEWS entry would be great. Then I think we're good to go here! Nice work :)

2017-05-31 13:32 UTC, yuyichao approved these changes

2017-05-31 14:37 UTC, alyst commented
Squashed and added NEWS entry.
Thanks everyone for the lively discussion! :)

2017-06-01 14:55 UTC, alyst commented
Anything else to do before merging?

2017-06-01 15:28 UTC, merged