RFC: Speedup generic LowerTriangular chol
JuliaLang/julia pull request #22221
Opened 2017-06-05 08:08 UTC by bshall

The generic `LowerTriangular` `_chol!` function is a bit slower than its `UpperTriangular` counterpart. After removing some unnecessary multiplications and branches they are about the same speed. Bellow are a couple of benchmarks to demonstrate. On master
```julia
srand(1234)
A = randn(100,100) |> t -> t't
@benchmark invoke(Base.LinAlg._chol!, Tuple{AbstractMatrix, Type{LowerTriangular}}, copy($A), LowerTriangular)
@benchmark invoke(Base.LinAlg._chol!, Tuple{AbstractMatrix, Type{UpperTriangular}}, copy($A), UpperTriangular)
```
Gives mean timings of 177.964 μs for the `LowerTriangular` version and 142.604 μs for the `UpperTriangular`. With this PR the same benchmark gives mean timings of 143.273 μs and 142.406 μs respectively.

2017-06-05 08:36 UTC, fredrikekre reviewed
Nice!

2017-06-05 08:36 UTC, fredrikekre commented on base/linalg/cholesky.jl
> +                for j = 1:k-1
perhaps spaces around `-` for consistency? `j = 1:k - 1`

2017-06-05 08:36 UTC, fredrikekre commented on base/linalg/cholesky.jl
> +                A[i,k] = A[i,k]*AkkInv'
maybe `A[i,k] *= AkkInv'`

2017-06-05 09:37 UTC, bshall commented
Thanks for the feedback. I've made the suggested changes.

2017-06-05 13:33 UTC, andreasnoack approved these changes

2017-06-05 13:48 UTC, KristofferC commented
For large matrices this is slower (likely due to worse access pattern).

For example, for a 1000 x 1000 matrix I get 180 ms with original code and 257 ms with this code.

2017-06-05 13:50 UTC, KristofferC requested changes
The performance impact on large matrices should be discussed.

2017-06-05 14:12 UTC, andreasnoack commented
@KristofferC Thanks for checking a larger matrix. I think it might be possible to improve the original version without reordering the loops.

2017-06-05 17:12 UTC, KristofferC commented on base/linalg/cholesky.jl
>                  for i = k + 1:n
`@simd` here makes the function 1.5x faster for large matrices. (Same could be done for UpperTriangular)?

2017-06-05 17:15 UTC, bshall commented
@KristofferC Thanks for pointing that out. Another option (the latest commit) is to keep the original loop order but move the scaling to the end. This requires an extra loop but the performance is still pretty good. I've included some more detailed benchmarks below.

| size | master/lower | master/upper | option 1 | option 2 |
| --- | --- | --- | --- | --- |
| 10 | 564.525 ns | 379.070 ns | 387.591 ns | 462.354 ns |
| 100 | 178.669 μs | 146.599 μs | 152.830 μs | 157.919 μs |
| 1000 | 151.652 ms | 144.080 ms | 582.975 ms | 124.658 ms |
| 2000 | 1.333 s | 1.316 s | 2.320 s | 1.112 s |

2017-06-05 17:17 UTC, KristofferC commented
Perhaps you can try again with my `@simd` suggestion?

2017-06-05 17:18 UTC, bshall commented
Sure. I only saw that after commenting.

2017-06-05 17:37 UTC, bshall commented
@KristofferC I've added your `@simd` to the benchmarks table and it does indeed make a significant difference for larger matrices.

2017-06-05 21:01 UTC, tkelman commented on base/linalg/cholesky.jl
> +                for j = 1:k-1
I wouldn't do that without also putting spaces around the `:`

2017-06-05 21:10 UTC, KristofferC commented on base/linalg/cholesky.jl
> +                for j = 1:k-1
+1, putting spaces around `k-1` when the precedence is `k-1` first doesn't make sense to me.

2017-06-05 21:21 UTC, bshall commented on base/linalg/cholesky.jl
> +                for j = 1:k-1
So it should stay `1:k-1` without the spaces?

2017-06-21 18:29 UTC, kshyatt commented
@KristofferC does anything else need to be changed on this?

2017-06-21 18:44 UTC, KristofferC commented
If the SIMD version was faster it should be added.

2017-06-22 09:01 UTC, bshall commented
I've updated the lower triangular version to use SIMD. Does anyone have any idea why SIMD won't kick in on the upper triangular version though?

2017-07-31 12:03 UTC, KristofferC approved these changes

2017-07-31 12:03 UTC, KristofferC commented
Is this good to go?

2017-07-31 22:10 UTC, tkelman commented on base/linalg/cholesky.jl
> +                @simd for i = k + 1:n
kind of misleading precedence vs spacing here - was like that way before, but now there are 3 instances of it instead of 1

2017-07-31 22:15 UTC, KristofferC commented on base/linalg/cholesky.jl
> +                @simd for i = k + 1:n
The whole file is like this.

2017-08-03 20:37 UTC, Sacha0 approved these changes
Thanks @bshall! :)

2017-08-03 20:40 UTC, merged