Added docstring to @fastmath macro.
JuliaLang/julia pull request #22359
Opened 2017-06-13 23:16 UTC by NHDaly

Adds docstring to @fastmath macro that explains a bit about what it does, and includes examples how to use it.

Pulled the detailed list of effects from the top of the file.

2017-06-13 23:29 UTC, yuyichao requested changes

2017-06-13 23:29 UTC, yuyichao commented on base/fastmath.jl
> +        of an argument rather than perform division.
Assuming you are copying from langref, the transformation allowed is much broader than this list.

2017-06-13 23:30 UTC, yuyichao commented on base/fastmath.jl
> +        of an argument rather than perform division.
Ah, I see that you pull the list from the comment, in that case, maybe you should use http://llvm.org/docs/LangRef.html#fast-math-flags

2017-06-13 23:38 UTC, NHDaly commented on base/fastmath.jl
> +        of an argument rather than perform division.
Oh, thanks! I've updated with a second commit. I can squash before merging.

Does this look better? I added a link to the llvm docs (and added one at the top of the file), and I listed the missing flags.

2017-06-13 23:40 UTC, ararslan commented on base/fastmath.jl
> +        of an argument rather than perform division.
No need to manually squash; we can squash the commits on merge.

2017-06-13 23:40 UTC, yuyichao approved these changes
I'd prefer shrinking this a little (i.e. `@fastmath` allows all sorts of transformation and then mention the few specific ones as special cases) but this looks correct and complete enough to me....

2017-06-13 23:41 UTC, yuyichao requested changes

2017-06-13 23:41 UTC, yuyichao commented on base/fastmath.jl
> +@fastmath expr
Actually, this should be a code block (indent it) and this should be added to the doc/stdlib/

2017-06-13 23:52 UTC, NHDaly commented on base/fastmath.jl
> +@fastmath expr
>Actually, this should be a code block (indent it) 

Just indent everything inside the triple quotes, you mean?

> and this should be added to the doc/stdlib/

Sorry, I don't understand what you mean. Like, there should be a page for this in the official docs? Like a new markdown file?

2017-06-13 23:59 UTC, yuyichao commented on base/fastmath.jl
> +@fastmath expr
> Just indent everything inside the triple quotes, you mean?

No, just the signature, see [the doc for other macros/functions](https://github.com/JuliaLang/julia/blob/d3db31200c09a99ad9f7cbc019dd0aa56c6944a7/base/essentials.jl#L200)

> added to the doc/stdlib/

See https://github.com/JuliaLang/julia/blob/d3db31200c09a99ad9f7cbc019dd0aa56c6944a7/CONTRIBUTING.md#improving-documentation There are examples there that you can follow. And you can decide which file to put it in...

2017-06-14 01:42 UTC, NHDaly commented on base/fastmath.jl
> +@fastmath expr
>No, just the signature, see the doc for other macros/functions

Gotcha.  Done. thanks!

See [CONTRIBUTING.md#improving-documentation](https://github.com/JuliaLang/julia/blob/d3db31200c09a99ad9f7cbc019dd0aa56c6944a7/CONTRIBUTING.md#improving-documentation)

Okay thanks. I made those changes, and I'm running `make docs` now. I'll post again when that's done.

2017-06-14 03:04 UTC, NHDaly commented on base/fastmath.jl
> +@fastmath expr
oh noes! Jk i can't build on this computer; i don't have all the dependencies installed. I'll push this tomorrow. Thanks! :)

2017-06-14 03:10 UTC, yuyichao commented on base/fastmath.jl
> +@fastmath expr
Note that `make docs` is only needed for testing. There shouldn't be anything that you need to push after that.

2017-06-14 03:10 UTC, yuyichao approved these changes

2017-06-14 03:14 UTC, ararslan commented
Thanks for the contribution! For future reference, it's a good idea to reference macros in commit messages as e.g. `at-fastmath rather than `@fastmath`. In the latter case, GitHub will send a notification to the user called fastmath. Whoever squash-merges this can edit the commit message here appropriately.

2017-06-14 14:26 UTC, NHDaly commented
> I'd prefer shrinking this a little (i.e. @fastmath allows all sorts of transformation and then mention the few specific ones as special cases) but this looks correct and complete enough to me....

@yuyichao I agree. What about just dropping everything after the definition, and dropping `fast` since it's so vague, so it looks like this:

```
"""
    @fastmath expr

Executes a transformed version of the expression, which calls
functions that may violate strict IEEE semantics. This allows
the fastest possible operation, but results are undefined.

This sets the [LLVM Fast-Math
flags](http://llvm.org/docs/LangRef.html#fast-math-flags), including
the following transformations:
- nnan: No NaNs
- ninf: No Infs
- nsz:  No Signed Zeros
- arcp: Allow Reciprocal
- contract: Allow floating-point contraction.

# Examples
```jldoctest
julia> @fastmath 1+2
3

julia> @fastmath(sin(3))
0.1411200080598672
```
"""
```

2017-06-14 14:28 UTC, NHDaly commented
> For future reference, it's a good idea to reference macros in commit messages as e.g. `at-fastmath` rather than `@fastmath`. In the latter case, GitHub will send a notification to the user called fastmath. Whoever squash-merges this can edit the commit message here appropriately.

:D haha that makes a lot of sense. Thanks!! I'll let you do the change so my rebase doesn't make the PR harder to read.

Cheers!
~Nathan

2017-06-14 14:35 UTC, yuyichao commented
> dropping fast since it's so vague,

I'll not drop the `fast` description though it'll be better to drop those flag names altogether, maybe only with a mention that this corresponds to the llvm `fast` flag. There are many more transformations allowed for `fast` that's not included in those categories.

2017-06-14 22:49 UTC, NHDaly commented on base/fastmath.jl
> +@fastmath expr
Gotcha. I have verified the docs build and look correct.

2017-06-14 22:50 UTC, NHDaly commented
> I'll not drop the fast description though it'll be better to drop those flag names altogether, maybe only with a mention that this corresponds to the llvm fast flag. There are many more transformations allowed for fast that's not included in those categories.

Okay, I've pushed a new version that removes the detailed bullets and instead links to the following page in the docs:
https://docs.julialang.org/en/stable/manual/performance-tips#performance-annotations

Is there a better way to link to docs, such that it will keep you in the correct, corresponding version? (ie don't always link to `stable`?)

2017-06-14 23:04 UTC, fredrikekre commented
> Is there a better way to link to docs

You can use `@ref` if you add an `@id` to the section header. Something like this:
```patch
diff --git a/base/fastmath.jl b/base/fastmath.jl
index f6be79a..6f925e4 100644
--- a/base/fastmath.jl
+++ b/base/fastmath.jl
@@ -133,7 +133,10 @@ functions that may violate strict IEEE semantics. This allows
 the fastest possible operation, but results are undefined.
 
 This sets the [LLVM Fast-Math
-flags](http://llvm.org/docs/LangRef.html#fast-math-flags), and corresponds to the `-ffast-math` option in clang. See [the notes on performance annotations](https://docs.julialang.org/en/stable/manual/performance-tips#performance-annotations) for more details.
+flags](http://llvm.org/docs/LangRef.html#fast-math-flags), and corresponds to the
+`-ffast-math` option in clang.
+See [the notes on performance annotations](@ref man-performance-annotations) for
+more details.
 
 # Examples
 ```jldoctest
diff --git a/doc/src/manual/performance-tips.md b/doc/src/manual/performance-tips.md
index d171cbf..02f609b 100644
--- a/doc/src/manual/performance-tips.md
+++ b/doc/src/manual/performance-tips.md
@@ -1082,7 +1082,7 @@ These are some minor points that might help in tight inner loops.
   * Use [`div(x,y)`](@ref) for truncating division of integers instead of [`trunc(x/y)`](@ref), [`fld(x,y)`](@ref)
     instead of [`floor(x/y)`](@ref), and [`cld(x,y)`](@ref) instead of [`ceil(x/y)`](@ref).
 
-## Performance Annotations
+## [Performance Annotations](@id man-performance-annotations)
 
 Sometimes you can enable better optimization by promising certain program properties.

```

2017-06-15 01:04 UTC, StefanKarpinski commented on base/fastmath.jl
> +flags](http://llvm.org/docs/LangRef.html#fast-math-flags), and corresponds to the `-ffast-math` option in clang. See [the notes on performance annotations](https://docs.julialang.org/en/stable/manual
wrap 92 please

2017-06-15 01:38 UTC, NHDaly commented on base/fastmath.jl
> +flags](http://llvm.org/docs/LangRef.html#fast-math-flags), and corresponds to the `-ffast-math` option in clang. See [the notes on performance annotations](https://docs.julialang.org/en/stable/manual
Oops. Done, thanks.

2017-06-15 01:58 UTC, NHDaly commented
PTAL: I think this is all set, and the docs build correctly. Thanks again for your reviewing!

> You can use @ref if you add an @id to the section header. Something like this:

Thanks, done.

2017-06-15 02:02 UTC, yuyichao commented
Be careful to code quote all `@`s that are not intended to mention people, even in text quote.....

I did not know that `ref` and `id` are real github users.... (with `id` actually seems to be active)

2017-06-15 02:50 UTC, NHDaly commented
Haha wow that's hard. I'll be sure to be careful. I didn't do it again, did I?

2017-06-15 03:37 UTC, yuyichao commented
> I didn't do it again, did I?

I edited the comment to fix it.

2017-06-15 04:29 UTC, ararslan approved these changes
LGTM. Thanks for the contribution!

2017-06-15 16:48 UTC, Sacha0 commented on base/fastmath.jl
> +Executes a transformed version of the expression, which calls functions that
Perhaps `Executes` -> `Execute` in keeping with the documentation guidelines? :)

2017-06-15 16:50 UTC, Sacha0 approved these changes
lgtm! Thanks @NHDaly! :)

2017-06-15 21:19 UTC, NHDaly commented on base/fastmath.jl
> +Executes a transformed version of the expression, which calls functions that
Done, thanks! Sorry about that.

2017-06-15 21:26 UTC, ararslan approved these changes

2017-06-16 18:24 UTC, merged

2017-06-16 18:25 UTC, Sacha0 commented
Thanks for the great contribution @NHDaly ! :)

2017-06-16 18:26 UTC, fastmath commented
Thank you for documenting me.