implement an isvalid function for sparse matrices and use it in show
JuliaLang/julia pull request #22529
Opened 2017-06-25 05:11 UTC by KristofferC

Closes https://github.com/JuliaLang/julia/issues/14489

cc @nalimilan, @Sacha0

2017-06-25 07:17 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +
no blank line at start of a block

2017-06-25 07:18 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +        if length(S.colptr) > 1 && !all(i -> S.colptr[i+1] >= S.colptr[i], 1:length(S.colptr)-1)
would issorted be any faster?

2017-06-25 07:20 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +_print_invalid(io, S) = print(io, typeof(S), " with invalid internal representation")
still worth showing the size

2017-06-25 07:21 UTC, tkelman commented
This should verify that the row indices are strictly sorted within each column, possibly under a different kwarg

2017-06-25 08:49 UTC, nalimilan commented
Thanks! However to be completely sure we can close #14489 after merging this, we would need to be check that no segfault can happen in other functions for invalid matrices (or at least, that the impact of fixing these crashes on performance would be acceptable).

2017-06-25 15:13 UTC, KristofferC commented
* Added a verification for rowindices in a column
* Added size when printing invalid matrices
* Removed closing statement of issue from first post.

2017-06-25 15:29 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +function Base.isvalid(S::SparseMatrixCSC; full = false)
why defaulting to only partial checks?

2017-06-25 15:30 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +            l_nzrange = length(nzrang)
unused variable

2017-06-25 15:30 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +                S.rowval[r+1] <= ri && (println("returning"); return false)
debugging print left in?

2017-06-25 15:31 UTC, KristofferC commented on base/sparse/sparsematrix.jl
> +function Base.isvalid(S::SparseMatrixCSC; full = false)
Yeah, perhaps full should be default. I'll change it.

2017-06-25 15:32 UTC, tkelman commented on test/sparse/sparse.jl
> +        @show x
debugging print left in

2017-06-25 15:33 UTC, KristofferC commented on base/sparse/sparsematrix.jl
> +                S.rowval[r+1] <= ri && (println("returning"); return false)
ops

2017-06-25 15:58 UTC, KristofferC commented
* Changed full to true by default
* Some other minor cleanups

2017-06-26 21:58 UTC, Sacha0 commented on base/sparse/sparsematrix.jl
> +O(nnz) checks are performed.
Should `O(1)` and `O(nnz)` be marked up somehow?

2017-06-26 22:04 UTC, Sacha0 commented on base/sparse/sparsematrix.jl
> +    length(S.colptr) != S.n + 1 && return false
This check seems too strict. For explanation, please see https://github.com/JuliaLang/julia/pull/20464#issuecomment-277540516 :).

2017-06-26 22:07 UTC, Sacha0 requested changes
Thanks @KristofferC! :)

Re. length checks, I advocate checking the set of constraints described in/around https://github.com/JuliaLang/julia/pull/20464#issuecomment-277540516 and no more. Thoughts? :)

2017-06-27 03:35 UTC, KristofferC commented
Thanks for pointing me to #20464. Will update accordingly.

2017-06-27 06:23 UTC, KristofferC commented
Updated. I mimicked a bit the `checkbounds` style where the code can either throw an exception or return true / false if a `Type{Bool}` is given as first argument.

2017-06-27 06:24 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +    return _checkvalid(S; full = full) == SparseArrayInvalid.VALID
Invalid.VALID is a messy name here

2017-06-27 06:24 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +```
no code here...

2017-06-27 06:25 UTC, KristofferC commented on base/sparse/sparsematrix.jl
> +```
Please elaborate.

2017-06-27 06:27 UTC, KristofferC commented on base/sparse/sparsematrix.jl
> +    return _checkvalid(S; full = full) == SparseArrayInvalid.VALID
Okay. Please suggest better name / names. `SparseArrayValidity`?

2017-06-27 06:28 UTC, KristofferC commented on base/sparse/sparsematrix.jl
> +```
Oh, I see now.

2017-06-27 06:30 UTC, KristofferC commented
* Updated name of module encapsulating enum as well as removed unwanted code block from a docstring.

2017-06-27 17:29 UTC, Sacha0 commented on base/sparse/sparsematrix.jl
> +    checkvalid(Bool, S::SparseMatrixCSC; full = true) -> Bool
Perhaps `Bool` should be `::Type{Bool}`? I was not certain whether the first argument should be a boolean value or the `Bool` type prior to reading the examples. Or do you prefer this signature with the examples to clarify?

2017-06-27 17:32 UTC, Sacha0 commented on base/sparse/sparsematrix.jl
> +    end
Beautiful error messages! :) Perhaps the code snippets should be quoted?

2017-06-27 17:37 UTC, KristofferC commented on base/sparse/sparsematrix.jl
> +    checkvalid(Bool, S::SparseMatrixCSC; full = true) -> Bool
Hmm, looking at the docs for `checkbounds`:

>  `checkbounds(Bool, A, I...)`

>  Return true if the specified indices I are in bounds for the given array A.
>  Subtypes of AbstractArray should specialize this method if they need to
>  provide custom bounds checking behaviors; however, in many cases one can
>  rely on A's indices and checkindex.

so this is consistent with that. In my opinion `::Type{Bool}` is more clear though. Thoughts?

2017-06-27 17:37 UTC, Sacha0 approved these changes
Beautiful! :) :100:

2017-06-27 17:37 UTC, Sacha0 commented on base/sparse/sparsematrix.jl
> +    checkvalid(Bool, S::SparseMatrixCSC; full = true) -> Bool
Whichever you deem best :).

2017-06-27 17:46 UTC, KristofferC commented on base/sparse/sparsematrix.jl
> +    end
Good point. Will update accordingly.

2017-06-27 18:13 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +    checkvalid(Bool, S::SparseMatrixCSC; full = true) -> Bool
this isn't right as a signature, it would locally overwrite Bool as a variable name

2017-06-27 18:29 UTC, KristofferC commented on base/sparse/sparsematrix.jl
> +    end
Regarding quoting error messages; do we usually quote things in error message strings? They will not be rendered as markdown and I'm not sure if we use "`" as a convention for code in strings.

2017-06-27 18:30 UTC, KristofferC commented on base/sparse/sparsematrix.jl
> +    checkvalid(Bool, S::SparseMatrixCSC; full = true) -> Bool
Pushed a commit that changes this for the pertinent check-methods.

2017-06-28 05:15 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +    end
we frequently do, yes

2017-06-28 05:40 UTC, KristofferC commented on base/sparse/sparsematrix.jl
> +    end
I was checking e.g. https://github.com/JuliaLang/julia/pull/20464/files#diff-fceaad3480ef8dc3a224be725fa10678R866. Anyway, updated with code quotes.

2017-06-28 05:48 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +        err_str = "length of `S.colptr` must be at least `size(S,2)` + 1 = $(S.n + 1) but was $(length(S.colptr))"
would include the + 1 or - 1 in the highlighting

2017-06-28 05:50 UTC, KristofferC commented on base/sparse/sparsematrix.jl
> +        err_str = "length of `S.colptr` must be at least `size(S,2)` + 1 = $(S.n + 1) but was $(length(S.colptr))"
As you wish.

2017-06-28 17:56 UTC, Sacha0 commented on base/sparse/sparsematrix.jl
> +
(Extra empty line under the seemingly just-established convention, but could be fixed in the dedicated PR instead.)

2017-06-28 17:58 UTC, Sacha0 approved these changes
lgtm for the touchups! :)

2017-06-28 18:04 UTC, tkelman commented on base/sparse/sparsematrix.jl
> +        err_str = "each element in `S.rowval` must be > 0 and ⩽ `size(S,1)`"
should use ≤, not `\leqslant`

2017-08-05 14:35 UTC, KristofferC commented
Comments addressed

2017-08-05 14:43 UTC, tkelman commented on test/sparse/sparse.jl
> +        @test_throws ArgumentError SparseArrays.checkvalid(mat; full=full)
would it be worth adding
```
        if full
            @test SparseArrays._checkvalid(mat; full=false) == SparseArrays.SparseArrayValidity.VALID
            @test SparseArrays.checkvalid(Bool, mat; full=false) == true
            @test SparseArrays.checkvalid(mat; full=false) === nothing
        end
```
for coverage of that case?

2018-12-17 03:38 UTC, ViralBShah commented
It would be nice to revive this one.

2019-06-26 22:05 UTC, ViralBShah commented
@KlausC implemented much of this in b32c1b837e14e2f3f9ee5615af9da5c84a73a4e8. I think all we need is a `checkvalid` wrapper.

2020-03-04 03:44 UTC, ViralBShah commented
@KristofferC Is it ok to close?

2021-04-07 08:18 UTC, KristofferC commented
I think this is still useful (ref https://discourse.julialang.org/t/weird-duplicated-entries-with-different-values-in-sparsematrixcsc/).

2021-04-07 20:45 UTC, ViralBShah commented
Definitely useful if we can rebase and merge.

2022-01-14 22:48 UTC, DilumAluthge commented
It looks like this PR touches three files. One of those files (`base/abstractarray.jl`) is in `Base`. The remaining two files are part of the SparseArrays stdlib.

We have moved the SparseArrays stdlib to an external repository. Therefore, for the portion of this PR that modifies the SparseArrays stdlib, can you please:

1. Remove the SparseArrays changes from this PR.
2. Open a new PR against https://github.com/JuliaLang/SparseArrays.jl with the SparseArrays changes.

Thank you!

2022-01-17 19:46 UTC, ViralBShah commented
SparseArrays.jl is now in its own separate repo. Please open the PR there if still relevant.

2022-01-17 19:46 UTC, closed without merging