Fix #18479, path completion of paths with ampersand characters.
JuliaLang/julia pull request #22531
Opened 2017-06-25 16:45 UTC by dhoegh

This supersedes #18567 without the controversial part.

2017-07-25 10:16 UTC, dhoegh commented
Bump

2017-07-25 15:01 UTC, tkelman commented on test/replcompletions.jl
> +                    @test c[1] == test_dir*(is_windows() ? "\\\\" : "/")
`Sys.iswindows()`

2017-07-26 12:06 UTC, tkelman commented on test/replcompletions.jl
> +                    @test c[1] == test_dir*(is_windows() ? "\\\\" : "/")
no underscore

2017-07-27 06:18 UTC, StefanKarpinski requested changes

2017-07-27 06:18 UTC, StefanKarpinski commented on test/replcompletions.jl
> +                    @test c[1] == test_dir*(Sys.is_windows() ? "\\\\" : "/")
The new version is also without the underscore.

2017-08-03 17:44 UTC, dhoegh commented
I have fixed the `Sys.iswindows` rename.

2017-08-03 23:03 UTC, StefanKarpinski approved these changes

2017-08-03 23:05 UTC, StefanKarpinski commented
Failures were the now-ubiquitous timeout/arnoldi test combo.

2017-08-03 23:05 UTC, merged