Add more `@test` tests
JuliaLang/julia pull request #22609
Opened 2017-06-29 14:57 UTC by omus

Minor follow up to #22558.

I also discovered a small issue when invalid syntax is used when calling `isapprox` or `isequal` where a `MethodError` will be thrown instead of a syntax error:
```julia
julia> isequal(; a=1:2...)
ERROR: syntax: splicing with "..." cannot be used for a keyword argument value

julia> @test isequal(; a=1:2...)
Error During Test
  Test threw an exception of type MethodError
  Expression: isequal(; a=1:2...)
  MethodError: no method matching Pair(::Symbol, ::Int64, ::Int64)
```
Due to the way `@test` revises the expression so that each argument is evaluated I'm not sure much can be done here without evaluating the original expression and the arguments separately (effectively evaluating the arguments twice). I can open an issue if need be.

2017-06-29 16:15 UTC, DrKrar requested changes

2017-06-29 16:15 UTC, DrKrar commented on test/test.jl
> +@test isapprox(1, 3, atol=0; atol=2) atol=1
this and the previous test should be removed as they produce error
syntax: keyword argument "atol" repeated in call to "Base.Test.Expr"

2017-06-29 16:18 UTC, omus commented on test/test.jl
> +@test isapprox(1, 3, atol=0; atol=2) atol=1
Can you give an example where this is giving a syntax error?

2017-06-29 17:59 UTC, Sacha0 commented on test/test.jl
> +@test isapprox(1, 3, atol=0; atol=2) atol=1
I can reproduce `@DrKrar`'s concern at the REPL
```julia
julia> versioninfo()
Julia Version 0.7.0-DEV.703
Commit 4226320 (2017-06-24 18:23 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
Environment:
  JULIA_EDITOR = mate

julia> using Base.Test

julia> @test isapprox(1, 2, atol=0) atol=1
ERROR: syntax: keyword argument "atol" repeated in call to "Base.Test.Expr"

julia> @test isapprox(1, 3, atol=0; atol=2) atol=1
ERROR: syntax: keyword argument "atol" repeated in call to "Base.Test.Expr"
```
Rebuilding master now, will update afterwards.

2017-06-29 18:06 UTC, Sacha0 commented on test/test.jl
> +@test isapprox(1, 3, atol=0; atol=2) atol=1
Works on up-to-date master, so chances are `@DrKrar`'s concern applies to a slightly out-of-date build. Best!
```julia
julia> versioninfo()
Julia Version 0.7.0-DEV.796
Commit 2c85595 (2017-06-29 16:32 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
Environment:
  JULIA_EDITOR = mate

julia> using Base.Test

julia> @test isapprox(1, 2, atol=0) atol=1
Test Passed

julia> @test isapprox(1, 3, atol=0; atol=2) atol=1
Test Passed
```

2017-06-29 18:07 UTC, Sacha0 approved these changes
superficially lgtm! :)

2017-06-29 18:10 UTC, omus commented on test/test.jl
> +@test isapprox(1, 3, atol=0; atol=2) atol=1
Gotcha. You definitely need the hot out of the oven `0.7.0-DEV.791` for these tests to work.

2017-06-30 15:03 UTC, merged

2017-06-30 16:48 UTC, omus commented
Thanks Tony