pager: split the argument for handling options
JuliaLang/julia pull request #22852
Opened 2017-07-18 06:41 UTC by rfourquet

For some reason (that I don't know), my pager is defined to be "less -R", which is not recognized as the name of a program, unless it's split. I don't know whether it's common for a program name (without options) in "ENV" to have spaces, but this fix would break that. I also don't know if this fix shoud be applied on windows?

2017-07-18 08:09 UTC, tkelman commented
we use shell_split for the editor, though I can't figure out from a quick look at the code and related docstring how it would differ

2017-07-18 08:20 UTC, rfourquet commented
OK. It differs when an argument is explicitly quoter, e.g. : `command = """progname -f "a b\""""`

2017-07-18 08:23 UTC, rfourquet commented
Should I update the code similarly in the Windows case? I don't know enough about  Windows and have no access to a machine to test myself.

2017-07-18 08:24 UTC, tkelman commented
Not sure. It may have the same problem regarding arguments, but I suspect paths with spaces would be more common there.

2017-07-18 08:28 UTC, rfourquet commented
> but I suspect paths with spaces would be more common there

Indeed. On the other hand, with `shell_split`, it would still possible to specify a path with space by using quotes. I will update the Windows case for now.

2017-07-18 15:28 UTC, BobPortmann commented
The "correct" way to set options for `less` is to use (assuming you are using `bash` )
```
export PAGER='less'
export LESS="-R"
```
If you want more than one option they are separated by spaces.

However, perhaps `@less` should deal with spaces better, since not everyone uses this.

2017-07-18 16:20 UTC, rfourquet commented
> The "correct" way to set options for less

But I'm unable to find where it's defined in my case (but I could override that in my config files). And there may be other pagers without such a correct way?

2017-07-23 08:37 UTC, rfourquet commented
I will merge within one or two days if no objection.

2017-07-24 19:50 UTC, StefanKarpinski requested changes

2017-07-24 19:50 UTC, StefanKarpinski commented on base/interactiveutil.jl
>          g = pager == "more" ? "" : "g"
Don't you want to look at `pager[1]` here? Since `pager` will be an array here this test will always fail (silently).

2017-07-25 10:14 UTC, rfourquet commented on base/interactiveutil.jl
>          g = pager == "more" ? "" : "g"
Oups sorry, I should not change something that I cannot test. Fixed now.

2017-07-25 20:45 UTC, merged