"octal" plain error for strings(?)
JuliaLang/julia pull request #22927
Opened 2017-07-23 18:11 UTC by PallHaraldsson

2017-07-23 18:16 UTC, yuyichao requested changes
The old text is correct.

Octal escape sequence does not have a prefix other than the "escape" (i.e. `\`).

```julia
julia> "\123"
"S"
```

2017-07-23 19:56 UTC, ararslan commented on doc/src/manual/strings.md
> +  * `\x` and hexadecimal escape sequence produce the *byte* corresponding to the escape value.
"sequences" was correct here, "sequence" is not

2017-07-24 19:58 UTC, closed without merging

2017-07-24 20:12 UTC, yuyichao commented
Note that my request for change instead of closing is because the octal escape sequence isn't actually being specified here.

2017-07-24 20:34 UTC, StefanKarpinski commented
As you said, the old text is correct, so what's to do here?

2017-07-24 20:51 UTC, yuyichao commented
Mentions that octal escape sequence means `\nnn`?