RFC / WIP: no longer warn in code_warntype for variables not used in the body
JuliaLang/julia pull request #23280
Opened 2017-08-16 09:39 UTC by KristofferC

The fact that `@code_warntype` shows unused variables in red is something that keeps tripping up users (both new and experienced), see e.g. https://discourse.julialang.org/t/question-about-type-stability-of-arrays-in-julia-0-6/5389.

This PR traverses the codeinfo to check if the variable is actually used somewhere in the body. If not, we no longer print the variable in red even if it is inferred as a non concrete type. 

Before:

![image](https://user-images.githubusercontent.com/1282691/29356286-0ebfa9a8-8274-11e7-8e12-f910d14f8aa3.png)

After:

![image](https://user-images.githubusercontent.com/1282691/29356292-13aeb90e-8274-11e7-9821-047e7e6356f4.png)

Maybe the `(Unused in body)` is too verbose?

This might not pass ci right now, and will add test / docs later if people think this is a good idea. Also, I'm new to the codeinfo data structure so someone should probably look over that code. CI skipped to not waste resources so don't merge.

2017-08-16 12:12 UTC, yuyichao requested changes

2017-08-16 12:12 UTC, yuyichao commented on base/interactiveutil.jl
> +    is_variable_used(arg::SlotNumber, slotnames, v) = slotnames[arg.id] == v
Compare the id directly.

2017-08-16 12:21 UTC, yuyichao requested changes

2017-08-16 12:21 UTC, yuyichao commented on base/interactiveutil.jl
> +    function is_variable_used(bodies::Vector, slotnames, v)
This is also wrong. This can incorrectly catch constant arrays spliced into the code.

2017-08-16 12:26 UTC, yuyichao commented on base/interactiveutil.jl
> +    is_variable_used(arg::SlotNumber, slotnames, v) = slotnames[arg.id] == v
Also should be `::Slot`instead.

2017-08-16 12:37 UTC, oscardssmith commented
Would it make sense to make things yellow if unused in body? I feel like that would be a useful piece of info (although code warntype might not be a good place to show it)

2017-08-16 12:42 UTC, yuyichao commented
What's this info (unused vars) useful for? It's just a signature of the optimization.

It might also be better to just do a single scan of slots uses instead of multiple ones and there's no need to use dispatch for that.

2017-08-16 15:41 UTC, KristofferC commented
I changed to only doing a single scan. I am not sure how I would avoid using dispatch and if the Vector dispatch function is still problematic.

2017-08-16 15:50 UTC, yuyichao commented
```
    function scan_exprs(exprs, used)
        for expr in exprs
            if isa(ex, Slot)
                used[ex.id] = true
            elseif isa(ex, Expr)
                scan_expr(ex, used)
            end
        end
    end
    function slot_usaged(ci, slotnames)
        used = falses(length(slotnames))
        scan_exprs(ex, used)
        return used
    end
```

2017-08-16 15:56 UTC, yuyichao requested changes

2017-08-16 15:56 UTC, yuyichao commented on base/interactiveutil.jl
> +function code_warntype(io::IO, f, t::ANY) #@nospecialize(t))
Also, I imagine this is for testing only but this should be changed back....

2017-08-16 16:03 UTC, yuyichao commented
Note that the code above rely on the AST to be valid. You can add `ex.id <= length(used) && (used[ex.id] = true)` to guard it if you want.

2017-08-16 17:28 UTC, KristofferC commented on base/interactiveutil.jl
> +function code_warntype(io::IO, f, t::ANY) #@nospecialize(t))
Yeah

2017-08-17 12:26 UTC, KristofferC commented
Thanks! Updated with that code. Also added a test.

Now for the details. I currently avoid printing the inferred type and just print `(unused)` when the variable is not used. Do people like that or are there other suggestions for other ways of printing that gives the same information (not used + inferred type is not important for performance)?

2017-08-19 11:34 UTC, KristofferC commented
With some inspiration from GDB I went with:

![image](https://user-images.githubusercontent.com/1282691/29486316-282df46e-84e3-11e7-9c27-b7e306af782c.png)

Any opinions on that?

2017-08-19 12:55 UTC, yuyichao approved these changes

2017-08-19 13:02 UTC, KristofferC commented
Not sure if eligible for backport but tentatively putting the label there.

2017-08-20 23:41 UTC, KristofferC commented
Will merge tomorrow unless [the usual stuff].

2017-08-21 19:30 UTC, merged

2017-08-22 14:26 UTC, fredrikekre commented
Could we do something like this for the red `Union{}` on `throw` lines as well?
![screenshot from 2017-08-22 16-25-47](https://user-images.githubusercontent.com/11698744/29570385-a117dda2-8756-11e7-9ddf-fb9cdf346a2e.png)

2017-08-22 14:28 UTC, KristofferC commented
Yeah, should be fairly easy.