add RowVectors to to list of types included in sparse concatinations
JuliaLang/julia pull request #23297
Opened 2017-08-17 15:07 UTC by KristofferC

Should fix #23296 

```
@time [hxx   hxs   hxt
              hxs'  hss   hst
              hxt'  hst'  htt]
```

Before: `5.766938 seconds (321 allocations: 67.169 MiB, 0.42% gc time)`

After: `0.204763 seconds (5.26 M allocations: 114.399 MiB, 7.11% gc time)`

2017-08-17 18:34 UTC, tkelman commented
Should this only apply to RowVectors that wrap SparseVectors?

2017-08-17 18:42 UTC, KristofferC commented
I don't think so, no.

2017-08-17 18:53 UTC, tkelman commented
This makes `[[1,2,3]'; [1,2,3]']` now return a SparseMatrixCSC which seems not quite right. The return type of that is surprisingly not tested, apparently.

2017-08-17 18:59 UTC, KristofferC commented
Aha, so perhaps `RowVector{<:SparseVector}` should be added to `_SparseArrays`?

2017-08-17 19:15 UTC, pabloferz commented
> Aha, so perhaps `RowVector{<:SparseVector}` should be added to `_SparseArrays`?

I believe it should be `RowVector{<:Any,<:SparseVector}`

2017-08-17 19:42 UTC, Sacha0 requested changes
The following should fix the immediate as well as some associated issues: Remove the `RowVector` from `_SpecialArrays`, place a `RowVector{<:Any,<:SparseVector}` in `_SparseArrays`, and a `RowVector{<:Any,<:Vector}` alongside `Vector` in each of `_SparseConcatGroup` and `_DenseConcatGroup`. Best!

2017-08-17 19:43 UTC, Sacha0 requested changes
You might also need a `RowVector{T,Vector{T}}` in `_TypedDenseConcatGroup{T}`. Best!

2017-08-17 20:45 UTC, KristofferC commented
Updated and added test for the thing Tony pointed out.

2017-08-18 19:17 UTC, Sacha0 commented on base/sparse/sparsevector.jl
>  const _DenseConcatGroup = Union{Vector, Matrix, _Annotated_DenseArrays}
Still need a `RowVector{<:Any,<:Vector}` in `_DenseConcatGroup` I think?

2017-08-19 00:21 UTC, Sacha0 approved these changes
Thanks @KristofferC! :)

(The one potentially worthwhile addition I can think of is a test for the heterogeneously typed case that IIRC necessitates the `RowVector{<:Any,<:Vector}` in `_DenseConcatGroup`.)

2017-08-19 10:51 UTC, KristofferC commented
Added tests for heterogenous row vectors.

2017-08-21 06:37 UTC, KristofferC commented
Will merge tomorrow unless [the usual reasons]

2017-08-22 07:12 UTC, merged