Misc remove `&x` ccall  syntax
JuliaLang/julia pull request #23301
Opened 2017-08-17 16:28 UTC by musm

2017-08-17 20:32 UTC, yuyichao commented on base/irrationals.jl
> +            return c[]
Why?

2017-08-17 20:34 UTC, musm commented on base/irrationals.jl
> +            return c[]
I am following the suggestion here https://github.com/JuliaMath/SpecialFunctions.jl/pull/44#discussion_r133771693

2017-08-17 20:37 UTC, yuyichao commented on base/irrationals.jl
> +            return c[]
The Ref is not doing anything and you **ARE** mutating the `BigFloat` so adding a `Ref` seems like a bad idea.

2017-08-17 20:44 UTC, musm commented on base/irrationals.jl
> +            return c[]
OK thank you very much for clarifying this! Droped the last commit. Other than that is this LGTY?

2017-08-17 20:50 UTC, yuyichao requested changes

2017-08-17 20:50 UTC, yuyichao commented on base/printf.jl
> +                (Ptr{UInt8}, Culong, Ptr{UInt8}, Ref{BigFloat}),
Keep the `...` It can affect calling convention (and does on x86_64).

2017-08-17 20:54 UTC, yuyichao approved these changes

2017-08-17 20:55 UTC, musm commented
Thanks for the review @yuyichao

2017-08-18 04:59 UTC, musm commented
part of https://github.com/JuliaLang/julia/issues/6080 (ref)

2017-08-21 19:01 UTC, musm commented
good to merge?

2017-08-24 17:51 UTC, rfourquet approved these changes

2017-08-25 07:50 UTC, merged