Float16/32 inconsistent compact NaN printing #23248
JuliaLang/julia pull request #23334
Opened 2017-08-18 20:55 UTC by Vaibhavdixit02

2017-08-18 22:00 UTC, fredrikekre commented on test/numbers.jl
> +    @test_broken sprint(io->show(IOContext(io, :compact => true), NaN32)) == "NaN"
This one should be `@test`, it is what this PR fixes :)

2017-08-19 15:11 UTC, Vaibhavdixit02 commented
@StefanKarpinski there seems to be some problem with the change.

2017-08-19 17:53 UTC, StefanKarpinski requested changes

2017-08-19 17:53 UTC, StefanKarpinski commented on base/grisu/grisu.jl
> +        _show(io, x, PRECISION, 6, isa(x,Float32), true)
Sorry, I got this condition backwards, which is why the test is failing. Should be `x isa Float64`.

2017-08-19 17:56 UTC, Vaibhavdixit02 commented on base/grisu/grisu.jl
> +        _show(io, x, PRECISION, 6, isa(x,Float32), true)
Yeah I was thinking the same thing!

2017-08-21 16:44 UTC, merged

2017-08-21 16:44 UTC, StefanKarpinski commented
Thanks for the fix, @Vaibhavdixit02!