implement islower, isupper and istitle for String
JuliaLang/julia pull request #23394
Opened 2017-08-22 17:15 UTC by rfourquet

`islower` and `isupper` were deprecated to a simplistic
behavior which left to be desired; the new functions
check that the predicate is true *only* for letters,
and that there is at least one letter. This is the behavior
of some other languages (e.g. Python) and is inspired by
http://www.unicode.org/L2/L1999/99190.htm.
Also, `islower(lowercase(s))` is now true for many more
strings (false only if s doesn't contain any letter).

Note: I'm still confused by the difference between `isupper` and `istitle` for characters - this may need to be adjusted.

2017-08-22 17:39 UTC, JeffBezanson requested changes

2017-08-22 17:39 UTC, JeffBezanson commented on base/strings/utf8proc.jl
> +islower(ccode::Int32) = ccode == UTF8PROC_CATEGORY_LL
This should be a separate function, not a method of `islower`.

2017-08-22 18:45 UTC, StefanKarpinski commented
I don't think Base should be in the business of implementing subtle Unicode string tests.

2017-08-22 18:47 UTC, stevengj commented on base/strings/utf8proc.jl
> +julia> islower(lowercase(randstring())) # very unlikely to be false
don't use a random string here

2017-08-22 18:48 UTC, stevengj commented
What is the use-case for this function?

2017-08-22 19:36 UTC, rfourquet commented
> What is the use-case for this function?

I have to admit that I only used them at the REPL while testing #23379 and was surpised to see them deprecated; I wanted to use them in the tests of this PR. So I don't badly need those functions.

2017-08-23 02:34 UTC, stevengj commented
Without a real use case, it seems difficult to decide on the best semantics, much less decide whether it is worth including.

2017-08-23 16:38 UTC, bean6178 commented on NEWS.md
> +    is at least on letter in `s` (the old behavior was `all(islower, s)`); also, a new
Should be: at least one letter
Not: at least on letter

2021-04-03 04:41 UTC, oscardssmith commented
we have `isuppercase`, `islowercase` now.

2021-04-03 04:41 UTC, closed without merging