Removed default descriptions from multidimensional.jl
JuliaLang/julia pull request #23542
Opened 2017-09-01 09:36 UTC by shorty66

Removed default descriptions which were redundant with the method signature.

E.g.
```julia
cumsum!(B, A, dim::Integer=1)

  Cumulative sum of A along a dimension, storing the result in B. The dimension defaults to 1. See also cumsum.
```

2017-09-01 10:39 UTC, fredrikekre commented on base/multidimensional.jl
> +Cumulative operation `op` on `A` along a dimension, storing the result in `B`. See also [`accumulate`](@ref).
Perhaps add a linebreak before the second sentence? We try to stay within 92 characters per line, see https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#code-formatting-guidelines

2017-09-01 17:05 UTC, StefanKarpinski commented
See also https://github.com/JuliaLang/julia/issues/19451, https://github.com/JuliaLang/julia/issues/20041.

2017-09-04 07:58 UTC, nalimilan approved these changes
Thanks @shorty66!

@StefanKarpinski I think you misunderstood what this PR does: it just removes information from the description when it's redundant with the signature.

2017-09-04 07:59 UTC, nalimilan requested changes

2017-09-04 07:59 UTC, nalimilan commented on base/multidimensional.jl
> +Cumulative product of `A` along a dimension, storing the result in `B`.
Woops, turns out the CI failures are legitimate and related to the trailing space here.

2017-09-04 08:36 UTC, nalimilan approved these changes

2017-09-05 17:23 UTC, StefanKarpinski commented
Fair enough, but we need to remove the argument altogether.

2017-10-01 11:57 UTC, merged