make IOBuffer(array) writable by defualt
JuliaLang/julia pull request #24430
Opened 2017-11-01 05:30 UTC by bicycle1885

`IOBuffer(UInt8[])` is not writable by default while `IOBuffer()` is. This looks inconsistent to me, and so I'd like to make `IOBuffer(array)` writable by default. `IOBuffer(string)` is kept as-is because making it writable may result in an expected behavior.

2017-11-02 20:51 UTC, JeffBezanson approved these changes

2017-11-02 21:02 UTC, vtjnash requested changes
> This looks inconsistent to me

Why is this inconsistent? `open` is also usually read-only by default.

2017-11-03 06:13 UTC, bicycle1885 commented
One may expect `IOBuffer()` is a shorthand of `IOBuffer(UInt8[])` but actually it isn't due to the difference of the writable flag. `open` is a function to open a file and so it is not directly related to `IOBuffer`'s constructor. Also, in most cases, `IOBuffer(array)` calls are with writable=true:

```
~/v/julia (master|…) $ rg '=.*IOBuffer\(' base | rg -v "IOBuffer\(\)" | rg -v "\w+\(.*="
base/io.jl:julia> buf = IOBuffer("    text")
base/iobuffer.jl:    b = IOBuffer(StringVector(32), readable, writable)
base/printf.jl:    fmt = IOBuffer(fmt_len)
base/dates/io.jl:    io = IOBuffer(Vector{UInt8}(bufsize), true, true)
base/strings/basic.jl:    out = IOBuffer(StringVector(endof(s)),true,true)
base/strings/basic.jl:    out = IOBuffer(StringVector(endof(s)),true,true)
base/strings/io.jl:    s = IOBuffer(StringVector(size), true, true)
base/strings/io.jl:    s = IOBuffer(StringVector(tostr_sizehint(xs[1])), true, true)
base/strings/io.jl:julia> io = IOBuffer("Haho");
base/strings/io.jl:    buf = IOBuffer(StringVector(endpos), true, true)
base/strings/util.jl:    out = IOBuffer(StringVector(floor(Int, 1.2sizeof(str))), true, true)
```

2017-11-15 08:49 UTC, samoconnor commented
related #24526

2017-11-15 20:10 UTC, StefanKarpinski commented
Bump – can we make some progress here? @JeffBezanson has already approved so my merge finger is getting itchy...

2018-02-01 19:41 UTC, stevengj commented
Read-only seems like a safer default here.   (Note that most of the writable usages in Base employ the undocumented `StringVector`.)   @vtjnash's analogy with `open` makes sense to me.  Note that making it writable changes the behavior of `take!`, for example.

Most of the cases where you pass a writable array seem to be just cases where you want a size hint, and it would be better in this case to actually have a `sizehint` parameter (e.g. so that it uses a `StringVector`).

Now that keywords are fast, can we just change the `IOBuffer` arguments into keywords?   `IOBuffer(array, writable=true)` is a lot more readable than `IOBuffer(array, true, true)`, and then we could add `IOBuffer(sizehint=10)`.

2018-02-01 20:13 UTC, StefanKarpinski commented
From triage: this should behave like `open` and use the same `open_flags` keyword pre-processing as `open` does with a few additional options like `sizehint`. There are a few other optional positional arguments that we may not want to expose as part of the public API of `IOBuffer`.

2018-02-07 17:09 UTC, closed without merging