Deprecate DevNull to DEVNULL
JuliaLang/julia pull request #25959
Opened 2018-02-08 19:26 UTC by ararslan

This is consistent with the other stream constants, i.e. `STDOUT`, `STDIN`, and `STDERR`, and indeed this was a violation of the typical style of all-caps constants.

Fixes #25786.

2018-02-08 20:06 UTC, stevengj approved these changes

2018-02-08 21:27 UTC, vtjnash commented
> was a violation of the typical style of all-caps constants.

In that case, shouldn't we make all of these lower-caps instead? (that's how they are in C, for example: stdin / stdout / stderr / stdio / devnull).

2018-02-08 21:39 UTC, ararslan commented
> In that case, shouldn't we make all of these lower-caps instead?

I don't understand what you mean. We don't do that for anything else, and these aren't just for C compatibility.

2018-02-08 21:53 UTC, JeffBezanson commented on base/exports.jl
> +    DEVNULL,
Should move this to the constants block alongside `STDOUT` etc.

2018-02-08 22:11 UTC, StefanKarpinski commented
Most of our global singletons like `nothing` and `missing` are lowercase. There's also the fact that this looks quite suggestive of what it does:
```jl
pipeline(`echo Hello`, stdout=stderr)
```
i.e. temporarily replace `stdout` with the value of `stderr`. I'm in favor of changing these all to lowercase: `stdin`, `stdout`, `stderr`, `devnull`.

2018-02-08 22:23 UTC, ararslan commented
In the particular example of `pipeline`, you run into the issue where the keyword argument name shadows a global:
```
julia> const x = 1
1

julia> f(x=4, y=x) = (x, y)
f (generic function with 3 methods)

julia> f()
(4, 4)
```
Note that the keyword argument value of `x` is used rather than the global `x`. In `pipeline`, it's possible to specify both `stdout` and `stderr`, so without constants that can be differentiated by name from those, everything will get all messed up.

2018-02-09 03:43 UTC, JeffBezanson commented
That's only an issue for the method definition, not call sites. In the method definition these default to `nothing`, so there should be no problem.

2018-02-14 02:38 UTC, JeffBezanson requested changes
I think there's still some controversy here over whether we want lowercase or uppercase.

2018-02-15 23:29 UTC, ararslan commented
Per triage consensus, this now deprecates `DevNull`, `STDIN`, `STDOUT`, and `STDERR` to `devnull`, `stdin`, `stdout`, and `stderr`, respectively. I did this in three commits: one to change uses of the lowercase versions as local variables, one to deprecate `DevNull`, and one to deprecate the others.

2018-02-15 23:42 UTC, JeffBezanson approved these changes

2018-02-16 00:06 UTC, StefanKarpinski commented
I find this to be rather pleasant. Thanks for doing it despite dissenting, Alex! In 1.0 we could rename DevNullStream to DevNull. Not sure if that’s even a public name.

2018-02-16 05:54 UTC, ararslan commented
Hm, looks like there's an issue building the docs. I'm not sure what the deal is yet.

2018-02-19 02:04 UTC, ararslan commented
Okay, doc building is apparently still an issue, even after updating Documenter.

2018-02-19 03:41 UTC, mortenpi commented
In case you already didn't come to the same conclusion: [`withoutput`](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Utilities/Utilities.jl#L558-L604) crashes when evaluating the following REPL block:

````
```@repl
versioninfo()
```
````

It works fine on `master` though, so it's something in this PR.

2018-02-19 20:34 UTC, ararslan commented
Hm, somewhere it's using `Core.stdout` where it should be using `Base.stdout`, which is a `LibuvStream` and thus can be passed to `redirect_stdout`.

2018-02-20 21:48 UTC, JeffBezanson commented
This is because binding deprecations only work with constants. `Base.stdout` changes at some point, and `Base.STDOUT` continues to point to the value it had when deprecated.jl ran.

The simplest fix is to also update the old names in reinit_stdio in libuv.jl. But of course that won't handle any other cases of changing the variables.

2018-02-20 21:56 UTC, vtjnash commented
> But of course that won't handle any other cases of changing the variables.

The only other place they can be changed is via the `redirect_std*` functions defined in stream.jl

2018-02-20 23:15 UTC, ararslan commented
Can someone explain why `Core.stdout` and `Base.stdout` are and need to be distinct?

2018-02-20 23:23 UTC, JeffBezanson commented
It's so some basic printing functionality can be available before Base is defined.

2018-02-20 23:28 UTC, ararslan commented
Okay, makes sense, thanks. I figured it would have to be something like that.

Could we make `Base.stdout` et al. `const`s? Is there a reason why they aren't currently?

2018-02-20 23:50 UTC, JeffBezanson commented
They are changed to acquire more functionality after bootstrap, and they're changed by the `redirect_` functions.

2018-02-22 18:56 UTC, JeffBezanson commented
Are you close here or should I make the remaining change?

2018-02-23 00:52 UTC, JeffBezanson commented
Will do.

2018-02-23 05:32 UTC, merged

2018-02-23 06:53 UTC, fredrikekre commented
```julia
julia> print(STDOUT, "foo")
WARNING: Base.STDOUT is deprecatednothing
 in module Main
foo
```

2018-02-23 17:18 UTC, stevengj commented
(Unfortunately, this PR is going to cause an huge number of deprecation warnings, and just switching to lowercase and doing `using Compat` will not be sufficient.  People will need to put `@compat` decorators everywhere they use the uppercase names.)

2018-02-23 17:26 UTC, StefanKarpinski commented
Why can't `Compat` export `stdin`, `stdout`, `stderr` and `devnull` as aliases? None of those names are exported or defined by `Base` in any earlier version of Julia.

2018-02-23 17:39 UTC, KristofferC commented
Because functions like `redirect_stdout` rebinds the variables.

2018-02-23 17:52 UTC, StefanKarpinski commented
That is annoying. I'm not sure what we can do about it though.

2018-02-23 18:00 UTC, KristofferC commented
I thought about using `getproperty`-overloading but that is not available on 0.6 :(

2018-02-23 18:02 UTC, StefanKarpinski commented
How about making `stdout` et al. mutable wrappers around an io object that just proxies IO calls through. Then the binding can be `const` and to redirect it, you just put a different IO object inside the wrapper. That definition could be put in Base and copied in Compat.

2018-02-23 18:04 UTC, mbauman commented
Seems like we could have Compat override the `Base._redirect_*` methods that actually do the rebindings.  They're totally untyped so we might even be able to do it without a warning with a `::IO` annotation.

2018-03-27 19:57 UTC, ararslan commented
This has the critically unfortunate consequence of conflicting with `StatsBase.stderr`.

2018-03-27 20:04 UTC, stevengj commented
Note that the SciPy [`stats.stderr` function was deprecated in favor of `stats.sem`](https://docs.scipy.org/doc/scipy-0.8.x/reference/generated/scipy.stats.mstats.stderr.html).

2018-06-05 02:39 UTC, sbromberger commented
Sorry for jumping in here so late, but what about `Random.GLOBAL_RNG`?

2018-06-05 06:01 UTC, KristofferC commented
That is a constant so how does the discussion here apply?

2018-06-05 06:07 UTC, sbromberger commented
ah, I see:

```
const GLOBAL_RNG = MersenneTwister(0)
```

Thanks.