Adapt to LLVM 6.0 changes
JuliaLang/julia pull request #26229
Opened 2018-02-27 15:00 UTC by vchuravy

there is now a release_60 branch and this PR supersedes #24845

2018-03-05 19:58 UTC, yuyichao requested changes

2018-03-05 19:58 UTC, yuyichao commented on src/llvm-muladd.cpp
> +#if JL_LLVM_VERSION >= 60000
These are pre-5.0.

2018-03-08 16:17 UTC, yuyichao approved these changes

2018-03-09 01:25 UTC, merged

2018-03-09 12:14 UTC, CodeLenz commented
Hi.

just made a git pull in current master, make cleanall  and set LLVM_VER=6.0.0 in Make.user

> ....
> ....
>     CC src/crc32c.o
>     CC src/processor.o
>     CC src/codegen.o
> /home/lenz/julia/src/codegen.cpp:41:10: fatal error: llvm/Target/TargetSubtargetInfo.h: No such file or directory
>  #include <llvm/Target/TargetSubtargetInfo.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[1]: *** [Makefile:136: codegen.o] Error 1
> make: *** [Makefile:76: julia-src-release] Error 2
> 

Am I missing some step ? Thanks for your help.

2018-03-09 12:19 UTC, vchuravy commented
Can you I unset `LLVM_VER`, then do a `make -C deps uninstall-llvm`, and
then set `LLVM_VER`?

Also note while this fixes compilation on 6.0.0 we still only support LLVM
3.9.1

On Fri, Mar 9, 2018, 07:14 CodeLenz <notifications@github.com> wrote:

> Hi.
>
> just made a git pull in current master, make cleanall and set
> LLVM_VER=6.0.0 in Make.user
>
> ....
> ....
> CC src/crc32c.o
> CC src/processor.o
> CC src/codegen.o
> /home/lenz/julia/src/codegen.cpp:41:10: fatal error:
> llvm/Target/TargetSubtargetInfo.h: No such file or directory
> #include <llvm/Target/TargetSubtargetInfo.h>
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[1]: *** [Makefile:136: codegen.o] Error 1
> make: *** [Makefile:76: julia-src-release] Error 2
>
> Am I missing some step ? Thanks for your help.
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/JuliaLang/julia/pull/26229#issuecomment-371796873>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAI3aojU23A_KqZ4_vSXxESuUKkPuLcdks5tcnIegaJpZM4SVE-6>
> .
>

2018-03-09 12:37 UTC, CodeLenz commented
Dear @vchuravy 

No luck with those modifications. 

It seems that  TargetSubtargetInfo.h is now in CodeGen/TargetSubtargetInfo.h instead of Target/TargetSubtargetInfo.h. I tried to change it in codegen.cpp but the error remains. I dont know if some -I/ has to be set in order to make it work. 

Regarding Julia support for newer LLVM versions, I have been using LLVM 5.0.1 along with master for some time, without issues. So, when I saw your patch I and the fact that LLVM 6.0.0 was released ....you know :0)

Thanks!

2018-03-09 12:46 UTC, vchuravy commented
Well that probably means I missed and ifelse, will look into it.

On Fri, Mar 9, 2018, 07:37 CodeLenz <notifications@github.com> wrote:

> Dear @vchuravy <https://github.com/vchuravy>
>
> No luck with those modifications.
>
> It seems that TargetSubtargetInfo.h is now in
> CodeGen/TargetSubtargetInfo.h instead of Target/TargetSubtargetInfo.h. I
> tried to change it in codegen.cpp but the error remains. I dont know if
> some -I/ has to be set in order to make it work.
>
> Regarding Julia support for newer LLVM versions, I have been using LLVM
> 5.0.1 along with master for some time, without issues. So, when I saw your
> patch I and the fact that LLVM 6.0.0 was released ....you know :0)
>
> Thanks!
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/JuliaLang/julia/pull/26229#issuecomment-371801479>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAI3atWY8AGaKGt-DZ1lSJE2k2qzI9eiks5tcnelgaJpZM4SVE-6>
> .
>