Switch Float16 representation to half
JuliaLang/julia pull request #26381
Opened 2018-03-09 00:29 UTC by vchuravy

This is a first step towards implementing the parts of #18927 and #18734
in the laziest most straight-forward possible.

1. Use LLVM's half type for Float16
2. Use LLVM intrinsics for basic operations on Float16
3. Provide fallbacks for methods missing in our current libc.

This foregoes the completnes aspect of #18927, while providing
a way forward to potentially extend this to `Float128`, and it doesn't add
additional dependencies like #18734.

Follow-up PR's could extend RTLIB to be more generic or to not use Base
(thus allowing it to be it's own shared library). There are other places
where `Float16` currently are eagerly converted to `Float32` so this is 
not an attempt at completness.

All the code paths are tested on x86 Linux and I am currently testing on ARM.
(There is a known PPC codegen issue, but I guess nobody but me cares about that).

@vtjnash is there anything I would need to do for `anticodegen`/LLVM free builds?

2018-03-09 00:33 UTC, vchuravy commented on base/rtlib/RTLIB.jl
> +function register(f, rtype, argt, name)
@vtjnash I was trying to use `@ccallable` here but I was getting failures during sysimage building.

2018-03-09 00:54 UTC, vchuravy commented
@vtjnash On AArch64 I am running into:

```
Wrong types for attribute: byval inalloca nest noalias nocapture nonnull readnone readonly signext sret zeroext dereferenceable(1) dereferenceable_or_null(1)
float (half)* @jlcapi_extendhfsf2_3064
LLVM ERROR: Broken function found, compilation aborted!
```

2018-03-09 02:27 UTC, vchuravy commented
Further update on PPC situation. The backend can't select FP16 operations (even on master), so I will first need to work with upstream on adding support for that.
That means that this PR is currently blocked until I get around to that :(, except if somebody else has a clever idea.

I wouldn't want to simply disable this on PPC since that would inhibit GPU code on PPC from using `Float16`.

2018-03-09 04:09 UTC, vchuravy commented
Today does not seem to be my day. It only worked beautifully on my tests because I have the `F16C` instruction set extension.
After fighting with recursive definitions I am now stuck on a seqfault that is probably related to my usage of `jl_extern_c`.

2018-03-09 16:25 UTC, stevengj commented
The title of this PR refers to switching the representation.  Does this actually change the `Float16` format, or does it only change the algorithms for working with `Float16`?

2018-03-09 16:36 UTC, yuyichao commented
I believe it changes the representation in LLVM but it shouldn't change the bit pattern.

2018-09-17 15:45 UTC, philtomson commented
What's the status of this PR? (conflicts, of course, but is anyone working on it?)

2018-09-17 18:36 UTC, vchuravy commented
Still blocked today on https://github.com/JuliaLang/julia/pull/26381#issuecomment-371693243

2018-09-17 21:27 UTC, vchuravy commented
No I don't think that is feasible we have `CodegenParameters` but that would require a fair amount of refactoring to get it to all places it needs to be, and it is unclear how we would handle it in pure Julia... It might be feasible to use `i16` on PPC for host and GPU (e.g. turn `float16` off completely).

2019-05-05 23:46 UTC, ViralBShah commented
Close this?

2019-05-05 23:51 UTC, vchuravy commented
While this PR is outdated, it is still an issue that needs fixing. So I
would say leave it open.

On Sun, May 5, 2019, 19:47 Viral B. Shah <notifications@github.com> wrote:

> Close this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JuliaLang/julia/pull/26381#issuecomment-489473980>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABDO2WJGP3YM4A2TYXMTEDPT5WXLANCNFSM4EUOIRBA>
> .
>

2019-08-05 13:39 UTC, vtjnash requested changes
@vchuravy says this PR is outdated

2020-09-10 13:11 UTC, vchuravy commented
Closed in favour of  #37510

2020-09-10 13:11 UTC, closed without merging