Fix size of R in sparse QR
JuliaLang/julia pull request #26391
Opened 2018-03-09 13:04 UTC by andreasnoack

Fixes #26368

2018-03-09 16:18 UTC, stevengj approved these changes

2018-03-09 17:16 UTC, KlausC commented
Did you also check, that `F.Q * F.R` works as expected, when `m > n` ?

2018-03-10 13:39 UTC, KlausC requested changes
F.Q * F.R still throws exception, when size(A, 1) > size(A, 2)

2018-03-23 10:36 UTC, andreasnoack commented
The rest of this is tracked by https://github.com/JuliaLang/julia/issues/26588

2018-03-23 10:36 UTC, merged