default tolerance of pinv uses `max(size(A)...)`
JuliaLang/julia pull request #26429
Opened 2018-03-12 18:14 UTC by KlausC

According to the documentation of `pinv`
```
The default value of tol is eps(real(float(one(eltype(M)))))*maximum(size(M))
```
That was adjusted in the code, which used `minimum`. The documentation seems to be correct, as the use of `maximum` is common in all similar situations I am aware of.

2018-03-12 18:27 UTC, andreasnoack commented
We are using `min` on purpose here. The documentation should be adjusted. See https://github.com/JuliaLang/julia/pull/23523/files and the references.

2018-03-12 18:27 UTC, andreasnoack requested changes
A doc issue

2018-03-12 20:34 UTC, KlausC commented
In spqr.jl I found a similar kind of tolerance value, unfortunately a typo in the code.
Wouldn't it be a good idea to use relative tolerance values and minimum instead of maximum there, too?

2018-03-13 20:20 UTC, andreasnoack approved these changes

2018-03-13 20:29 UTC, andreasnoack commented
> Wouldn't it be a good idea to use relative tolerance values and minimum instead of maximum there, too?

I think the tolerance is relative here because of the norm factor in the tolerance. The simulations and "analysis" used for the pseudo inverse were specifically for the SVD so it would be useful to look at the error growth as a function of `m`, `n`, and `nnz` in the SPQR case but it probably depends a lot on the sparsity pattern.

2018-03-13 20:30 UTC, merged

2018-03-13 22:33 UTC, KlausC commented
> so it would be useful to look at the error growth as a function of m, n, and nnz in the SPQR case but it probably depends a lot on the sparsity pattern.

Actually I made some experiments with QR-factorization of random dense matrices with (m,n) in (10:1000,10:1000) given singular values. I wanted to see, how close to zero were the diagonal elements of 
`R`, which correspond to the zero-singular values. (Without rounding errors they should be exactly zero). That would be relevant, if we want to estimate the rank of `A` by the QR-factors.
Result was, the absolute errors were in all tested cases in the order of magnitude `eps() * maximum(norm(...) ) * sqrt(m)`. There was also a small dependencies on the rank deficit (number of zeros in `diag(R)` and on the SV distribution, but not on `n` for `n >= 10`.

I did not make experiments with sparse matrices, though, but I expect the errors below the given limit as well. A low `nnz` could further reduce it.