[WIP] Reintegrate external profiling
JuliaLang/julia pull request #27466
Opened 2018-06-06 20:12 UTC by DokFaust

# Julia external profiling plus perf support
As presented in #26999, during ORC JIT transition Julia lost the LLVM native support to register JIT events. This was my first activity.
Also with my mentors of the Gsoc we agreed on adding perf support, similarly to what @maleadt did in #14727 .
Then I have added IntelJITEventListener and OProfile support. OProfile is currently missing line level code annotations, as the current OProfile LLVM support is not implementing it. 
That's why I have linked directly the OPprofileJITEventListener code, to avoid having to re-compile LLVM each time :sweat_smile: .

## TODO 
- [ ] Work on making an LLVM Patch to add DWARF debug symbols support in Operf.
- [ ] After that, the OProfileJITEventListener source can be ditched, and the LLVM event listener can be registered directly to the Julia execution engine.
- [ ] Maybe move the `PerfJITEventListener` class somewhere else, like in `debuginfo.cpp`, as it is quite awful linked in the Makefile.
- [ ] @vtjnash suggested to add some features to the `@profile` macro. This can be useful, as perf support is intended to profile the whole runtime. I can add a feature so that a particular section of Julia code is profiled with perf events. Also it would not require to compile Julia with perf support.
If anybody fthinks that this can be useful, I will work on that too.

2018-06-06 20:27 UTC, vchuravy reviewed
I would still prefer if we could use the `OProfileWrapper` from LLVM instead of duplicating it here. Are there any patches we need for that?

2018-06-06 20:27 UTC, vchuravy commented on deps/checksums/llvm-6.0.0.src.tar.xz/md5
> +788a11a35fa62eb008019b37187d09d2
Maybe rebase onto master which already should have these files (You should not check them int)

2018-06-06 20:27 UTC, vchuravy commented on src/OProfileJITEventListener.cpp
> +																				<< "/cmdline";
Formatting seems weird here

2018-06-06 20:41 UTC, DokFaust commented
Well if we want to integrate line level annotations for OProfile yup, I need to patch the LLVM integration. 

Either way the OProfile code will be ditched as it is redundant, and I will register the event from LLVM, as is done with `IntelJITEventListener`.
I have added it as for the moment is more convenient to test than recompiling every time LLVM :smile:

2018-06-09 23:53 UTC, vchuravy reviewed
Great! `PerfJITEventListener.cpp` is from LLVM as well right? If so we should also add this as a patch and any changes that you made should be contributed back upstream.

2018-06-09 23:53 UTC, vchuravy commented on deps/llvm.mk
> +$(eval $(call LLVM_PATCH,llvm-OProfile-line-num)) # In #27466, to be upstreamed
You should probably rebase your branch onto current master so that you have the other 6.0 patches as well

2018-06-11 15:40 UTC, DokFaust commented
Ehm this rebase went too far I think. I am working on fixin this

2018-06-16 06:44 UTC, vchuravy commented
You probably also want to squash your commits into one introducing the LLVM patches and one or two for the integration work.

2018-06-18 13:12 UTC, DokFaust commented
Yup it should be cleaner now
Also the OProfile patch has now been upstreamed!

As for a wrapper to Perf events in Julia [LinuxPerf.jl](https://github.com/DokFaust/LinuxPerf.jl) will be maintained as an external package, so I took that out of th todo list.

2018-07-05 14:56 UTC, vtjnash reviewed
Looks good to me (other than some minor formatting changes). Can you rebase to get CI to re-run? We'll also need BinaryBuilder to ingest these patches. But since this is off by default, I don't think that needs happen before merging.

2018-07-05 14:56 UTC, vtjnash commented on src/jitlayers.cpp
> +    if(!L)
space between `if` and `(`

2018-07-05 14:56 UTC, vtjnash commented on src/jitlayers.cpp
> +    for(auto &Listener : EventListeners)
space between `for` and `(`

2018-07-05 14:56 UTC, vtjnash commented on src/codegen.cpp
> +    if(jl_using_intel_jitevents)
space between `if` and `(`

2018-07-13 14:57 UTC, vtjnash approved these changes

2018-07-13 14:58 UTC, vtjnash commented
(CI failures are unrelated – httpbin.com flakiness and macOS FileWatching)

2018-07-13 17:59 UTC, vchuravy requested changes
Please squash the commits and do we need to add https://reviews.llvm.org/D47343 and https://reviews.llvm.org/D44890?

2018-07-13 17:59 UTC, vchuravy commented on deps/llvm.mk
> +$(eval $(call LLVM_PATCH,llvm-OProfile-line-num)) # In #27466, to be upstreamed
Duplicate

2018-07-13 21:40 UTC, DokFaust commented
`D44890` and `D47343` are superfluous as we do object notification in JuliaOJIT!

2018-07-19 04:31 UTC, vchuravy approved these changes
LGTM, after CI passes

2018-07-19 14:45 UTC, merged