[WIP] RCU primitives in Julia + typemap thread safety
JuliaLang/julia pull request #28202
Opened 2018-07-20 05:15 UTC by DokFaust

In this PR is intended to implement [RCU primitives](https://lwn.net/Articles/573436/) on the Julia userland.

2018-07-20 18:24 UTC, yuyichao reviewed
Right not it's not 100% clear to me that we actually need any of these primitives. For the implemetation we mirrors, I think all of the function it provides already exists due to the GC.

2018-07-20 18:37 UTC, yuyichao commented
So I believe the properties we need in general are,

1. No data race (between readers, between writers and between reader and writer)
2. No memory leask during deletion

The particular class of RCU implementation accomplishes this by

1. Data race between readers does not exist.
2. Data race between writers are protected with lock (or any other "traditional" way)
3. Data race between readers and writer are avoided by atomics (or in kernel case, barriers) to make sure all the updates are seen atomically (though different reader might observe the change in an inconsistent way).
4. The synchronization is needed to avoid memory leak during deletion operation since the deletion can only be done after the last concurrent reader finishes.

The only place that needs RCU primitives is actually the synchronization, the data races needs careful atomic operations but there aren't really any RCU specific operation needed. This is exactly what the primitives in this PR provide (AFAICT the counter is used to mark if the reader is in critical region so that the writer can wait for it). The other way used in the kernel is to wait for context switch in non-preemptive kernel. However, this is also exactly what the GC provide already. There won't be any memory leak to begin with so we don't actually need any of these primitives to help us. (Or you can say that `jl_gc_collect` is the `rcu_synchronize`)

2018-07-20 18:45 UTC, yuyichao commented on src/threading.c
> +    rcu_reader_gp[jl_threadid()] = rcu_gp_ctr + 1;
Also I'm pretty sure these needs to have the right ordering too. The unlock should have a release ordering. The lock must not be reordered with a read later so I feel like you actually need seq_cst here.

2018-07-24 11:40 UTC, DokFaust commented
> This is exactly what the primitives in this PR provide (AFAICT the counter is used to mark if the reader is in critical region so that the writer can wait for it).

Exactly, in the first commit I added memory barriers, but they were not needed as @vtjnash noticed that we already prevent memory leaks thanks to the GC.

In the title I wrote "typemap thread safety", but the typemap is almost already thread safe ATM.
The only problem may rise if the writer thread is manipulating the cache while other threads are reading, giving incoherence between a reader thread that entered the critical section before manipulation and stalls there afterwards (for any reason). That's what the global counter accomplishes.

I acknowledge that maybe this PR can reveal to be unnecessary, as maybe the insertion-deletion lock in the writing thread is enough to block incoherent readers after insertion-deletion.
Anyway I began to sketch it! Also the typemap cache lookup still needs to be fully guarded.

2018-07-24 15:15 UTC, yuyichao commented
> Exactly, in the first commit I added memory barriers, but they were not needed as @vtjnash noticed that we already prevent memory leaks thanks to the GC.

No. What I mean is nothing currently in this PR is needed.

> In the title I wrote "typemap thread safety", but the typemap is almost already thread safe ATM.

Not really. It doesn't use any atomics so it needs a lot of changes to make it thread safe. And yes, the typemap thread safety in the title is the reason I didn't close this.

> block incoherent readers after insertion-deletion.

Incoherent readers (depend on what exactly you mean) either doesn't exist or harmless. Readers that is concurrent with insertion/deletion may not see the update and may see deleted notes but that's harmless. No readers should actually see an partially updated states. The current readers are the whole point of RCU and as I said, the RCU primitives has nothing to do with why they are harmless that's the point of atomics.

> The only problem may rise if the writer thread is manipulating the cache while other threads are reading, giving incoherence between a reader thread that entered the critical section before manipulation and stalls there afterwards (for any reason). That's what the global counter accomplishes.

Not really. As mentioned above, such readers are not a problem at all. If they are, then you can't use RCU to improve performance. The basic requirement is that the writer has to be able to do the update atomically (or at least each atomic update should leave a valid global state, it doesn't have to, for example, insert multiple method atomically at the same time of course). If this can't be done with concurrent readers, waiting for readers won't help since you have to find a way to block the readers when you are doing update so you have to be back to read-write lock. If this can be done, you don't need to synchronize with the reader with any other primitive than the atomic update either since all reader will always see a valid state. Again, the RCU primitive implemented here is only useful in the book since the writer has to wait for the reader before freeing memory, which is not a problem here at all...

2018-07-24 15:17 UTC, yuyichao requested changes

2018-07-24 15:17 UTC, yuyichao commented on src/threading.h
> +#define ACCESS_ONCE(x) (*(volatile typeof(x) *)&(x))
This is wrong. Use atomic instead.

2018-07-24 15:17 UTC, yuyichao commented on src/threading.c
> +    jl_ptls_t ptls = jl_get_ptls_states();
If anything, ptls should probably be passed in as a parameter

2018-07-24 15:17 UTC, yuyichao commented on src/threading.c
> +        while( ((ptls->rcu_reader_gp) & 0x1) &&
`i` is still not used.

2018-07-27 19:00 UTC, DokFaust commented
OK the problem that blocked me was that I couldnt't find a way to fetch TLS for each thread. Now I've used `jl_all_tls_states`. That's why there was always that `i` index hanging there!

Anyway after giving a second glance at typemap, yeah it seems that only `jl_typemap_list_insert_sorted` of the insertion methods is protected with a signal fence, so maybe working on writer safety could be a priority.

If you think that anyway reader RCUs are not needed ATM, we can freeze this and I can proceed to work on typemap cache insertion.

2018-07-27 19:17 UTC, yuyichao commented
> only `jl_typemap_list_insert_sorted` of the insertion methods is protected with a signal fence

Errr.......... The signal fence has nothing to do with thread safety there. Signals and threads has completely different requirement.

> so maybe working on writer safety could be a priority.

No, I believe the trickly part is reader safety not writer safety. Writer safety just need lock and it should be easy to add. Reader safety, as mentioned above, requires using atomics properly (not `volatile`, don't follow linux kernel here).

> reader RCUs are not needed ATM

Not sure what do you mean by reader RCU here. What I mean is that the RCU intrinsics (you have functions for both readers and writers here) are not needed. Not just ATM, but ever, as long as all the memory are managed by the GC.

> work on typemap cache insertion

You need to work on both read and write to make it thread safe. Atomics always come in pairs.

2018-07-27 19:31 UTC, yuyichao reviewed
I did not think through the whole scheme to figure out what ordering is needed. I do feel like that this is similar enough to Dekker's algorithm that many of the stores and loads have to be seq_cst ordered (basically equivalent to a full barrier in the linux kernel). The comment about the code I left (this time and previous times) are just to point out the issues in understanding thread synchronization. It'll be nice if you don't blindly follow my comment but actually understand how you need to do it. If you actually want to implement the synchronization between reader and writers in typemap by adding proper use of atomics, which is great, I recommend you watch https://channel9.msdn.com/Shows/Going+Deep/Cpp-and-Beyond-2012-Herb-Sutter-atomic-Weapons-1-of-2 . The book you reference is good for high level understanding but provide no help at all for implementing anything in anywhere other than the linux kernel.

2018-07-27 19:31 UTC, yuyichao commented on src/threading.c
> +    jl_atomic_fetch_add(&tmp, 1);
It's never useful to have an atomic operation on a variable that will only be access by one thread....

2018-07-27 19:31 UTC, yuyichao commented on src/threading.c
> +    ptls->rcu_reader_gp = tmp;
It's **this** write that needs to be synchronized. Likely with `seq_cst` ordering.

2018-07-27 19:31 UTC, yuyichao commented on src/threading.c
> +            ((ptls->rcu_reader_gp - jl_atomic_load_acquire(&rcu_gp_ctr)) < 0) )
This is on the wrong variable again... Only this thread is writing to this variable so you don't need any ordering for the load. OTOH, you do need ordering for the `ptls->rcu_reader_gp`.

2018-07-27 19:31 UTC, yuyichao commented on src/threading.c
> +    int tmp = rcu_gp_ctr;
This load might need to be ordered as well.

2018-07-27 19:31 UTC, yuyichao commented on src/threading.c
> +    ptls->rcu_reader_gp = jl_atomic_load_acquire(&rcu_gp_ctr);
And the store almost certainly need ordering....

2020-08-28 13:22 UTC, closed without merging