POC/WIP: leverage LLVM function attributes for better CSE
JuliaLang/julia pull request #29566
Opened 2018-10-08 14:46 UTC by jrevels

This branch is a proof-of-concept showing how we can get LLVM to do better CSE by leveraging/inferring function attributes. This is entirely @maleadt's work, I just want to call attention to it before the branch goes stale w.r.t. master 😛

I think Tim might be a bit busy right now, but I would be willing to devote some cycles to polishing this in November, if folks agree it's a good idea.

```julia
julia> function f(x)
         _1 = exp(x)
         _2 = exp(x)
         return _1 + _2
       end
f (generic function with 1 method)

julia> @code_llvm f(1.)

; Function f
; Location: REPL[1]:2
; Function Attrs: readnone
define double @julia_f_1527076232(double) #0 {
top:
  %1 = call double @julia_exp_1527076233(double %0) #0
; Location: REPL[1]:4
; Function +; {
; Location: float.jl:395
  %2 = fadd double %1, %1
;}
  ret double %2
}
```

2018-10-08 15:08 UTC, Keno commented
I think this is reasonable, though I think it would be even better to track this kind of thing during inference.

2018-10-09 18:52 UTC, vtjnash requested changes
I don't think doing this as an IPO pass is valid (or, at least, won't be in the future, when we allow caching native code and compiling functions non-recursively).

2018-11-05 19:29 UTC, Keno commented
Yes, we could have a GVN pass in the optimizer. However, GVN is a non-trivial pass to implement, so since LLVM already has it, it'd be nice to at least pass that information down.

2018-12-22 23:32 UTC, vchuravy commented
As a side-note I was looking today at function attributes since I would love to do LICM on Julia functions. For that we would want to infer functions attributes much earlier in the pipeline (this PR does it at the end), but if we do it before `LowerPTLS` the call to `julia.ptls_states` prohibits any inference of interesting attributes like `readnone`, `readonly`, `argmemonly`, and we also can't get rid of the PTLS getter until late in the pipeline.

2022-12-27 20:05 UTC, closed without merging