Build: fix output directory when specified with O=
JuliaLang/julia pull request #30431
Opened 2018-12-18 11:01 UTC by fredrikekre

Fix `abspath` call when output directory is specified with `O=` and `SRCDIR` is not set.

2018-12-18 15:39 UTC, staticfloat approved these changes

2018-12-18 15:39 UTC, staticfloat commented
@fredrikekre does this at least fix the issue you were seeing?

2018-12-18 15:40 UTC, fredrikekre commented
Yes.

2018-12-18 19:27 UTC, vtjnash requested changes
How would SRCDIR manage not to get set? This will not do the same task.

2018-12-18 19:36 UTC, vtjnash commented
`SRCDIR` is the first line of the Makefiles—it always gets set first. This won't do the same task in any situation, since it's computing a function of a different value.

2018-12-18 19:39 UTC, staticfloat commented
`SRCDIR` is not defined within `Make.inc`; so its usage here is wrong.  It will always expand to an empty string, due to the usage of `:=`.  There is no situation in which this line of code will be correct; so we either need to define a value for `SRCDIR` earlier, remove the usage of `:=`, or manually insert something that will compute the value that `SRCDIR` "should" have had, which is what this PR does.

2018-12-18 20:02 UTC, vtjnash commented
> SRCDIR is not defined within Make.inc; so its usage here is wrong. It will always expand to an empty string, due to the usage of :=. There is no situation in which this line of code will be correct

Make.inc doesn't define any rules and is never used, so it should never expand to the empty string

> or manually insert something that will compute the value that SRCDIR "should" have had, which is what this PR does.

That is not what this PR does. If it was that easy to compute, we would have done that originally.

2018-12-18 20:53 UTC, staticfloat commented
I think what you're trying to say is that `SRCDIR` should be set in all calling `Makefile`s before including `Make.inc`, and it should therefore be set by the time we get to this line in `Make.inc`.  In that case, could you explain what the proper value to set `SRCDIR` is for the top-level `Makefile`, because there is no `SRCDIR` set in that `Makefile`.

2018-12-18 22:46 UTC, fredrikekre commented
Right, defining `SRCDIR` in the main `Makefile`, before https://github.com/JuliaLang/julia/blob/eddcbd7585152c1e404ed0481ffe44c61d504e77/Makefile#L2 will probably also fix the issue.

2018-12-19 10:13 UTC, fredrikekre commented
Demonstration of the problem:
```
[~/sandbox]$ git clone https://github.com/JuliaLang/julia.git julia-source
[~/sandbox]$ export SOURCE=$PWD/julia-source
[~/sandbox]$ export INSTALL=$PWD/julia-install
[~/sandbox]$ make -C $SOURCE O=$INSTALL print-BUILDDIR
make: Entering directory '/home/fredrik/sandbox/julia-source'
BUILDDIR=/home/fredrik/sandbox/julia-install/home/fredrik/sandbox/julia-source <-- ????
make: Leaving directory '/home/fredrik/sandbox/julia-source'
```

2019-01-31 20:17 UTC, JeffBezanson commented
Should this be backported?

2019-02-04 17:07 UTC, fredrikekre commented
Would https://github.com/JuliaLang/julia/pull/30431#issuecomment-448400584 be a better fix than what is on this branch now @vtjnash ?

2019-02-04 17:42 UTC, vtjnash commented
That's at least not an incorrect change (unlike this PR), although nobody has yet said why this is a bug.   There's a repro above that shows that an ignored variable has an undefined value—but which is normal to not care what happens to the value of something that is not used.

2019-02-05 10:56 UTC, fredrikekre commented
> nobody has yet said why this is a bug

You don't think this is a bug: https://github.com/JuliaLang/julia/pull/30431#issuecomment-448541544 ? I would expect
```
BUILDDIR=/home/fredrik/sandbox/julia-source
```
and not
```
BUILDDIR=/home/fredrik/sandbox/julia-install/home/fredrik/sandbox/julia-source
```

2019-03-14 18:56 UTC, Keno commented
@vtjnash says this change is incorrect. It seems like there's still some confusion about that, so ideally let's figure out what the actual issue here is before triaging whether to backport it.

2019-03-14 20:00 UTC, staticfloat commented
@vtjnash can you explain a little more concretely why this is incorrect?

2019-03-14 20:06 UTC, vtjnash commented
It replaces some code that does the desired thing with code that does something else. The only claim so far seems to be that an unused variable has an undefined value. But yeah, we have many of those.

2019-03-14 20:11 UTC, staticfloat commented
So let's talk about the incorrect behavior that we see right now then.  The fundamental issue is that running `make -C $SOURCE O=$INSTALL print-BUILDDIR` doesn't work properly due to `SRCDIR` not being set within the top-level `Makefile`.  Perhaps the proper fix is as @fredrikekre said above, and to define `SRCDIR := $(JULIAHOME)` within our top-level `Makefile`.

2019-03-14 21:57 UTC, vtjnash commented
OK, but this can't be the only unused variable (used by some other arbitrary build script) that has a random value. As you point out, SRCDIR and SRCCACHE also don't have the correct values

2019-04-01 23:25 UTC, staticfloat commented
@fredrikekre I tried to re-create this and I couldn't; if you include the `make configure` step from the README (Which I don't see in your code traces above) does this work properly for you now?

2020-10-29 18:23 UTC, closed without merging