Fixed sprand for integer type
JuliaLang/julia pull request #30516
Opened 2018-12-26 09:34 UTC by raghav9-97

Fixes #30502.

2018-12-26 11:49 UTC, abraunst commented
You should also fix `sprand(m, n, p, rfn)` (the function right below); otherwise `sprand(UInt8(16), UInt8(16), 1.0, ones)` has the same problem.

2018-12-26 12:03 UTC, raghav9-97 commented
Please re review this PR.

2018-12-26 16:57 UTC, ViralBShah commented
@raghav9-97 PRs do get reviewed as you submit them (unless you put WIP in the title). In general, you want to bump it up for review if it has not received any attention in about 3-4 days. Hope that helps.

2018-12-26 17:00 UTC, ViralBShah requested changes

2018-12-26 17:00 UTC, ViralBShah commented on stdlib/SparseArrays/test/sparse.jl
> +end
Can we have a test that checks correctness of the intended answer with `==`? Also, only one test would be enough here.

2018-12-27 06:05 UTC, raghav9-97 commented
Is this PR now ready to be merged?

2018-12-27 06:43 UTC, merged