Tests for stridedarray/sparse mult
JuliaLang/julia pull request #30557
Opened 2019-01-02 13:10 UTC by kshyatt

Trying to get at [this](https://codecov.io/gh/kshyatt/julia/src/master/stdlib/SparseArrays/src/linalg.jl#L118) and the method above it.

2019-01-03 00:14 UTC, ViralBShah commented
@kshyatt Nice to have your eyes on the sparse libraries!

2019-01-06 03:57 UTC, Sacha0 approved these changes
Thanks @kshyatt! :)

2019-01-07 08:45 UTC, andreasnoack requested changes

2019-01-07 08:45 UTC, andreasnoack commented on stdlib/SparseArrays/test/sparse.jl
> +        @test Array(sA*b) == Array(sA)*Array(b)
This has to be tested with `≈`.

2019-01-12 02:54 UTC, kshyatt commented
@andreasnoack is that better? Should all of them be approx?

2019-01-13 18:26 UTC, andreasnoack approved these changes

2019-01-13 18:26 UTC, merged