Fix #30876, make GITHUB_REGEX match ssh://git@github.com URLs.
JuliaLang/julia pull request #30907
Opened 2019-01-30 20:49 UTC by tkoolen

2019-01-31 15:45 UTC, omus requested changes

2019-01-31 15:45 UTC, omus commented on stdlib/LibGit2/src/LibGit2.jl
> +    r"^(?:git@|git://|https://|ssh://git@(?:[\w\.\+\-]+@)?)github.com[:/](([^/].+)/(.+?))(?:\.git)?$"i
This change breaks HTTPS as the general username parsing needs to be applied only on that protocol. A test should be added along the lines of: "https://username@github.com"

Instead, we can do:
```suggestion
    r"^(?:(?:ssh://)?git@|git://|https://(?:[\w\.\+\-]+@)?)github.com[:/](([^/].+)/(.+?))(?:\.git)?$"i
```

2019-01-31 15:45 UTC, omus commented on stdlib/LibGit2/test/libgit2.jl
> +            @test m != nothing
```suggestion
            @test m !== nothing
```

2019-01-31 15:45 UTC, omus commented on stdlib/LibGit2/test/libgit2.jl
> +        @test match(LibGit2.GITHUB_REGEX, "git@notgithub.com/$user/$repo.git") == nothing
```suggestion
        @test occursin(LibGit2.GITHUB_REGEX, "git@notgithub.com/$user/$repo.git")
```

2019-01-31 16:12 UTC, tkoolen reviewed
Thanks for the comments.

2019-01-31 16:12 UTC, tkoolen commented on stdlib/LibGit2/test/libgit2.jl
> +        @test match(LibGit2.GITHUB_REGEX, "git@notgithub.com/$user/$repo.git") == nothing
`!occursin`, I assume?

2019-01-31 16:47 UTC, omus commented on stdlib/LibGit2/test/libgit2.jl
> +        @test match(LibGit2.GITHUB_REGEX, "git@notgithub.com/$user/$repo.git") == nothing
Whoops, yes you are correct

2019-01-31 16:47 UTC, omus approved these changes

2019-01-31 20:07 UTC, StefanKarpinski approved these changes

2019-02-03 01:08 UTC, omus commented
Looks like an unrelated network error

2019-02-03 01:09 UTC, merged