More efficient indexing by CartesianIndices
JuliaLang/julia pull request #31214
Opened 2019-02-28 22:47 UTC by mbauman

Treat CartesianIndices as its tuple of ranges when indexing. This allows views that use CartesianIndices as indices to be strided and changes the complexity of boundschecking from O(n^d) to O(d)

2019-03-02 05:00 UTC, eulerkochy requested changes
`@testset "indexing by CartesianIndices"` should be `@testset "indexing by CartesianIndices" begin`, imo

2019-03-02 05:02 UTC, mbauman commented on test/arrayops.jl
> +@testset "indexing by CartesianIndices"
```suggestion
@testset "indexing by CartesianIndices" begin
```

2019-03-02 05:03 UTC, mbauman commented
Thanks @eulerkochy!

2020-01-22 08:17 UTC, timholy approved these changes
Arrived while I was immersed in other tasks (writing JuliaIntepreter, I think). Nice!

2020-01-22 08:20 UTC, KristofferC commented
Rebased it to re-run CI.

2020-01-23 19:13 UTC, merged