Documentation, dependency install command (macOS, Homebrew)
JuliaLang/julia pull request #32113
Opened 2019-05-22 22:06 UTC by justingeeslin

Including the command to install dependency gfortran for macOS via Homebrew. Hopefully this will be helpful for a first-timer.

2019-05-24 23:36 UTC, Keno approved these changes
Seems good to me.

2019-05-24 23:38 UTC, fredrikekre commented on doc/build/macos.md
> +```bash
```suggestion
```bash
```

2019-08-01 23:19 UTC, ViralBShah commented
@staticfloat Isn't gfortran part of the gcc install on brew nowadays?

2019-08-01 23:21 UTC, ViralBShah commented
Also, given BinaryBuilder, I think we no longer need `gfortran` to build julia. Perhaps this PR should be updated accordingly.

2019-08-06 06:04 UTC, staticfloat requested changes

2019-08-06 06:04 UTC, staticfloat commented on doc/build/macos.md
> +brew cask install gfortran
You should instead just `brew install gcc`, rather than installing a `gfortran` cask.

2020-02-29 15:48 UTC, merged