add eps(::Missing) = missing
JuliaLang/julia pull request #32235
Opened 2019-06-03 20:43 UTC by francescoalemanno

avoids ERROR: MethodError: no method matching eps(::Missing)
which can happen in generic code

2019-06-05 23:30 UTC, JeffreySarnoff commented
for the same reason that this PR exists,
please add a method `signbit(missing) = missing`

2019-06-06 09:15 UTC, francescoalemanno commented
this PR is about this single method, and i think @JeffBezanson is against adding this method

2019-06-10 11:15 UTC, KristofferC requested changes
I don't think we should add more Missing methods until there is a clear guideline for when it is appropriate.

2019-06-10 19:55 UTC, nalimilan commented
At this point we provide `missing`-propagating methods for most math functions in Base, so I think it would be consistent to add a few more if they are missing (even if a more general system like `f?(x)` would be better in the long term). Though it would be a good idea to make a list of math functions in Base to check how many would have to be added if we adopt that policy.

2019-06-10 20:01 UTC, KristofferC commented
`eps` is not a math function though

2019-06-10 21:26 UTC, iamed2 commented
It's likely that whatever function calls this is the one which should support a separate dispatch on `Missing`. `eps` really only makes sense if you're doing some operations which assume you have a floating point representation, so the code is already not very generic.

2019-06-11 02:27 UTC, ararslan commented
Yeah I think this is a case where it doesn't make sense to have a method for `missing`.

2019-06-11 07:35 UTC, nalimilan commented
Yes, `eps` is a bit special. OTOH we already implement `isnan`, so...

2019-06-11 10:28 UTC, KristofferC commented
> OTOH we already implement isnan, so...

so let's not make a bad situation worse.

2019-06-11 10:48 UTC, francescoalemanno commented
it should be consistent IMHO.

either all methods not purely mathematical are removed or all methods 
(like eps) are added.

Il giorno mar 11 giu 2019 alle 12:29, Kristoffer Carlsson 
<notifications@github.com> ha scritto:
>> OTOH we already implement isnan, so...
>> 
> so let's not make a bad situation worse.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/JuliaLang/julia/pull/32235?email_source=notifications&email_token=AME7LDRHBYQGVZAH2H6UAC3PZ5467A5CNFSM4HSR36QKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXMVPOA#issuecomment-500783032>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/AME7LDSTE6C3CTRUUA2YZUDPZ5467ANCNFSM4HSR36QA>.
> 
> [ { "@context": "http://schema.org", "@type": "EmailMessage", 
> "potentialAction": { "@type": "ViewAction", "target": 
> "https://github.com/JuliaLang/julia/pull/32235?email_source=notifications\u0026email_token=AME7LDRHBYQGVZAH2H6UAC3PZ5467A5CNFSM4HSR36QKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXMVPOA#issuecomment-500783032", 
> "url": 
> "https://github.com/JuliaLang/julia/pull/32235?email_source=notifications\u0026email_token=AME7LDRHBYQGVZAH2H6UAC3PZ5467A5CNFSM4HSR36QKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXMVPOA#issuecomment-500783032", 
> "name": "View Pull Request" }, "description": "View this Pull Request 
> on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", 
> "url": "https://github.com" } } ]

2019-06-11 11:53 UTC, KristofferC commented
> it should be consistent IMHO.

Consistency implies some sort of criteria that one can be consistent with. There is no documentation or guidelines yet about `Missing` so it is hard to even say what is consistent. But, clearly, adding special case for `Missing` for all functions is a non-starter. In addition, functions in Base are not even supposed to be special so this sets a precedent that everyone writing any type of function has to think about Missing.

> either all methods not purely mathematical are removed or all methods (like eps) are added.

Removing methods are breaking so we need to live with past mistakes.

2019-06-11 12:46 UTC, ararslan commented
> OTOH we already implement `isnan`, so...

`isnan` is pretty different, IMO, and makes sense for `missing` because you don't know whether the given value would be `NaN` were it present. Eric's point about `eps` is pretty on-point; `eps` isn't really generic to begin with, and if your precision is based on a missing value, you have more serious problems.

2019-07-20 21:48 UTC, KristofferC commented
Closing based on the discussion.

2019-07-20 21:48 UTC, closed without merging