Move "sparse" code for structured matrices to "SparseMatrixCSC"
JuliaLang/julia pull request #32466
Opened 2019-07-01 18:01 UTC by dkarrasch

This keeps identical functionality, but makes the specialized constructors for structured matrices such as `Diagonal`, `Bidiagonal` etc. available to the broadcast machinery.

Fixes #31770.

2019-07-03 01:33 UTC, ViralBShah commented
This looks good. Needs tests for the conversions and then good to merge.

2019-07-03 01:33 UTC, ViralBShah requested changes
Looks good. It would be good to get some tests in and merge.

2019-07-03 10:01 UTC, dkarrasch commented
There exist these:

https://github.com/JuliaLang/julia/blob/4b6ab68900448a14dc214ad08611c3e09fef1ec5/stdlib/SparseArrays/test/sparse.jl#L1463-L1479

Since `sparse` calls `SparseMatrixCSC` they are tested already. Should I simply duplicate these tests and replace each `sparse` by `SparseMatrixCSC` or is it enough what we have.

On a different note, I have code that does what was asked for in https://github.com/JuliaLang/julia/pull/10843#issuecomment-93715724. I could add it here and leave the individual commits for review, or open another PR.

2019-07-03 14:11 UTC, merged

2019-07-03 14:12 UTC, ViralBShah commented
I agree. Merged this one in - but we can have further optimizations if you already have them in a separate PR.

2019-07-08 02:14 UTC, Roger-luo commented
Will this be backported?

2019-07-08 04:16 UTC, ViralBShah commented
Triage should decide whether this goes into 1.2.

2019-07-08 14:58 UTC, StefanKarpinski commented
This is a feature, so no.