Issue 32690 : SSHManager with csh shell
JuliaLang/julia pull request #32765
Opened 2019-08-02 08:04 UTC by DcfGH

Dear Julia team,

A pull request from issue 32690
Best regards

2019-10-15 15:37 UTC, kshyatt commented
@amitmurthy do you want to review this?

2020-04-10 18:20 UTC, ViralBShah commented
@tanmaykm Can you review and merge this? I don't fully understand the intricacies of `csh`, but it looks like a small change.

2020-04-12 01:52 UTC, tanmaykm requested changes

2020-04-12 01:52 UTC, tanmaykm commented on stdlib/Distributed/src/managers.jl
> +    cmds = """cd -- $(shell_escape_posixly(dir)) ; $(isempty(tval) ? "" : "export JULIA_WORKER_TIMEOUT=$(shell_escape_posixly(tval))") $(shell_escape_posixly(exename)) $(shell_escape_posixly(exeflags
If multiple lines were merged, shouldn't there be a command separator after all the lines? I don't see one after the second line.

2020-04-12 01:56 UTC, tanmaykm commented
Since this is quite old, it will be good to rebase this once with master.

We probably do not run our CI tests with `csh`. So we may be only testing for regressions here and not the actual fix. Is there any way to do that?

2020-09-08 02:15 UTC, FelipeLema commented
fixes https://github.com/JuliaLang/julia/issues/32690

2020-09-08 15:41 UTC, FelipeLema commented
@tanmaykm you can do something like `sudo usermod --shell=/usr/bin/csh travis` (asuming I got the username right).

However, that will make _all_ shells spawned with `csh` instead of default `bash`, which is likely (?) to have consequences midway through the test run.

Is there a proper place where we can set-and-unset `csh` as shell? I was thinking "before remote process tests", is this possible?

2021-07-09 18:52 UTC, closed without merging