Add argumentless anonymous function example to manual/functions
JuliaLang/julia pull request #32915
Opened 2019-08-15 19:07 UTC by elalaouifaris

To resolve #32785 I added a example in the corresponding section in the manual based on the example given the issue discussion.

2019-08-15 19:12 UTC, ararslan requested changes
Welcome and thanks for the contribution! I have a few stylistic and wording suggestions but overall this looks good.

2019-08-15 19:12 UTC, ararslan commented on doc/src/manual/functions.md
> +```jldoctes
```suggestion
```jldoctest
```
I assume this was a mistake?

2019-08-15 19:12 UTC, ararslan commented on doc/src/manual/functions.md
> +The code above is equivalent to calling get with an anonymous function containing the code
```suggestion
The code above is equivalent to calling `get` with an anonymous function containing the code
```

2019-08-15 19:12 UTC, ararslan commented on doc/src/manual/functions.md
> +inclosed between do and end, like so:
```suggestion
enclosed between `do` and `end`, like so:
```

2019-08-15 19:12 UTC, ararslan commented on doc/src/manual/functions.md
> +get( () -> time(), dict, key)
```suggestion
get(()->time(), dict, key)
```

2019-08-15 19:12 UTC, ararslan commented on doc/src/manual/functions.md
> +The call to [`time`](@ref) is delayed by wrapping it in an argumentless anonymous function
```suggestion
The call to [`time`](@ref) is delayed by wrapping it in a 0-argument anonymous function
```

2019-08-15 19:12 UTC, ararslan commented on doc/src/manual/functions.md
> +that is called only when the requested key is absent from dict.
```suggestion
that is called only when the requested key is absent from `dict`.
```

2019-08-15 19:12 UTC, ararslan commented on doc/src/manual/functions.md
> +A use case example is [`get`](@ref).
```suggestion
As an example, consider this call to [`get`](@ref):
```

2019-08-15 19:14 UTC, elalaouifaris commented on doc/src/manual/functions.md
> +```jldoctes
Yes I noticed it after submitting.

2019-08-15 19:43 UTC, KristofferC commented on doc/src/manual/functions.md
> +```jldoctes
This is not resolved.

2019-08-15 20:50 UTC, ararslan approved these changes

2019-08-16 11:02 UTC, fredrikekre commented
Thanks, and welcome as a contributor to Julia!

2019-08-16 11:02 UTC, merged