Include parent testset descriptions in immediate test report
JuliaLang/julia pull request #32938
Opened 2019-08-17 08:44 UTC by tkf

With this PR, the failure message printed immediately after the test failure (i.e., not `Test Summary`) includes testset descriptions of all parent test sets.  This clarifies the context in which the failure occurs.  This is important especially in Julia CI (`Base.runtests`) which does not print `Test Summary` (https://github.com/JuliaLang/julia/issues/32924#issuecomment-521995755).

Some examples.  The contents between `Test Set:` and `Test Failed at` are added in this PR:

```julia
julia> @testset "first level test set" begin @test false end
Test Set: first level test set
Test Failed at REPL[3]:1
  Expression: false
Stacktrace:
 [1] top-level scope at REPL[3]:1
 [2] top-level scope at /home/takafumi/repos/watch/_wt/julia/parentset/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1137
 [3] top-level scope at REPL[3]:1
Test Summary:        | Fail  Total
first level test set |    1      1
ERROR: Some tests did not pass: 0 passed, 1 failed, 0 errored, 0 broken.

julia> @testset "first level test set" begin
           @testset "second level test set" begin
               @testset "third level test set" begin
                   @test false
               end
           end
       end
Test Set:
first level test set
  second level test set
    third level test set
Test Failed at REPL[4]:4
  Expression: false
Stacktrace:
 [1] top-level scope at REPL[4]:4
 [2] top-level scope at /home/takafumi/repos/watch/_wt/julia/parentset/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1137
 [3] top-level scope at REPL[4]:4
 [4] top-level scope at /home/takafumi/repos/watch/_wt/julia/parentset/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1137
 [5] top-level scope at REPL[4]:3
 [6] top-level scope at /home/takafumi/repos/watch/_wt/julia/parentset/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1137
 [7] top-level scope at REPL[4]:2
Test Summary:            | Fail  Total
first level test set     |    1      1
  second level test set  |    1      1
    third level test set |    1      1
ERROR: Some tests did not pass: 0 passed, 1 failed, 0 errored, 0 broken.
```

2019-08-19 07:20 UTC, andreasnoack commented
I think this is a good change. Please speak out if you have any objections.

2019-11-13 18:44 UTC, vtjnash commented
WeakRef seems like the wrong choice, why not just a normal reference? Otherwise, seems like @andreasnoack already approved this and so it's good to merge.

2019-11-13 22:07 UTC, tkf commented
I removed WeakRef

2021-11-19 02:31 UTC, tkf commented
@vtjnash Do you want to review the post-merge diff? Or can I merge this?

2021-11-19 03:23 UTC, DilumAluthge commented
You'll need to fix the doctest failures.

2021-11-19 04:16 UTC, vtjnash approved these changes
I don't remember ever looking at this before

2021-11-19 09:44 UTC, rfourquet commented
Unless I'm missing something, given that the parent testsets are stored in the task locak storage, it doesn't seem necessary to add `parent` as a field of `DefaultTestSet` nor to add the `subtestset` function, strictly for the purpose of including parent testsets in test report (it might be useful for other reasons though?)

2021-11-19 15:53 UTC, vtjnash requested changes
Thanks @rfourquet for review. I agree: since we got to this `record` function by calling `get_testset`, and that function had the full list of testset parents already, it looks like we don't need to add a field to do this printing.

2021-11-19 23:20 UTC, tkf commented
Thanks, @rfourquet. Yes, that's a good point. I don't remember why I didn't take that strategy. It's probably easy to fix.

2026-02-09 03:12 UTC, DilumAluthge commented
This PR has had no activity for four years+, so I'll close it as stale.

If somebody is interested in taking over this PR and continuing to work on it, let me know.

2026-02-09 03:12 UTC, closed without merging