speed up matching_methods for dispatch tuples
JuliaLang/julia pull request #33261
Opened 2019-09-13 21:22 UTC by JeffBezanson

`jl_matching_methods` is one of the inner loops in type inference. When the argument is `isdispatchtuple` (by far the common case) we can use a faster query since at most one method matches. This gives a very modest speedup of around 4-5%, but it affects almost everything and has basically no cost so it's nice anyway.

Time to first plot before:
```
 23.422304 seconds (46.91 M allocations: 2.295 GiB, 5.94% gc time)
```
after:
```
 21.891047 seconds (46.19 M allocations: 2.263 GiB, 6.56% gc time)
```

2019-09-13 21:35 UTC, vtjnash requested changes
I’ve wanted this many times too. But unfortunately since it doesn’t set the world-limit output fields, it cannot be used currently.

2019-09-13 21:38 UTC, vtjnash reviewed
(fwiw, even if that wasn’t the case, I think this would may still be the wrong place to put this logic, as all intersection visitors would probably want this optimization)

2019-09-13 21:52 UTC, JeffBezanson commented
> But unfortunately since it doesn’t set the world-limit output fields, it cannot be used currently.

Ah, right. That seems easy to fix though --- can we just intersect the range with the values in the typemap entry that gets looked up?


> as all intersection visitors would probably want this optimization

Skipping the overhead of the intersection visitor is part of the optimization though, e.g. setting up the closure environment.

2019-09-16 13:36 UTC, vtjnash commented on src/gf.c
> +        jl_method_instance_t *sf = jl_mt_assoc_by_type(mt, types, 1, world);
```suggestion
        jl_method_instance_t *sf = jl_mt_assoc_by_type(mt, types, 0, world);
```

2019-09-16 13:36 UTC, vtjnash commented
> can we just intersect the range with the values in the typemap entry that gets looked up?

no: it's the range of the intersection, not the lookup.

2020-02-17 19:52 UTC, vtjnash commented
Replaced by https://github.com/JuliaLang/julia/pull/34745

2020-02-17 19:52 UTC, closed without merging