Fix #34414: remove legacy doc content [skip ci]
JuliaLang/julia pull request #34416
Opened 2020-01-17 13:50 UTC by WenjieZ

Remove the paragraphs saying "Immutable composite types with no fields are singletons".

Previously, `MutableNoFields() === MutableNoFields()`, but this was changed in #25854. When that got changed, the existing docs was tweaked to say that the struct had to be immutable(#25862) . However, there is no longer anything specific about it having no fields. The docs about singletons can thus just be removed since they are not special anymore.

2020-01-17 13:55 UTC, yuyichao requested changes
See comment in the issue. This part is still correct (use of `===`), relevant (it's defining singleton) and should not be removed. It can be improved by mentioning the consistency with the immutable semantics and such change will be welcome.

2020-04-30 14:10 UTC, ViralBShah commented
Please reopen if @yuyichao's suggestion is updated into this PR.

2020-05-19 08:45 UTC, WenjieZ commented
Sorry for my delayed reply. I am working on COVID-19, and thus this PR is not on my priority list. I would be happy if someone else is willing to take care of this PR.

2020-05-19 12:22 UTC, ViralBShah commented
@JeffBezanson Perhaps this is a quick one for you?

2020-05-19 13:24 UTC, StefanKarpinski commented
https://github.com/JuliaLang/julia/pull/35938

2020-05-19 13:24 UTC, closed without merging