Missing accumulate tests
JuliaLang/julia pull request #34534
Opened 2020-01-27 15:10 UTC by bramtayl

[Uncovered](https://codecov.io/gh/JuliaLang/julia/src/master/base/accumulate.jl#L245)
[Uncovered](https://codecov.io/gh/JuliaLang/julia/src/master/base/accumulate.jl#L299)
[Uncovered](https://codecov.io/gh/JuliaLang/julia/src/master/base/accumulate.jl#L304)
[Uncovered](https://codecov.io/gh/JuliaLang/julia/src/master/base/accumulate.jl#L333)

2020-01-29 06:56 UTC, dkarrasch approved these changes

2020-01-29 07:19 UTC, dkarrasch requested changes

2020-01-29 07:19 UTC, dkarrasch commented on test/arrayops.jl
> +        "acccumulate does not support the keyword arguments Symbol[:unsupported]"
should be
```julia
"acccumulate does not support the keyword arguments [:unsupported]"
```
same below.

2020-01-29 18:48 UTC, bramtayl commented on test/arrayops.jl
> +        "acccumulate does not support the keyword arguments Symbol[:unsupported]"
Oops. Thanks!

2020-01-29 19:47 UTC, dkarrasch approved these changes
LGTM now.

2020-03-04 02:27 UTC, bramtayl commented
Let me know if you want me rebase this

2020-03-04 02:27 UTC, closed without merging