In open(f, ...), call flush before calling `close`
JuliaLang/julia pull request #35303
Opened 2020-03-30 01:27 UTC by Keno

In #35217, I noticed that if we call `close` on an IOStream, but the device
that has the underlying file is full, we silently truncate the file without
error. To remidy that, introduce an explicit flush call before closing the
file. This should either succeed and reflect the changes on disk, or fail
and throw an appropriate error.

2020-03-30 14:01 UTC, StefanKarpinski approved these changes
👍

2020-03-30 14:16 UTC, KristofferC commented
[just stating the obvious, all CI failed because of errors in package loading]

2020-03-30 14:31 UTC, StefanKarpinski commented
While this is a good idea and should work, I fear that there are many kinds of IO objects where this will not work. I've seen it break things before. In general, I fear we seem to be in a state where the whole flush/close dance is very, very brittle.

2020-03-30 14:40 UTC, vtjnash approved these changes
@StefanKarpinski This change should be fine. It's just implicit-return that got broken by mistake.

2020-03-30 14:44 UTC, vtjnash requested changes
```julia
julia> open("VERSION") do f; close(f); flush(f); end

julia> open(`cat`, "w") do f; close(f); flush(f); end
ERROR: IOError: stream is closed or unusable
```

^ Do we have any tests like these?

2020-03-30 14:46 UTC, StefanKarpinski commented
If it works on all built-in IO types, I'll be happy (a little surprised, but happy), but I've definitely seen external IO types that would break with this change, e.g. TranscodingStreams.

2020-03-30 17:14 UTC, JeffBezanson commented
I'm also fine with this in theory but I'm worried about breakage. Why not add a call to `flush` in `close(::IOStream)` instead?

2020-03-30 17:16 UTC, JeffBezanson commented
Ah, in fact ios_close already calls ios_flush internally, it just doesn't report the error.

2020-03-30 20:56 UTC, Keno commented
> Ah, in fact ios_close already calls ios_flush internally, it just doesn't report the error.

Right, so the question is should close throw an error instead. And when we talked about it, the sense was that `close` should not error, which is why I'm proposing this instead.

The point is at some point, we should throw an error here, because otherwise subsequent code assumes that the file operation was complete, which may not be the case.

2020-03-30 21:19 UTC, JeffBezanson commented
It seems strange to me to only throw the error if you use the `open(::Function,...)` form. It also conflicts with having a more general `with`-style construct --- is the destructor/finalizer for a file `close`, or `flush` plus `close`? What do other systems do in this situation?

2020-03-30 21:21 UTC, Keno commented
`fclose` returns an error code, but not sure if anybody ever checks it.

2020-03-30 22:01 UTC, JeffBezanson commented
`close` methods in Java and Python throw errors in this kind of situation, so I think it would be simpler and more consistent to propagate the error from the existing `flush` call inside `close`.

2020-03-31 18:09 UTC, StefanKarpinski commented
Agree. If write stuff and close a file and it didn't get successfully written to the file, I want an error.

2020-03-31 19:17 UTC, JeffBezanson commented
If `flush` fails inside close, should we continue closing the file anyway, or leave the file open? My gut reaction is that it's more predictable to close it no matter what, but that does mean you could lose buffered data.

2020-03-31 19:32 UTC, StefanKarpinski commented
Agree: close is better. If there's an error, you can't really assume the resulting file is in any kind of recoverable state anyway.

2020-04-06 17:57 UTC, closed without merging