SparseArrays: Allow division by diagonal matrices
JuliaLang/julia pull request #35533
Opened 2020-04-20 15:46 UTC by eschnett

2020-04-20 18:55 UTC, dkarrasch commented on stdlib/SparseArrays/src/linalg.jl
> +    rdiv!(LinearAlgebra.copy_oftype(A, T), A, D)
CI suggests there is no such `rdiv!` method...

2020-04-20 18:57 UTC, dkarrasch commented on stdlib/SparseArrays/src/linalg.jl
> +    T = Base.promote_op(/, eltype(D), eltype(A))
```suggestion
    T = Base.promote_op(/, eltype(A), eltype(D))
```

2020-04-20 19:49 UTC, eschnett commented on stdlib/SparseArrays/src/linalg.jl
> +    T = Base.promote_op(/, eltype(D), eltype(A))
Done. Thanks.

2020-04-21 07:18 UTC, dkarrasch requested changes
The 2-arg `*div!`s should work, at least they exist.

2020-04-21 07:18 UTC, dkarrasch commented on stdlib/SparseArrays/src/linalg.jl
> +    ldiv!(LinearAlgebra.copy_oftype(A, T), D, A)
```suggestion
    ldiv!(D, LinearAlgebra.copy_oftype(A, T))
```

2020-04-21 07:18 UTC, dkarrasch commented on stdlib/SparseArrays/src/linalg.jl
> +    rdiv!(LinearAlgebra.copy_oftype(A, T), A, D)
```suggestion
    rdiv!(LinearAlgebra.copy_oftype(A, T), D)
```

2020-04-22 00:21 UTC, eschnett commented on stdlib/SparseArrays/src/linalg.jl
> +    ldiv!(LinearAlgebra.copy_oftype(A, T), D, A)
Thanks. Done.

2020-04-22 18:13 UTC, dkarrasch commented
S**t, I thought I wrote a long comment, but must have forgotten to push the button. To make the long story short, the left-division is currently working nicely, there is no need for an additional method. The right-division is not too bad in that it doesn't fall back to generic dense methods or whatever, but can be improved still
```julia
using SparseArrays, LinearAlgebra, BenchmarkTools, Test

A = sprand(10000,10000,0.1);
D = Diagonal(rand(10000));

function mydiv(A::AbstractMatrix, D::Diagonal)
    rdiv!(typeof(oneunit(eltype(A))/oneunit(eltype(D))).(A), D)
end

@test A/D ≈ mydiv(A, D)
@btime mydiv($A, $D);
@btime $A / $D;
@btime $D \ $A; # for comparison with mydiv
```
My function `mydiv` is meant to be the relaxation of

https://github.com/JuliaLang/julia/blob/ac825137958bf0bd4cfd61b3722622c8880146c0/stdlib/LinearAlgebra/src/diagonal.jl#L486-L487

to `AbstractMatrix`es. I'd suggest to relax that method, remove the newly added methods, and keep the tests, maybe adding further sparsity tests.

2020-04-22 18:39 UTC, eschnett commented
@dkarrasch Do you suggest to provide a generic method for `AbstractMatrix` that handles division by diagonal matrices? It seems dangerous to apply a point-wise operation to them since we know nothing about their internal storage. We can't guarantee that the result of a division by a diagonal matrix can be stored in their internal representation. For example, this function would fail if called for `UniformScaling`.

Should we instead relax the existing division operator to include sparse matrices only?

2020-04-22 18:51 UTC, dkarrasch commented
> Do you suggest to provide a generic method for AbstractMatrix that handles division by diagonal matrices? 

Yes. Look at this one:

https://github.com/JuliaLang/julia/blob/ac825137958bf0bd4cfd61b3722622c8880146c0/stdlib/LinearAlgebra/src/diagonal.jl#L597-L598

If there is an issue with the underlying `ldiv!` for that specific array type, we'll get a `MethodError`, and I think that's just fine. IIRC, `UniformScaling` is not an `AbstractMatrix`. And this one _is_ called currently for the left-division of a sparse matrix by a `Diagonal`.

2020-04-23 04:03 UTC, eschnett commented
@dkarrasch Done.

2020-04-23 08:18 UTC, dkarrasch commented
Ok, my sincere apologies for the mess. Now we've got a method ambiguity. Apparently, there is a subtle reason for the different signatures of `ldiv!` and `rdiv!`, for why one can handle `AbstractMatrix` and the other is more specialized. So I hope we should be fine with adding
```julia
function (/)(A::AbstractSparseMatrixCSC, D::Diagonal)
    T = typeof(oneunit(eltype(A))/oneunit(eltype(D)))
    rdiv!(LinearAlgebra.copy_oftype(A, T), D)
end
```
to `SparseArrays` (and leaving the one in `diagonal.jl` unchanged compared to `master`).

Initially, my main point was that `D \ A` works just fine, so we don't need to change anything to allow for that. `A / D` also works, but has a little overhead due to the multiple `adjoints`, so we can improve that.

2020-04-23 08:24 UTC, dkarrasch requested changes
Sorry again for the back and forth, this time just a trivial comment on the tests, and I hope with my last suggestion we'll be all set.

2020-04-23 08:24 UTC, dkarrasch commented on stdlib/SparseArrays/test/sparse.jl
> +        @test Diagonal(b) \ copy(sA) == ldiv!(Diagonal(b), copy(sA))
No need for the copy, and I'd suggest so check for sparsity.
```suggestion
        @test Diagonal(b) \ sA == ldiv!(Diagonal(b), copy(sA))
        @test issparse(Diagonal(b) \ sA)
```

2020-04-23 08:24 UTC, dkarrasch commented on stdlib/SparseArrays/test/sparse.jl
> +        @test copy(sAt) / Diagonal(b) == rdiv!(copy(dAt), Diagonal(b))
same here...

2020-04-23 14:30 UTC, eschnett commented
@dkarrasch Done. Thanks for the suggestions; this is now a much better implementation.

2020-04-23 16:46 UTC, dkarrasch commented
@eschnett Ok, the tests look good now, but you still have the method ambiguity due to my own bold suggestion (sorry again). You'll need to undo the change in `LinearAlgebra/diagonal.jl`, and add https://github.com/JuliaLang/julia/pull/35533#issuecomment-618254702 to `SparseArrays/linalg.jl`. Then I'd expect this to pass tests.

2020-04-23 17:41 UTC, eschnett commented
Sorry, did not see your final comment earlier.

I didn't spot the method ambiguity when I ran the test suite locally.

2020-04-26 17:10 UTC, dkarrasch commented on stdlib/LinearAlgebra/src/diagonal.jl
> +    rdiv!((typeof(oneunit(eltype(D))/oneunit(eltype(A)))).(A), D)
whitespace
```suggestion
(/)(A::Union{StridedMatrix, AbstractTriangular}, D::Diagonal) =
    rdiv!((typeof(oneunit(eltype(D))/oneunit(eltype(A)))).(A), D)
```

2020-04-27 06:50 UTC, merged