Add a pointer to GPUs in parallel computing
JuliaLang/julia pull request #36043
Opened 2020-05-27 13:31 UTC by ViralBShah

cc @vchuravy @maleadt

2020-05-27 13:42 UTC, DilumAluthge requested changes

2020-05-27 13:42 UTC, DilumAluthge commented on doc/src/manual/parallel-computing.md
>  Julia supports three main categories of features for concurrent and parallel programming:
```suggestion
Julia supports four main categories of features for concurrent and parallel programming:
```

2020-05-27 16:01 UTC, vchuravy commented
I would not strongly differentiate between coroutines and multi-threading. Julia uses the language of tasks and coroutines and you should use channels alongside parallel execution. In essence multi-threading is an implementation detail, and the semantic components are `Tasks`.

2020-05-27 16:23 UTC, StefanKarpinski commented
But there are two different ways to start tasks: `@async` which creates a new task that will always run on the same core and `@spawn` which creates a new task that will potentially run on a different core. That's a fairly key distinction which surely should be mentioned here.

2020-05-27 19:07 UTC, ViralBShah commented
@vchuravy Can you review?

@StefanKarpinski Mentioning `@async` vs. `@spawn` here seems a bit too early, when neither have yet been described. But it definitely makes sense to do it in the chapters that follow.

2020-05-27 19:51 UTC, jonas-schulze commented on doc/src/manual/parallel-computing.md
> +    are an example of such an abstraction. On the other hadn, packages like [`MPI.jl`](https://github.com/JuliaParallel/MPI.jl) and
```suggestion
    are an example of such an abstraction. On the other hand, packages like [`MPI.jl`](https://github.com/JuliaParallel/MPI.jl) and
```

2020-05-28 00:43 UTC, StefanKarpinski commented
My point is that having those two primitive s means that concurrency and threading are different concepts in the language.

2020-05-28 13:10 UTC, merged