macOS lazily saves the AVX512 context
JuliaLang/julia pull request #36330
Opened 2020-06-17 18:31 UTC by YingboMa

Fix #36329

2020-06-17 18:37 UTC, yuyichao requested changes

2020-06-17 18:37 UTC, yuyichao commented on src/processor_x86.cpp
> +#ifdef OS_DARWIN
`_OS_DARWIN_` i believe.

2020-06-17 18:37 UTC, yuyichao commented on src/processor_x86.cpp
> +    // Darwin lazily saves the AVX512 context on first use
also https://github.com/apple/darwin-xnu/blob/a449c6a3b8014d9406c2ddbdc81795da24aa7443/osfmk/i386/fpu.c#L174 or whatever appropriate direct document from apple.

2020-06-17 19:01 UTC, yuyichao approved these changes
LGTM. Do note that since it seems that loop vectorizer might be involved there'll still be other issues that you'll need to hack around until it is moved to the LLVM level.

2020-06-17 19:41 UTC, vchuravy commented
We should also back-port the llvm patch.

2020-06-17 22:27 UTC, Keno commented
This seems like a terrible idea on their part, but I guess it's what we have to do.

2020-06-17 22:35 UTC, yuyichao commented
IIUC it sounds like they are reimplementing `xsave`. It's pretty unfortunate that they deviate from the intel document...

I assume it also means that running a darwin vm that doesn't support avx512 on hardware that does is basically unsupported then... (which is probably something that apple couldn't care less about...)

2020-06-18 19:42 UTC, merged

2020-06-18 19:42 UTC, Keno commented
I doubt this is the last we've heard along these lines, but let's try this for now, since it matches LLVM.

2020-09-09 17:24 UTC, YingboMa commented
Is it possible to back port this change?