LinearAlgebra.givens with unitful arguments
JuliaLang/julia pull request #36430
Opened 2020-06-25 15:08 UTC by KlausC

Solves #36429

2020-06-25 15:13 UTC, StefanKarpinski commented
Thanks! Would be great to add the example from the issue as a test.

2020-06-25 15:20 UTC, KlausC commented
The example is from external package `Unitful`. Is there a type `T` in `Base` with `one(T) != oneunit(T)`?

2020-06-25 15:25 UTC, StefanKarpinski commented
Right. Sometimes we'll mock up very minimal types for this kind of testing. Not sure if we have one already...

2020-06-25 15:46 UTC, KlausC commented
> Right. Sometimes we'll mock up very minimal types for this kind of testing. Not sure if we have one already...

I did not find one. Will make a minimal type similar to `Unitful.Quantity` in module `TestGivens`.

2020-06-25 18:04 UTC, StefanKarpinski commented
This seems pretty simple, but it would be good if someone who actually knows what a Givens rotation is took a look. @andreasnoack, could you review?

2020-07-01 10:26 UTC, dkarrasch reviewed
LGTM, except for one minor style comment.

2020-07-01 10:26 UTC, dkarrasch commented on stdlib/LinearAlgebra/src/givens.jl
> +    c, s, r * oneunit(T)
Nitpicking, but the above methods do have a `return` statement.
```suggestion
    return c, s, r * oneunit(T)
```

2020-07-01 13:46 UTC, andreasnoack approved these changes

2020-07-01 14:24 UTC, dkarrasch approved these changes

2020-07-02 12:19 UTC, dkarrasch requested changes
There is some nasty method ambiguity error, so this cannot be merged as is, unfortunately. It's a strange error, because it seems to relate to multiplication methods defined in the tests, not in the code. Would it be possible to reformulate the MockUnitful tests in terms of Furlongs?

2020-07-02 14:21 UTC, KlausC commented
> Would it be possible to reformulate the MockUnitful tests in terms of Furlongs?

Unfortunately not, because `Furlong` does not have the property that `f / oneunit(f) isa Union{AbstractFloat,Complex{<:AbstractFloat}}` for `f::Furlong`, which is needed to call `givensAlgorithm`.

The fix assumes, that `f / oneunit(f)` strips off the unit from the type of `f`; there seems no other way inside `Base` to accomplish that :-1: . (I could imagine something like `stripunit` as a companion of `oneunit` to do that).

The detected ambiguities are an insane interaction of `Furlong` and `MockUnitful`. I change the definition of `MockUnitful` to get rid of it. If they are detected or not seems to be a timing problem, when test-ambiguities is still working while test-LinearAlgebra is executed.

2020-07-03 09:34 UTC, dkarrasch approved these changes

2020-07-03 09:34 UTC, merged

2021-03-01 17:54 UTC, stevengj commented
> Unfortunately not, because `Furlong` does not have the property that `f / oneunit(f)` isa `Union{AbstractFloat,Complex{<:AbstractFloat}}` for `f::Furlong`, which is needed to call `givensAlgorithm`.

Arguably this was a bug in the `Furlong` test type, which should have been fixed rather than defining yet another unitful test type.   It's fixed in #39852.