Need `LinearAlgebra` to use `I`
JuliaLang/julia pull request #36687
Opened 2020-07-16 01:39 UTC by likanzhan

Need `LinearAlgebra` to use `I`

2020-07-16 15:35 UTC, StefanKarpinski commented
Can you add blank lines after each of these since that's how the REPL prints them? (Note that this breaks the doctests, so you may want to make sure it doesn't do that.)

2020-07-16 17:38 UTC, StefanKarpinski requested changes
No blank lines above the first prompt. In general: take a look at how the surrounding code and/or docs look and emulate it.

2020-07-16 17:38 UTC, StefanKarpinski commented on stdlib/SparseArrays/src/sparsematrix.jl
> +
```suggestion
```

2020-07-16 17:38 UTC, StefanKarpinski commented on stdlib/SparseArrays/src/sparsematrix.jl
> +
```suggestion
```

2020-07-16 17:38 UTC, StefanKarpinski commented on stdlib/SparseArrays/src/sparsematrix.jl
> +
```suggestion
```

2020-07-16 17:38 UTC, StefanKarpinski commented on stdlib/SparseArrays/src/sparsematrix.jl
> +
```suggestion
```

2020-07-16 17:38 UTC, StefanKarpinski commented on stdlib/SparseArrays/src/sparsematrix.jl
> +
```suggestion
```

2020-07-16 21:49 UTC, Keno commented
Would it be better to just have SparseArrays re-export `I`?

2021-03-31 19:36 UTC, StefanKarpinski commented
Let's see if tests pass these days.

2021-03-31 20:30 UTC, KristofferC commented
You need to rebase it since the buildbots don't run on the merge commit.

2021-04-20 19:22 UTC, vtjnash commented
We already do this, via `make.jl`, so if we think it should be in each example, we should remove it from the global config:
```
DocMeta.setdocmeta!(
    SparseArrays,
    :DocTestSetup,
    maybe_revise(:(using SparseArrays, LinearAlgebra));
    recursive=true, warn=false,
)
```

I'm inclined to instead reject this PR, but I'm not opposed to it if others feel it is reads better.

2021-05-04 19:03 UTC, closed without merging