Sticky shell REPL mode
JuliaLang/julia pull request #38646
Opened 2020-12-01 22:14 UTC by crstnbr

This PR makes the shell REPL mode sticky similar to the package manager REPL mode. This has been requested by many (see below).

Issues: #6320, #19202, #31910
Previous PR: #33174 (should probably be closed as it is outdated/not functional)

* Functionality is there.
* I have fixed the tests, that is I have added backspace commands to leave the shell mode after every individual test. This implicitly tests the stickiness of the REPL mode. Locally, all tests pass except for one: strangely, the test block (line 828 in REPL/test/repl.jl)
```julia
    # Test stream mode
    p = open(`$exename --startup-file=no -q`, "r+")
    write(p, "1\nexit()\n")
    @test read(p, String) == "1\n"
```
which seems to be completely **unrelated to this PR** fails
```julia
Test Failed at /Users/crstnbr/compiled/julia/usr/share/julia/stdlib/v1.6/REPL/test/repl.jl:832
  Expression: read(p, String) == "1\n"
   Evaluated: "\e[0m\e[0m1\n\e[0m" == "1\n"
ERROR: LoadError: LoadError: There was an error during testing
in expression starting at /Users/crstnbr/compiled/julia/usr/share/julia/stdlib/v1.6/REPL/test/repl.jl:787
in expression starting at /Users/crstnbr/compiled/julia/usr/share/julia/stdlib/v1.6/REPL/test/runtests.jl:3
ERROR: Package REPL errored during testing
```
If I manually run the test block above in the REPL (instead of `test REPL`) it works.... Any idea what's going on here?
* For some reason I had to change `@assert n_succeeded > 1200` to `@assert n_succeeded > 1100` (the threshold is 1183) in `generate_precompile.jl` for the build process to run through. A comment above that line says "adjust as needed" so I assume this is fine.

Would be great if someone could review!

2020-12-02 13:19 UTC, KristofferC requested changes
Didn't you break the precompile runner with this PR and that's why you get fewer precompile statements?

See https://github.com/JuliaLang/julia/blob/63ca5185f78863e226a2f55d089fac403f714651/contrib/generate_precompile.jl#L43

2020-12-02 17:31 UTC, rfourquet commented
I just would like to link to #33875, which also offers a way to get a sticky shell mode. These are not "competing" PRs, but can be considered in tandem for a decision.

2020-12-02 19:54 UTC, crstnbr commented
> Didn't you break the precompile runner with this PR and that's why you get fewer precompile statements?
> 
> See
> 
> https://github.com/JuliaLang/julia/blob/63ca5185f78863e226a2f55d089fac403f714651/contrib/generate_precompile.jl#L43

Ah, I see! I committed a fix (which gives 1269 > 1200 precompile statements).

2020-12-03 19:42 UTC, JeffBezanson commented
Triage approves.

2020-12-03 23:51 UTC, merged