Allow scalars to be assigned to 1-element array
JuliaLang/julia pull request #39725
Opened 2021-02-18 04:41 UTC by BioTurboNick

`a[1:1, 2:2] = 5` currently errors because `setindex_shape_check` throws an error.

Changing the check to let an item through when the length of the destination is 1 allows setindex to work.

```
a = [1 2; 3 4]
a[1:1, 2:2] = 9
a[1:1, 1:2] = 9 # throws
```

Allowing this makes it easier to work with mixed arrays and scalars. Looking to see if any tests fail.

2021-02-19 08:17 UTC, BioTurboNick commented
Hmm, found one bug here:
```
o = fill("test", 1)
o[1] = "foo"
o[1:1] = "bar" # throws because it is trying to assign chars rather than the whole string
```

2021-02-20 04:31 UTC, mbauman commented
Hunh, I’ll have to look at this more closely. I could’ve sworn we limited iteration to `AbstractArray` sources.

2021-02-20 14:59 UTC, BioTurboNick commented
> Hunh, I’ll have to look at this more closely. I could’ve sworn we limited iteration to `AbstractArray` sources.

I guess strings are a bit weird because they define length, can be indexed, etc. Looking through Discourse it seems it's been that way for a long time, though also a common source of confusion.

Wonder if it would make sense / be possible to have a macro that opted a block out of treating strings as iterables? (I know very little about macros though.)

2021-02-22 15:09 UTC, mbauman commented
Ah, ok, phew, iteration _is_ restricted to `AbstractArray` RHS's (it's done in that shape check).  It's [documented](https://docs.julialang.org/en/v1/manual/arrays/#man-indexed-assignment) as:

> If any index `I_k` selects more than one location, then the right hand side `X` must be an array with the same shape as the result of indexing `A[I_1, I_2, ..., I_n]` or a vector with the same number of elements.

That should probably be written as "If any index `I_k` _has more than 0 dimensions_."

I don't think we should add a special case for a one-element (but not zero-dimensional) slice here.  Indexing like `A[1:1]` doesn't drop back down to a scalar value.  This is just the inverse — assigning to `A[1:1]` is assigning _to an array_ and thus you _need an array_ for that to work.  The way to assign scalars _to an array_ is through broadcasting, which is where we've jammed this sort of <abbr title="Do What I Mean">"DWIM"</abbr> dimension matching.

2021-02-22 15:18 UTC, mbauman requested changes
For a bit of history here, see #26347.  _If_ we're going to do this, (and I don't think we should), we need to do this more comprehensively than just whitelisting `AbstractString` using something like the infrastructure of [`_iterable`](https://github.com/JuliaLang/julia/blob/5a062fa65e5adbe78b3a2f3803af9fd70aa9f5e3/base/multidimensional.jl#L665-L666) (which treated all non-AbstractArrays as "scalar" — this was the behavior before #26347) or `broadcastable`.

2021-02-22 16:23 UTC, BioTurboNick commented
Okay, good perspective. I'll look at those.

2021-02-22 16:41 UTC, mbauman commented
I should also just say that the concatenation code was the _worst_ to update because it _so heavily_ depended upon this old behavior.  So I'm not surprised you're feeling this pain and would like to to go back to the way it was.  When I said we'd shoved all this sort of dimension-matching stuff into broadcast that's not entirely true.  It's also in concatenation and `mapslices`.

2021-02-22 20:42 UTC, BioTurboNick commented
Alright, I'm convinced by that reasoning. Thanks!

2021-02-22 20:42 UTC, closed without merging