Add cross references in subset related operator's docs.
JuliaLang/julia pull request #39750
Opened 2021-02-19 12:24 UTC by AtsushiSakai

I added cross references in subset related operator's docs to fix #22639.
I think adding cross references is a good idea to allows us to find the desired function easily.

2021-03-14 13:21 UTC, bicycle1885 requested changes
I think it would be better to quote operators in docstring.

2021-03-14 13:21 UTC, bicycle1885 commented on base/abstractset.jl
> +Here are some operators related to subset: [`issubset`](@ref)(⊆), [`⊈`](@ref).
```suggestion
Here are some operators related to subset: [`issubset`](@ref) (`⊆`), [`⊈`](@ref).
```

2021-03-14 13:21 UTC, bicycle1885 commented on base/abstractset.jl
> +Here are some operators related to subset: [`issubset`](@ref)(⊆), [`⊊`](@ref).
```suggestion
Here are some operators related to subset: [`issubset`](@ref) (`⊆`), [`⊊`](@ref).
```

2021-03-14 13:39 UTC, mcabbott commented on base/abstractset.jl
> +Here are some operators related to subset: [`⊊`](@ref), [`⊈`](@ref).
I think the phrasing in many other docstrings is this, possibly with more explanation inserted:
```suggestion

See also [`⊊`](@ref), [`⊈`](@ref).
```

2021-03-22 05:39 UTC, AtsushiSakai commented
I addressed all review comments. The CI failures looks like unrelated this PR change:
```
Error in testset cmdlineargs:
Error During Test at /buildworker/worker/tester_linux32/build/share/julia/test/cmdlineargs.jl:209
  Test threw exception
  Expression: read(`$exename -t $cpu_threads -e $code`, String) == string(cpu_threads)
  failed process: Process(`/buildworker/worker/tester_linux32/build/bin/julia -Cnative -J/buildworker/worker/tester_linux32/build/lib/julia/sys.so --depwarn=error --check-bounds=yes -g1 --startup-file=no --startup-file=no --color=no -t 256 -e 'print(Threads.nthreads())'`, ProcessSignaled(11)) [0]
```

2021-04-03 12:44 UTC, simeonschaub approved these changes

2021-04-03 15:39 UTC, merged