allow pkgdir accept paths
JuliaLang/julia pull request #40839
Opened 2021-05-16 23:23 UTC by Roger-luo

I find it's quite often that when one uses `pkgdir` one actually wants to get the path of some subdir of the package directory, which as a result doing something like

```julia
joinpath(pkgdir(Foo), "src", "subdir")
```

this PR allows `pkgdir` to take a vararg `paths`, so if one wants to do something like above, can now just write

```julia
pkgdir(Foo, "src", "subdir")
```

and it preserves the original behaviour that you can still just put a module to get the root of a module path.

2021-05-17 04:18 UTC, johnnychen94 commented
might need to explain it in the docstring with appropriate compat note.

2021-05-17 20:50 UTC, Roger-luo commented
not sure which version this PR will be merged into, I currently mark compatibility for 1.7, but might need to update it to 1.8 it doesn't go into it. I'm not sure why there is ambiguity error, the implementation itself seems fine?

2021-05-17 22:47 UTC, IanButterworth requested changes
Great idea. Just a suggestion for the docstring

2021-05-17 22:47 UTC, IanButterworth commented on base/loading.jl
> +argument `paths` can be used to access subdirs of the module root.
```suggestion
Return the root directory of the package that imported module `m`,
or `nothing` if `m` was not imported from a package. Optionally further
path component strings can be provided to construct a path within the 
package root.

```julia
julia> pkgdir(Foo)
"/path/to/Foo.jl"

julia> pkgdir(Foo, "src", "file.jl")
"/path/to/Foo.jl/src/file.jl"
```

2021-05-17 23:20 UTC, IanButterworth commented
@Roger-luo it seems github suggestions don't play nicely with nested triple quotes. Needs a closing ``` on the example in the docstring

2021-05-18 01:01 UTC, giordano commented
>  it seems github suggestions don't play nicely with nested triple quotes. Needs a closing ``` on the example in the docstring

Use quadruple backticks for the suggestion block

2021-05-18 01:07 UTC, StefanKarpinski commented
This is very handy and reads nicely too 👍🏻

2021-05-19 02:23 UTC, IanButterworth approved these changes

2021-05-19 02:28 UTC, merged

2021-05-19 02:28 UTC, IanButterworth commented
Nice!