Remove confusion between libsuitesparse the C library and SuiteSparse the stdlib
JuliaLang/julia pull request #40920
Opened 2021-05-23 02:35 UTC by ViralBShah

Fix #40854

2021-05-23 19:35 UTC, staticfloat requested changes
Good start; we'll also need to fix:

* https://github.com/JuliaLang/julia/blob/4ecbc16df572f54d3f05d872f13f31f9e6abc7ef/contrib/refresh_checksums.mk#L22
* https://github.com/JuliaLang/julia/blob/bb5b98e72a151c41471d8cc14cacb495d647fb7f/base/Makefile#L221-L228
* https://github.com/JuliaLang/julia/blob/bb5b98e72a151c41471d8cc14cacb495d647fb7f/Make.inc#L48 (and many other places that use `SUITESPARSE`)
* https://github.com/JuliaLang/julia/blob/a08a3ff1f957f6bd570ff5756dff4290eb6f43da/Makefile#L174

2021-05-23 19:35 UTC, staticfloat commented on deps/libsuitesparse.mk
> +$(eval $(call bb-install,libsuitesparse,SUITESPARSE,false))
```suggestion
$(eval $(call bb-install,libsuitesparse,LIBSUITESPARSE,false))
```

2021-05-24 00:13 UTC, ViralBShah commented
How does it look now? The only place where it is now SUITESPARSE (instead of LIBSUITESPARSE) is in `stdlib/SuiteSparse.version`.

Can you see if `stdlib/Makefile` should use LIBSUITESPARSE? I wasn't quite sure.

2021-05-24 00:27 UTC, ViralBShah commented
We really do sprinkle this stuff all over the place!

2021-05-25 04:57 UTC, staticfloat approved these changes

2021-05-25 12:10 UTC, ViralBShah commented
Should we change the checksumming files to also use `libsuitesparse`?

2021-05-25 12:21 UTC, ViralBShah commented
I thought these checksums are a problem with the SuiteSparse stdlib, and not the C library.

2021-05-25 12:27 UTC, KristofferC commented
Yes, the last commit doesn't look right, those are indeed for the stdlib.

2021-05-25 12:30 UTC, ViralBShah commented
I'm reverting the last commit.

2021-05-25 13:11 UTC, ViralBShah commented
Is this possibly some kind of disk full thing?

```
/usr/local/bin/gtar: write error
Makefile:421: recipe for target 'binary-dist' failed
make: *** [binary-dist] Error 2
```

2021-05-25 13:13 UTC, KristofferC commented
That feels likely to me.

2021-05-25 13:51 UTC, merged

2021-05-25 16:51 UTC, staticfloat commented
Without the last commit, if you try to refresh the suitesparse checksums you don't get the proper packing; you get an empty `deps/checksums/libsuitesparse` file and a bunch of `deps/checksums/SuiteSparse*.tar.gz/` folders.  This is because there's now a name mismatch between the make variable LIBSUITESPARSE and the files on-disk.  My commit was an attempt to fix that, but clearly I messed something up.  I'll open a new PR.

2021-05-25 17:58 UTC, ViralBShah commented
Ok. Sorry about that. I was mainly comfortable merging since it was green. Thanks for the new pr