fix #40814, fix type inference regression introduced in #40379
JuliaLang/julia pull request #40987
Opened 2021-05-28 13:38 UTC by aviatesk

Fixes the inference regression, while retaining the cases addressed by
<https://github.com/JuliaLang/julia/pull/40379>.

The same `Type`-name comparison pass (i.e. a branch of `isa(c, DataType) && t.name === c.name`)
can lead to more accurate result by recursive comparison than `isType`
check pass (i.e. a branch of `isType(t)`), and preferring the former
over the latter fixes the regression.

But just swapping the branch will lead to <https://github.com/JuliaLang/julia/issues/40336>,
and so this PR also implements additional check to make sure `type_more_complex`
still detects a single-level nesting correctly (especially, the `tt === c` parts).

2021-05-31 10:54 UTC, aviatesk commented
@nanosoldier `runtests(ALL, vs = ":master")`

2021-06-01 01:42 UTC, nanosoldier commented
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40987#issuecomment-851406215) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/c3490c0_vs_97aa831/report.md). cc @maleadt

2021-06-01 02:40 UTC, aviatesk commented
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

2021-06-01 13:02 UTC, nanosoldier commented
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40987#issuecomment-851763464) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/28b3e7b_vs_27aaadb/report.md). cc @christopher-dG

2021-06-01 13:10 UTC, aviatesk commented
The benchmark results look okay to me.

2021-06-02 16:48 UTC, vtjnash requested changes
This appears to get the check exactly backwards: while the test in this function is supposed to find a reason that the recursion is safe, this instead looks if the recursion matches a known reason it is unsafe. As such, this would seem to be neither total nor transitive.

2021-06-03 17:14 UTC, aviatesk commented
> while the test in this function is supposed to find a reason that the recursion is safe, this instead looks if the recursion matches a known reason it is unsafe. As such, this would seem to be neither total nor transitive.

Hmm, I'm not quite sure what you mean by this. Why should inference always be conservative when seeing `Type` in a recursion ? 

The comment of `limit_type_size` says:
https://github.com/JuliaLang/julia/blob/8535b8c4d7f4179f7b13a04f16074a2446dda3ac/base/compiler/typelimits.jl#L15-L18

and I'm not sure why we should give up the comparison pass (i.e. `elseif isa(c, DataType) && t.name === c.name`) when `isType(t)`.
Even if we go with the comparison pass first, eventually a single-level complexity difference (e.g. `Type{Type{Int}}` vs. `Type{Int}` will be caught by newly introduced check `tt === c` and more level complexity difference will be caught by `isType(tt)` as before.
Maybe you mean the `tt === c` part is too ad-hoc to be safe in all the possible cases ?

2021-06-03 18:05 UTC, vtjnash commented
We could delete the case for Type entirely, but we cannot move it without re-introducing the previous bug that PR fixed. The question is mainly which rule we like better. The implementation of `_totuple` currently uses the `tuple_type_tail` function, which we probably should deprecate, as it is causing `_totuple` to make inaccurate subtyping claims. I haven't yet been able to find a better formulation however, so we might need better compiler support first for `Core._apply`.

2021-06-28 04:39 UTC, closed without merging