RFC: remove deprecatoin of getproperty on Pair
JuliaLang/julia pull request #41027
Opened 2021-05-31 15:24 UTC by KristofferC

This causes hundred+ of packages (looking at https://github.com/JuliaLang/julia/pull/39448#issuecomment-771338937) to start giving deprecation warnings by default. The motivation for the feature (https://github.com/JuliaLang/julia/issues/25750) also seems highly speculative so making something disruptive based on that doesn't feel like it is a good tradeoff.

2021-05-31 15:30 UTC, vtjnash requested changes
It is not necessary to delete the deprecation. It is why we have deprecations, particularly for packages that are buggy.

2021-05-31 15:43 UTC, KristofferC commented
>  It is not necessary to delete the deprecation. It is why we have deprecations, particularly for packages that are buggy.

Please address the comment in the OP; it is never claimed that it is a necessity. It is claiming that the annoyance it brings for users is not worth the benefit it provides. That trade-off has to always be considered when implementing something, no matter if it is internal or not.

2021-06-01 18:07 UTC, simeonschaub commented
Would just removing the `force=true` be a reasonable compromise? That way, it would only show up in tests, not regular usage. We don't document the internal fields of `Pairs` anywhere, so I don't think a deprecation here is unreasonable.

2021-06-18 08:27 UTC, KristofferC commented
We don't document almost any fields and there is still no deprecation warning when accessing them. And the whole point is that

> We don't document the internal fields of Pairs anywhere, so I don't think a deprecation here is unreasonable

means there is no need to add a deprecation warning. It is completely arbitrary why this specific field has a deprecation warning and now e.g. PkgEval logs are spammed with this.

2021-06-18 08:42 UTC, simeonschaub commented
Can PkgEval just disable deprecation warnings in tests?

> means there is no need to add a deprecation warning.

So you think this should just be an error? The problem is that this would be quite disruptive, since a lot of packages rely on this internal detail.

2021-06-29 21:23 UTC, KristofferC commented
> So you think this should just be an error?

No, I think nothing should be done. Just like in https://github.com/JuliaLang/julia/pull/41018.

2021-06-29 22:14 UTC, vtjnash commented
How does this compare to #41018? We can restore those named bits if you want, I was probably going to bring them back eventually via compiler features anyways. That contrasts to this PR, where we plan to make this go away permanently in the next release.

2021-06-30 11:20 UTC, KristofferC commented
> where we plan to make this go away permanently in the next release.

Are we?

https://github.com/JuliaLang/julia/issues/25750#issuecomment-687849563

https://github.com/JuliaLang/julia/issues/25750#issuecomment-360641204

https://github.com/JuliaLang/julia/issues/25750#issuecomment-360640899

etc.

2022-05-17 11:01 UTC, closed without merging