fix #40814, improve type stability of `_totuple`
JuliaLang/julia pull request #41074
Opened 2021-06-03 16:48 UTC by aviatesk

Replaces #40987, as suggested by #40814.

We can simply add an annotation to force the return type to be propagated to a caller,
even when inference gives up anywhere in recursed calls.

2021-06-03 17:59 UTC, vtjnash requested changes
`nothing` is a valid iterator state, and therefore can't be ignored. Please remove that part of the change.

2021-06-03 18:06 UTC, aviatesk commented
Right. Done.

2021-06-04 20:23 UTC, simeonschaub approved these changes
LGTM

2021-06-06 07:33 UTC, merged

2021-07-19 10:01 UTC, KristofferC commented
This looks like it already is on the 1.7 branch so removing backport label.
https://github.com/JuliaLang/julia/blame/release-1.7/base/tuple.jl#L330-L334