An API for unsafe_store!-ing GC-managed objects
JuliaLang/julia pull request #41217
Opened 2021-06-13 22:42 UTC by tkf

Accessing pointer representation of mutable objects in a GC-compatible manner would be highly useful. Motivating examples include:

* [Completing `StructArrays.MArray`'s `setindex!` implementation](https://github.com/JuliaArrays/StaticArrays.jl/blob/c29a9e23b541eb0ea5f67ebbb814a01c6c9a2bc0/src/MArray.jl#L90-L103)
* Aligned and/or padded allocation of a group of mutable objects (for optimizing parallel mutation). It can be done by storing immutable struct in a vector (e.g., [RecordArrays.jl](https://github.com/tkf/RecordArrays.jl)).
* Shuffling heap allocating objects in vectors using SIMD instructions. Useful for, e.g., radix sort.

As a possible solution, this PR tries to implement the following experimental API:

>     Experimental.gc_compatible_pointer(value) -> (handle, ptr::Ptr{Cvoid})
>
> Return a pointer `ptr` of a `value` that can be stored into locations of GC-managed object using `unsafe_store!(_::Ptr{Ptr{Cvoid}}, ptr)`.  The caller is responsible for preserving the opaque object `handle` during `unsafe_store!`.
>
> This is equivalent to `value -> (value, pointer_from_objref(value))` for mutable `value`s.  However, this function also works when `value` is an immutable type. See also: [`unsafe_store!`](@ref), [`GC.@preserve`](@ref)
>
> **Examples**
> ```julia
> julia> handle, ptr = Base.Experimental.gc_compatible_pointer(Some(1));
>
> julia> xs = Any[nothing];
>
> julia> GC.@preserve xs handle begin
>            unsafe_store!(Ptr{Ptr{Cvoid}}(pointer(xs, 1)), ptr)
>        end;
>
> julia> xs[1]
> Some(1)
> ```

2021-06-14 02:02 UTC, vtjnash requested changes
This appears to explicitly mark the "gc-compatible-pointer" as something the GC should not track, which is not something that can be made legal. You would need to start from something like my RefField PR and Keno's Mutable Immutables Julep, and then explore changes to the conceptual object model that permits interior pointers.

2021-06-14 02:17 UTC, tkf commented
> This appears to explicitly mark the "gc-compatible-pointer" as something the GC should not track, which is not something that can be made legal.

That's why the docstring explicitly says "*The caller is responsible* for preserving the opaque object `handle` during `unsafe_store!`." Teaching GC to follow the pointer `ptr` is not the purpose of the API. Wouldn't it be enough for writing correct programs if the user understands the invariance one needs to manually maintain?

2021-06-14 02:51 UTC, vtjnash commented
There doesn't appear to be any GC reference to `handle` returned from that function, just an undef pointer that possibly used to be an object, so there is nothing legal you can do with that pointer (and particularly not observe it or let the GC see it ever again) as the creation of that pointer was unexpected in the Julia compiler object model. It sounds mostly like you want `x = Ref(value); GC.@preserve x ...`?

2021-06-14 05:38 UTC, tkf commented
> It sounds mostly like you want `x = Ref(value); GC.@preserve x ...`?

I needed `x = Ref{Any}(value)` to "force" heap-allocation of `value` (when `value` is an immutable):

```julia
handle = Ref{Any}(Some(1))
xs = Any[nothing];
GC.@preserve xs handle begin
    ptr = unsafe_load(Ptr{Ptr{Cvoid}}(pointer_from_objref(handle)))
    unsafe_store!(Ptr{Ptr{Cvoid}}(pointer(xs, 1)), ptr)
end
```

But I thought you mentioned that this won't work in the earlier discussion in slack? (Though my example there included other things.)

> just an undef pointer

I thought I was essentially just doing

```julia
ref = Ref{Some{Any}}(Some{Any}(0))
ref[] = Some{Any}(value)  # happening in the ccall
ref[]
```

Could you point out main missing pieces in my code? Also, since this can be implemented in a plain Julia code, how can this break any rules (if implemented correctly)?

(Just as a sanity check, I included a llvm pass test that the GC "recognizes" the object by inserting a safepoint in the test and see if it creates a GC frame. Of course, it doesn't prove any kind of correctness but this makes me more curious in which way my code is broken.)

> the creation of that pointer was unexpected in the Julia compiler object model

If the construction of the `handle` object is the only problem, I can imagine implementing this as

```julia
handle = _Handle{value}
ptr = ccall(:jl__gc_compatible_pointer, UInt, (Any,), handle)
return (handle, Ptr{Cvoid}(ptr))
```

with an appropriate `jl__gc_compatible_pointer` that does something like `unsafe_load(Ptr{Ptr{Cvoid}}(pointer_from_objref(handle)))` but for an immutable `handle`. (Additionally, I wonder if we need a "dummy" function that does nothing but interpreted as an escape for AllocOpt.)

Does this solve the problem?

2021-06-14 06:11 UTC, vtjnash commented
`Ref{Any}` is okay to work with, but it is forbidden to use this object with `unsafe_store!`. Only `isbits` objects are allowed to violate that part of the Julia object model and operate on a Julia object. So that type mostly exists for passing objects to C. This probably shouldn't be a github discussion, but the issue is also with the `GC.@preserve`: this declares the objects are valid until that ends, but you are prohibited from allowing these objects to escape that region of code annotation through any of the `unsafe` calls. But there is no way to limit their lifetime to that block in Julia.

2021-06-14 09:05 UTC, tkf commented
> you are prohibited from allowing these objects to escape that region of code annotation through any of the `unsafe` calls

Why is this? Is this because the compiler cannot insert the proper write barrier? (actually, I forgot about the issue with write barrier until now...)

Can the currently proposed API work if `@julia.write_barrier` is also exposed at Julia level?

> This probably shouldn't be a github discussion

Do you prefer Discourse?

2021-06-15 18:44 UTC, yuyichao commented
1. The new API introduced in this PR (getting a pointer that's protectable) is already possible and already used (See `cconvert` and `unsafe_convert` for `Ref{Any}`) so it's not really necessary.
2. Exposing write barrier to julia code is simply impossible without major compiler change. (You don't have any control on the code surrounding the load. The compiler is currently free to insert a GC safepoint anywhere and does do that in many cases and a GC safepoint between the store and the write barrier is invalid). Detailed proposal of how to introduce such a mode with more control to the controller is welcome but it won't be easy.
3. As such any api that involves modifying the heap cannot possibly involve only pointers, it must have access to the original objects. Because of that, the julia API should just take the value to be stored as an object rather as a pointer. There are a few different possibilities for how to specify the slot but in many cases it should be either an array or a field reference.

2021-06-15 19:15 UTC, closed without merging

2021-06-15 22:40 UTC, tkf commented
Thanks for the explanation.

> 3\. Because of that, the julia API should just take the value to be stored as an object rather as a pointer. (edit: i.e. getting a pointer from the object to be stored shouldn't be part of that API anyway...)

One of my interests was to use CAS of an element of an array. This would require accessing pointers at LLVM IR level ATM. But I suppose adding this into `@atomicreplace` directly is a much easier route than adding low-level constructs for getting the pointers and inserting proper write barriers.

2021-06-16 13:54 UTC, yuyichao commented
That is correct. I'm just listing the fundamental requirements you need and I'm not saying that nothing can/need to be changed/added.
For example, for type stability and such, I'm all for adding a generic concrete reference type that refers to the parent object and identifies the slot to be stored by address, just that such a type will need to have an intrinsic that does everything at once instead of exposing those to julia code. Similarly, all other operations, atomics, whatever, will also have to use a codegen/runtime implementation rather than julia.