"fixed" static linking of libllvm and julia
JuliaLang/julia pull request #41276
Opened 2021-06-18 15:36 UTC by vogt31337

Hi,

I'm not a professional make file creator, so this will be a not optimal solution. But it worked in my case: I had the problem running julia together with python + numba. Which always died with a seg fault. Since julia's version of llvm isn't compatible with the versions of numba (llvmlite); Even when you use the exact same versions, at least on linux.
I tested: numba 0.53 + llvmlite 0.36 (libllvm10) and julia 1.6.1 -> seg fault.
Next try: numba 0.50.1 + llvmlite 0.33 (libllvm9 9.0.1) and julia 1.5.4 (libllvm9 9.0.1jl) -> seg fault.

Only solution, static compilation of julia 1.5.4 which is broken, but this pr fixed it for my setup (similar to #32665).

BR

2021-06-22 14:30 UTC, friederikemeier commented
Thank you so much for this fix!

2021-06-27 14:42 UTC, ViralBShah commented
I believe we want this perhaps to be controlled by a build flag and not change this globally for everyone.

cc @staticfloat @vchuravy

2021-06-27 16:58 UTC, vchuravy commented
This will break quite a few Julia packages such as LLVM.jl and it's dependent's. Can I ask where you got Julia from/how you built it? We are using symbol versioning to prevent Julia's LLVM to conflict with a system LLVM, but I have seen other build configurations ignoring the necessary flags.

2021-06-27 16:59 UTC, vchuravy requested changes, later dismissed
There a users who depend on the dynamic library built so I don't think we can do this generally.

2021-06-27 17:01 UTC, vchuravy commented
In particular see #39390

2021-06-27 18:04 UTC, ViralBShah commented
Just adding a Do Not Merge label to caution against merging until the issues are discussed and sorted.

2021-06-27 18:09 UTC, yuyichao commented
> I believe we want this perhaps to be controlled by a build flag and not change this globally for everyone.

But this doesn't change things globally and only for `USE_LLVM_SHLIB=0`??

2021-06-28 17:08 UTC, staticfloat commented
If `USE_LLVM_SHLIB=0` is set, linking things as statically as possible makes sense to me.  I am curious as to why the symbol versioning didn't work though, as if we can retain linking dynamically, that will help with JLLs that expect `libLLVM.so` to exist.

2021-07-05 12:57 UTC, vogt31337 commented
> 
> 
> This will break quite a few Julia packages such as LLVM.jl and it's dependent's. Can I ask where you got Julia from/how you built it? We are using symbol versioning to prevent Julia's LLVM to conflict with a system LLVM, but I have seen other build configurations ignoring the necessary flags.

I've downloaded the versions from the homepage. Building I've done like described on the webpage / README files. 
Regarding symboling I thought this would be the case, but It wasn't. It simply seg faulted on starting.

>
>
> There a users who depend on the dynamic library built so I don't think we can do this generally.

Then trying `USE_LLVM_SHLIB=0` didn't work because of errors in the makefiles, hence this Merge request. I tried making it, so that this flag works again (so that it won't statically link generally). As stated earlier I'm no expert in make files. But these fixes worked for me and everything started without seg faulting.

I've used the quite old version 1.5.4 since our stuff is tested on this version. I think this should also work with the most recent version.

2021-07-07 12:31 UTC, vchuravy commented
> I've downloaded the versions from the homepage. Building I've done like described on the webpage / README files.
> Regarding symboling I thought this would be the case, but It wasn't. It simply seg faulted on starting.

Did you only try 1.5 or also 1.6? Can you post the seqfault?

2021-07-07 12:35 UTC, vchuravy reviewed
Does `llvm-config --system-libs` not include `pthread`?

2021-07-07 23:02 UTC, staticfloat commented
> Does `llvm-config --system-libs` not include `pthread`?

With the default BB build, it does not.  With this branch and `USE_LLVM_SHLIB=0 USE_BINARYBUILDER_LLVM=0`, I get the following:

```
$ ./usr/tools/llvm-config --system-libs
-lrt -ldl -lpthread -lm
```

2021-08-24 23:42 UTC, vtjnash commented
`-pthreads` is not needed on most platforms / compilers, though for some it is required

2021-08-24 23:48 UTC, merged