[Distributed] make finalizer messages threadsafe
JuliaLang/julia pull request #42240
Opened 2021-09-13 18:03 UTC by vchuravy

Partial revert of #41722

Fixes #42126

2021-09-13 20:40 UTC, Sacha0 commented
Tentatively marking backport-1.7, given the issue this patch targets has been observed on 1.7 previously.

2021-09-14 20:16 UTC, vtjnash requested changes, later dismissed
From CI, this hangs

2021-09-14 21:34 UTC, vtjnash commented
Looks like this would be vulnerable to a lock priority inversion deadlock situation

2021-09-14 22:04 UTC, vchuravy commented on stdlib/Distributed/src/messages.jl
> +    lock(w.msg_lock) do # TODO: lock_inversion?
```suggestion
    lock(w.msg_lock) do
```

2021-09-14 22:34 UTC, vchuravy commented on stdlib/Distributed/src/messages.jl
>          remote_do(del_clients, w, msgs)
```suggestion
        remote_do(del_clients, w, del_msgs)
```

2021-09-16 06:02 UTC, tkf commented
Would using a lock-free queue, stack, or "channel" for the messages help here? It sounds nice to not block and do minimal work inside a finalizer.

2021-09-16 15:33 UTC, vchuravy commented
> Would using a lock-free queue, stack, or "channel" for the messages help here? It sounds nice to not block and do minimal work inside a finalizer. (You can always `schedule` a task and so maybe this is not the issue/solution though.)

Yeah that would be a good optimization, but I don't think we have that in base right now?

But even with a lock-free queue, notifying the consumer is a problem.

2021-09-16 21:37 UTC, tkf commented
For a queue with notification, we can use a lock-free unbounded "channel" (aka dual queue). It's possible to implement lock-free(-ish) `push!` even when `popfirst!` can wait. One catch is that `push!` needs to be able to run `schedule` [^1] but it's already usable in the finalizer. I think I can create a PR for adding the queue in this: Scherer & Scott (2004) Nonblocking Concurrent Data Structures with Condition Synchronization https://link.springer.com/chapter/10.1007/978-3-540-30186-8_13

[^1]: It's also conceivable to use lock-free(-ish) queues inside the Julia runtime. It'd then make `push!` "more" lock-free.

2021-09-23 20:22 UTC, merged

2021-09-23 20:25 UTC, vchuravy commented
@KristofferC I would like to let this bake on master for a while before backporting. Should I remove the tag until a week or two from now?

2021-09-23 20:40 UTC, KristofferC commented
Sounds good.