Update mbedtls to final 2.x release
JuliaLang/julia pull request #42311
Opened 2021-09-19 09:19 UTC by jeremiahpslewis

2021-09-19 09:51 UTC, KristofferC commented
There seems to be a bunch of irrelevant commits on this branch. Perhaps rebasing on master would get rid of them.

2021-09-19 10:03 UTC, jeremiahpslewis commented
> There seems to be a bunch of irrelevant commits on this branch. Perhaps rebasing on master would get rid of them.

Yep, thanks for the nudge. Fixed.

2021-10-13 21:01 UTC, vtjnash requested changes
Looks like you need to submit a PR to build binaries for this (https://github.com/JuliaPackaging/Yggdrasil/tree/master/M/MbedTLS)

Then run `make -f ./contrib/refresh_checksums.mk mbedtls` in your Julia tree.

2021-10-17 11:55 UTC, jeremiahpslewis commented
Yggdrasil is done. https://github.com/JuliaRegistries/General/pull/46907

2021-10-17 12:01 UTC, jeremiahpslewis commented
I reran the hash update script, but there were no changes, think I already had this covered in an earlier commit (the second commit in the PR).

@vtjnash Think both points raised are ✅

2021-10-18 16:03 UTC, vtjnash approved these changes
I updated the stdlib version number and reran the script to download the Yggdrasil files. All version numbers now look consistent to me.

2021-12-21 15:24 UTC, carlocab commented
FYI, 2.27 has fixes for two high-severity security advisories: https://tls.mbed.org/tech-updates/security-advisories/mbedtls-security-advisory-2021-07-1, https://tls.mbed.org/tech-updates/security-advisories/mbedtls-security-advisory-2021-07-2

I don't know if these vulnerabilities are exposed through Julia.

2022-01-06 07:59 UTC, mkitti commented
The issue is that we have Mbed TLS pinned to version 2.24 in three places in BinaryBuilder
1. [LibSSH2](https://github.com/JuliaPackaging/Yggdrasil/blob/f81c3d85a7c911c796cefa08091210d1810cac80/L/LibSSH2/build_tarballs.jl#L45
)
2. [LibGit2](https://github.com/JuliaPackaging/Yggdrasil/blob/f81c3d85a7c911c796cefa08091210d1810cac80/L/LibGit2/build_tarballs.jl#L62)
3. [Curl](https://github.com/JuliaPackaging/Yggdrasil/blob/f81c3d85a7c911c796cefa08091210d1810cac80/L/LibCURL/build_tarballs.jl#L79)

Updating Mbed TLS to 2.27 changes the SO number from 5 to 7. That's why `libmbedcrypto.so.5` is missing.

Compiling julia with this patch merged onto master and `USE_BINARYBUILDER_LIBGIT2=0 USE_BINARYBUILDER_LIBSSH2=0 USE_BINARYBUILDER_LIBCURL=0` works.

Also there is now Mbed TLS 2.28 due [CVE-2021-44732](https://tls.mbed.org/tech-updates/security-advisories/mbedtls-security-advisory-2021-12)

2022-01-07 09:31 UTC, mkitti commented
@jeremiahpslewis Would you be interested in updating this PR to Mbed TLS 2.28 ?

2022-01-07 09:58 UTC, jeremiahpslewis commented
> @jeremiahpslewis Would you be interested in updating this PR to Mbed TLS 2.28 ?

Sure, superficially it's done. But until there's a 2.28.0 version available on Yggdrasil, I can't bump the _jll dependency.

2022-01-07 10:28 UTC, jeremiahpslewis commented
Just saw https://github.com/JuliaPackaging/Yggdrasil/pull/4179 was merged. Now updated.

2022-01-07 10:29 UTC, jeremiahpslewis commented
One note...given that `MbedTLS_jll` has a lower bound of Julia 1.8, don't think this PR is a backport candidate...perhaps the labels should be removed?

2022-01-07 11:11 UTC, mkitti commented
Just a reminder that this will not work until we also update LibGit2 and Libssh2, and pin them on Mbed TLS 2.28 intead of 2.24 due to ABI changes in Mbed TLS.

https://github.com/JuliaPackaging/Yggdrasil/blob/90c82e2bb9c64f80893a8a25f5d2111400c7c333/L/LibGit2/build_tarballs.jl#L62
https://github.com/JuliaPackaging/Yggdrasil/blob/90c82e2bb9c64f80893a8a25f5d2111400c7c333/L/LibSSH2/build_tarballs.jl#L45

I think it's possible to update LibGit2 now since there is a new version available. There is not a new version of Libssh2 as far as I know.

2022-01-07 11:14 UTC, jeremiahpslewis commented
@mkitti Ok. Is it worth doing the fake version bump trick for Libssh2?

2022-01-07 11:20 UTC, mkitti commented
That's above my paygrade. Given that we likely have some time before everything is in place, we probably should just wait to see if Libssh2 releases anything. Another possibility is moving to Libssh instead of Libssh2, but that will require some action upstream:
https://github.com/libgit2/libgit2/issues/4338
or moving away from Libgit2 entirely:
https://github.com/JuliaLang/Pkg.jl/issues/2679

2022-01-30 19:00 UTC, ViralBShah commented
@jeremiahpslewis has an issue open on libssh2 and it seems that a 1.11 release is coming soon: https://github.com/libssh2/libssh2/issues/657

2022-04-01 13:45 UTC, ViralBShah commented
I think we can close this one, since the other one (#43250) was merged and addresses the security issues (and there are no changes in the diff here).

2022-04-01 13:47 UTC, closed without merging