inference: forward `Conditional` inter-procedurally
JuliaLang/julia pull request #42529
Opened 2021-10-07 13:17 UTC by aviatesk

The PR #38905 only "back-propagates" conditional constraint
(from callee to caller), but currently we don't "forward" it
(caller to callee), and so inter-procedural constraint propagation
won't happen for e.g.:
```julia
ifelselike(cnd, x, y) = cnd ? x : y
@test Base.return_types((Any,Int,)) do x, y
    ifelselike(isa(x, Int), x, y)
end |> only == Int
```

This commit complements #38905 and enables further inter-procedural
conditional constraint propagation by forwarding `Conditional` to
callees when it imposes a constraint on any other argument,
during constant propagation.

---

- IIUC, this PR will be a requirement of #37343 ?
- /cc @c42f @chriselrod

2021-10-08 00:25 UTC, c42f reviewed
This seems great! I had a read through though I don't know the surrounding code well enough to review properly.

2021-10-12 14:33 UTC, aviatesk commented
Alright, I think this PR is ready to go. @vtjnash can I ask your review on this ?

2021-10-20 17:12 UTC, aviatesk commented
@vtjnash I'd like to merge this PR tomorrow on my responsibility, but I'd appreciate if you could review it if you have a time.

2021-10-20 20:48 UTC, vtjnash requested changes

2021-10-21 16:55 UTC, vtjnash approved these changes

2021-10-21 16:56 UTC, merged