Work around type intersection bug in `_isequal`, `_isless`, `__inc`, and `__dec`
JuliaLang/julia pull request #42686
Opened 2021-10-18 09:15 UTC by martinholters

The underlying intersection bug looks like
```
julia> typeintersect(Tuple{Tuple{Any, Vararg{Any, N}}, Tuple{Any, Vararg{Any, N}}} where N, Tuple{Tuple{Int,Int,Int}, Tuple})
Tuple{Tuple{Int64, Int64, Int64}, NTuple{4, Any}}
```

It leads to the argument types of the functions with signatures of this type to be inferred wrongly, not actually matching the signature, which easily leads to problems down the road.

For the four methods touched here, the fact that the two tuple arguments must have the same length is not actually relevant for dispatch as they are internal functions which are only called if this actually holds. Also, this change will just replace the method error with another error if, for some reason, these functions would get called for tuples of unequal length. (For `_isequal` and `_isless` I've added type-assertions to ensure this, for `__inc` and `__dec` I'm not sure about the early returns, maybe someone who knows this code might take a look. Although it probably doesn't matter anyway.)

@aviatesk Can you confirm this preserves the benefits from #40594?

Fixes #42457. Closes #42682.

2021-10-18 15:40 UTC, martinholters commented
Yes, that would be it. I meant to link to it but forgot, thanks for bringing it up.

2021-10-18 21:05 UTC, JeffBezanson approved these changes

2021-10-18 21:21 UTC, vtjnash requested changes

2021-10-19 11:44 UTC, aviatesk approved these changes
Great, the method bodies seem much cleaner than before, and it's also nice that we can keep method signatures introduced in #40594 !
Thanks for working on this :)

2021-10-19 12:18 UTC, merged