inference: improve management of non-type parameters
JuliaLang/julia pull request #42693
Opened 2021-10-18 21:08 UTC by vtjnash

Prevent occurrence of v or Type{v} in the type-lattice, where v is not a
Type (or TypeVar).

Fixes #42646, and similar problems from code-reading.

2021-10-19 06:36 UTC, martinholters requested changes

2021-10-19 08:06 UTC, aviatesk reviewed
Good to unify `rewrap` and `rewrap_unionall` :)

2021-10-21 11:43 UTC, aviatesk approved these changes

2021-10-22 08:11 UTC, martinholters approved these changes

2021-10-25 18:29 UTC, merged