Add underscore to punctuation.md
JuliaLang/julia pull request #44552
Opened 2022-03-10 19:50 UTC by nathanrboyer

Feel free to edit as necessary.

2022-03-10 21:26 UTC, JeffBezanson approved these changes

2022-03-11 07:28 UTC, aviatesk requested changes, later dismissed
Needs to fix invalid references.

2022-03-14 12:29 UTC, nathanrboyer commented
I don't know how to test the references. The links I was shooting for are below:
https://docs.julialang.org/en/v1/manual/functions/#destructuring-assignment
https://docs.julialang.org/en/v1/manual/arrays/#man-comprehensions

The second link doesn't have any examples with underscores, but it seems to be common to use underscores with comprehensions.

2022-04-06 12:04 UTC, inkydragon commented on doc/src/base/punctuation.md
> +| `_`         | underscores may be assigned values which will not be saved, often used to ignore [multiple return values](@ref Destructuring-Assignment-and-Multiple-Return-Values) or create repetitiv
```suggestion
| `_`         | underscores may be assigned values which will not be saved, often used to ignore [multiple return values](@ref destructuring-assignment) or create repetitive [comprehensions](@ref man-comprehensions) |
```

2022-05-06 12:03 UTC, merged