Add \neq tab completion to ≠
JuliaLang/julia pull request #44849
Opened 2022-04-04 16:41 UTC by gaurav-arya

Adds `\neq` as an alternative to `\ne` for tab completing to `≠`, just like `\le` and `\leq` both tab complete to `≤`.

2022-04-05 02:55 UTC, Moelf approved these changes

2022-04-05 15:52 UTC, oscardssmith approved these changes

2022-04-06 00:41 UTC, aviatesk requested changes
One case within REPL stdlib test suite seems to be failing
because of this.

2022-04-06 03:02 UTC, aviatesk approved these changes

2022-04-06 16:01 UTC, merged