Support italic style in printstyled.
JuliaLang/julia pull request #45164
Opened 2022-05-03 09:20 UTC by fredrikekre

2022-05-09 11:31 UTC, KristofferC commented on NEWS.md
> +* `printstyled` now support italic output ([#?]).
```suggestion
* `printstyled` now supports italic output ([#?]).
```

?

2022-05-09 11:31 UTC, KristofferC approved these changes

2022-05-09 15:53 UTC, vtjnash requested changes
We did not include this because it does not reliably make it italic, except on monochrome monitors. On color monitors, it may invert the colorscheme instead:

macOS Terminal running tmux:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/330950/167448221-646d0553-b33e-4bc5-b955-8d8bed09df37.png">

macOS Terminal not running tmux:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/330950/167448456-27acda7f-fec2-4a7b-8088-ee6226f454e3.png">

https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters

2022-05-09 15:58 UTC, vtjnash commented
Note that even this support might be quite recent, since people were writing blogs about it not working within the past few years: https://weibeld.net/terminals-and-shells/italics.html

2023-02-13 11:52 UTC, fredrikekre commented
Rebased. I included a note about terminal support in the docstring.

2023-02-13 21:19 UTC, vtjnash approved these changes

2023-02-13 21:20 UTC, merged

2023-05-19 02:15 UTC, tecosaur commented
It's worth noting (and I think short of the docs a comment here has a chance of being seen at least) that italic support can be checked for in terminfo, and so the best practice would be adapting the printing behavior based on the terminal capabilities.