Profile: save a heap snapshot after a profile peek via SIGUSR1/SIGINFO (with opt-out)
JuliaLang/julia pull request #47134
Opened 2022-10-12 03:16 UTC by IanButterworth

If the user is backed into a situation where the SIGUSR1/SIGINFO profile peek is useful, grabbing a heap snapshot may also be.

An env var is exposed to turn it off, although I guess that won't take effect with an already running julia process.

Needs docs and tests if approved.

2022-10-18 02:47 UTC, NHDaly commented
In our experience (CC: @vilterp) taking a heap snapshot can be _super slow_. Like 15+ seconds slow.

I'm not sure if this makes sense to do all the time.... 🤔 
Can we use a different signal for it? 😊 how many user-space signals are there?

2022-10-18 02:47 UTC, NHDaly commented
I could be wrong though!

2022-10-18 02:50 UTC, IanButterworth commented
Can it be made quicker easily?

2022-10-18 14:38 UTC, NHDaly commented
Probably a better question for @apaz-cli and @vtjnash at this point.

2022-10-18 18:10 UTC, apaz-cli commented
The code for `jl_gc_take_heap_snapshot()` literally calls `jl_gc_collect(JL_GC_FULL)`, and it's the GC sweep that does the recording. After that, we just write the result. So, the performance of `take_heap_snapshot()` should be almost exactly the same as a full GC, plus the time it takes to write out the result. It's worth noting though that GC traces over the entire heap, including things like method instances. So, the bigger the heap or system image you're working with the longer it will take. It appears though that most of the time is spent writing the result, which is a whole lot of JSON.

```julia
using Profile;
@time Profile.take_heap_snapshot(tempname());
# apaz[x][master][~/git/julia]$ ./julia snap.jl 
#  5.397448 seconds (20 allocations: 1.930 KiB, 34.34% gc time)
```

```julia
using LoopVectorization
using Profile;
@time Profile.take_heap_snapshot(tempname());
# apaz[x][master][~/git/julia]$ ./julia biggersnap.jl 
#  7.153016 seconds (20 allocations: 1.930 KiB, 35.07% gc time)
```

I think that taking a heap snapshot in response to a signal sounds like a really good idea, but given that it's so slow I don't think it should be the default on an already existing feature. It should probably be a separate thing.

2022-10-18 18:19 UTC, gbaraldi commented
@apaz-cli do you think there is some room left for improvement in the JSON writing department? There is a lot of very optimized JSON writing code out there.

2022-10-18 18:55 UTC, apaz-cli commented
@gbaraldi Right now we build the JSON as though it were flat, and just append to an `ios_t` with `ios_printf()`. It looks though like a lot of those calls could be combined into one. GCC or clang usually would see through this sort of thing with normal `printf` calls (unless you tell it not to with -fno-builtin), but it doesn't know about `ios_printf`. There's probably some savings to be had, and I have legitimately no idea by how much I should expect it to improve things. Still, it's worth a try.

https://github.com/JuliaLang/julia/compare/master...apaz-cli:julia:ap/snapshot-write

2022-10-18 19:24 UTC, apaz-cli commented
It looks like we have some modest improvements, I'll go create a PR.
```
apaz[x][ap/snapshot-write][~/git/julia]$ ./julia snap.jl 
  4.277987 seconds (20 allocations: 1.930 KiB, 46.74% gc time)
```
```
apaz[x][ap/snapshot-write][~/git/julia]$ ./julia biggersnap.jl
  5.569107 seconds (20 allocations: 1.930 KiB, 44.65% gc time)
```

2022-10-18 19:32 UTC, gbaraldi commented
Can you profile the profiling 😄

2022-10-21 18:22 UTC, IanButterworth commented
We just discussed in the profiling call that perhaps we can give this a go as-is, and people can try it out to see if it's manageable as opt-out via an env var, as this PR currently is

2022-10-21 18:52 UTC, vtjnash requested changes
This seems far too slow to be running from SIGINFO by default

2022-10-24 22:36 UTC, NHDaly commented
yeah i have to agree with @vtjnash. I really like using `ctrl-t` on macos, and i think i wouldn't be able to do that if it was doing this dump. 

Is there no way we can add different signal / key combo for this?
Or maybe we can trigger the writing to happen in the background somehow?

2022-11-02 12:08 UTC, IanButterworth commented
@vtjnash I can't merge while your review is red. Can you go ahead if you're ok with opt-in

2022-11-02 13:48 UTC, vtjnash approved these changes

2022-11-02 13:50 UTC, vtjnash commented
Should this use `yes`/`1` for setting this? I don't know if we use `true` as much for ENV, but know we use `yes` for all our command line option parsing

2022-11-02 19:21 UTC, StefanKarpinski commented
There's a standard function in Pkg that allows `r"^(0|1|f|t|false|true|n|y|no|yes)$"i`. Maybe use that for consistency?

2022-11-02 19:29 UTC, IanButterworth commented
Yeah, I was going to PR that over to Base. It needs a bit of work to make it fully symmetrical based on what the default you expect is.

2022-11-02 19:39 UTC, IanButterworth commented
https://github.com/JuliaLang/julia/pull/47436

2022-11-06 01:31 UTC, IanButterworth commented
#47436 is stalling so I just made this PR's env var require being set to "1" as that seems the most common for enable/disable env vars in https://docs.julialang.org/en/v1/manual/environment-variables/#Environment-Variables

2022-11-06 01:43 UTC, DilumAluthge commented
If you wanted, you could instead do `parse(Bool, get(ENV, "JULIA_PROFILE_PEEK_HEAP_SNAPSHOT", "false"))`, which would allow both 0/1 and false/true.

But I feel like that can probably be done in follow-up PRs, instead of holding up this PR.

2022-11-06 01:46 UTC, IanButterworth commented
Yeah, follow-on sounds good. Whether it's https://github.com/JuliaLang/julia/pull/47436 or another, I think it would be good to make all the enable/disable env vars accept the same set of inputs.

2022-11-06 04:23 UTC, IanButterworth commented
The failure is an unrelated intermittent network Pkg failure that is soon to be improved by #47468

2022-11-06 04:24 UTC, merged