Add sleep precision tests [WIP]
JuliaLang/julia pull request #47528
Opened 2022-11-10 10:51 UTC by LilithHafner

2022-11-10 12:19 UTC, Seelengrab commented on test/misc.jl
> +    println("GREP TARGET 1729 A")
I wonder if adding functionality for a logging blurb when a testset starts to run and ends to the basic testset directly would be good :thinking:

2022-11-10 13:28 UTC, vtjnash requested changes
Sleep is guaranteed only to return "eventually". It regularly takes many seconds longer than requested. This should not be tested for tolerances unless you have installed a custom RT kernel

2022-11-11 01:52 UTC, LilithHafner commented
The primary reason I opened this PR is to get empirical results to inform discussion at #45144. It's also of note that windows sometimes sleeps for _less_ time than requested; I find that strange and disconcerting.

2022-11-11 19:52 UTC, vtjnash commented
The Windows documentation for `Sleep` does make that explicit claim about returning early, but the documentation is wrong. I confirmed that with Microsoft developers here: https://github.com/MicrosoftDocs/sdk-api/blob/docs/sdk-api-src/content/synchapi/nf-synchapi-sleepex.md

2023-05-27 13:26 UTC, closed without merging