deprecate @pure and make it just @assume_effects :foldable
JuliaLang/julia pull request #48588
Opened 2023-02-08 14:04 UTC by oscardssmith

At this point the effects system is the better way to express these types of guarantees. (Also @vtjnash told me this was OK).

2023-02-08 14:16 UTC, vchuravy commented on base/compiler/abstractinterpretation.jl
>          return CallMeta(Const(length(svecval)), EFFECTS_TOTAL, MethodResultPure())
Is `MethodResultPure` not still `@pure`? We also still have `is_method_pure/pure_eval_eligible`. Whereas you now want this to be `concrete_eval_eligible`. In any case changing the comment here is misleading.

2023-02-08 14:16 UTC, vchuravy commented on base/compiler/ssair/inlining.jl
>          if info isa MethodResultPure
Same. This is still `@pure` handling

2023-02-08 14:17 UTC, vchuravy commented on base/compiler/stmtinfo.jl
> +effect-free, including being no-throw
Same. `ConcreteResult/ConstCall` is the new pure. This is still `@pure`

2023-02-08 14:18 UTC, vchuravy commented on base/deprecated.jl
> +    modeling and the effect system enables a wider range of optimizations.
add a `!!! note` about it being deprecated in 1.10

2023-02-08 14:19 UTC, vchuravy commented
Ideally this would remove the `pure` handling in abstractinterpretation as well.

2023-02-08 21:53 UTC, vchuravy commented on base/compiler/stmtinfo.jl
> +    effects::Effectsz
```suggestion
    effects::Effects
```

2023-02-09 14:29 UTC, aviatesk requested changes

2023-02-09 14:43 UTC, oscardssmith commented on base/compiler/abstractinterpretation.jl
> -            return CallMeta(Const(rty.val === false), EFFECTS_TOTAL, MethodResultPure())
couldn't this just check the effects rather than using `MethodResultPure`?

2023-02-09 14:46 UTC, aviatesk commented on base/compiler/abstractinterpretation.jl
> -            return CallMeta(Const(rty.val === false), EFFECTS_TOTAL, MethodResultPure())
We currently don't propagate per-statement level effects. `CallInfo` is what we use for propagating per-statement information to the optimizer.

2023-02-15 13:36 UTC, closed without merging