Only add big objarray to remset once
JuliaLang/julia pull request #49315
Opened 2023-04-10 16:26 UTC by gbaraldi

Fixes https://github.com/JuliaLang/julia/issues/49205

2023-04-10 16:36 UTC, vtjnash approved these changes

2023-04-10 17:32 UTC, d-netto commented on src/gc.c
> +        if ((nptr & 0x3) != 0x2) {
Why are we creating a chunk conditioned on `(nptr & 0x3) != 0x2`?

2023-04-10 17:36 UTC, d-netto commented
What's the performance impact of this PR on https://github.com/JuliaLang/julia/issues/49205?

2023-04-10 17:57 UTC, gbaraldi commented
Makes it faster than on 1.8

2023-04-10 18:26 UTC, d-netto requested changes
The logic for decide whether we need to chunk or push the array into the `remset` could be a bit cleaner. I'd refactor:

```c
size_t too_big = (obj_end - obj_begin) / MAX_REFS_AT_ONCE > step; // use this order of operations to avoid idiv
jl_value_t **scan_end = obj_end;
if (too_big) {
    scan_end = obj_begin + step * MAX_REFS_AT_ONCE;
    if ((nptr & 0x3) != 0x2) {
        jl_gc_chunk_t c = {GC_objary_chunk, obj_parent, scan_end,
                           obj_end,      NULL,       NULL,
                           step,         nptr};
        gc_chunkqueue_push(mq, &c);
        obj_end = scan_end;
    }
}
for (; obj_begin < scan_end; obj_begin += step) {
    new_obj = *obj_begin;
    if (new_obj != NULL) {
        verify_parent2("obj array", obj_parent, obj_begin, "elem(%d)",
                       gc_slot_to_arrayidx(obj_parent, obj_begin));
        gc_try_claim_and_push(mq, new_obj, &nptr);
        gc_heap_snapshot_record_array_edge(obj_parent, &new_obj);
    }
}
if (too_big) {
    if (obj_end != scan_end) {
        jl_gc_chunk_t c = {GC_objary_chunk, obj_parent, scan_end,
                           obj_end,      NULL,       NULL,
                           step,         nptr};
        gc_chunkqueue_push(mq, &c);
    }
}
else {
    gc_mark_push_remset(ptls, obj_parent, nptr);
}
```

into:

```c
size_t too_big = (obj_end - obj_begin) / MAX_REFS_AT_ONCE > step; // use this order of operations to avoid idiv
jl_value_t **scan_end = obj_end;
if (too_big) {
    scan_end = obj_begin + step * MAX_REFS_AT_ONCE;
}
for (; obj_begin < scan_end; obj_begin += step) {
    new_obj = *obj_begin;
    if (new_obj != NULL) {
        verify_parent2("obj array", obj_parent, obj_begin, "elem(%d)",
                       gc_slot_to_arrayidx(obj_parent, obj_begin));
        gc_try_claim_and_push(mq, new_obj, &nptr);
        gc_heap_snapshot_record_array_edge(obj_parent, &new_obj);
    }
}
if (too_big) {
    jl_gc_chunk_t c = {GC_objary_chunk, obj_parent, scan_end,
                        obj_end,      NULL,       NULL,
                        step,         nptr};
    gc_chunkqueue_push(mq, &c);
}
else {
    gc_mark_push_remset(ptls, obj_parent, nptr);
}
```

Same change for `gc_mark_array8/16`.

2023-04-10 19:58 UTC, vtjnash commented
As long as you don't care that your change eliminates the possibility of intra-array thread-stealing and thus slightly reduces parallelism of threaded GC, yeah, that rearrangement is fine.

2023-04-10 20:06 UTC, d-netto commented
> slightly reduces parallelism of threaded GC

This should be fine. If an array is large enough to be chunked then it will expose a lot of `jl_value_t *` that could potentially be stolen.

2023-04-10 20:09 UTC, d-netto commented
Also, in https://github.com/JuliaLang/julia/pull/48600 we prioritize stealing pointers before chunks.

2023-04-10 21:15 UTC, d-netto commented on src/gc.c
> +                               ary8_end,      NULL,       NULL,
Replace `NULL, NULL` here with `elem_begin, elem_end`. Same for `array16`.

2023-04-11 17:30 UTC, vtjnash commented on src/gc.c
> +                            elsize,         nptr};
```suggestion
                           ary8_end,        elem_begin,       elem_end,
                           0,               nptr};
```

2023-04-11 17:31 UTC, vtjnash commented on src/gc.c
>      for (; ary16_begin < ary16_end; ary16_begin += elsize) {
```suggestion
    for (; ary16_begin < scan_end; ary16_begin += elsize) {
```

2023-04-20 16:50 UTC, merged