speed-up `randperm` by using our current `rand(1:n)`
JuliaLang/julia pull request #50509
Opened 2023-07-11 16:22 UTC by rfourquet

And similarly for `randcycle` and `shuffle`.

We had a custom version of range generation for `randperm`, which was based on the ideas of our previous default range sampler `SamplerRangeFast` (generate `k`-bits integers using masking and reject out-of-range ones) and took advantage of the fact that `randperm` needs to generate `rand(1:i)` for `i = 2:n`.

But our current range sampler ("Nearly Division Less") is usually better than this hack, and makes these functions more readable. Typically, for array lengths `< 2^20`, the new version is faster, but gets slightly slower beyond 2^22.

Here are some speedups:
![randperm-ndl-speedup](https://github.com/JuliaLang/julia/assets/8462914/b999ba43-e588-49f4-91a2-a4b23e79716d)

The slow down for big arrays seems fine to me, but I will see if I can find an easy workaround.

2023-07-20 11:17 UTC, rfourquet commented on stdlib/Random/src/misc.jl
> -ltm52(n::Int, mask::Int=nextpow(2, n)-1) = LessThan(n-1, Masked(mask, UInt52Raw(Int)))
Oh good catch! I pretty much prefer deleting this function, so will attempt PRs against these packages.

2025-04-12 14:22 UTC, rfourquet commented
Revisiting this: I lost the original benchmark code, so I don't remember if it was using an explicit rng, or the implicit one. Here is a more comprehensive graph, which shows the same tendencies:

![new-shuffle](https://github.com/user-attachments/assets/aa19abda-f9a1-46d1-93cc-10726ff9f708)

However, if #58089 would be merged, the changes here would seem to always be an improvement:

![new-shuffle-ndl](https://github.com/user-attachments/assets/292a9cb7-4877-4d75-b474-e0ac6a6fed32)

2025-04-12 16:54 UTC, jakobnissen commented
Does this close https://github.com/JuliaLang/julia/issues/57771 ?

2025-04-13 10:14 UTC, rfourquet commented
> Does this close https://github.com/JuliaLang/julia/issues/57771 ?

Yes.

2025-04-14 14:15 UTC, adienes commented
> The slow down for big arrays seems fine to me

me as well, given that the larger the shuffled array gets the more likely that the user will want to do it with a distributed algorithm anyway, like the hypothetical https://github.com/JuliaFolds2/OhMyThreads.jl/issues/139

2025-04-14 17:18 UTC, rfourquet commented
Nice reference! But also, with #58089, I believe there won't actually be slowdowns anyway.

2025-05-09 12:09 UTC, jakobnissen requested changes

2025-05-09 12:09 UTC, jakobnissen commented on stdlib/Random/src/misc.jl
> +    @inbounds for i = 2:length(a)
Can we delete this `@inbounds`, given that this is out-of-bounds for OffsetArrays? Benchmarking in #57771 suggests this `@inbounds` has almost no effect on speed.

2025-05-09 12:09 UTC, jakobnissen commented on stdlib/Random/src/misc.jl
> +    @inbounds for i = 2:length(a)
```suggestion
    for i = 2:length(a)
```

2025-05-09 12:09 UTC, jakobnissen commented on stdlib/Random/src/misc.jl
> +function randperm!(rng::AbstractRNG, a::Array{<:Integer})
Any reason this, and `randcycle!` are not defined for `AbstractArray`?

2025-05-09 12:20 UTC, rfourquet commented on stdlib/Random/src/misc.jl
> +    @inbounds for i = 2:length(a)
We currently support one one-based indexing, but yes I will re-benchmark without the `@inbounds`.

2025-05-09 12:20 UTC, rfourquet commented on stdlib/Random/src/misc.jl
> +function randperm!(rng::AbstractRNG, a::Array{<:Integer})
Interesting, I also just noticed that!

2025-08-30 22:00 UTC, adienes commented
since https://github.com/JuliaLang/julia/pull/58089 is merged, is this basically ready besides the doctests?

2025-10-25 21:41 UTC, rfourquet commented
The test failure looks unrelated, if that's the case I will merge in a couple of days.

2025-10-26 00:37 UTC, merged