implement `Base.hastypemax` with `hasmethod` instead of `applicable`
JuliaLang/julia pull request #50770
Opened 2023-08-02 20:45 UTC by nsajko

Unlike `applicable`, `hasmethod` gets constant-folded.

Just the fallback method is modified.

Codegen examples, taking `BigFloat` as an example:

On master (3eddd1783f29eaf60ab817301bc8c3d084e417a4):
```julia-repl
julia> Base.print_statement_costs(stdout, Base.hastypemax, Tuple{Type{BigFloat}})
hastypemax(::Type{T}) where T @ Base intfuncs.jl:940
 40 1 ─ %1 = Base.applicable(Base.typemin, BigFloat)::Bool
  0 └──      return %1
```

With this commit:
```julia-repl
julia> Base.print_statement_costs(stdout, Base.hastypemax, Tuple{Type{BigFloat}})
hastypemax(::Type{T}) where T @ Base intfuncs.jl:940
 0 1 ─     return true
```

2023-08-04 10:11 UTC, petvana commented
Is this trick applicable for other occurrences as well? ... such as
https://github.com/JuliaLang/julia/blob/2c45e3ba9a2cf801d5b8da433552541c196ab54b/base/reducedim.jl#L115

2023-08-04 11:53 UTC, nsajko commented
@petvana It might be, I don't know. I found the example you point to before doing the PR, but I gave up after seeing that `T` seems to be only known at run time inside that function, even though it's a type.

2023-08-04 12:21 UTC, petvana commented
@nsajko It may be naive, but would it be possible to redefine `applicable` for two arguments rather than solving one special case?
```applicable(f, T) = hasmethod_one_type(f, T)```

2023-08-04 13:46 UTC, nsajko commented
I think we'd need to constrain the final argument to be a `Type`, so it could perhaps look something like this:

```julia
applicable(f, ::Type{T}) where {T} = hasmethod(f, Tuple{Type{T}})
```

However, I'm not totally sure of the implications of this, that's why I didn't do it like that in the PR. Insight is welcome, of course.

2023-08-14 11:36 UTC, KristofferC commented on base/intfuncs.jl
> -hastypemax(::Type{T}) where {T} = applicable(typemax, T) && applicable(typemin, T)
Imo just inline the `hasmethod_one_type` here and remove it. Feels excessive to have to look into another file for such a small utility function to understand what this is doing.

2023-08-14 16:13 UTC, vtjnash requested changes
The overhead of calling `hasmethod` is usually much higher, since `applicable` is the much easier and more correct query (unless you really are intending to query for the behavior of `invoke`, since that is what `hasmethod` implements). So overall, this PR seems to be worse than the existing code?

That seems to be an optimizer bug you are seeing. I can't directly tell where that occurred, since I can see it on some builds but not others.

2024-01-29 21:34 UTC, closed without merging