Don't use '#' when naming global variables.
JuliaLang/julia pull request #51099
Opened 2023-08-29 09:36 UTC by maleadt

On 1.11, I'm seeing GVs with definitions like:

```llvm
@"_j_const#3" = private unnamed_addr addrspace(1) constant [2 x double] [double 0x7FF8000000000000, double 0x7FF8000000000000], align 8
```

LLVM doesn't like these, https://github.com/llvm/llvm-project/blob/6982f1fc2e750cfbb4b0098a6294d341238656ca/llvm/lib/MC/MCAsmInfo.cpp#L104-L109, resulting in issues compiling GPU code. I'm not sure why the Base JIT doesn't run into this...

2023-08-29 14:07 UTC, Keno commented
Fine with the PR, but LLVM is supposed to mangle names that the backend doesn't support. Same deal with unicode chars for example - I suspect something is going wrong here on the GPU side.

2023-08-29 18:37 UTC, maleadt commented
> LLVM is supposed to mangle names that the backend doesn't support

I'll first have a closer look then. Any ideas where that's supposed to happen?

2023-08-29 19:09 UTC, gbaraldi commented
Maybe it's a backend issue? Because on CPU it doesn't mangle. At least in the code_native printing I see
```s
.set ".L*Main.a#1098.jit", 140087501449024
```

2023-08-29 19:18 UTC, vtjnash commented
Some names are "special" and change linker behavior. Our aotcompile code mangles them to "safe" characters to avoid anything like that happening in the system linker. The OrcJIT linker doesn't use the name to change behavior, so it isn't an issue there.

2023-08-30 14:42 UTC, vtjnash requested changes
IIUC, you are supposed to set `policy == CompilationPolicy::Default` if you want to opt into safe names. Otherwise you are expected to be able to handle arbitrary names (this is by far not the only places we emit names with `#`)
https://github.com/JuliaLang/julia/blob/197180d8589ad14fc4bc4c23782b76739c4ec5a4/src/aotcompile.cpp#L455-L461

2023-08-30 15:02 UTC, maleadt commented
> IIUC, you are supposed to set `policy == CompilationPolicy::Default` if you want to opt into safe names.

We're using the extern policy, which was added specially for GPUCompiler (by @vchuravy IIRC). Should we just rename all global objects ourselves then? We already do so for functions, but Keno's comment above seemed to indicate that LLVM should handle this, not Julia/GPUCompiler.

2023-08-30 15:49 UTC, vchuravy commented
Yeah compilation policy was never intended to change anything about names, it should be purely about what kind of cache lookups we are allowed to do.

2023-08-30 18:39 UTC, gbaraldi commented
https://github.com/JuliaLang/julia/pull/39387 Made the `makeSafeName` Default only.

2023-09-06 11:52 UTC, closed without merging