Added docstring for Artifacts.jl
JuliaLang/julia pull request #52913
Opened 2024-01-15 19:57 UTC by jam-khan

This is a part of issue #52725.

2024-01-15 23:51 UTC, stevengj commented on stdlib/Artifacts/src/Artifacts.jl
> +artificats in Julia packages. Artifacts are containers that can contain
```suggestion
artifacts in Julia packages. Artifacts are containers that can contain
```

2024-01-15 23:53 UTC, stevengj commented
You also need to update the test at https://github.com/JuliaLang/julia/blob/89710bf8a1914e22fe61e4e087f5ff5e97a32f02/stdlib/Artifacts/test/runtests.jl#L265-L269 to
```jl
@testset "Docstrings" begin
    @test isempty(Docs.undocumented_names(Artifacts))
end
```

2024-02-07 01:07 UTC, fingolfin commented on stdlib/Artifacts/test/runtests.jl
> +end
```suggestion
end

```

2024-02-07 01:07 UTC, fingolfin approved these changes

2024-02-07 14:46 UTC, fingolfin requested changes

2024-02-07 14:46 UTC, fingolfin commented on stdlib/Artifacts/test/runtests.jl
>      @test_broken isempty(undoc)
This doesn't look right: you are not setting `undoc` anymore here but still try to use it. Also, this test is not broken anymore.

How about this:
```suggestion
    @test isempty(Docs.undocumented_names(Artifacts))
```

2024-02-07 23:56 UTC, fingolfin approved these changes
Seems OK now

2024-02-08 11:52 UTC, merged