allow external absint to hold custom data in `codeinst.inferred`
JuliaLang/julia pull request #53300
Opened 2024-02-12 16:40 UTC by aviatesk

It has been possible for external abstract interpreters to keep custom data in `codeinst.inferred` (together /w overloading `inlining_policy`). After JuliaLang/julia#52233, when such external absint uses `InternalCodeCache`, this data is passed to `jl_ir_flag_inferred`, leading to segfaults in assertion builds.

This commit resolves the issue by omitting `jl_ir_flag_inferred` checks when the `cache_owner` is external. Nonetheless, a better resolution might be necessary. It suggests that the current design of `code_owner` and `InternalCodeCache` for the external cache system is somewhat flawed. A conceivable approach could involve:
- Adding a layer similar to `inlining_policy` in `CC.get(::WorldView{InternalCodeCache})` to enable safe redirection of custom data to the native interpreter's implementation.
- Prohibiting custom data in the `inferred` field and directing such data to be kept in `analysis_results`.

2024-02-12 16:53 UTC, vchuravy commented
Does #53219 resolve this? It removes the need to handle code-instances in this location.

#52964 does require  that `code.inferred` is something codegen and the interpreter can understand, so stashing additional data in `.inferred` is problematic and I would prefer custom data to go into `analysis_results`.

2024-02-12 16:53 UTC, vchuravy commented on base/compiler/types.jl
> +    curr_world = get_world_counter()
`curr_max_world`?

2024-02-12 16:55 UTC, vchuravy commented
In https://github.com/JuliaDebug/Cthulhu.jl/pull/540 I continued using the external code cache instead of using the internal code cache (but the external code cache no longer participates in invalidation logic)

2024-02-12 17:01 UTC, aviatesk commented
> Does #53219 resolve this? It removes the need to handle code-instances in this location.

Probably. I'm looking into it.

> In [JuliaDebug/Cthulhu.jl#540](https://github.com/JuliaDebug/Cthulhu.jl/pull/540) I continued using the external code cache instead of using the internal code cache (but the external code cache no longer participates in invalidation logic)

Cthulhu has traditionally created a new cache for each instance of `CthulhuInterpreter`, which meant there was no inherent support for invalidation required. On a personal note, I'm inclined to retain it as it facilitates easier reflection of outcomes following modifications to the base abstract interpretation's implementation.

2024-02-12 17:44 UTC, Keno commented
I think it's fine to have non-CodeInfo objects in `(::CodeInstance).inferred`. That's an explicit goal of https://github.com/JuliaLang/julia/pull/53219. https://github.com/JuliaLang/julia/pull/53219 also removes the `(::CodeInfo).inferred` field, which fixes the issue in this PR. It also fixes the underlying issue where the compiler is looking at the wrong CodeInstance in some cases. The only constraint we do need is that for `owner==nothing`, the CodeInstance's `inferred` field needs to be something the compiler understands.

2024-02-13 02:29 UTC, vtjnash requested changes
Waiting on resolution of https://github.com/JuliaLang/julia/pull/53219, since that already addresses the `.inferred` field issue here, and then this will need to be rebased

2024-02-13 04:43 UTC, aviatesk commented
Yeah I'll work on the PR first and then we only need the test cases from this PR.

2024-02-13 23:47 UTC, vchuravy requested changes
There are currently more places that make assumptions about the content of this field.

If the relocatability flag on the codeinstance is 0x0 we do not safe it as part of a package image. This is determined here https://github.com/JuliaLang/julia/blob/288912a62d80844a1b7ef75cf09c29cd3f2a39da/base/compiler/typeinfer.jl#L314-L328
and checked here https://github.com/JuliaLang/julia/blob/a7b68cf0a65aef7e44c2fa1c53f8b35263ab02eb/src/staticdata_utils.c#L233

Even if I force relocatability to 0x1 we hit an assertion later https://github.com/JuliaLang/julia/blob/a7b68cf0a65aef7e44c2fa1c53f8b35263ab02eb/src/ircode.c#L993 from https://github.com/JuliaLang/julia/blob/a7b68cf0a65aef7e44c2fa1c53f8b35263ab02eb/src/precompile_utils.c#L189

While we could thread everything through this does raise the question that we store inferred normally in a compressed format, using jl_compress_ir which of course doesn't know how to handle custom results. 
 
For me this indicates that using `analysis_results` over additional data in inferred should be preferred. Or we need to figure out how to compress custom data.

2024-02-16 18:22 UTC, vchuravy approved these changes
I am still not a big fan of using `.inferred` for these purposes, 
but I am okay with this change to unblock current uses of AbstractInterpreter. 

@aviatesk do you want to add an explicit serialization test, where you override `relocatability`?

2024-02-17 17:41 UTC, vtjnash commented
Yeah, since `jl_ir_flag_inferred` is deleted in https://github.com/JuliaLang/julia/pull/53219 it may conflict somewhat with that PR content, but seems safe to merge this now as it is mostly just added tests

2024-02-17 17:41 UTC, vtjnash approved these changes

2024-02-17 17:41 UTC, merged

2024-02-17 18:30 UTC, vtjnash commented
To address Valentin's comment: it looks like this doesn't really express an opinion specifically on whether it is acceptable to use this field, but simply attempts to address the possibility of a missing type assert, which would be valid to check there regardless of whether we later state that other content should be put here

Thinking more broadly, I wonder if we should restructure this layering of types to instead look like this, so that there is a more bright line distinction in the types what is volatile and what is constant:
```julia
struct MethodInstance #= mostly unchanged =# end

mutable struct CodeCache # renamed from CodeInstance to indicate this is volatile
    parent::MethodInstance # for show reflection
    #= most fields from existing CodeInstance =#
   ...
    @acomic inferred::Union{CodeInfo, CompressedCodeInfo}
end

struct CodeInfo # partially kept as-is, but extended to allow external stmt representations
    #= fields from existing CodeInstance that are properties of the whole function =#
    ...
    parent::MethodInstance # for show reflection
    stmts::Union{StmtInfo, OpaqueExternalObjects, Nothing} # custom info goes here
end

struct StmtInfo # split from CodeInfo
    #= fields from existing CodeInstance that are arrays of per stmt info =#
   ...
end
```