Export jl_gc_new_weakref again via julia.h
JuliaLang/julia pull request #56373
Opened 2024-10-28 21:50 UTC by fingolfin

This is how it used for at least Julia 1.0 - 1.11

2024-10-28 22:34 UTC, d-netto requested changes
Seems strange to have this function defined in the interface and implemented in gc-common.

Perhaps the right approach to make this function available through julia.h (and to avoid the cyclic header dependency) would be to make gc-common.h not include julia.h and then include it in julia.h.

Right now, gc-common.h doesn't seem to use much of julia.h, but I didn't attempt to remove that dependency to see how feasible this refactor would be.

2024-10-29 19:27 UTC, d-netto commented
> how moving this function declaration directly into julia.h temporarily until we can come up with a better restructuring. This has precedent in so far as several other jl_gc_* symbols are already in there.

Yes, this seems better.

2024-10-30 16:57 UTC, fingolfin commented
@d-netto updated now

2024-10-31 00:11 UTC, d-netto approved these changes
👍

2024-10-31 05:49 UTC, merged