Switch from MbedTLS to OpenSSL
JuliaLang/julia pull request #56708
Opened 2024-11-28 16:45 UTC by eschnett

Based on @fxcoudert's openssl branch and pull request at https://github.com/JuliaLang/julia/pull/53891.

- diff re-applied to current Julia master (hence the new commit)
- LibCURL, LibGit2, LibSSH2, OpenSSL updated to newest version
- MbedTLS removed

Fix #48799.

2024-11-28 21:47 UTC, eschnett commented
Current to-do list:
- [ ] Understand how NetworkOptions and OpenSSL cooperate regarding CA roots. Possibly remove all NetworkOptions stuff from the OpenSSL_jll stdlib.
- [ ] NetworkOptions has some MbedTLS-specific code. This needs to be switched to OpenSSL.
- [ ] I added some OpenSSL CA-root work-around into the test cases. That should probably be removed again.
- [ ] Something is off with LibCURL. We need to decide what to do, at the moment likely just staying at an older version.

2024-11-28 22:04 UTC, giordano commented
> Something is off with LibCURL. We need to decide what to do, at the moment likely just staying at an older version.

If you mean with libcurl v8.10+ https://github.com/JuliaLang/Downloads.jl/issues/260, https://github.com/JuliaLang/Downloads.jl/issues/260#issuecomment-2423908447 should fix it. But there are still other failures: https://github.com/JuliaLang/Downloads.jl/issues/261

2024-11-29 18:13 UTC, eschnett commented
This PR requires the two other PRs
- https://github.com/JuliaLang/NetworkOptions.jl/pull/36
- https://github.com/JuliaLang/Pkg.jl/pull/4100
Currently these other PRs are hardcoded in `stdlib/NetworkOptions.version` and `Pkg.version`. That also needs to be undone.

2024-11-29 19:57 UTC, eschnett commented
@giordano There is a likely-spurious test failure. Can you restart `test x86_64-unknown-freebsd`?

2024-11-29 21:52 UTC, giordano commented on deps/checksums/SuiteSparse-e8285dd13a6d5b5cf52d8124793fc4d622d07554.tar.gz/md5
Why was this file removed? Is it a leftover of a previous PR?

2024-11-29 21:52 UTC, giordano commented on deps/checksums/clang
Why was this file touched?

2024-11-29 21:52 UTC, giordano commented on deps/checksums/llvm
Why was this file touched?

2024-11-29 21:52 UTC, giordano commented on deps/checksums/suitesparse
Why was this file touched?

2024-11-29 21:52 UTC, giordano commented on deps/checksums/unwind
Why was this file touched?

2024-11-29 21:52 UTC, giordano commented on deps/curl.mk
I remember there's a patch we carry here was a backport from a later version of curl and it should be removed here, I don't remember if that was only relevant for v8.10 or also v8.9 (I ran into that while trying to debug the issue in Downloads.jl)

2024-11-29 21:53 UTC, eschnett commented on deps/checksums/SuiteSparse-e8285dd13a6d5b5cf52d8124793fc4d622d07554.tar.gz/md5
I reran `contrib/refresh_checksums.mk`. This is what it produced.

2024-11-29 21:54 UTC, eschnett commented on deps/curl.mk
I am using the patches from BinaryBuilder. The previous patch didn't apply any more, and the new patch seems to do the same thing.

2024-11-29 23:14 UTC, giordano commented on deps/checksums/SuiteSparse-e8285dd13a6d5b5cf52d8124793fc4d622d07554.tar.gz/md5
I don't think this is right.  I recommend reverting all unrelated checksums

2024-11-29 23:20 UTC, giordano commented on deps/curl.mk
I was referring to https://github.com/JuliaLang/julia/blob/c1f806dfc168fa2a3dd426f0c003a843bd01aaad/deps/patches/curl-8.6.0-build.patch, which was [backported from curl 8.7.0](https://github.com/curl/curl/commit/5cc2b016c36aaf5a08e2feb7c068fca5bb0a8052), so it isn't necessary in curl v8.9.1 and it should be removed.

2024-11-30 01:39 UTC, eschnett commented on deps/checksums/SuiteSparse-e8285dd13a6d5b5cf52d8124793fc4d622d07554.tar.gz/md5
Will do.

2024-11-30 01:41 UTC, eschnett commented on deps/curl.mk
That's the patch I removed. (It didn't apply anyway.)

2024-11-30 15:38 UTC, eschnett commented on deps/checksums/SuiteSparse-e8285dd13a6d5b5cf52d8124793fc4d622d07554.tar.gz/md5
Done.

2024-11-30 15:38 UTC, eschnett commented on deps/checksums/llvm
Undone.

2024-11-30 15:38 UTC, eschnett commented on deps/checksums/unwind
Undone.

2024-11-30 15:38 UTC, eschnett commented on deps/checksums/clang
Undone.

2024-11-30 15:38 UTC, eschnett commented on deps/checksums/suitesparse
Undone.

2024-11-30 15:57 UTC, eschnett commented
@giordano I'm seeing this build error:
```
ERROR: The working directory is dirty.
Output of git status:
HEAD detached at c4427131d2
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	deps/checksums/SuiteSparse-e8285dd13a6d5b5cf52d8124793fc4d622d07554.tar.gz/
```
Should we ignore it (assuming it's unrelated) or re-add the checksum changes?

2024-11-30 17:13 UTC, Zentrik commented
There seems to be an error creating the checksum causing that, looking now.

2024-11-30 17:48 UTC, IanButterworth commented
When this merges what do loading errors look like when the manifest pre-dates this change?

I'm wondering if we can get out ahead of that pain and have some automated fixup in loading code that knows to switch the deps over.

2024-11-30 18:15 UTC, eschnett commented
@IanButterworth Here is one error I see:
```
(base) eschnett@indigo:~/src/julia$ ./usr/bin/julia-debug
(@v1.12) pkg> status --manifest
Status `~/.julia/environments/v1.12/Manifest.toml`
ERROR: Could not locate the source code for the MbedTLS_jll package. Are you trying to use a manifest generated by a different version of Julia?

(@v1.12) pkg>
```

I removed `MbedTLS_jll` from the source. Maybe I should re-add it? If so, would it be enough to just keep the source there, or does it also need to remain in e.g. `stdlib/Manifest.toml`?

2024-11-30 18:57 UTC, eschnett commented
@IanButterworth I don't see other errors, e.g. this works:
```
julia> using Downloads

julia> Downloads.download("https://github.com/eschnett/Pkg.jl")
"/tmp/jl_UvWhePmhGr"
```

2024-12-01 18:26 UTC, giordano commented
Ok, now we're back to the point where Julia's own CI passes, but trying to load `PyCall` wreaks havoc:
```
$ julia +pr56708 --project -q
julia> using PyCall

julia> py"""
       import urllib.request
       with urllib.request.urlopen('http://python.org/') as response:
          html = response.read()
       """
ERROR: PyError ($(Expr(:escape, :(ccall(#= /home/mose/.julia/packages/PyCall/1gn3u/src/pyeval.jl:38 =# @pysym(:PyEval_EvalCode), PyPtr, (PyPtr, PyPtr, PyPtr), o, globals, locals))))) <class 'urllib.error.URLE
rror'>
URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))
```
This is where we were stuck with #53891.

2024-12-01 18:30 UTC, giordano commented on stdlib/LibSSH2_jll/test/runtests.jl
> -    vn = startswith(unsafe_string(ccall((:libssh2_version, libssh2), Cstring, (Cint,), 0)), "1.9.0")
I presume this is still a thing?

2024-12-01 18:36 UTC, giordano commented
Should PyCall/PythonCall do something like
```julia
    py"""
    import ssl
    def create_julia_https_context():
        return ssl.create_default_context(cafile=$(NetworkOptions.bundled_ca_roots()))

    ssl._create_default_https_context = create_julia_https_context
    """
```
as suggested by @mkitti at https://github.com/JuliaLang/julia/pull/53891#issuecomment-2427760913?  That does seem to work for me:
```
$ julia +pr56708 --project -q
julia> using PyCall, NetworkOptions

julia> py"""
       import ssl
       def create_julia_https_context():
           return ssl.create_default_context(cafile=$(NetworkOptions.bundled_ca_roots()))
       ssl._create_default_https_context = create_julia_https_context
       import urllib.request
       with urllib.request.urlopen('http://python.org/') as response:
           html = response.read()
       """

julia> py"html"
"<!doctype html>\n<!--[if lt IE 7]>   <html class=\"no-js ie6 lt-ie7 lt-ie8 lt-ie9\">   <![endif]-->\n<!--[if IE 7]>      <html class=\"no-js ie7 lt-ie8 lt-ie9\">          <![endif]-->\n<!--[if IE 8]>      <html class=\"no-js ie8 lt-ie9\">                 <![endif]-->\n<!--[if gt IE " ⋯ 50648 bytes ⋯ "s/IE8-min.8af6e26c7a3b.js\" charset=\"utf-8\"></script>\n    \n    \n    <![endif]-->\n\n    <!--[if lte IE 8]>\n
    <script type=\"text/javascript\" src=\"/static/js/plugins/getComputedStyle-min.d41d8cd98f00.js\" charset=\"utf-8\"></script>\n    \n    \n    <![endif]-->\n\n    \n\n    \n    \n\n</body>\n</html>\n"
```

CC @cjdoris @stevengj we really need your input here, otherwise this PR will be stuck again for ages and we don't move on.

2024-12-01 19:13 UTC, KristofferC commented
Maybe asking for forgiveness is better than asking for permission here. As I understand it, this is quite important from a security standpoint so it if the ecosystem has to catch up for a while then so be it?

2024-12-02 16:06 UTC, eschnett commented on stdlib/LibSSH2_jll/test/runtests.jl
> -    vn = startswith(unsafe_string(ccall((:libssh2_version, libssh2), Cstring, (Cint,), 0)), "1.9.0")
Done.

2024-12-02 16:11 UTC, DilumAluthge commented
Are PyCall/PythonCall the only places in the ecosystem that this PR breaks?

Could we run a PkgEval on this PR, to see if any other parts of the ecosystem are broken by this PR?

2024-12-02 16:21 UTC, giordano commented
This is the summary of last time I looked at PkgEval: https://github.com/JuliaLang/julia/pull/53891#issuecomment-2058016995

2024-12-02 18:18 UTC, giordano requested changes

2024-12-02 18:18 UTC, giordano commented on stdlib/Pkg.version
Reminder that before merging this PR the PRs to Pkg and NetworkOptions must be merged, and these files changed back to point to the original repo

2024-12-02 18:27 UTC, KristofferC commented on stdlib/Pkg.version
Tests on Pkg doesn't pass until this is merged so it is a bit tricky.

2024-12-02 19:06 UTC, KristofferC commented on stdlib/Pkg.version
I think it is fine to merge here and then when master updates rerun CI on Pkg and merge it there (and then update the commit again). The activity in the Pkg repo is not super high nowadays.

The alternative is to write the tests so that they pass both here and on master but that might be a bit more effort than it is worth.

2024-12-02 19:11 UTC, giordano commented on stdlib/Pkg.version
The problem of merging this PR first is that it'd make its merge commit not buildable from source if Erik's branch or fork are deleted.

2024-12-02 19:40 UTC, KristofferC commented on stdlib/Pkg.version
We can merge it on Pkg with tests breaking if the manifest is the only test that matters. Or both manifests are checked in and the relevant one is renamed based on the version.

2024-12-02 19:50 UTC, giordano commented on stdlib/Pkg.version
> And thus can possibly break git bisect in the future?

Yeah, whenever someone needs to build a specific commit, git bisect is indeed my main concern.

2024-12-02 20:38 UTC, mkitti commented
Can we package mbedTLS as an independent package for other packages which may still have a hard dependency on it?

2024-12-02 22:21 UTC, giordano commented
@nanosoldier runtests()

2024-12-02 22:50 UTC, DilumAluthge commented
I think the backticks are mandatory.

2024-12-02 22:50 UTC, DilumAluthge commented
@nanosoldier `runtests()`

2024-12-02 23:01 UTC, eschnett commented on stdlib/Pkg.version
Let me know when is a good time to do so. (After doing so, many things will fail on this branch before these repos are updated. We should do so only shortly before merging.)

2024-12-03 11:08 UTC, nanosoldier commented
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56708#issuecomment-2513143812) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/report.html) is available.

2024-12-03 14:52 UTC, eschnett commented
Some interesting failures: EasyCurl, JLLPrefixes.
Some expected/benign failures: SciMLTutorials (stores Manifest.toml in the repository, fails because MbedTLS_jll isn't there any more)

2024-12-06 21:16 UTC, oscardssmith commented
pressing the merge button? :)

2024-12-10 15:20 UTC, eschnett commented
If you are worried about merging three PRs simultaneously: With semver, the technically correct path would be to declare compatibilities via version numbers (i.e. bumping the major version number of `NetworkOptions.jl` and `Pkg.jl`) and applying the patches there, and then merging this PR here.

2024-12-10 18:25 UTC, mkitti commented
How do we make MbedTLS_jll available?

2024-12-10 20:02 UTC, eschnett commented
@mkitti `MbedTLS_jll` is available via the standard package registry. If you `add MbedTLS_jll` in your project it'll be added in the usual way. Having it in your `Project.toml` as dependency suffices. See e.g. https://github.com/JuliaLang/MbedTLS.jl/blob/master/Project.toml .

This PR removes `MbedTLS_jll` from the `Project.toml` in Julia's `stdlib` directory because no stdlib depends on it any more.

Julia's build-from-source mechanism can operate in two ways, either building all stdlibs from source, or (and that's the default) downloading jlls from the package registry. This is how `MbedTLS_jll` is installed by default.

I don't know whether I'm answering your question or saying something trivial.

2024-12-10 20:27 UTC, mkitti commented
What's the fix for SciMLTutorials?

2024-12-11 11:48 UTC, KristofferC commented
The Pkg bump should at least be rebased on current Pkg master.

2024-12-11 17:06 UTC, eschnett commented
The fix for SciMLTutorials is to update all the `Manifest.toml` files in the repository. I assume that a `using Pkg; Pkg.instantiate()` would be sufficient. `Pkg.update()` would also work.

2024-12-17 00:29 UTC, eschnett commented
@KristofferC I updated the Pkg.jl PR.

2024-12-18 15:46 UTC, giordano commented
I went through all the new 35 failures [reported by PkgEval](https://github.com/JuliaLang/julia/pull/56708#issuecomment-2514241685):

* issues to be solved in PyCall/PythonCall
  * [PyArrow](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/PyArrow.primary.log)
  * [Seaborn](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/Seaborn.primary.log)
  * [NeidArchive](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/NeidArchive.primary.log)
  * [CometLogger](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/CometLogger.primary.log)
  * [EcRequests](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/EcRequests.primary.log)
  * [SunAsAStar](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/SunAsAStar.primary.log)
* packages that need to be adapted (e.g. simply need to re-resolve an environment, or adapt compat bounds)
  * [JLLPrefixes](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/JLLPrefixes.primary.log)
  * [BinaryBuilderSources](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/BinaryBuilderSources.primary.log)
  * [BinaryBuilderAuditor](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/BinaryBuilderAuditor.primary.log)
  * [SciMLBenchmarks](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/SciMLBenchmarks.primary.log)
  * [SciMLTutorials](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/SciMLTutorials.primary.log)
  * [BenchmarkProfiles](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/BenchmarkProfiles.primary.log)
  * [GeoEstimation](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/GeoEstimation.primary.log)
* packages using libcurl API directly
  * [EasyCurl](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/EasyCurl.primary.log)
* unrelated failures (e.g. flaky tests, or with unreliable numerical tolerances)
  * [BPGates](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/BPGates.primary.log)
  * [NumericalAlgorithms](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/NumericalAlgorithms.primary.log)
  * [GeoJSON](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/GeoJSON.primary.log)
  * [EulerAngles](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/EulerAngles.primary.log)
  * [NMRTools](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/NMRTools.primary.log)
  * [TuePlots](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/TuePlots.primary.log)
  * [BayesianQuadrature](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/BayesianQuadrature.primary.log)
  * [UnivariateFunctions](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/UnivariateFunctions.primary.log)
  * [LinearRationalExpectations](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/LinearRationalExpectations.primary.log)
* didn't understand what's the issue, but likely unrelated (e.g. timeout)
  * [EinExprs](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/EinExprs.primary.log)
  * [ParallelAnalysis](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/ParallelAnalysis.primary.log)
  * [OpenTelemetryExporterPrometheus](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/OpenTelemetryExporterPrometheus.primary.log)
  * [Yunir](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/Yunir.primary.log)
  * [GLPK](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/GLPK.primary.log)
  * [CDDLib](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/CDDLib.primary.log)
  * [ODEInterfaceDiffEq](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/ODEInterfaceDiffEq.primary.log)
  * [OrdinaryDiffEqQPRK](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/OrdinaryDiffEqQPRK.primary.log)
  * [OrdinaryDiffEqFeagin](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/OrdinaryDiffEqFeagin.primary.log)
  * [OrdinaryDiffEqHighOrderRK](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/OrdinaryDiffEqHighOrderRK.primary.log)
  * [IRKGaussLegendre](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/IRKGaussLegendre.primary.log)
  * [OceanRobots](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7af55f_vs_5053a17/OceanRobots.primary.log)

If we're happy to let downstream developers fix the issues in their packages, e.g. for PyCall/PythonCall (the three BinaryBuilder-related ones are fine to ignore, issues should definitely be fixed in the package), then this is good to go from my point of view, as long as we decide what to do with the versions of the external stdlibs that need to be updated (I vote to merge the PRs to the external repos all together and then merge this PR, too, tests here are passing for julia + stdlibs)

2024-12-19 18:39 UTC, eschnett commented
I merged in the master branch to resolve conflicts.

2024-12-19 19:19 UTC, eschnett commented on stdlib/Pkg.version
For these files to be updated the respective changes to NetworkOptions and Pkg need to be merged first.

2024-12-28 18:11 UTC, eschnett commented
Three days until our MbedTLS runs out of long-term support...

2024-12-28 18:21 UTC, giordano commented
Until PRs https://github.com/JuliaLang/Pkg.jl/pull/4100 and https://github.com/JuliaLang/NetworkOptions.jl/pull/36 aren't merged, we're blocked here, I'm not personally involved with the development of those stdlibs (don't even have access to `NetworkOptions.jl` at all).

2024-12-28 19:03 UTC, DilumAluthge commented
> (don't even have access to `NetworkOptions.jl` at all).

I've fixed this. The JuliaLang committers team now has commit access on that repo.

2024-12-29 17:36 UTC, IanButterworth commented
I've proposed an alternative Pkg change making its tests work with both master and this PR here https://github.com/JuliaLang/Pkg.jl/pull/4123

2024-12-29 18:11 UTC, eschnett commented
I've switched this PR to @IanButterworth's PR for Pkg.jl.

2024-12-30 17:05 UTC, IanButterworth commented on deps/checksums/Pkg-05df5cb52a60672120f84ce0cb0edaf053ebfbae.tar.gz/md5
These need dropping too

2024-12-30 18:20 UTC, eschnett commented on deps/checksums/Pkg-05df5cb52a60672120f84ce0cb0edaf053ebfbae.tar.gz/md5
Not quite sure about the remaining two checksums for `Pkg` – do we need both?

2024-12-31 01:53 UTC, IanButterworth commented
Odd errors. Anyone seen them outside this PR?
![image](https://github.com/user-attachments/assets/2e8a5e4f-298e-4046-9a0a-b8588e02ea7b)

2024-12-31 08:28 UTC, giordano commented
No, but it looks like somehow it started with moving to the newer Pkg: [`da8acaf` (#56708)](https://github.com/JuliaLang/julia/pull/56708/commits/da8acaf60f0c145d1537143da8b611cff3c2f069)

2024-12-31 13:02 UTC, IanButterworth commented
There are two issues here. Could the windows one be the filesystem not fully finishing the mv before mv returns? https://github.com/JuliaLang/Pkg.jl/compare/master...IanButterworth:Pkg.jl:ib/fix_windows

2024-12-31 19:25 UTC, giordano commented
x86_64-darwin failure happened also on master: https://buildkite.com/julialang/julia-master/builds/43333#01941d20-ec70-48ea-9e9b-a9de9a585ff7/1304-1305. In any case that's only during the clean-up of the tests, tests themselves here are successful, which is good. So the only remaining mystery is the Windows failure.

2024-12-31 22:18 UTC, IanButterworth commented
I've added a more informative error here https://github.com/JuliaLang/Pkg.jl/pull/4126 if anyone can reproduce locally, or update this. Showing the manifest content debug log requires `JULIA_DEBUG=API` or `Pkg`

2025-01-01 05:37 UTC, IanButterworth commented
I think the issue is that OpenSSL_jll isn't actually loaded at the time the test is run on windows for some reason. So Pkg needs to check for it another way.

2025-01-01 07:51 UTC, giordano commented
> I think the issue is that OpenSSL_jll isn't actually loaded at the time the test is run on windows for some reason

Oh, on windows and macos we don't use it
https://github.com/JuliaLang/julia/blob/7f8f587bd8035b50ed85acb86a0431c576c61ae7/stdlib/LibCURL_jll/src/LibCURL_jll.jl#L7-L10
https://github.com/JuliaLang/julia/blob/7f8f587bd8035b50ed85acb86a0431c576c61ae7/stdlib/LibGit2_jll/src/LibGit2_jll.jl#L7-L10

2025-01-01 11:44 UTC, IanButterworth commented
Weird that the tests work on macOS then..

2025-01-01 14:22 UTC, IanButterworth commented
Investigating why it doesn't fail on MacOS. Indeed Pkg loads OpenSSL_jll on macOS, which seems unexpected?
```
% ./julia --start=no
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.0-DEV.1844 (2025-01-01)
 _/ |\__'_|_|_|\__'_|  |  pr/56708/7f8f587bd8 (fork: 31 commits, 0 days)
|__/                   |

julia> keys(Base.loaded_modules)
KeySet for a Dict{Base.PkgId, Module} with 12 entries. Keys:
  Base.PkgId(Base.UUID("4536629a-c528-5b80-bd46-f80d51c5b363"), "OpenBLAS_jll")
  Base.PkgId(Base.UUID("8f399da3-3557-5675-b5ff-fb832c97cbdb"), "Libdl")
  Base.PkgId(Base.UUID("ea8e919c-243c-51af-8825-aaa63cd721ce"), "SHA")
  Base.PkgId(Base.UUID("7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"), "FileWatching")
  Base.PkgId(Base.UUID("56f22d72-fd6d-98f1-02f0-08ddc0907c33"), "Artifacts")
  Base.PkgId(Base.UUID("8e850b90-86db-534c-a0d3-1478176c7d93"), "libblastrampol…
  Base.PkgId(nothing, "Main")
  Base.PkgId(nothing, "Core")
  Base.PkgId(Base.UUID("37e2e46d-f89d-539d-b4ee-838fcccc9c8e"), "LinearAlgebra")
  Base.PkgId(nothing, "Base")
  Base.PkgId(Base.UUID("9a3f8284-a2c9-5f02-9a11-845980a1fd5c"), "Random")
  Base.PkgId(Base.UUID("6462fe0b-24de-5631-8697-dd941f90decc"), "Sockets")

julia> import Pkg

julia> keys(Base.loaded_modules)
KeySet for a Dict{Base.PkgId, Module} with 32 entries. Keys:
  Base.PkgId(Base.UUID("29816b5a-b9ab-546f-933c-edad1886dfa8"), "LibSSH2_jll")
  Base.PkgId(Base.UUID("458c3c95-2e84-50aa-8efc-19380b2a3a95"), "OpenSSL_jll")
  Base.PkgId(Base.UUID("4536629a-c528-5b80-bd46-f80d51c5b363"), "OpenBLAS_jll")
  Base.PkgId(Base.UUID("8e850ede-7688-5339-a07c-302acd2aaf8d"), "nghttp2_jll")
  Base.PkgId(Base.UUID("e37daf67-58a4-590a-8e99-b0245dd2ffc5"), "LibGit2_jll")
  Base.PkgId(Base.UUID("8f399da3-3557-5675-b5ff-fb832c97cbdb"), "Libdl")
  Base.PkgId(Base.UUID("ea8e919c-243c-51af-8825-aaa63cd721ce"), "SHA")
  Base.PkgId(Base.UUID("f43a241f-c20a-4ad4-852c-f6b1247861c6"), "Downloads")
  Base.PkgId(Base.UUID("44cfe95a-1eb2-52ea-b672-e2afdf69b78f"), "Pkg")
  Base.PkgId(Base.UUID("7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"), "FileWatching")
  Base.PkgId(Base.UUID("56f22d72-fd6d-98f1-02f0-08ddc0907c33"), "Artifacts")
  Base.PkgId(Base.UUID("ade2ca70-3891-5945-98fb-dc099432e06a"), "Dates")
  Base.PkgId(Base.UUID("8e850b90-86db-534c-a0d3-1478176c7d93"), "libblastrampol…
  Base.PkgId(Base.UUID("3f19e933-33d8-53b3-aaab-bd5110c3b7a0"), "p7zip_jll")
  Base.PkgId(Base.UUID("cf7118a7-6976-5b1a-9a39-7adc72f591a4"), "UUIDs")
  Base.PkgId(Base.UUID("14a3606d-f60d-562e-9121-12d972cd8159"), "MozillaCACerts…
  Base.PkgId(Base.UUID("deac9b47-8bc7-5906-a0fe-35ac56dc84c0"), "LibCURL_jll")
  Base.PkgId(Base.UUID("fa267f1f-6049-4f14-aa54-33bafae1ed76"), "TOML")
  Base.PkgId(nothing, "Main")
  ⋮

julia>
```

2025-01-01 14:41 UTC, giordano commented
That's because of libssh2 then https://github.com/JuliaLang/julia/blob/7f8f587bd8035b50ed85acb86a0431c576c61ae7/stdlib/LibSSH2_jll/src/LibSSH2_jll.jl#L7-L10

2025-01-04 14:58 UTC, giordano approved these changes

2025-01-04 17:09 UTC, fxcoudert commented
Single failure in test x86_64-apple-darwin, codegen:

```
Compiler/codegen                                 (3) |        started at 2025-01-04T08:05:48.661
      From worker 3:	WARNING: method definition for f56739 at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-grannysmith-C07ZQ07RJYVY.0/build/default-grannysmith-C07ZQ07RJYVY-0/julialang/julia-master/julia-8bb516f20e/share/julia/Compiler/test/codegen.jl:1034 declares type variable T but does not use it.
Compiler/codegen                                 (3) |         failed at 2025-01-04T08:07:22.987
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-grannysmith-C07ZQ07RJYVY.0/build/default-grannysmith-C07ZQ07RJYVY-0/julialang/julia-master/julia-8bb516f20e/share/julia/Compiler/test/codegen.jl:412
  Expression: abs(#= /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-grannysmith-C07ZQ07RJYVY.0/build/default-grannysmith-C07ZQ07RJYVY-0/julialang/julia-master/julia-8bb516f20e/share/julia/Compiler/test/codegen.jl:412 =# @allocated(f_dict_hash_alloc()) / #= /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-grannysmith-C07ZQ07RJYVY.0/build/default-grannysmith-C07ZQ07RJYVY-0/julialang/julia-master/julia-8bb516f20e/share/julia/Compiler/test/codegen.jl:412 =# @allocated(g_dict_hash_alloc()) - 1) < 0.1
   Evaluated: 0.3193392980041294 < 0.1
```

2025-01-04 17:11 UTC, giordano commented
That's #56748

2025-01-04 17:12 UTC, merged